force-app/main/default/objects/Block_Dimension__c/Block_Dimension__c.object-meta.xml
<CustomObject>
    <label>Block Dimension</label>
    <nameField>
        <label>Block Dimension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Block Dimensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Block_Dimension__c/fields/SBU_Code__c.field-meta.xml
<CustomField>
    <fullName>SBU_Code__c</fullName>
    <label>SBU Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Annual_Business_Revenue_Unit_10k_USD__c.field-meta.xml
<CustomField>
    <fullName>Annual_Business_Revenue_Unit_10k_USD__c</fullName>
    <description>渠道该品类年度销售额（万美元）</description>
    <inlineHelpText>Annual sales of the product line in the channel</inlineHelpText>
    <label>Annual Business Revenue (Unit: 10k USD)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Channel_Code__c.field-meta.xml
<CustomField>
    <fullName>Channel_Code__c</fullName>
    <description>渠道编码，系统自动生成，同一个渠道名称只有一个渠道编码，规则：CH+5位数字，如CH00000（已废弃）</description>
    <displayFormat>CH{00000}</displayFormat>
    <label>Channel Code(Backend usage)</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Cooperating_Customer_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Cooperating_Customer_Entity_Name__c</fullName>
    <description>合作主体名称（品牌直营：同渠道名称；代理合作：填写代理名称），需校验和客户管理名称保持一致</description>
    <inlineHelpText>Cooperting Customer Entity Name. It includes brand direct operation and agent cooperation. For brand direct operation, it&apos;s the same as channel name; for agent cooperation, it should fill in the agent name.</inlineHelpText>
    <label>Cooperating  Customer Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Cooperating_Customer_SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>Cooperating_Customer_SAP_Code__c</fullName>
    <description>合作主体SAP</description>
    <inlineHelpText>Cooperating customer SAP code. For brand direct operation, it should fill in the SAP code of the channel; for agent cooperation, it should fill in the SAP code of the agent customer.</inlineHelpText>
    <label>Cooperating  Customer SAP Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Cooperating_Method__c.field-meta.xml
<CustomField>
    <fullName>Cooperating_Method__c</fullName>
    <description>合作模式，对于已合作或计划开发的渠道：若与海信直接合作，此处请填写“品牌直营”；若通过代理合作，此处请填写“代理合作”。</description>
    <inlineHelpText>It&apos;s used for cooperated channel or planning to develop channel. For channel that cooperated directly with Hisense, it should fill in brand direct operation; for channel that cooperated with Hisense through agent, it should fill in agent cooperation.</inlineHelpText>
    <label>Cooperating Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>品牌直营</fullName>
            </value>
            <value>
                <fullName>代理合作</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Cooperating_Status__c.field-meta.xml
<CustomField>
    <fullName>Cooperating_Status__c</fullName>
    <description>合作状态，分为已合作、未合作、计划开发和已停止合作四种状态。本年度有开发计划的选择“计划开发”，本年度无开发计划的选择“未合作”。</description>
    <inlineHelpText>There are three types of status: cooperated, uncooperated, and plan to develop. Fill in “plan to develop” if you have a development plan for the current year, or “uncooperated” if you do not have a development plan for the current year.</inlineHelpText>
    <label>Cooperating Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>已合作</fullName>
            </value>
            <value>
                <fullName>计划开发</fullName>
            </value>
            <value>
                <fullName>未合作</fullName>
            </value>
            <value>
                <fullName>已停止合作</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Cooperating_Time__c.field-meta.xml
<CustomField>
    <fullName>Cooperating_Time__c</fullName>
    <description>实际合作时间，具体到月份，需校验不能填未来时间（即时间小于等于导入当天所在月份）。文本格式yyyymm</description>
    <inlineHelpText>The actual time of cooperation, specific to the month, need to check can not be filled in the future time (i.e. the time is less than or equal to the import day in the month). Text format: yyyymm</inlineHelpText>
    <label>Cooperating Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>销售国家</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Hisense_Value_Share__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Value_Share__c</fullName>
    <description>海信在渠道内份额（填写上一年年度数据）</description>
    <inlineHelpText>Hisense&apos;s share in the channel (fill in the previous year&apos;s annual data)</inlineHelpText>
    <label>Hisense Value Share</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Market_Share__c.field-meta.xml
<CustomField>
    <fullName>Market_Share__c</fullName>
    <description>渠道所在国分品类的市场份额，填写上一年年度数据</description>
    <inlineHelpText>Market share by product line in the country where the channel is located, with data for the previous year.</inlineHelpText>
    <label>Market Share</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Number_of_Entered_Stores__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Entered_Stores__c</fullName>
    <description>已进驻门店数，填写上一年年度数据</description>
    <inlineHelpText>Number of entered stores, fill in the previous year&apos;s annual data</inlineHelpText>
    <label>Number of Entered Stores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Number_of_New_Store_Entering_Plan_2024__c.field-meta.xml
<CustomField>
    <fullName>Number_of_New_Store_Entering_Plan_2024__c</fullName>
    <description>2024年计划新进店数</description>
    <inlineHelpText>Number of stores planned to enter for 2024</inlineHelpText>
    <label>Number of New Store Entering Plan</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Number_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Stores__c</fullName>
    <description>渠道门店数，填写上一年年度数据</description>
    <inlineHelpText>Number of channel stores, fill in the previous year&apos;s annual data</inlineHelpText>
    <label>Number of Stores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Planned_Cooperating_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Cooperating_Time__c</fullName>
    <description>计划合作时间，只有“计划开发”状态的渠道需填写，具体到月份</description>
    <inlineHelpText>only “plan to develop” status of the channel to fill in, specific to the month</inlineHelpText>
    <label>Planned Cooperating Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>产品线</description>
    <label>Product Line</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <description>销售单元，匹配信数区组维表中的grp_zh（其他大区）和sub_zh（欧洲大区）</description>
    <label>SBU</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/SBU_Code__c.field-meta.xml
<CustomField>
    <fullName>SBU_Code__c</fullName>
    <description>销售单元编码，通过销售单元匹配信数区组维表中的sub_zh字段获取sub</description>
    <inlineHelpText>It acquires field sub by matching field sub_zh from HiData</inlineHelpText>
    <label>SBU Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Statistical_Year__c.field-meta.xml
<CustomField>
    <fullName>Statistical_Year__c</fullName>
    <description>统计年份，指更新渠道的年份（每年更新一次渠道）</description>
    <inlineHelpText>Statistical year, the year in which the channels were updated (channels are updated annually)</inlineHelpText>
    <label>Statistical Year</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Management__c/Customer_Management__c.object-meta.xml
<CustomObject>
    <description>客户管理名称</description>
    <label>Customer Management</label>
    <nameField>
        <label>Customer Management Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendChannelToBigDataTest.cls
@isTest
private class SendChannelToBigDataTest {
    static testMethod void testMethod1() {
        Test.startTest();

        Block_Dimension__c bd = new Block_Dimension__c(
            name = '日本',
            SBU_Code__c = 'rb'
        );
        insert bd;

        Customer_Management__c cm = new Customer_Management__c();
        cm.Name = 'YAMADA';
        insert cm;

        Channel__c c = new Channel__c(
            Name = 'YAMADA',
            Annual_Business_Revenue_Unit_10k_USD__c = '100000.0',
            // Channel_Code__c = '10',
            Cooperating_Customer_Entity_Name__c = '',
            Cooperating_Customer_SAP_Code__c = '',
            Cooperating_Method__c = '代理合作',
            Country__c = '日本',
            Hisense_Value_Share__c = '10.00',
            Market_Share__c = '26.0%',
            Number_of_Entered_Stores__c = '22',
            Number_of_New_Store_Entering_Plan_2024__c = '10.0%',
            Number_of_Stores__c = '998',
            Product_Line__c = '电视',
            SBU__c = '日本',
            Cooperating_Status__c = '已合作',
            Planned_Cooperating_Time__c = '',
            Statistical_Year__c = '2024',
            Cooperating_Time__c = '2024-01'
        );

        insert c;

        RestRequest req = new RestRequest();
		req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = Blob.valueOf('{"startTime":"2023-12-01 00:00:00","endTime":"2025-02-10 00:00:00"}');
		SendChannelToBigData.adoPost();
        req.requestBody = Blob.valueOf('{"startTime":"2023-12-01 00:00:00","en');
        SendChannelToBigData.adoPost();
        Test.stopTest();
    }
}