force-app/main/default/objects/Share_Log__c/Share_Log__c.object-meta.xml
<CustomObject>
    <label>共享日志</label>
    <nameField>
        <displayFormat>SL-{YYYYMMDD}-{00000000}</displayFormat>
        <label>共享日志编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>共享日志</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_Log__c/fields/Parameter__c.field-meta.xml
<CustomField>
    <fullName>Parameter__c</fullName>
    <label>参数(List&lt;sObject&gt;)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Share_Log__c/fields/Row_Cause__c.field-meta.xml
<CustomField>
    <fullName>Row_Cause__c</fullName>
    <label>原因</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Share_Log__c/fields/Share_Object__c.field-meta.xml
<CustomField>
    <fullName>Share_Object__c</fullName>
    <label>共享对象</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Log__c/fields/Share_Time__c.field-meta.xml
<CustomField>
    <fullName>Share_Time__c</fullName>
    <label>时间</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/Share_Object__c.object-meta.xml
<CustomObject>
    <label>共享对象</label>
    <nameField>
        <label>共享对象名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>共享对象</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_Object__c/fields/Account_API__c.field-meta.xml
<CustomField>
    <fullName>Account_API__c</fullName>
    <description>目标对象中的客户SF编码, 类型: 文本/公式文本</description>
    <inlineHelpText>目标对象中的客户SF编码, 类型: 文本/公式文本  (若此表存在产品线纬度,请勿填写此项, 仅供存在门店/客户纬度使用)</inlineHelpText>
    <label>客户字段API名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Account_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Account_Product_Line__c</fullName>
    <inlineHelpText>目标对象中的: 客户SF编码 + 产品线  类型:文本/公式文本</inlineHelpText>
    <label>客户产品线字段API名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Batch_AddMinutes__c.field-meta.xml
<CustomField>
    <fullName>Batch_AddMinutes__c</fullName>
    <label>Batch调用周期(Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Gridding_Filed_API__c.field-meta.xml
<CustomField>
    <fullName>Gridding_Filed_API__c</fullName>
    <description>目标对象中的网格编码 类型:文本/公式文本</description>
    <inlineHelpText>目标对象中的网格编码 类型:文本/公式文本</inlineHelpText>
    <label>网格字段API名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>是否启用</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/IsRelyThisShare__c.field-meta.xml
<CustomField>
    <fullName>IsRelyThisShare__c</fullName>
    <defaultValue>false</defaultValue>
    <label>是否依赖该共享对象</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Object_API__c.field-meta.xml
<CustomField>
    <fullName>Object_API__c</fullName>
    <inlineHelpText>要与用户共享的对象API名, 自定义对象需__c后缀</inlineHelpText>
    <label>共享对象API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Object_Share__c.field-meta.xml
<CustomField>
    <fullName>Object_Share__c</fullName>
    <description>填写该对象对应的Share对象名称</description>
    <externalId>true</externalId>
    <inlineHelpText>填写该对象对应的Share对象名称</inlineHelpText>
    <label>共享对象_ShareAPI</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Product_Line_API__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_API__c</fullName>
    <description>目标对象中的产品线字段, 选项列表值的Value</description>
    <inlineHelpText>目标对象中的产品线字段, 选项列表值的Value</inlineHelpText>
    <label>产品线字段API名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Query_Statement__c.field-meta.xml
<CustomField>
    <fullName>Query_Statement__c</fullName>
    <label>查询语句</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Refresh_Query_Statement__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Query_Statement__c</fullName>
    <label>岗位刷新查询语句</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Share_Chunk__c.field-meta.xml
<CustomField>
    <fullName>Share_Chunk__c</fullName>
    <label>共享分块</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Share_RowCause__c.field-meta.xml
<CustomField>
    <fullName>Share_RowCause__c</fullName>
    <description>共享原因的API名称</description>
    <inlineHelpText>共享原因的API名称</inlineHelpText>
    <label>共享原因</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Share_Type__c.field-meta.xml
<CustomField>
    <fullName>Share_Type__c</fullName>
    <label>共享类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Shop_Filed_API__c.field-meta.xml
<CustomField>
    <fullName>Shop_Filed_API__c</fullName>
    <label>门店字段API名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Relation_Object__c/Share_Relation_Object__c.object-meta.xml
<CustomObject>
    <label>共享关系对象</label>
    <nameField>
        <label>共享关系对象名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>共享关系对象</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_Relation_Object__c/fields/Object_Share__c.field-meta.xml
<CustomField>
    <fullName>Object_Share__c</fullName>
    <label>共享关系对象_ShareAPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Relation_Object__c/fields/Share_Object__c.field-meta.xml
<CustomField>
    <fullName>Share_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>共享对象</label>
    <referenceTo>Share_Object__c</referenceTo>
    <relationshipLabel>共享关系对象</relationshipLabel>
    <relationshipName>Share_Object_Relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Share_Relation_Object__c/fields/Share_RowCause__c.field-meta.xml
<CustomField>
    <fullName>Share_RowCause__c</fullName>
    <label>共享原因</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Relationship_Item__c/Share_Relationship_Item__c.object-meta.xml
<CustomObject>
    <label>共享关系行</label>
    <nameField>
        <displayFormat>SRI-{YYYYMMDD}-{0000000000}</displayFormat>
        <label>共享关系行编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>共享关系行</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_Relationship_Item__c/fields/External_Key_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Key_ID__c</fullName>
    <externalId>true</externalId>
    <label>*Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Share_Relationship_Item__c/fields/Share_Relationship_ID__c.field-meta.xml
<CustomField>
    <fullName>Share_Relationship_ID__c</fullName>
    <label>共享关系记录Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Relationship_Item__c/fields/ShareItemId__c.field-meta.xml
<CustomField>
    <fullName>ShareItemId__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>共享对象数据的Id,与共享关系记录组成一对多关系</inlineHelpText>
    <label>共享子关系Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Share_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>WhoId</fullName>
    </customValue>
    <customValue>
        <fullName>WhatId</fullName>
    </customValue>
    <customValue>
        <fullName>ParentId</fullName>
    </customValue>
    <masterLabel>共享类型</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Share_Common_IntegrationTDGW.cls
/**
 * @description       : Share_Common_Integration transfer data gather way
 * @author            : chenpeng@deloitte.com.cn
 * @group             : 
 * @last modified on  : 03-23-2022
 * @last modified by  : chenpeng@deloitte.com.cn
**/
public withOut sharing class Share_Common_IntegrationTDGW {
    public static void deleteChangeDataShare(Share_Object__c shareObj, 
                                             Map<String, List<String>> checkShareDataIdMap, 
                                             List<Object> shareDataList,
                                             List<String> deleteSriList,
                                             Set<String> changeIdSet) {
        system.debug('wwwwwddd----'  + JSON.serialize(shareObj));
        system.debug('wwwwwddd----'  + JSON.serialize(checkShareDataIdMap));
        system.debug('wwwwwddd----'  + JSON.serialize(shareDataList));
        system.debug('wwwwwddd----'  + JSON.serialize(deleteSriList));
        system.debug('wwwwwddd----'  + JSON.serialize(changeIdSet));
        if(checkShareDataIdMap.isEmpty()){
            return;
        }

        //系统中的change数据的共享关系记录
        Map<String, List<String>> shareDataIdMap = new Map<String, List<String>>();

        //可以删除的共享关系对象的 目标对象ID
        Set<String> deleteParentIdSet = new Set<String>();

        //查找共享关系行中的 Share_Relationship_ID__c 为 checkShareDataIdMap.keySet()
        for (Share_Relationship_Item__c sri : queryShareRelationshipItemList(checkShareDataIdMap.keySet())) {
            if(shareDataIdMap.containsKey(sri.Share_Relationship_ID__c)) {
                shareDataIdMap.get(sri.Share_Relationship_ID__c).add(sri.ShareItemId__c);
            }else {
                shareDataIdMap.put(sri.Share_Relationship_ID__c, new List<String>{sri.ShareItemId__c});
            }
        }
        system.debug('shareDataIdMap'+shareDataIdMap);
        for(String strKey : shareDataIdMap.keySet()) {
            if(checkShareDataIdMap.values().size() == shareDataIdMap.values().size()) {
                deleteParentIdSet.add(strKey);
            }

        }
        system.debug('deleteParentIdSet'+deleteParentIdSet);

        //要删除的更新的共享对象共享数据
        Map<String, List<SObject>> deleteChangeShareListMap = new Map<String, List<SObject>>();

        //通过 changeIdSet 查找关系对象中的共享数据
        for (Share_Relation_Object__c sro : shareObj.Share_Object_Relation__r) {
            String deleteRelatShareQuery = 'SELECT Id,UserOrGroupId FROM ' + sro.Object_Share__c;
            deleteRelatShareQuery += ' WHERE ' + sro.Share_Type__c + ' IN :deleteParentIdSet';
            system.debug('deleteRelatShareQuery'+deleteRelatShareQuery);
            List<SObject> deleteChangeShareList = new List<SObject>();
            for (SObject sob : Database.query(deleteRelatShareQuery)) {
                deleteChangeShareList.add(sob);
            }
            if(!deleteChangeShareList.isEmpty()) {
                deleteChangeShareListMap.put(sro.Id, deleteChangeShareList);
            }
        }

        String deleteShareQuery = 'SELECT Id FROM ' + shareObj.Object_Share__c;
        deleteShareQuery += ' WHERE ' + shareObj.Share_Type__c + ' IN :changeIdSet';
        List<SObject> deleteChangeShareList = new List<SObject>();
        system.debug('deleteShareQuery'+deleteShareQuery);
        for (SObject sob : Database.query(deleteShareQuery)) {
            deleteChangeShareList.add(sob);
        }
        if(!deleteChangeShareList.isEmpty()) {
            deleteChangeShareListMap.put(shareObj.Id, deleteChangeShareList);
        }

        if(!deleteChangeShareList.isEmpty()){
            for (String strKey : deleteChangeShareListMap.keySet()) {
                Database.delete(deleteChangeShareListMap.get(strKey), false);
            }
        }

        //删除共享关系行
        List<Share_Relationship_Item__c> shareRelationshipItemByKeyList = queryShareRelationshipItemByKeyList(deleteSriList);
        if(!shareRelationshipItemByKeyList.isEmpty()) {
            DELETE shareRelationshipItemByKeyList;
        }
    }

    public static List<SObject> sortChunks(List<SObject> scope) {
        Map<String, List<SObject>> sortMap = new Map<String, List<SObject>>();
        for (SObject rec : scope) {
            String keyPrefix = rec.getSObjectType().getDescribe().getName();
            if (!sortMap.containsKey(keyPrefix)) {
            sortMap.put(keyPrefix, new List<SObject>());
            }
            sortMap.get(keyPrefix).add(rec);
        }

        List<SObject> flattenedList = new List<SObject>();
        for ( String key: sortMap.keySet() ) {
            flattenedList.addAll( sortMap.get(key) );
        }
        return flattenedList;
    }

    /**
    * @description 
    * @author chenpeng@deloitte.com.cn | 01-24-2022 
    * @param objectName  - 对象名
    * @param parameter - (List<Object>)
    * @param cause - Row_Cause__c
    **/
    public static void writeShareLogs(String objectName,
                                      Map<String, List<String>> parameterList, 
                                      Map<String, String> causeMap) {

        try {
            Share_Log__c log = new Share_Log__c();
            log.Share_Object__c = objectName;
            log.Row_Cause__c = JSON.serialize(causeMap);
            log.Parameter__c = JSON.serialize(parameterList);
            log.Share_Time__c = System.now();
            INSERT log;

        } catch(Exception ex) {
            System.debug(LoggingLevel.INFO, '*** Insert Log Error: ' + ex.getMessage() + '\n' + ex.getStackTraceString());
        }
    }

    public static List<Share_Relationship_Item__c> queryShareRelationshipItemList(Set<String> shareRelatIdSet){
        return [SELECT External_Key_ID__c,
                       ShareItemId__c,
                       Share_Relationship_ID__c
                FROM Share_Relationship_Item__c
                WHERE Share_Relationship_ID__c IN :shareRelatIdSet];
    }

    public static List<Share_Relationship_Item__c> queryShareRelationshipItemByKeyList(List<String> deleteSriList){
        return [SELECT External_Key_ID__c,
                       ShareItemId__c,
                       Share_Relationship_ID__c
                FROM Share_Relationship_Item__c
                WHERE External_Key_ID__c IN :deleteSriList];
    }

    public static List<Share_Object__c> queryShareObject(){
        return [SELECT Name, 
                        Object_API__c,
                        Gridding_Filed_API__c,
                        Account_API__c,
                        Account_Product_Line__c,
                        Object_Share__c,
                        Share_Type__c,
                        Share_RowCause__c,
                        Share_Chunk__c,
                        Batch_AddMinutes__c,
                        Query_Statement__c,
                        IsRelyThisShare__c,
                        Product_Line_API__c,
                        Refresh_Query_Statement__c,
                        Shop_Filed_API__c
                FROM Share_Object__c
                WHERE IsActive__c = true AND Object_Share__c  != 'Customer_Visit__Share'];
    }
}