force-app/main/default/objects/ExpoApplyInfo__c/ExpoApplyInfo__c.object-meta.xml
<CustomObject>
    <label>Exhibition Customer</label>
    <nameField>
        <label>VisitorCode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoApplyInfo__c/fields/ExpoId__c.field-meta.xml
<CustomField>
    <fullName>ExpoId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Information</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Exhibition Customers</relationshipLabel>
    <relationshipName>ExpoApplyInfos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/FirstNameCN__c.field-meta.xml
<CustomField>
    <fullName>FirstNameCN__c</fullName>
    <label>First Name CN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/FirstNameEN__c.field-meta.xml
<CustomField>
    <fullName>FirstNameEN__c</fullName>
    <label>First Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/Is_Present__c.field-meta.xml
<CustomField>
    <fullName>Is_Present__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attand on-site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/LastNameEN__c.field-meta.xml
<CustomField>
    <fullName>LastNameEN__c</fullName>
    <label>Last Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <label>Telephone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/WorkTel__c.field-meta.xml
<CustomField>
    <fullName>WorkTel__c</fullName>
    <label>Work Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/ExpoInfo__c.object-meta.xml
<CustomObject>
    <description>展会信息</description>
    <label>Exhibition Management</label>
    <nameField>
        <label>Exhibition Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Managements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoInfo__c/fields/DisplayInThePortal__c.field-meta.xml
<CustomField>
    <fullName>DisplayInThePortal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display in the Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/LastRegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>LastRegistrationDate__c</fullName>
    <label>Last Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/TitleEN__c.field-meta.xml
<CustomField>
    <fullName>TitleEN__c</fullName>
    <label>Exhibition Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExhibitionInvitationLetterTest.cls
@isTest
private class ExhibitionInvitationLetterTest {
    static testMethod void testMethod1() {
        ExpoInfo__c e1 = new ExpoInfo__c(
        	LastRegistrationDate__c = Date.today()+15, 
        	StartDate__c = Date.today()-90, 
        	EndDate__c = Date.today()+10,
        	Name = '展会信息',
        	TitleEN__c = 'Exhibition Informatino',
        	DisplayInThePortal__c = true
        	);
        INSERT e1;

        ExpoApplyInfo__c e2 = new ExpoApplyInfo__c(
        	ExpoId__c = e1.Id,
        	FirstNameEN__c = 'San',
        	FirstNameCN__c = '三',
        	LastNameCN__c = '张',
        	LastNameEN__c = 'Zhang',
        	Email__c = 'zs@zs.com',
        	Telephone__c = '18712345678',
        	WorkTel__c = '18712345678',
			Is_Present__c = true        	
			);
        INSERT e2;



        ExhibitionInvitationLetterSchedule sch = new ExhibitionInvitationLetterSchedule();
		String fmt = '0 0 0/1 * * ? *';
		System.schedule('ExhibitionInvitationLetterSchedule for Test', fmt, sch);

    }

    static testMethod void testMethod2() {
        String profileName  = '展会 行政商务组';
        Id profileId = [SELECT Id FROM profile WHERE Name = :profileName][0].Id; 
        User user1 = new User(alias = '区域经理', email='TestTom@noemail.com',
        emailencodingkey='UTF-8', lastname='TestTom', languagelocalekey='en_US',
        localesidkey='en_US',profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='testTom@noemail.com');
        INSERT user1;
        
        ExpoInfo__c e1 = new ExpoInfo__c(
        	LastRegistrationDate__c = Date.today()+15, 
        	StartDate__c = Date.today()-90, 
        	EndDate__c = Date.today()+10,
        	Name = '展会信息',
        	TitleEN__c = 'Exhibition Informatino',
        	DisplayInThePortal__c = true
        	);
        INSERT e1;

        ExpoApplyInfo__c e2 = new ExpoApplyInfo__c(
        	ExpoId__c = e1.Id,
        	FirstNameEN__c = 'San',
        	FirstNameCN__c = '三',
        	LastNameCN__c = '张',
        	LastNameEN__c = 'Zhang',
        	Email__c = 'zs@zs.com',
        	Telephone__c = '18712345678',
        	WorkTel__c = '18712345678',
			Is_Present__c = true        	
			);
        INSERT e2;



		ExhibitionInvitationLetterBatch eb = new ExhibitionInvitationLetterBatch();
		Database.executeBatch(eb, 80);

    }
}