force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>销售姓名</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>Salesperson No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/IsKeyUser__c.field-meta.xml
<CustomField>
    <fullName>IsKeyUser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If there are multiple sales in the same product line, select one sales person as the key user for reports and statistics</inlineHelpText>
    <label>IsKeyUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target__c/Sales_Target__c.object-meta.xml
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>SN-{00000}</displayFormat>
        <label>Sales Target No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Target__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Forecasts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Target__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SalesTargetShareBatch.cls
/**********************************************************************
* Name: SalesTargetShareBatch
* Object: Sales_Target__c 
* Purpose: 
* SalesTarget share权限
* Create Date: 2019-06-19
*************************************************************************/
global class SalesTargetShareBatch implements Database.Batchable<sObject> {
    public String query;
    public String year;

    global SalesTargetShareBatch(String year) {
        this.year = year;
        this.query = 'SELECT id, Customer_Name__c,Product_Line__c,OwnerId FROM Sales_Target__c WHERE Year__c = :year AND Product_Line__c != null AND Customer_Name__c !=null';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sales_Target__c> salesTargetList) {
        Set<String> cusIdSet = new Set<String>();
        Set<String> salesTargetIdSet = new Set<String>();

        for (Sales_Target__c salesTargetData : salesTargetList) {
            salesTargetIdSet.add(salesTargetData.Id);
            cusIdSet.add(salesTargetData.Customer_Name__c);
        }

        List<Sales__c> salesList = [SELECT id, Customer__c, Sales__c, Sales__r.IsActive,IsKeyUser__c ,Product_Line__c FROM Sales__c WHERE Customer__c IN : cusIdSet AND Sales__r.IsActive = TRUE];
        Map<String, List<Sales__c>> salesMap = new Map<String, List<Sales__c>>();
        for (Sales__c salesData : salesList) {
            if(salesMap.containsKey(salesData.Customer__c)){
                salesMap.get(salesData.Customer__c).add(salesData);
            }else{
                salesMap.put(salesData.Customer__c,new List<Sales__c>{salesData});
            }
        }

        List<Sales_Target__Share> insertSalesTargetList = new List<Sales_Target__Share>();
        // List<Sales_Target__Share> existSalesTargetList =[SELECT ParentId,UserOrGroupId FROM Sales_Target__Share WHERE ParentId IN :salesTargetIdSet];
        // Map<String,Set<String>> accessUserMap = new Map<String,Set<String>>();

        // for(Sales_Target__Share salesTargetShareData : existSalesTargetList){
        //     if(accessUserMap.containsKey(salesTargetShareData.ParentId)){
        //         accessUserMap.get(salesTargetShareData.ParentId).add(salesTargetShareData.UserOrGroupId);
        //     }else{
        //         accessUserMap.put(salesTargetShareData.ParentId, new Set<String>{salesTargetShareData.UserOrGroupId});
        //     }
        // }


        //设置Share
        Map<String, Sales_Target__Share> insertSalesTargetMap = new Map<String, Sales_Target__Share>();
        for (Sales_Target__c salesTargetData : salesTargetList) {
            List<Sales__c> salescList = salesMap.get(salesTargetData.Customer_Name__c);
            List<Sales__c> productLineSalesList = new List<Sales__c>();
            Boolean flag = false;
            if (salescList == null) {
                continue;
            }
            for (Sales__c salesme : salescList) {
                // if (salesTargetData.OwnerId != salesme.Sales__c) {
                //     if(accessUserMap.containsKey(salesTargetData.Id) && accessUserMap.get(salesTargetData.Id).contains(salesme.Sales__c)){
                //         continue;
                //     }
                // }
                
                if (Utility.isExistProductLine(salesme.Product_Line__c,salesTargetData.Product_Line__c)) {
                    Sales_Target__Share salesTargetShareData = new Sales_Target__Share();
                    salesTargetShareData.RowCause = 'Manual';
                    salesTargetShareData.ParentId = salesTargetData.Id;
                    salesTargetShareData.UserOrGroupId  = salesme.Sales__c;
                    salesTargetShareData.AccessLevel = 'Read';
                    String idKeyString = String.valueOf(salesTargetData.Id)+String.valueOf(salesme.Sales__c);
                    insertSalesTargetMap.put(idKeyString, salesTargetShareData);
                    productLineSalesList.add(salesme);
                    //如果为keyuser，设置为owner
                    if (salesme.IsKeyUser__c) {
                        salesTargetData.OwnerId = salesme.Sales__c;
                        // String existOwnerReDataId =String.valueOf(salesTargetData.Id)+String.valueOf(salesme.Sales__c);
                        // insertSalesTargetMap.remove(existOwnerReDataId);
                        flag = true;
                    }
                }
            }
            if (flag == false && productLineSalesList.size() > 0) {
                salesTargetData.OwnerId = productLineSalesList[0].Sales__c;
                
            }
            String mapString = String.valueOf(salesTargetData.Id)+String.valueOf(salesTargetData.OwnerId);
            if (insertSalesTargetMap.containsKey(mapString)) {
                insertSalesTargetMap.remove(mapString);
            }
            
        }
        
        
        try{
            update salesTargetList;
        }catch(Exception e){
            system.debug('error message'+e.getMessage());
            system.debug('line number'+e.getLineNumber());
        }

        if(insertSalesTargetMap.size() > 0){
            insertSalesTargetList = insertSalesTargetMap.values();
            try{
                Database.upsert(insertSalesTargetList);
            }catch(Exception e){
                system.debug('error message'+e.getMessage());
                system.debug('line number'+e.getLineNumber());
            }
        }

    }

    global void finish(Database.BatchableContext BC) {

    }
}