force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>销售姓名</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>Salesperson No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/IsKeyUser__c.field-meta.xml
<CustomField>
    <fullName>IsKeyUser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If there are multiple sales in the same product line, select one sales person as the key user for reports and statistics</inlineHelpText>
    <label>IsKeyUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SC_Base.cls
global virtual class SC_Base {
    public String salesQuery = 'SELECT Id,Name,Customer__c,IsKeyUser__c,Product_Line__c,IsDeleted,Sales__c '
        +'FROM Sales__c WHERE Sales__r.IsActive=true ';

    public String startDate;
    public String endDate;
    public List<Sales__c> salesList;
    public Set<String> customerIdSet;

    global SC_Base() {
        Date today = System.today();
        Date yesterday = today.addDays(-1);
        Date tomorrow = today.addDays(1);
        this.startDate = yesterday.format();
        this.endDate = tomorrow.format();
    }

    global SC_Base(String startDate, String endDate) {
        this.startDate = startDate;
        this.endDate = endDate;
    }

    public List<Sales__c> updatedList(){
        List<Sales__c> r = new List<Sales__c>();
        if(this.salesList!=null){
            for(Sales__c sales: this.salesList) {
                if(!sales.IsDeleted){
                    r.add(sales);
                }
            }
        }
        return r;
    }

    public List<Sales__c> deletedList(){
        List<Sales__c> r = new List<Sales__c>();
        if(this.salesList!=null){
            for(Sales__c sales: this.salesList) {
                if(sales.IsDeleted){
                    r.add(sales);
                }
            }
        }
        return r;
    }
}