force-app/main/default/objects/Customer_Visit__c/Customer_Visit__c.object-meta.xml
<CustomObject>
    <label>Customer Visit</label>
    <nameField>
        <label>Customer Visit Topic</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Visit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Visit__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Visit__c/fields/Sales_Expected_Remind_Date__c.field-meta.xml
<CustomField>
    <fullName>Sales_Expected_Remind_Date__c</fullName>
    <label>Expected Reminding Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Visit__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CustomerVisitCloneController.cls
public class CustomerVisitCloneController {

    public static Map<String,Schema.SObjectField> quoteLoopMap = Schema.SObjectType.Customer_Visit__c.fields.getMap();
    
    public class ReturnResult{
        public String code; //code "0" means success, and other codes means failure
        public String msg;  //result message
    }

    @AuraEnabled
    public static String copyCustomerVisit(String cvId) {
        ReturnResult result = new ReturnResult();
        result.code = '0';
        result.msg = 'Copied!';
        Customer_Visit__c newCV = new Customer_Visit__c();
        Savepoint sp = Database.setSavepoint();
        try{
            String querySql1 = 'SELECT ' + Utility.getQueryStringByFieldMap(quoteLoopMap) + ' FROM Customer_Visit__c WHERE Id =:cvId';
            Customer_Visit__c thisCV = Database.query(querySql1);
            newCV = thisCV.clone(false);
            newCV.Name += '_Copy';
            newCV.Status__c = 'Not Started';
            newCV.Approval_Status__c = 'Draft';
            newCV.Visit_Date__c = null;
            newCV.Sales_Expected_Remind_Date__c = null;
            
            insert newCV;
        }catch(Exception e){
            Database.rollback(sp);
            system.debug('error message: '+e.getMessage());
            system.debug('line number: '+e.getLineNumber());
            result.code = '1';
            result.msg = Utility.getProperErrorMessage(e.getMessage());
            return JSON.serialize(result);
        }
        result.msg = newCV.Id;
        return JSON.serialize(result);
    }
}