force-app/main/default/objects/Learning_File_View_Details__c/Learning_File_View_Details__c.object-meta.xml
<CustomObject>
    <label>Learning File View Details</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning File View Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_File_View_Details__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Learning_File_View_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Learning_File_View_Details_Total__c/Learning_File_View_Details_Total__c.object-meta.xml
<CustomObject>
    <label>Learning File View Details Total</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning File View Details Total</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_File_View_Details_Total__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <formula>TEXT( User__r.Sales_Region__c )</formula>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Learning_File_View_Details_Total__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Learning_File_View_Details_Total</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Learning_Platform_Management__c/Learning_Platform_Management__c.object-meta.xml
<CustomObject>
    <label>Learning Platform Management</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Platform Management</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Platform_Management__c/fields/Person_Type__c.field-meta.xml
<CustomField>
    <fullName>Person_Type__c</fullName>
    <label>Person Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Learning_Platform_Management__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Learning_Platform_Management__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product knowledge</fullName>
            </value>
            <value>
                <fullName>competition</fullName>
            </value>
            <value>
                <fullName>Sales skill</fullName>
            </value>
            <value>
                <fullName>Corporate culture</fullName>
            </value>
            <value>
                <fullName>Strengthening of product</fullName>
            </value>
            <value>
                <fullName>Marketing case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Learning_Platform_Management__c/fields/Validity__c.field-meta.xml
<CustomField>
    <fullName>Validity__c</fullName>
    <label>Validity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>永久</fullName>
                <label>Permanent</label>
            </value>
            <value>
                <fullName>一年</fullName>
                <label>A year</label>
            </value>
            <value>
                <fullName>两年</fullName>
                <label>Two Years</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Personnel__c/Training_Personnel__c.object-meta.xml
<CustomObject>
    <label>Training Personnel</label>
    <nameField>
        <label>Training Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Personnels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Personnel__c/fields/Training_Content__c.field-meta.xml
<CustomField>
    <fullName>Training_Content__c</fullName>
    <formula>Training_Task__r.Training_Content__c</formula>
    <label>Training Content</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Personnel__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Training Personnels</relationshipLabel>
    <relationshipName>Training_Personnels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Personnel__c/fields/Training_Task_User__c.field-meta.xml
<CustomField>
    <fullName>Training_Task_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Task User</label>
    <referenceTo>Training_Task_User__c</referenceTo>
    <relationshipLabel>Training Personnels</relationshipLabel>
    <relationshipName>Training_Personnels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Personnel__c/fields/Training_Time__c.field-meta.xml
<CustomField>
    <fullName>Training_Time__c</fullName>
    <formula>Training_Task__r.Training_Time__c</formula>
    <label>Training Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training_Personnel__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Training_Personnels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Task__c/Training_Task__c.object-meta.xml
<CustomObject>
    <label>Training Task</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Training Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_Task__c/fields/Pass_Score__c.field-meta.xml
<CustomField>
    <fullName>Pass_Score__c</fullName>
    <label>Pass Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Task__c/fields/Training_Content__c.field-meta.xml
<CustomField>
    <fullName>Training_Content__c</fullName>
    <label>Training Content</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Task__c/fields/Training_Time__c.field-meta.xml
<CustomField>
    <fullName>Training_Time__c</fullName>
    <label>Training Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training_Task_User__c/Training_Task_User__c.object-meta.xml
<CustomObject>
    <label>Training Task User</label>
    <nameField>
        <displayFormat>TTU-{YYYY}{MM}-{0000}</displayFormat>
        <label>Training Task User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Task Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Task_User__c/fields/Training_Task__c.field-meta.xml
<CustomField>
    <fullName>Training_Task__c</fullName>
    <label>Training Task</label>
    <referenceTo>Training_Task__c</referenceTo>
    <relationshipLabel>Training Task Users</relationshipLabel>
    <relationshipName>Training_Task_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Task_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Training_Task_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>USA(OEM)</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense Malaysia</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>American Sales Department</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa Sales Department</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific Sales Department</fullName>
            </value>
            <value>
                <fullName>Key Account Sales Department</fullName>
            </value>
            <value>
                <fullName>Europe Sales Department</fullName>
            </value>
            <value>
                <fullName>Communications Sales Department</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Thailand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>Hisense Indonesia</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense West Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Hisense Vietnam</fullName>
            </value>
            <value>
                <fullName>Hisense Philippines</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Singapore</fullName>
            </value>
            <value>
                <fullName>Hisense International</fullName>
            </value>
            <value>
                <fullName>Hisense UK</fullName>
            </value>
            <value>
                <fullName>Hisense Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Role_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Promoter</fullName>
    </customValue>
    <customValue>
        <fullName>Floorwalker</fullName>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Training Manager</fullName>
    </customValue>
    <masterLabel>Role Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hisense USA</fullName>
    </customValue>
    <customValue>
        <fullName>USA(OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense South Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Japan</fullName>
    </customValue>
    <customValue>
        <fullName>American Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and Africa Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Asia-Pacific Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Key Account Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Europe Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Communications Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Home Appliances Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense India</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Panama</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Peru</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Saudi</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Vietnam</fullName>
    </customValue>
    <customValue>
        <fullName>ASEAN</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense West Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Sales Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UploadVideoControllerTest.cls
@isTest
private class UploadVideoControllerTest {

    static testMethod void testMethod1() {
        String profileName = '巡店员'; 
        Id profileId = [SELECT Id FROM profile WHERE Name = :profileName][0].Id; 
        User user1 = new User(alias = '区域经理', email='UploadVideoControllerTest@noemail.com',
        emailencodingkey='UTF-8', lastname='UploadVideoControllerTest', languagelocalekey='en_US',
        localesidkey='en_US',profileid = profileId,country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='UploadVideoControllerTest@noemail.com',Sales_Region__c='Hisense South Africa');
        INSERT user1;

        
        Training_Task__c tt = new Training_Task__c();
        tt.Training_Content__c = '培训任务-001';
        tt.Pass_Score__c = 1;
        tt.Training_Time__c = Datetime.now();
        tt.Approval_Status__c = 'Approved';
        insert tt;
        // 添加培训人员
        Training_Task_User__c ttu = new Training_Task_User__c();
        ttu.Training_Task__c = tt.id;
        ttu.User__c = UserInfo.getUserId();
        insert ttu;
        // 培训人员
        Training_Personnel__c tp = new Training_Personnel__c();
        tp.Training_Task__c = tt.id;
        tp.Training_Task_User__c = ttu.id;
        tp.User__c = UserInfo.getUserId();
        insert tp;

        ContentVersion contentVersion = new ContentVersion(
          Title = 'Penguins',
          PathOnClient = 'Penguins.jpg',
          VersionData = Blob.valueOf('Test Content'),
          IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = tp.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        ContentDocumentLink cdl1 = New ContentDocumentLink();
        cdl1.LinkedEntityId = tt.id;
        cdl1.ContentDocumentId = documents[0].Id;
        cdl1.shareType = 'V';
        insert cdl1;  

        Learning_Platform_Management__c lpm = new Learning_Platform_Management__c();
        lpm.Name = '1';
        lpm.Type__c = 'competition';
        lpm.Author_Email__c = 'UploadVideoControllerTest@noemail.com';
        lpm.Validity__c = '永久';
        lpm.Sales_Region__c = 'Hisense USA';
        lpm.Person_Type__c = 'Promoter';
        insert lpm;
        
        Test.startTest();

        UploadVideoController.saveData(tp.id);
        UploadVideoController.saveData(null);

        UploadVideoController.getAttachedDocuments(tp.Id);
        UploadVideoController.getTrainingTaskAttachedDocuments(tp.Id);
        UploadVideoController.getAttachedDocuments(null);
        UploadVideoController.getTrainingTaskAttachedDocuments(null);

        UploadVideoController.verifyPublication(tp.id);

        UploadVideoController.saveCheckFileDetail(tp.id, 'a1', 'a2', 'a3');
        UploadVideoController.saveCheckFileDetail(null, 'a1', 'a2', 'a3');

        UploadVideoController.deleteFile(documents[0].Id);
        UploadVideoController.deleteFile(null);

        UploadVideoController.saveFileViewDetail('Learning_File_View_Details__c', 'Learning_File_View_Details_Total__c' , lpm.Id,  documents[0].Id, 'test11');

        Test.stopTest();
    }
}