force-app/main/default/objects/Message_Read_State__c/Message_Read_State__c.object-meta.xml
<CustomObject>
    <label>留言读取状态</label>
    <nameField>
        <displayFormat>MRS-{YYYYMMDD}-{00000000}</displayFormat>
        <label>留言读取状态编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>留言读取状态</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Message_Read_State__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Target_User__c + Shop_Message_Board__c</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Message_Read_State__c/fields/Shop_Message_Board__c.field-meta.xml
<CustomField>
    <fullName>Shop_Message_Board__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>留言板</label>
    <referenceTo>Shop_Message_Board__c</referenceTo>
    <relationshipLabel>留言读取状态</relationshipLabel>
    <relationshipName>Shop_Message_Board</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message_Read_State__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状态</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>未读</fullName>
            </value>
            <value>
                <fullName>已读</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Message_Read_State__c/fields/Target_User__c.field-meta.xml
<CustomField>
    <fullName>Target_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>目标用户</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Target_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop_Message_Board__c/Shop_Message_Board__c.object-meta.xml
<CustomObject>
    <label>留言板</label>
    <nameField>
        <label>主题</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>留言板</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/MessageBoardReadController.cls
public without sharing class MessageBoardReadController {
    @AuraEnabled
    public static void updateMessageBoardReadStatus(String recordId) {
        Message_Read_State__c mrsItem = new Message_Read_State__c();
        mrsItem.Target_User__c = UserInfo.getUserId();
        mrsItem.Shop_Message_Board__c = recordId;
        mrsItem.ExternalId__c = mrsItem.Target_User__c + '_' + mrsItem.Shop_Message_Board__c;
        mrsItem.Status__c = '已读';
        upsert mrsItem ExternalId__c;
    }   
}