force-app/main/default/objects/Hope_Attendance_Day__c/Hope_Attendance_Day__c.object-meta.xml
<CustomObject>
    <description>希望出勤日</description>
    <label>Hope Attendance Day</label>
    <nameField>
        <displayFormat>HAD-{YYYY}{MM}-{000000000}</displayFormat>
        <label>Hope Attendance Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hope Attendance Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hope_Attendance_Day__c/fields/X10__c.field-meta.xml
<CustomField>
    <fullName>X10__c</fullName>
    <defaultValue>false</defaultValue>
    <label>10</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promoter_Attendance__c/Promoter_Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>PA-{YYYY}{MM}{0000}</displayFormat>
        <label>考勤编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Attendance__c/fields/Attendance_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Type__c</fullName>
    <label>考勤类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>出勤日</fullName>
                <default>true</default>
                <label>出勤日</label>
            </value>
            <value>
                <fullName>休息日</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promoter_Attendance__c/fields/CheckIn_Date__c.field-meta.xml
<CustomField>
    <fullName>CheckIn_Date__c</fullName>
    <label>打卡日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promoter_Attendance__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>OwnerId + &apos;_&apos; + CheckIn_Date__c</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Promoter_Attendance__c/recordTypes/InspectorAttendace.recordType-meta.xml
<RecordType>
    <fullName>InspectorAttendace</fullName>
    <active>true</active>
    <label>巡店员考勤</label>
</RecordType>

force-app/main/default/objects/Promoter_Attendance__c/recordTypes/PromoterAttendance.recordType-meta.xml
<RecordType>
    <fullName>PromoterAttendance</fullName>
    <active>true</active>
    <label>促销员考勤</label>
</RecordType>

force-app/main/default/classes/InitAttendanceInformationBatch.cls
/**********************************************************************
* Name: InitAttendanceInformationBatch 
* Object: Promoter_Attendance__c
* Purpose: 系统每天自动生成每个巡店员/促销员的考勤空数
* Author: WFC
* Create Date: 2022-04-01
* 执行方法 Database.executeBatch(new InitAttendanceInformationBatch('2022-04-01'),200);
*************************************************************************/
public class InitAttendanceInformationBatch implements Database.Batchable<sObject> {

    public Date thisDay;
    // 巡店员简档
    public String inspectionProfile;
    // 促销员简档
    public String promoterProfile;

    public InitAttendanceInformationBatch (String thisDay) {
        this.inspectionProfile = Label.Inspection_Profile;
        this.promoterProfile = Label.Promoter_Profile;
        this.thisDay = Date.valueOf(thisDay);
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id,Profile.name FROM User WHERE Profile.name =:inspectionProfile OR Profile.name =:promoterProfile');
    }
    public void execute(Database.BatchableContext BC, List<User> userList) {
        // 今天促销员和巡店员考勤类型
        Set<String> externalIdSet = new Set<String>();
        Map<String, Boolean> hadMap = new Map<String, Boolean>();
        String year1 =  thisDay.year() + '';
        String month1 =  thisDay.month() + '';
        // 当前日期api 例：X10__c
        String dayField =  'X' + thisDay.day() + '__c';
        for (User u : userList) {
            externalIdSet.add(u.id + '_' + year1 + '_' + month1);
        }
        String sql = 'SELECT OwnerId, '+ dayField +' FROM Hope_Attendance_Day__c WHERE ExternalId__c = :externalIdSet';
        List<Hope_Attendance_Day__c> hadList =  Database.query(sql);
        for(Hope_Attendance_Day__c had : hadList){
            hadMap.put(had.OwnerId, Boolean.valueOf(had.get(dayField)));
        }
        

        // 考勤初始化
        List<Promoter_Attendance__c> promoterAttendanceAddList = new List<Promoter_Attendance__c>();
        for (User u : userList) {
            Promoter_Attendance__c paItem = new Promoter_Attendance__c();
            if(String.isNotBlank(u.Profile.name) && u.Profile.name.equals(inspectionProfile)){
                paItem.RecordTypeId = Schema.SObjectType.Promoter_Attendance__c.getRecordTypeInfosByDeveloperName().get('InspectorAttendace').getRecordTypeId();
            }else {
                paItem.RecordTypeId = Schema.SObjectType.Promoter_Attendance__c.getRecordTypeInfosByDeveloperName().get('PromoterAttendance').getRecordTypeId();
            }
            
            paItem.OwnerId = u.id;
            paItem.CheckIn_Date__c = thisDay;
            paItem.ExternalId__c = u.id + '_' + String.valueOf(paItem.CheckIn_Date__c);
            if(hadMap.get(u.id) != null && hadMap.get(u.id)){
                paItem.Attendance_Type__c = '休息日';
            }else {
                paItem.Attendance_Type__c = '出勤日';
            }
           
            promoterAttendanceAddList.add(paItem);
        }

        Database.upsert(promoterAttendanceAddList, Promoter_Attendance__c.ExternalId__c, false);
    }
    public void finish(Database.BatchableContext BC) {

    }

}