force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionConfiguration__c/CommissionConfiguration__c.object-meta.xml
<CustomObject>
    <label>Commission Configuration</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Commission Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionConfiguration__c/fields/ResponsiblePerson__c.field-meta.xml
<CustomField>
    <fullName>ResponsiblePerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hisense Indonesia</value>
        </filterItems>
        <filterItems>
            <field>Responsible_Person__c.RecordType__c</field>
            <operation>equals</operation>
            <value>促销员</value>
        </filterItems>
        <filterItems>
            <field>Responsible_Person__c.Shop_Name__r.Sales_Region__c</field>
            <operation>equals</operation>
            <value>Hisense Indonesia</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Responsible_Person__c</referenceTo>
    <relationshipLabel>Commission Configurations</relationshipLabel>
    <relationshipName>Commission_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommissionConfiguration__c/recordTypes/HisenseIndonesia.recordType-meta.xml
<RecordType>
    <fullName>HisenseIndonesia</fullName>
    <active>true</active>
    <label>Hisense Indonesia</label>
</RecordType>

force-app/main/default/objects/CommissionDetail__c/CommissionDetail__c.object-meta.xml
<CustomObject>
    <label>Commission Detail</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Commission Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CommissionDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionDetail__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission</label>
    <referenceTo>Commission__c</referenceTo>
    <relationshipName>Commission_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CommissionDetail__c/fields/CommissionConfiguration__c.field-meta.xml
<CustomField>
    <fullName>CommissionConfiguration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commission Configuration</label>
    <referenceTo>CommissionConfiguration__c</referenceTo>
    <relationshipLabel>CommissionDetails</relationshipLabel>
    <relationshipName>CommissionDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommissionDetail__c/fields/ResponsiblePerson__c.field-meta.xml
<CustomField>
    <fullName>ResponsiblePerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible Person</label>
    <referenceTo>Responsible_Person__c</referenceTo>
    <relationshipLabel>CommissionDetails</relationshipLabel>
    <relationshipName>CommissionDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommissionDetail__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>CommissionDetails</relationshipLabel>
    <relationshipName>CommissionDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/Responsible_Person__c.object-meta.xml
<CustomObject>
    <label>Responsible person</label>
    <nameField>
        <displayFormat>RP-{YYYY}{MM}{0000}</displayFormat>
        <label>门店负责人编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsible persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Responsible_Person__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>负责人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Responsible_Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>负责人类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>巡店员</fullName>
            </value>
            <value>
                <fullName>促销员</fullName>
            </value>
            <value>
                <fullName>Regional Manager</fullName>
                <label>区域经理</label>
            </value>
            <value>
                <fullName>Backup Floorwalker</fullName>
                <isActive>false</isActive>
                <label>Backup Floorwalker</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>门店名称</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Responsible_Person</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店员</label>
    <referenceTo>User</referenceTo>
    <relationshipName>shops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;USA(OEM)&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Thailand&apos;) , &apos;Hisense Thailand&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense India&apos;) , &apos;Hisense India&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Dubai&apos;) , &apos;Hisense Dubai&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;American Sales Department&apos;) , &apos;American Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Middle East and Africa Sales Department&apos;) , &apos;Middle East and Africa Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Asia-Pacific Sales Department&apos;) , &apos;Asia-Pacific Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Key Account Sales Department&apos;) , &apos;Key Account Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Europe Sales Department&apos;) , &apos;Europe Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Colombia&apos;) , &apos;Hisense Colombia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Argentina&apos;) , &apos;Hisense Argentina&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <description>销售区域</description>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sales_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hisense USA</fullName>
    </customValue>
    <customValue>
        <fullName>USA(OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense South Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Japan</fullName>
    </customValue>
    <customValue>
        <fullName>American Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and Africa Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Asia-Pacific Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Key Account Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Europe Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Communications Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Home Appliances Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense India</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Panama</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Peru</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Saudi</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Vietnam</fullName>
    </customValue>
    <customValue>
        <fullName>ASEAN</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense West Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Sales Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GenerateCommonCommissionBatch.cls
global with sharing class GenerateCommonCommissionBatch  extends LinkedListBatch{
    
    String[] userIds = null;
    Date today = null;
    Date exeDay {
        get {
            return today.addDays(-1);
        }
    }

    global GenerateCommonCommissionBatch() {
        today = System.today();
    }
    
    global GenerateCommonCommissionBatch(Date d) {
        today = d == null ? System.today() : d;
    }

    global GenerateCommonCommissionBatch(String[] userIds) {
        this();
        this.userIds = userIds;
    }

    global GenerateCommonCommissionBatch(Date d, String[] userIds) {
        this(d);
        this.userIds = userIds;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('GenerateCommonCommissionBatch start');
        String query = 'SELECT ID, Principal__c, Shop_Name__c, Shop_Name__r.Sales_Region__c FROM Responsible_Person__c WHERE Shop_Name__r.Sales_Region__c = \'Hisense Indonesia\' AND RecordType__c = \'促销员\'';
        if (userIds != null) {
            query += ' AND Principal__c IN :userIds ';
        }
        System.debug('query=' + query);
        System.debug('userIds=' + userIds);
        return Database.getQueryLocator(query);
    }

    static String getCommsionDetailDataIndexByPerson(Responsible_Person__c cc, Date d) {
        return cc.Id + '_' + d.year() + '_' + d.month();
    }

    static String getCommissionDataIndexByPerson(Responsible_Person__c cc, Date d) {
        return cc.Principal__c + '_' + d.year() + '_' + d.month();
    }

    global void execute(Database.BatchableContext BC, List<Responsible_Person__c> sobjectList) {
        
        LisqContainer psersonLc = new LisqContainer(sobjectList);
        CommissionConfiguration__c cc = (CommissionConfiguration__c)SobjectHelper.first([SELECT ID FROM CommissionConfiguration__c WHERE (StartDate__c = NULL OR StartDate__c <= :exeDay) AND (EndDate__c = NULL OR EndDate__c >= :exeDay) AND IsActive__c = TRUE AND ResponsiblePerson__c = NULL AND RecordType.DeveloperName = 'HisenseIndonesia']);
        if (cc == null) {
            System.debug('cc=null');
            return;
        }
        Map<String, Responsible_Person__c> scMap = new Map<String, Responsible_Person__c>();
        List<String> commissionDataIndexList = new List<String>();
        List<CommissionDetail__c> needCreateCommissionDetailList = new List<CommissionDetail__c>();
        for (Responsible_Person__c cf : sobjectList) {
            scMap.put(getCommsionDetailDataIndexByPerson(cf, exeDay), cf);
            commissionDataIndexList.add(getCommissionDataIndexByPerson(cf, exeDay));
        }

        if (commissionDataIndexList.size() == 0) {
            return;
        }

        Map<String, sobject> commissionMap = CalculateCommissionHelper.getCommissionMap(commissionDataIndexList, exeDay);
        Map<String, SObject> existCDMap = CalculateCommissionHelper.getCommissionDetailMap(scMap.keySet());
        for (String key : scMap.keySet()) {
            if (existCDMap.containsKey(key)) {
                System.debug(key + ' exists in existCDMap');
                continue;
            }

            Responsible_Person__c rp = scMap.get(key);
            if (!commissionMap.containsKey(getCommissionDataIndexByPerson(rp, exeDay))) {
                System.debug(getCommissionDataIndexByPerson(rp, exeDay) + ' is not found in commissionMap');
                continue;
            }

            needCreateCommissionDetailList.add(CalculateCommissionHelper.handleCommissionDetail(new CommissionDetail__c(
                Commission__c = commissionMap.get(getCommissionDataIndexByPerson(rp, exeDay)).Id,
                CommissionConfiguration__c = cc.Id,
                Store__c = rp.Shop_Name__c,
                ResponsiblePerson__c = rp.Id,
                CurrencyIsoCode = ((Commission__c)commissionMap.get(getCommissionDataIndexByPerson(rp, exeDay))).CurrencyIsoCode
            )));
        }
        
        system.debug('needCreateCommissionDetailList.size=' + needCreateCommissionDetailList.size());
        insert needCreateCommissionDetailList;
    }

}