force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Annual_Business_Revenue_Unit_10k_USD__c.field-meta.xml
<CustomField>
    <fullName>Annual_Business_Revenue_Unit_10k_USD__c</fullName>
    <description>渠道该品类年度销售额（万美元）</description>
    <inlineHelpText>Annual sales of the product line in the channel</inlineHelpText>
    <label>Annual Business Revenue (Unit: 10k USD)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Channel_Code_Formula__c.field-meta.xml
<CustomField>
    <fullName>Channel_Code_Formula__c</fullName>
    <description>从Channel_item__c 表中取Channel_Code__c的值，自动生成</description>
    <label>Channel Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Cooperating_Customer_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Cooperating_Customer_Entity_Name__c</fullName>
    <description>合作主体名称（品牌直营：同渠道名称；代理合作：填写代理名称），需校验和客户管理名称保持一致</description>
    <inlineHelpText>Cooperting Customer Entity Name. It includes brand direct operation and agent cooperation. For brand direct operation, it&apos;s the same as channel name; for agent cooperation, it should fill in the agent name.</inlineHelpText>
    <label>Cooperating  Customer Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Cooperating_Customer_SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>Cooperating_Customer_SAP_Code__c</fullName>
    <description>合作主体SAP</description>
    <inlineHelpText>Cooperating customer SAP code. For brand direct operation, it should fill in the SAP code of the channel; for agent cooperation, it should fill in the SAP code of the agent customer.</inlineHelpText>
    <label>Cooperating  Customer SAP Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Cooperating_Method__c.field-meta.xml
<CustomField>
    <fullName>Cooperating_Method__c</fullName>
    <description>合作模式，对于已合作或计划开发的渠道：若与海信直接合作，此处请填写“品牌直营”；若通过代理合作，此处请填写“代理合作”。</description>
    <inlineHelpText>It&apos;s used for cooperated channel or planning to develop channel. For channel that cooperated directly with Hisense, it should fill in brand direct operation; for channel that cooperated with Hisense through agent, it should fill in agent cooperation.</inlineHelpText>
    <label>Cooperating Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>品牌直营</fullName>
            </value>
            <value>
                <fullName>代理合作</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Cooperating_Status__c.field-meta.xml
<CustomField>
    <fullName>Cooperating_Status__c</fullName>
    <description>合作状态，分为已合作、未合作、计划开发和已停止合作四种状态。本年度有开发计划的选择“计划开发”，本年度无开发计划的选择“未合作”。</description>
    <inlineHelpText>There are three types of status: cooperated, uncooperated, and plan to develop. Fill in “plan to develop” if you have a development plan for the current year, or “uncooperated” if you do not have a development plan for the current year.</inlineHelpText>
    <label>Cooperating Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>已合作</fullName>
            </value>
            <value>
                <fullName>计划开发</fullName>
            </value>
            <value>
                <fullName>未合作</fullName>
            </value>
            <value>
                <fullName>已停止合作</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Cooperating_Time__c.field-meta.xml
<CustomField>
    <fullName>Cooperating_Time__c</fullName>
    <description>实际合作时间，具体到月份，需校验不能填未来时间（即时间小于等于导入当天所在月份）。文本格式yyyymm</description>
    <inlineHelpText>The actual time of cooperation, specific to the month, need to check can not be filled in the future time (i.e. the time is less than or equal to the import day in the month). Text format: yyyymm</inlineHelpText>
    <label>Cooperating Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>销售国家</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Hisense_Value_Share__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Value_Share__c</fullName>
    <description>海信在渠道内份额（填写上一年年度数据）</description>
    <inlineHelpText>Hisense&apos;s share in the channel (fill in the previous year&apos;s annual data)</inlineHelpText>
    <label>Hisense Value Share</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <formula>Product_Line__c + &apos;_&apos; +  SBU__c + &apos;_&apos; + Country__c + &apos;_&apos; +  Channel_Code_Formula__c</formula>
    <label>Index</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Market_Share__c.field-meta.xml
<CustomField>
    <fullName>Market_Share__c</fullName>
    <description>渠道所在国分品类的市场份额，填写上一年年度数据</description>
    <inlineHelpText>Market share by product line in the country where the channel is located, with data for the previous year.</inlineHelpText>
    <label>Market Share</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Number_of_Entered_Stores__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Entered_Stores__c</fullName>
    <description>已进驻门店数，填写上一年年度数据</description>
    <inlineHelpText>Number of entered stores, fill in the previous year&apos;s annual data</inlineHelpText>
    <label>Number of Entered Stores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Number_of_New_Store_Entering_Plan_2024__c.field-meta.xml
<CustomField>
    <fullName>Number_of_New_Store_Entering_Plan_2024__c</fullName>
    <description>2024年计划新进店数</description>
    <inlineHelpText>Number of stores planned to enter for 2024</inlineHelpText>
    <label>Number of New Store Entering Plan</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Number_of_Stores__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Stores__c</fullName>
    <description>渠道门店数，填写上一年年度数据</description>
    <inlineHelpText>Number of channel stores, fill in the previous year&apos;s annual data</inlineHelpText>
    <label>Number of Stores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Planned_Cooperating_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Cooperating_Time__c</fullName>
    <description>计划合作时间，只有“计划开发”状态的渠道需填写，具体到月份</description>
    <inlineHelpText>only “plan to develop” status of the channel to fill in, specific to the month</inlineHelpText>
    <label>Planned Cooperating Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>产品线</description>
    <label>Product Line</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <description>销售单元，匹配信数区组维表中的grp_zh（其他大区）和sub_zh（欧洲大区）</description>
    <label>SBU</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/SBU_Code__c.field-meta.xml
<CustomField>
    <fullName>SBU_Code__c</fullName>
    <description>销售单元编码，通过销售单元匹配信数区组维表中的sub_zh字段获取sub</description>
    <inlineHelpText>It acquires field sub by matching field sub_zh from HiData</inlineHelpText>
    <label>SBU Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Statistical_Year__c.field-meta.xml
<CustomField>
    <fullName>Statistical_Year__c</fullName>
    <description>统计年份，指更新渠道的年份（每年更新一次渠道）</description>
    <inlineHelpText>Statistical year, the year in which the channels were updated (channels are updated annually)</inlineHelpText>
    <label>Statistical Year</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/InterfaceLog__c.object-meta.xml
<CustomObject>
    <label>InterfaceLog</label>
    <nameField>
        <label>No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InterfaceLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InterfaceLog__c/fields/ErrorMsg__c.field-meta.xml
<CustomField>
    <fullName>ErrorMsg__c</fullName>
    <label>ErrorMsg</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/Req_Json__c.field-meta.xml
<CustomField>
    <fullName>Req_Json__c</fullName>
    <label>Req Json</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/ReturnCode__c.field-meta.xml
<CustomField>
    <fullName>ReturnCode__c</fullName>
    <label>ReturnCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendChannelToBigData.cls
/**********************************************************************
 * function:将Channel推送给大数据
 * @author:lizunxing
 * @url: /services/apexrest
 * @data: 
 * date:2024-01-31
*************************************************************************/
@RestResource(urlMapping='/SendChannelToBigData')
global with sharing class SendChannelToBigData {  

    global class AppInput{
        public String startTime; 
        public String endTime; 
        public String pageIndex;
        public String pageSize;
    }
    global class AppOutPut{
        public Integer totalPage;
        List<ChannelInfo> channelInfoList;
    }

    public class ChannelInfo {
        public String id;
        public String CreatedDate;
        public String LastModifiedDate;  
        public String productLine;
        public String SBU;
        public String country;
        public String channelName;
        public String marketShare;
        public String annualBusinessRevenueUnit10kUSD;
        public String cooperatingMethod;
        public String cooperatingCustomerEntityName;
        public String cooperatingCustomerSAPCode;
        public String cooperatingStatus;
        public String hisenseValueShare;
        public String numberOfStores;
        public String numberOfEnteredStores;
        public String numberOfNewStoreEnteringPlan2024;
        public String plannedCooperatingTime;

        public String OwnerId;
        public String IsDeleted;
        public String CurrencyIsoCode;
        public String CreatedById;
        public String LastModifiedById;
        public String SystemModstamp;
        public String LastViewedDate;
        public String LastReferencedDate;
        public String Index;
        public String Key;
        public String SBUCode;
        public String StatisticalYear;
        public String CooperatingTime;
        public String Region;
        public String ChannelCodeFormula;

    }

    @HttpPost
    global static SendChannelToBigData.AppOutPut adoPost() {

        RestRequest req = RestContext.request;
        String reqBody = req.requestBody.tostring(); 
        //String reqBody = '{"startTime":"2024-01-09 00:00:00","endTime":"2024-01-10 00:00:00"}'; 
        SendChannelToBigData.AppInput appInput = new SendChannelToBigData.AppInput();
        
        SendChannelToBigData.AppOutPut result = new SendChannelToBigData.AppOutPut();
        
        try{
            appInput = (SendChannelToBigData.AppInput)JSON.deserialize(reqBody, SendChannelToBigData.AppInput.class);

            if(String.isBlank(appInput.startTime) || String.isBlank(appInput.endTime)){
                return result;
            }

            if(String.isBlank(appInput.pageIndex)){
                appInput.pageIndex = '1';
            }

            if(String.isBlank(appInput.pageSize) || Integer.valueOf(appInput.pageSize) < 200){
                appInput.pageSize = '200';
            }

            appInput.startTime = Utility.increaseHoursInStringDate(appInput.startTime,8).replace(' ','T') + '.000+0000';
            appInput.endTime = Utility.increaseHoursInStringDate(appInput.endTime,8).replace(' ','T') + '.000+0000';

            String sql = 'select '+

            'OwnerId,'+
            'IsDeleted,'+
            'CurrencyIsoCode,'+
            'CreatedById,'+
            'LastModifiedById,'+
            'SystemModstamp,'+
            'Index__c,'+
            'Key__c,'+
            'SBU_Code__c,'+
            'Statistical_Year__c,'+
            'Cooperating_Time__c,'+


            'id,'+
            'Name,'+
            'CreatedDate,'+
            'LastModifiedDate, '+
            'Annual_Business_Revenue_Unit_10k_USD__c,'+
            'Cooperating_Customer_Entity_Name__c,'+
            'Cooperating_Customer_SAP_Code__c,'+
            'Cooperating_Method__c,'+
            'Country__c,'+
            'Hisense_Value_Share__c,'+
            'Market_Share__c,'+
            'Number_of_Entered_Stores__c,'+
            'Number_of_New_Store_Entering_Plan_2024__c,'+
            'Number_of_Stores__c,'+
            'Product_Line__c,'+
            'SBU__c,'+
            'Cooperating_Status__c,'+
            'Region__c,'+
            'Channel_Code_Formula__c,'+
            'Planned_Cooperating_Time__c'+
            ' from Channel__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            //List<Channel__c> channelList = (List<Channel__c>)Utility.getRecordListPage(sql, appInput.pageIndex, appInput.pageSize);
            List<Channel__c> channelList = Utility.apexPagination(Database.query(sql), Integer.valueOf(appInput.pageIndex), Integer.valueOf(appInput.pageSize));
            List<ChannelInfo> channelInfoList = new List<ChannelInfo>();

            for(Channel__c a : channelList){
                ChannelInfo c = new ChannelInfo();
                c.id = a.id;
                c.channelName = a.Name;
                c.CreatedDate = checkNull(a.CreatedDate + '');
                c.LastModifiedDate = checkNull(a.LastModifiedDate + '');
                c.productLine = checkNull(a.Product_Line__c);
                c.SBU = checkNull(a.SBU__c);
                c.country = checkNull(a.Country__c);
                c.marketShare = checkNull(a.Market_Share__c);
                c.annualBusinessRevenueUnit10kUSD = checkNull(a.Annual_Business_Revenue_Unit_10k_USD__c);
                c.cooperatingStatus = checkNull(a.Cooperating_Status__c);
                c.cooperatingMethod = checkNull(a.Cooperating_Method__c);
                c.cooperatingCustomerEntityName = checkNull(a.Cooperating_Customer_Entity_Name__c);
                c.cooperatingCustomerSAPCode = checkNull(a.Cooperating_Customer_SAP_Code__c);
                c.numberOfStores = checkNull(a.Number_of_Stores__c);
                c.numberOfEnteredStores = checkNull(a.Number_of_Entered_Stores__c);
                c.numberOfNewStoreEnteringPlan2024 = checkNull(a.Number_of_New_Store_Entering_Plan_2024__c);
                c.hisenseValueShare = checkNull(a.Hisense_Value_Share__c);
                c.plannedCooperatingTime = checkNull(a.Planned_Cooperating_Time__c);

                c.OwnerId = checkNull(a.OwnerId);
                c.IsDeleted = checkNull(a.IsDeleted + '');
                c.CurrencyIsoCode = checkNull(a.CurrencyIsoCode);
                c.CreatedById = checkNull(a.CreatedById);
                c.LastModifiedById = checkNull(a.LastModifiedById);
                c.SystemModstamp = checkNull(a.SystemModstamp + '');
                c.LastViewedDate = '';
                c.LastReferencedDate = '';
                c.Index = checkNull(a.Index__c);
                c.Key = checkNull(a.Key__c);
                c.SBUCode = checkNull(a.SBU_Code__c);
                c.StatisticalYear = checkNull(a.Statistical_Year__c);
                c.CooperatingTime = checkNull(a.Cooperating_Time__c);

                c.Region = checkNull(a.Region__c + '');
                c.ChannelCodeFormula = checkNull(a.Channel_Code_Formula__c + '');



                ChannelInfoList.add(c);
            }
            result.channelInfoList = channelInfoList;
            String sql1 = 'select count(id) totalNumber from Channel__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            List<AggregateResult> c = Database.query(sql1);
            result.totalPage = (Integer.valueOf(c.get(0).get('totalNumber')) + Integer.valueOf(appInput.pageSize) - 1) / Integer.valueOf(appInput.pageSize);

            System.debug('result :' + result);
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendChannelToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '1';
            ic.Req_Json__c = reqBody;
            insert ic;

            return result; 
        }catch(Exception e){
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendChannelToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '0';
            ic.Req_Json__c = reqBody;
            ic.ErrorMsg__c = e.getMessage();
            insert ic;

            return result; 
        }
    }

    public static String checkNull(String str){
        if(String.isBlank(str)){
            return '';
        }else if('null'.equals(str)){
            return '';
        }else{
            return str;
        }
    }
}