force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Channel_Code__c.field-meta.xml
<CustomField>
    <fullName>Channel_Code__c</fullName>
    <description>渠道编码，系统自动生成，同一个渠道名称只有一个渠道编码，规则：CH+5位数字，如CH00000（已废弃）</description>
    <displayFormat>CH{00000}</displayFormat>
    <label>Channel Code(Backend usage)</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>产品线</description>
    <label>Product Line</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <description>销售单元，匹配信数区组维表中的grp_zh（其他大区）和sub_zh（欧洲大区）</description>
    <label>SBU</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>Small Domestic Home Appliances</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>Sound Bar</fullName>
            </value>
            <value>
                <fullName>Hitachi Commercial AC</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>B-Monitor</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>Shop Name(Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/Responsible_Person__c.object-meta.xml
<CustomObject>
    <label>Responsible person</label>
    <nameField>
        <displayFormat>RP-{YYYY}{MM}{0000}</displayFormat>
        <label>门店负责人编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsible persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Responsible_Person__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>负责品线</description>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>门店名称</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Responsible_Person</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SA_Weekly_Sales_Target_Product__mdt/SA_Weekly_Sales_Target_Product__mdt.object-meta.xml
<CustomObject>
    <description>南非周目标动态生成模板产品</description>
    <label>SA Weekly Sales Target Product</label>
    <pluralLabel>SA Weekly Sales Target Product</pluralLabel>
</CustomObject>

force-app/main/default/objects/SA_Weekly_Sales_Target_Product__mdt/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Makro</fullName>
                <default>true</default>
                <label>Makro</label>
            </value>
            <value>
                <fullName>Game</fullName>
            </value>
            <value>
                <fullName>Hirsch</fullName>
            </value>
            <value>
                <fullName>HFC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SA_Weekly_Sales_Target_Product__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SA_Weekly_Sales_Target_Product__mdt/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
                <default>true</default>
                <label>TV</label>
            </value>
            <value>
                <fullName>Sound Bar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sampling_Target__c/Sampling_Target__c.object-meta.xml
<CustomObject>
    <label>Sampling Target</label>
    <nameField>
        <label>Sampling Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sampling Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Target__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>渠道名称（和Customer_Management__c表中的客户管理名称Management_Name__c一致）</description>
    <label>Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sampling_Target__c/fields/Channel_Code__c.field-meta.xml
<CustomField>
    <fullName>Channel_Code__c</fullName>
    <description>渠道编码（根据渠道名称匹配Customer_Management__c表的Management_Name__c字段获取Customer_Management_Name_Code__c字段）</description>
    <label>Channel Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sampling_Target__c/fields/Platform_Model__c.field-meta.xml
<CustomField>
    <fullName>Platform_Model__c</fullName>
    <description>平台型号（总部上传）</description>
    <label>Platform Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sampling_Target__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>产品线（校验和系统中已有的产品线名称一致）</description>
    <inlineHelpText>product line (matches the name of the product line already in the system)</inlineHelpText>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sampling_Target__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>大区（匹配信数区组维表rgn_zh）</description>
    <inlineHelpText>region (matching field rgn_zh from HiData)</inlineHelpText>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sampling_Target__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <description>海外公司名称（如大区为欧洲大区，则匹配信数区组维表中的sub_zh，否则匹配grp_zh）</description>
    <inlineHelpText>Overseas company name (matches sub_zh from HiData if the region is Europe, otherwise matches grp_zh)</inlineHelpText>
    <label>SBU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sampling_Target__c/fields/Total_Sample_Targeted_Qty_in_2024__c.field-meta.xml
<CustomField>
    <fullName>Total_Sample_Targeted_Qty_in_2024__c</fullName>
    <description>2024累计出样目标（无需上传，系统自动取12月目标出样数量）</description>
    <label>Total Sample Targeted Qty in 2024</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sampling_Target__c/fields/USD__c.field-meta.xml
<CustomField>
    <fullName>USD__c</fullName>
    <description>价格段（匹配信数）</description>
    <inlineHelpText>Price range (matching HiData)</inlineHelpText>
    <label>USD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>区域</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店员</label>
    <referenceTo>User</referenceTo>
    <relationshipName>shops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExportController.cls
public class ExportController{
    public List<Sampling_Target__c> sampling{ get; set; }

    public ExportController(){
        sampling = [SELECT id, Region__c, SBU__c, Channel__c, Channel_Code__c, Product_Line__c, Brand__c, Platform_Model__c, USD__c, Total_Sample_Targeted_Qty_in_2024__c
                    FROM Sampling_Target__c];
    }

    /**
     * @Param:
     * @Return:
     * @Author: WFC
     * @Date: 2024-12-10 15:14:44
     * @Description: samplingConditionUploadTemplateLWC 导出excel
     */
    @AuraEnabled
    public static List<List<Object>> getSamplingTargetData(){
        List<List<Object>> returnList = new List<List<Object>>();
        // 标题头
        List<Object> title = new List<Object>();
        title.add('大区(Region)');
        title.add('海外公司 SBU(SBU)');
        title.add('渠道名称 Channel (与渠道信息一致)');
        title.add('客户管理名称编码(Channel code)');
        title.add('产品线Product line');
        title.add('品牌Brand');
        title.add('平台型号Platform Model (系统匹配)');
        title.add('价格段Price(USD)(匹配信数)');
        title.add('2024累计出样目标Total Sample Targeted Qty in 2024');
        title.add('出样状态：包括已完成、出样中、撤样中、已撤样和仅线上销售');
        title.add('累计实际出样数量Actual Sample Qty(市场月度更新)');
        returnList.add(title);
        // 内容
        List<Sampling_Target__c> stList = [SELECT id, Region__c, SBU__c, Channel__c, Channel_Code__c, Product_Line__c, Brand__c, Platform_Model__c, USD__c, Total_Sample_Targeted_Qty_in_2024__c
                                           FROM Sampling_Target__c];
        for (Sampling_Target__c st : stList){
            //正则表达
            List<Object> body = new List<Object>();
            body.add(st.Region__c != null ? st.Region__c + '' : '');
            body.add(st.SBU__c != null ? st.SBU__c + '' : '');
            body.add(st.Channel__c != null ? st.Channel__c + '' : '');
            body.add(st.Channel_Code__c != null ? st.Channel_Code__c + '' : '');
            body.add(st.Product_Line__c != null ? st.Product_Line__c + '' : '');
            body.add(st.Brand__c != null ? st.Brand__c + '' : '');
            body.add(st.Platform_Model__c != null ? st.Platform_Model__c + '' : '');
            body.add(st.USD__c != null ? st.USD__c + '' : '');
            body.add(st.Total_Sample_Targeted_Qty_in_2024__c != null ? (st.Total_Sample_Targeted_Qty_in_2024__c + '').replaceAll('0+?$', '').replaceAll('[.]$', '') : '');
            body.add('');
            body.add('');
            returnList.add(body);
        }
        return returnList;
    }

    /**
     * @Param:
     * @Return:
     * @Author: LZX
     * @Date: 2025-02-26 15:14:44
     * @Description: samplingConditionUploadTemplateLWC 导出excel
     */
    @AuraEnabled
    public static List<List<Object>> getSAWeeklySalesTargetTemplateData(){
        List<List<Object>> returnList = new List<List<Object>>();
        // 标题头
        List<Object> title = new List<Object>();
        title.add('Sales Region');
        //title.add('Channel');
        title.add('Store');
        //title.add('Product Line');
        title.add('Model');
        title.add('From Week');
        title.add('To Week');
        title.add('RSP');
        title.add('Target');
        //title.add('');
        returnList.add(title);
        // 示例
        // List<Object> example = new List<Object>();
        // example.add('Hisense South Africa');
        // example.add('Game');
        // example.add('GAME KLERKSDORP');
        // example.add('TV');
        // example.add('75U7N');
        // example.add('WK8');
        // example.add('WK12');
        // example.add('19999');
        // example.add('30');
        // example.add('Example');
        // returnList.add(example);

        // 查询自定义元数据记录
        List<SA_Weekly_Sales_Target_Product__mdt> metadataRecords = [SELECT Id, Channel__c, Product_Line__c, Product__c FROM SA_Weekly_Sales_Target_Product__mdt order by Channel__c];
        
        Set<String> channelSet = new Set<String>();
        for (SA_Weekly_Sales_Target_Product__mdt record : metadataRecords) {
            channelSet.add(record.Channel__c);
        }
        // 内容
        List<Responsible_Person__c> stList = [select Shop_Name__r.Sales_Region__c,Shop_Name__r.Channel_Name__c,Shop_Name__r.Name from Responsible_Person__c where Shop_Name__r.Channel_item__r.SBU__c = 'Hisense South Africa' and RecordType__c = '促销员' and Shop_Name__r.Channel_Name__c in :channelSet order by Shop_Name__r.Channel_Name__c];
        Set<String> checkSet = new Set<String>();
        
        for (Responsible_Person__c st : stList){
            if(checkSet.add(st.Shop_Name__r.Sales_Region__c + st.Shop_Name__r.Channel_Name__c + st.Shop_Name__r.Name)){
                
                for (SA_Weekly_Sales_Target_Product__mdt record : metadataRecords) {
                     
                    String[] productArr = new String[] {record.Channel__c, record.Product_Line__c, record.Product__c};
                    if(!productArr[0].equals(st.Shop_Name__r.Channel_Name__c)){
                        continue;
                    }

                    List<Object> body = new List<Object>();
                    body.add(String.isNotBlank(st.Shop_Name__r.Sales_Region__c) ? st.Shop_Name__r.Sales_Region__c : '');
                    //body.add(String.isNotBlank(st.Shop_Name__r.Channel_Name__c) ? st.Shop_Name__r.Channel_Name__c : '');
                    body.add(String.isNotBlank(st.Shop_Name__r.Name) ? st.Shop_Name__r.Name : '');
                    //body.add(productArr[1]);
                    body.add(productArr[2]);
                    body.add('');
                    body.add('');
                    body.add('');
                    body.add('');
                    returnList.add(body);
                }
            }
        }
        return returnList;
    }

    // public PageReference exportGoods() {
    //     return new PageReference('/apex/ExportPage');
    // }
    // public PageReference exportSamplingTarget() {
    //     return new PageReference('/apex/ExportPage');
    // }
}