force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <displayFormat>M-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>Market Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Markets</relationshipLabel>
    <relationshipName>Markets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MarketInsight__c/MarketInsight__c.object-meta.xml
<CustomObject>
    <label>Market Insight</label>
    <nameField>
        <label>Market Insight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Insight</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MarketInsight__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Insight</relationshipLabel>
    <relationshipName>Market_Insight</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MarketInsight__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Market Insight</relationshipLabel>
    <relationshipName>Market_Insight</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MarketInsight__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Market Insight</relationshipLabel>
    <relationshipName>Market_Insight</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shop_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MarketInsightControllerTest.cls
@isTest
public class MarketInsightControllerTest {
	@IsTest
    static void testMarketInsightController(){
        Test.startTest();
        
        NewTestDataUtility.makePromoterDailyReportData();
        NewTestDataUtility.makeBrandData();
        Account customer = NewTestDataUtility.customer;
        Shop__c store = NewTestDataUtility.store;
        Account brand = NewTestDataUtility.brand;
        Market__c market = NewTestDataUtility.market;
        String recordId = market.Id;
        MarketInsightController.getInitData(recordId);
        
		MarketInsight__c item = new MarketInsight__c();
        item.Market__c = market.Id;
        item.Store__c = store.Id;
        item.Brand__c = brand.Id;
        item.Quantity__c = 2;
        insert item;
        Map<String, Object> recordDataMap = new Map<String, Object>();
        recordDataMap.put('Store__c', store.Id);
        recordDataMap.put('Brand__c', brand.Id);
        recordDataMap.put('Quantity__c', 2);
        String recordDataJson = Json.serialize(new List<Map<String, Object>>{recordDataMap});
        MarketInsightController.getInitData(recordId);
        MarketInsightController.saveRecord(recordDataJson, new List<String>(), '', recordId);
        
        Shop__c store2 = new Shop__c();
        store2.Name = 'Hi Fi Corporation NEWCASTLE2';
        store2.Account__c = customer.Id;
        insert store2;
        recordDataMap.put('Id', item.Id);
        recordDataMap.put('Store__c', store2.Id);
        recordDataMap.put('fieldsEdit', 'true');
        recordDataJson = Json.serialize(new List<Map<String, Object>>{recordDataMap});
        MarketInsightController.saveRecord(recordDataJson, new List<String>(), '', recordId);
        
        recordDataJson = Json.serialize(new List<Map<String, Object>>());
        System.debug('item.Id：' + item.Id);
        MarketInsightController.saveRecord(recordDataJson, new List<String>{item.Id}, '', recordId);  
        
        Test.stopTest();
    }
}