force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interface_Url__c/Interface_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Interface_Url</label>
</CustomObject>

force-app/main/default/objects/Interface_Url__c/fields/Basic_Url__c.field-meta.xml
<CustomField>
    <fullName>Basic_Url__c</fullName>
    <label>Basic Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping__c/Mapping__c.object-meta.xml
<CustomObject>
    <label>对应关系</label>
    <nameField>
        <label>Original Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Product__c/SAP_Product__c.object-meta.xml
<CustomObject>
    <label>SAP Product</label>
    <nameField>
        <label>SAP Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <referenceTo>Mapping__c</referenceTo>
    <relationshipLabel>SAP Product</relationshipLabel>
    <relationshipName>SAP_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/BREIT__c.field-meta.xml
<CustomField>
    <fullName>BREIT__c</fullName>
    <description>宽度</description>
    <label>BREIT</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/BRGEW__c.field-meta.xml
<CustomField>
    <fullName>BRGEW__c</fullName>
    <description>毛重</description>
    <label>BRGEW</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/EAN11__c.field-meta.xml
<CustomField>
    <fullName>EAN11__c</fullName>
    <description>国际文件号(EAN/UPC)</description>
    <label>EAN11</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/External_key__c.field-meta.xml
<CustomField>
    <fullName>External_key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>外键  销售组织 + 客户型号（ZCUSTOMER）</description>
    <externalId>true</externalId>
    <label>External key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/GEWEI__c.field-meta.xml
<CustomField>
    <fullName>GEWEI__c</fullName>
    <description>重量单位</description>
    <label>GEWEI</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/GROES__c.field-meta.xml
<CustomField>
    <fullName>GROES__c</fullName>
    <description>大小/量纲</description>
    <label>GROES</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/GSBER__c.field-meta.xml
<CustomField>
    <fullName>GSBER__c</fullName>
    <description>业务范围</description>
    <label>GSBER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/Hisense_Entity__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Entity__c</fullName>
    <label>Hisense Entity</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/HOEHE__c.field-meta.xml
<CustomField>
    <fullName>HOEHE__c</fullName>
    <description>高度</description>
    <label>HOEHE</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/LAENG__c.field-meta.xml
<CustomField>
    <fullName>LAENG__c</fullName>
    <description>长度</description>
    <label>LAENG</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/MATKL__c.field-meta.xml
<CustomField>
    <fullName>MATKL__c</fullName>
    <description>物料组</description>
    <label>MATKL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/MEABM__c.field-meta.xml
<CustomField>
    <fullName>MEABM__c</fullName>
    <description>长度/宽度/高度的尺寸单位</description>
    <label>MEABM</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/NTGEW__c.field-meta.xml
<CustomField>
    <fullName>NTGEW__c</fullName>
    <description>净重</description>
    <label>NTGEW</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/NUMTP__c.field-meta.xml
<CustomField>
    <fullName>NUMTP__c</fullName>
    <description>国际商品编码的类别 (EAN)</description>
    <label>NUMTP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Line</label>
    <referenceTo>Mapping__c</referenceTo>
    <relationshipLabel>SAP Product (Product Line)</relationshipLabel>
    <relationshipName>SAP_Product1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/SPART__c.field-meta.xml
<CustomField>
    <fullName>SPART__c</fullName>
    <description>产品组</description>
    <label>SPART</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/VOLEH__c.field-meta.xml
<CustomField>
    <fullName>VOLEH__c</fullName>
    <description>体积单位</description>
    <label>VOLEH</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/VOLUM__c.field-meta.xml
<CustomField>
    <fullName>VOLUM__c</fullName>
    <description>业务量</description>
    <label>VOLUM</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZBRAND__c.field-meta.xml
<CustomField>
    <fullName>ZBRAND__c</fullName>
    <description>品牌</description>
    <label>ZBRAND</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZCUSMODEL__c.field-meta.xml
<CustomField>
    <fullName>ZCUSMODEL__c</fullName>
    <description>客户型号</description>
    <label>ZCUSMODEL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZDATE__c.field-meta.xml
<CustomField>
    <fullName>ZDATE__c</fullName>
    <description>导出日期</description>
    <label>ZDATE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZMMDTYPE__c.field-meta.xml
<CustomField>
    <fullName>ZMMDTYPE__c</fullName>
    <description>产品品种</description>
    <label>ZMMDTYPE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZNJWJ__c.field-meta.xml
<CustomField>
    <fullName>ZNJWJ__c</fullName>
    <description>内机/外机</description>
    <label>ZNJWJ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZPMTMODEL__c.field-meta.xml
<CustomField>
    <fullName>ZPMTMODEL__c</fullName>
    <description>推广型号</description>
    <label>ZPMTMODEL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZTYPEDSCEN__c.field-meta.xml
<CustomField>
    <fullName>ZTYPEDSCEN__c</fullName>
    <description>英文描述</description>
    <label>ZTYPEDSCEN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZZPRODH1__c.field-meta.xml
<CustomField>
    <fullName>ZZPRODH1__c</fullName>
    <description>产品层次 1</description>
    <label>ZZPRODH1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZZPRODH2__c.field-meta.xml
<CustomField>
    <fullName>ZZPRODH2__c</fullName>
    <description>产品层次2</description>
    <label>ZZPRODH2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZZPRODH3__c.field-meta.xml
<CustomField>
    <fullName>ZZPRODH3__c</fullName>
    <description>产品层次 3</description>
    <label>ZZPRODH3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZZPRODH4__c.field-meta.xml
<CustomField>
    <fullName>ZZPRODH4__c</fullName>
    <description>产品层次 4</description>
    <label>ZZPRODH4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZZPRODH5__c.field-meta.xml
<CustomField>
    <fullName>ZZPRODH5__c</fullName>
    <description>产品层次 5</description>
    <label>ZZPRODH5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Product__c/fields/ZZPRODH6__c.field-meta.xml
<CustomField>
    <fullName>ZZPRODH6__c</fullName>
    <description>产品层次 6</description>
    <label>ZZPRODH6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Call_GetProductFromSAP.cls
/******************************************************************************
 ************************
 * Name: Call_GetProductFromSAP
 * Description: 获取SAP产品信息
 * TestClassName:  Call_GetProductFromSAPTest
 * Version History: 0.01
 * Date: 2024-11-15
 * Author: lizunxing
 * Comments: 
 *******************************************************************************
 **************************/
public without sharing class Call_GetProductFromSAP{
    
    private static String url = Interface_Url__c.getValues('正式oldSAP').Basic_Url__c + 'CC_REST_GET_MATERIAL_SENDER'; //URL 
    private static String user = Interface_Url__c.getValues('正式oldSAP').User_Name__c; //账号
    private static String password = Interface_Url__c.getValues('正式oldSAP').Password__c; //密码

    //请求参数
    public class ReqInfo {
        public String DATE_FROM; //开始日期
        public String DATE_TO; //结束日期
        public String ZCUSMODEL; //客户型号
        public List<String> VKORG; //销售组织
        public String VTWEG; //分销渠道
        public String SPART; //产品组
        public String ZBRAND; //品牌
    }

    /**
     * @Param: 
     * @Return: void
     * @Author: lizunxing
     * @Date: 2024-11-15
     * @Description: 获取SAP产品信息，根据External_key__c进行upsert操作
     */
    @future(callout = true)
    public static void getProductFromSAPAll(String DATE_FROM, String DATE_TO, Integer index, Boolean allDateFlg, Boolean allHeFlg) {
        
        List<String> hisenseEntity = System.Label.GET_SAP_PRODUCT_HISENSE_ENTITY.split(',');

        List<String> VKORGS = new List<String>();
        if(index < hisenseEntity.size()){
            VKORGS.add(hisenseEntity[index]);
        }else{
            if(allDateFlg){

                if(isCurrentDate(DATE_TO)){
                    return;
                }

                // 当前时间N分钟，下一次定时时间
                DateTime reTime = System.Now().addSeconds(10);
                Integer second = reTime.second();
                Integer minute = reTime.minute();
                Integer hour = reTime.hour();  
                String con = second + ' ' + minute + ' ' + hour + ' * * ?';

                // 生成唯一值
                Blob b = Crypto.GenerateAESKey(128);
                String h = EncodingUtil.ConvertTohex(b);
                System.schedule(h, con, new GetSapProductSchedulable(h, DATE_TO, incrementDateByOneDay(DATE_TO), 0, allDateFlg, allHeFlg));
                return;
            }else{
                return;
            }
        }
                
        //请求参数
        ReqInfo reqInfo = new ReqInfo();
        reqInfo.DATE_FROM = DATE_FROM;
        reqInfo.DATE_TO = DATE_TO;
        reqInfo.VKORG = VKORGS;
        String body = JSON.serialize(reqInfo);
        System.debug('body:: ' + body); 

        //返回参数
        String bodyRes;
        try {
            Blob headerValue = Blob.valueOf(user + ':' + password);
            String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
            HttpRequest request = new HttpRequest();
            HttpResponse response = new HttpResponse();
            Http http_login = new Http();
            request.setEndpoint(url);
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setHeader('Authorization', authorizationHeader);
            request.setBody(body);
            request.setTimeout(120000); // timeout in milliseconds

            System.debug('request::: '+request);
            response = http_login.send(request);
            System.debug('response::: '+response);

            bodyRes = response.getBody();
            System.debug('bodyRes:' + bodyRes);

            if(String.isNotBlank(bodyRes) && !bodyRes.equals('""')){

                list<Mapping__c> ppList = [select Id, Name from Mapping__c where RecordType.name = 'SAP Product Line and Product Line Mapping'];
                Map<String, Sobject> ppMap = new LisqContainer(ppList).toMapS('Name');

                list<Mapping__c> brandList = [select Id, Name from Mapping__c where RecordType.name = 'Brand Code and Name Mapping'];
                Map<String, Sobject> brandMap = new LisqContainer(brandList).toMapS('Name');

                //返回参数序列化
                Map<String, Object> resInfo = (Map<String, Object>) JSON.deserializeUntyped(bodyRes);

                if(resInfo != null && resInfo.get('MATERIALS') != null && ((List<Object>)resInfo.get('MATERIALS')).size() > 0){
                    
                    //产品集合
                    List<SAP_Product__c> upsertList = new List<SAP_Product__c>();
                    //物料集合
                    //List<MAKTX__c> upsertMAKTXList = new List<MAKTX__c>();

                    //Map<String, SAP_Product__c> extKeyMap = new Map<String, SAP_Product__c>();
                    
                    for(Object obj : (List<Object>)resInfo.get('MATERIALS')){
                        
                        Map<String, Object> sp = (Map<String, Object>) obj;

                        SAP_Product__c spc = new SAP_Product__c();
                        if(sp.get('ZCUSMODEL') != null && String.isNotBlank(String.valueOf(((List<Object>)sp.get('ZCUSMODEL')).get(0)))){
                            spc.ZCUSMODEL__c = String.valueOf(((List<Object>)sp.get('ZCUSMODEL')).get(0));
                            spc.Name = String.valueOf(((List<Object>)sp.get('ZCUSMODEL')).get(0));
                        }else{
                            continue;
                        }

                        try{
                            if(sp.get('SPART') != null){
                                spc.SPART__c = String.valueOf(((List<Object>)sp.get('SPART')).get(0));
                                spc.Product_Line__c = ppMap.get(spc.SPART__c).Id == null ? null : ppMap.get(spc.SPART__c).Id;
                            }
                        }catch(Exception e){}
                        try{
                            if(sp.get('ZBRAND') != null){
                                spc.ZBRAND__c = String.valueOf(((List<Object>)sp.get('ZBRAND')).get(0));
                                spc.Brand__c = brandMap.get(spc.ZBRAND__c).Id == null ? null : brandMap.get(spc.ZBRAND__c).Id;
                            }
                        }catch(Exception e){}
                        
                        spc.MATKL__c = String.valueOf(sp.get('MATKL'));
                        spc.ZMMDTYPE__c = String.valueOf(sp.get('ZMMDTYPE'));
                        spc.ZTYPEDSCEN__c = String.valueOf(sp.get('ZTYPEDSCEN'));
                        spc.LAENG__c = String.isBlank(String.valueOf(sp.get('LAENG'))) ? null : Decimal.valueOf(String.valueOf(sp.get('LAENG')));
                        spc.BREIT__c = String.isBlank(String.valueOf(sp.get('BREIT'))) ? null : Decimal.valueOf(String.valueOf(sp.get('BREIT')));
                        spc.HOEHE__c = String.isBlank(String.valueOf(sp.get('HOEHE'))) ? null : Decimal.valueOf(String.valueOf(sp.get('HOEHE')));
                        spc.MEABM__c = String.valueOf(sp.get('MEABM'));
                        spc.BRGEW__c = String.isBlank(String.valueOf(sp.get('BRGEW'))) ? null : Decimal.valueOf(String.valueOf(sp.get('BRGEW')));
                        spc.NTGEW__c = String.isBlank(String.valueOf(sp.get('NTGEW'))) ? null : Decimal.valueOf(String.valueOf(sp.get('NTGEW')));
                        spc.GEWEI__c = String.valueOf(sp.get('GEWEI'));
                        spc.VOLUM__c = String.isBlank(String.valueOf(sp.get('VOLUM'))) ? null : Decimal.valueOf(String.valueOf(sp.get('VOLUM')));
                        spc.VOLEH__c = String.valueOf(sp.get('VOLEH'));
                        spc.GROES__c = String.valueOf(sp.get('GROES'));
                        spc.EAN11__c = String.valueOf(sp.get('EAN11'));
                        spc.NUMTP__c = String.valueOf(sp.get('NUMTP'));
                        spc.ZPMTMODEL__c = String.valueOf(sp.get('ZPMTMODEL'));
                        spc.ZNJWJ__c = String.valueOf(sp.get('ZNJWJ'));
                        spc.ZZPRODH1__c = String.valueOf(sp.get('ZZPRODH1'));
                        spc.ZZPRODH2__c = String.valueOf(sp.get('ZZPRODH2'));
                        spc.ZZPRODH3__c = String.valueOf(sp.get('ZZPRODH3'));
                        spc.ZZPRODH4__c = String.valueOf(sp.get('ZZPRODH4'));
                        spc.ZZPRODH5__c = String.valueOf(sp.get('ZZPRODH5'));
                        spc.ZZPRODH6__c = String.valueOf(sp.get('ZZPRODH6'));
                        spc.GSBER__c = String.valueOf(sp.get('GSBER'));
                        spc.ZDATE__c = String.valueOf(sp.get('ZDATE'));
                        spc.Hisense_Entity__c = VKORGS[0];

                        spc.External_key__c = spc.ZCUSMODEL__c + '-' + spc.SPART__c + '-' + spc.ZBRAND__c;

                        //物料信息
                        // if(sp.get('MAKTX') != null){
                        //     List<Object> MAKTXList = (List<Object>)sp.get('MAKTX');
                        //     for(Object obje : MAKTXList){
                        //         Map<String, Object> m = (Map<String, Object>) obje;

                        //         MAKTX__c mc = new MAKTX__c();
                        //         mc.SPRAS__c = String.valueOf(m.get('SPRAS'));

                        //         if(m.get('VKORG') != null){
                        //             mc.VKORG__c = String.valueOf(((List<Object>)m.get('VKORG')).get(0));
                        //         }
                        //         mc.MAKTX__c = String.valueOf(m.get('MAKTX'));
                        //         mc.External_key__c =  mc.VKORG__c + spc.ZCUSMODEL__c + '-' + mc.MAKTX__c;
                        //         upsertMAKTXList.add(mc);

                        //         //设置产品外键
                        //         spc.External_key__c = mc.VKORG__c + spc.ZCUSMODEL__c;

                        //         extKeyMap.put(mc.External_key__c, spc);
                        //     }
                            
                        // }else{
                        //     spc.External_key__c = spc.ZCUSMODEL__c;
                        // }

                        upsertList.add(spc);
                    }

                    //更新插入产品
                    Database.upsert(upsertList,SAP_Product__c.Fields.External_key__c,false);

                    //Batch_SapProductCreate ss  = new Batch_SapProductCreate();
		            //Database.executeBatch(ss);
                    
                    // for(MAKTX__c m : upsertMAKTXList){
                    //     //设置物料关联字段
                    //     m.SAP_Product__c = extKeyMap.get(m.External_key__c).Id;
                    // }
                    // //更新插入物料
                    // Database.upsert(upsertMAKTXList,MAKTX__c.Fields.External_key__c,false);
                }
            }
            
            //插入Log
            Utility.insertLog('Call_GetProductFromSAP', '1', body, '');
        } catch(Exception e) {
            //插入Log
            Utility.insertLog('Call_GetProductFromSAP', '0', body, 'failure: SF Call_GetProductFromSAP Failed! ' + e.getMessage());
        }finally{
            if(allHeFlg){
                // 当前时间N分钟，下一次定时时间
                DateTime reTime = System.Now().addSeconds(10);
                Integer second = reTime.second();
                Integer minute = reTime.minute();
                Integer hour = reTime.hour();  
                String con = second + ' ' + minute + ' ' + hour + ' * * ?';

                // 生成唯一值
                Blob b = Crypto.GenerateAESKey(128);
                String h = EncodingUtil.ConvertTohex(b);
                System.schedule(h, con, new GetSapProductSchedulable(h, DATE_FROM, DATE_TO, index + 1, allDateFlg, allHeFlg));
            }
        }
    }

    @future(callout = true)
    public static void getProductFromSAP(String DATE_FROM, String DATE_TO, List<String> VKORGS) {
        
        //请求参数
        ReqInfo reqInfo = new ReqInfo();
        reqInfo.DATE_FROM = DATE_FROM;
        reqInfo.DATE_TO = DATE_TO;
        reqInfo.VKORG = VKORGS;
        String body = JSON.serialize(reqInfo);
        System.debug('body:: ' + body); 

        //返回参数
        String bodyRes;
        try {
            Blob headerValue = Blob.valueOf(user + ':' + password);
            String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
            HttpRequest request = new HttpRequest();
            HttpResponse response = new HttpResponse();
            Http http_login = new Http();
            request.setEndpoint(url);
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setHeader('Authorization', authorizationHeader);
            request.setBody(body);
            request.setTimeout(120000); // timeout in milliseconds

            System.debug('request::: '+request);
            response = http_login.send(request);
            System.debug('response::: '+response);

            bodyRes = response.getBody();
            System.debug('bodyRes:' + bodyRes);

            if(String.isNotBlank(bodyRes) && !bodyRes.equals('""')){

                list<Mapping__c> ppList = [select Id, Name from Mapping__c where RecordType.name = 'SAP Product Line and Product Line Mapping'];
                Map<String, Sobject> ppMap = new LisqContainer(ppList).toMapS('Name');

                list<Mapping__c> brandList = [select Id, Name from Mapping__c where RecordType.name = 'Brand Code and Name Mapping'];
                Map<String, Sobject> brandMap = new LisqContainer(brandList).toMapS('Name');

                //返回参数序列化
                Map<String, Object> resInfo = (Map<String, Object>) JSON.deserializeUntyped(bodyRes);

                if(resInfo != null && resInfo.get('MATERIALS') != null && ((List<Object>)resInfo.get('MATERIALS')).size() > 0){
                    
                    //产品集合
                    List<SAP_Product__c> upsertList = new List<SAP_Product__c>();
                    //物料集合
                    //List<MAKTX__c> upsertMAKTXList = new List<MAKTX__c>();

                    //Map<String, SAP_Product__c> extKeyMap = new Map<String, SAP_Product__c>();
                    
                    for(Object obj : (List<Object>)resInfo.get('MATERIALS')){
                        
                        Map<String, Object> sp = (Map<String, Object>) obj;

                        SAP_Product__c spc = new SAP_Product__c();
                        if(sp.get('ZCUSMODEL') != null && String.isNotBlank(String.valueOf(((List<Object>)sp.get('ZCUSMODEL')).get(0)))){
                            spc.ZCUSMODEL__c = String.valueOf(((List<Object>)sp.get('ZCUSMODEL')).get(0));
                            spc.Name = String.valueOf(((List<Object>)sp.get('ZCUSMODEL')).get(0));
                        }else{
                            continue;
                        }

                        try{
                            if(sp.get('SPART') != null){
                                spc.SPART__c = String.valueOf(((List<Object>)sp.get('SPART')).get(0));
                                spc.Product_Line__c = ppMap.get(spc.SPART__c).Id == null ? null : ppMap.get(spc.SPART__c).Id;
                            }
                        }catch(Exception e){}
                        try{
                            if(sp.get('ZBRAND') != null){
                                spc.ZBRAND__c = String.valueOf(((List<Object>)sp.get('ZBRAND')).get(0));
                                spc.Brand__c = brandMap.get(spc.ZBRAND__c).Id == null ? null : brandMap.get(spc.ZBRAND__c).Id;
                            }
                        }catch(Exception e){}
                        
                        spc.MATKL__c = String.valueOf(sp.get('MATKL'));
                        spc.ZMMDTYPE__c = String.valueOf(sp.get('ZMMDTYPE'));
                        spc.ZTYPEDSCEN__c = String.valueOf(sp.get('ZTYPEDSCEN'));
                        spc.LAENG__c = String.isBlank(String.valueOf(sp.get('LAENG'))) ? null : Decimal.valueOf(String.valueOf(sp.get('LAENG')));
                        spc.BREIT__c = String.isBlank(String.valueOf(sp.get('BREIT'))) ? null : Decimal.valueOf(String.valueOf(sp.get('BREIT')));
                        spc.HOEHE__c = String.isBlank(String.valueOf(sp.get('HOEHE'))) ? null : Decimal.valueOf(String.valueOf(sp.get('HOEHE')));
                        spc.MEABM__c = String.valueOf(sp.get('MEABM'));
                        spc.BRGEW__c = String.isBlank(String.valueOf(sp.get('BRGEW'))) ? null : Decimal.valueOf(String.valueOf(sp.get('BRGEW')));
                        spc.NTGEW__c = String.isBlank(String.valueOf(sp.get('NTGEW'))) ? null : Decimal.valueOf(String.valueOf(sp.get('NTGEW')));
                        spc.GEWEI__c = String.valueOf(sp.get('GEWEI'));
                        spc.VOLUM__c = String.isBlank(String.valueOf(sp.get('VOLUM'))) ? null : Decimal.valueOf(String.valueOf(sp.get('VOLUM')));
                        spc.VOLEH__c = String.valueOf(sp.get('VOLEH'));
                        spc.GROES__c = String.valueOf(sp.get('GROES'));
                        spc.EAN11__c = String.valueOf(sp.get('EAN11'));
                        spc.NUMTP__c = String.valueOf(sp.get('NUMTP'));
                        spc.ZPMTMODEL__c = String.valueOf(sp.get('ZPMTMODEL'));
                        spc.ZNJWJ__c = String.valueOf(sp.get('ZNJWJ'));
                        spc.ZZPRODH1__c = String.valueOf(sp.get('ZZPRODH1'));
                        spc.ZZPRODH2__c = String.valueOf(sp.get('ZZPRODH2'));
                        spc.ZZPRODH3__c = String.valueOf(sp.get('ZZPRODH3'));
                        spc.ZZPRODH4__c = String.valueOf(sp.get('ZZPRODH4'));
                        spc.ZZPRODH5__c = String.valueOf(sp.get('ZZPRODH5'));
                        spc.ZZPRODH6__c = String.valueOf(sp.get('ZZPRODH6'));
                        spc.GSBER__c = String.valueOf(sp.get('GSBER'));
                        spc.ZDATE__c = String.valueOf(sp.get('ZDATE'));
                        spc.Hisense_Entity__c = VKORGS[0];

                        spc.External_key__c = spc.ZCUSMODEL__c + '-' + spc.SPART__c + '-' + spc.ZBRAND__c;

                        //物料信息
                        // if(sp.get('MAKTX') != null){
                        //     List<Object> MAKTXList = (List<Object>)sp.get('MAKTX');
                        //     for(Object obje : MAKTXList){
                        //         Map<String, Object> m = (Map<String, Object>) obje;

                        //         MAKTX__c mc = new MAKTX__c();
                        //         mc.SPRAS__c = String.valueOf(m.get('SPRAS'));

                        //         if(m.get('VKORG') != null){
                        //             mc.VKORG__c = String.valueOf(((List<Object>)m.get('VKORG')).get(0));
                        //         }
                        //         mc.MAKTX__c = String.valueOf(m.get('MAKTX'));
                        //         mc.External_key__c =  mc.VKORG__c + spc.ZCUSMODEL__c + '-' + mc.MAKTX__c;
                        //         upsertMAKTXList.add(mc);

                        //         //设置产品外键
                        //         spc.External_key__c = mc.VKORG__c + spc.ZCUSMODEL__c;

                        //         extKeyMap.put(mc.External_key__c, spc);
                        //     }
                            
                        // }else{
                        //     spc.External_key__c = spc.ZCUSMODEL__c;
                        // }

                        upsertList.add(spc);
                    }

                    //更新插入产品
                    Database.upsert(upsertList,SAP_Product__c.Fields.External_key__c,false);

                    //Batch_SapProductCreate ss  = new Batch_SapProductCreate();
		            //Database.executeBatch(ss);
                    
                    // for(MAKTX__c m : upsertMAKTXList){
                    //     //设置物料关联字段
                    //     m.SAP_Product__c = extKeyMap.get(m.External_key__c).Id;
                    // }
                    // //更新插入物料
                    // Database.upsert(upsertMAKTXList,MAKTX__c.Fields.External_key__c,false);
                }
            }
            
            //插入Log
            Utility.insertLog('Call_GetProductFromSAP', '1', body, '');
        } catch(Exception e) {
            //插入Log
            Utility.insertLog('Call_GetProductFromSAP', '0', body, 'failure: SF Call_GetProductFromSAP Failed! ' + e.getMessage());
        }
    }

    public static String incrementDateByOneDay(String dateStr) {
        // 将字符串转换为日期
        Date inputDate = Date.valueOf(dateStr.substring(0, 4) + '-' + dateStr.substring(4, 6) + '-' + dateStr.substring(6, 8));
        // 增加一天
        Date newDate = inputDate.addDays(1);
        // 将Date转换为DateTime以便使用format方法
        DateTime newDateTime = DateTime.newInstance(newDate.year(), newDate.month(), newDate.day());
        // 将新日期转换回字符串
        return newDateTime.format('yyyyMMdd');
    }

    public static Boolean isCurrentDate(String dateStr) {
        // 将字符串转换为日期
        Date inputDate = Date.valueOf(dateStr.substring(0, 4) + '-' + dateStr.substring(4, 6) + '-' + dateStr.substring(6, 8));
        // 获取当前日期
        Date currentDate = Date.today();
        // 比较两个日期
        return inputDate == currentDate;
    }
}