force-app/main/default/objects/Promoter_Cost__c/Promoter_Cost__c.object-meta.xml
<CustomObject>
    <label>Promoter Cost</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Promoter Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoter Cost</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Cost__c/fields/Year_Month__c.field-meta.xml
<CustomField>
    <fullName>Year_Month__c</fullName>
    <label>Year Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendPromoterCostToBigDataTest.cls
@isTest
private class SendPromoterCostToBigDataTest {
    static testMethod void testMethod1() {
        Test.startTest();

        Promoter_Cost__c c = new Promoter_Cost__c(
            Year_Month__c = '1'
        );

        insert c;

        RestRequest req = new RestRequest();
		req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = Blob.valueOf('{"startTime":"2023-12-01 00:00:00","endTime":"2050-02-10 00:00:00"}');
		SendPromoterCostToBigData.adoPost();
        req.requestBody = Blob.valueOf('{"startTime":"2023-12-01 00:00:00","en');
        SendPromoterCostToBigData.adoPost();
        Test.stopTest();
    }
}