force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>岗位</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>岗位编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>只能包含字母数字字符，必须以字母开头，不能以下划线字符结尾或包含两个连续的下划线字符，而且在所有岗位中必须是唯一的;</inlineHelpText>
    <label>岗位小组名</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position__c/fields/GroupId__c.field-meta.xml
<CustomField>
    <fullName>GroupId__c</fullName>
    <externalId>true</externalId>
    <label>岗位用户组ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position_Member__c/Position_Member__c.object-meta.xml
<CustomObject>
    <label>岗位成员</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>岗位成员编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位成员</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_Member__c/fields/External_Key_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Key_ID__c</fullName>
    <externalId>true</externalId>
    <label>*Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position_Member__c/fields/GroupId__c.field-meta.xml
<CustomField>
    <fullName>GroupId__c</fullName>
    <formula>Position__r.GroupId__c</formula>
    <label>GroupID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position_Member__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>岗位</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>岗位成员</relationshipLabel>
    <relationshipName>Position</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>用户</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/Position_Permissions__c.object-meta.xml
<CustomObject>
    <label>岗位权限</label>
    <nameField>
        <displayFormat>PER-{00000000}</displayFormat>
        <label>岗位权限编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位权限</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_Permissions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Account_Channel_Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>岗位</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Position_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Position_Permissions_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PositionMemberCreateHandler.cls
/**
 * @description       : 
 * @author            : chenpeng@deloitte.com.cn
 * @group             : 
 * @last modified on  : 03-15-2022
 * @last modified by  : chenpeng@deloitte.com.cn
**/
public withOut sharing class PositionMemberCreateHandler implements Triggers.Handler {
    public void handle() {
        if(Trigger.isBefore && Trigger.isInsert) {
            List<GroupMember> insertGmList = new List<GroupMember>();
            Set<String> posIdSet = new Set<String>();

            List<Position_Member__c> newPosMemList = (List<Position_Member__c>)Trigger.new;
            for (Position_Member__c pm : newPosMemList) {
                posIdSet.add(pm.Position__c);
            }
            Map<Id, Position__c> positionGroupMap = new Map<Id, Position__c>();
            positionGroupMap = queryPosition(posIdSet);

            System.debug(LoggingLevel.INFO, '*** positionGroupMap: ' + positionGroupMap);
            for (Position_Member__c pm : newPosMemList) {
                if(positionGroupMap.get(pm.Position__c) != null) {
                    String ExternalKeyID = positionGroupMap.get(pm.Position__c).GroupId__c + '-' + pm.User__c;
                    System.debug(LoggingLevel.INFO, '*** ExternalKeyID: ' + ExternalKeyID);
                    pm.External_Key_ID__c = ExternalKeyID;
                    
                }
            }
        }

        if(Trigger.isAfter && Trigger.isInsert) {
            List<Position_Member__c> newPosMemList = (List<Position_Member__c>)Trigger.new;
            List<GroupMember> insertGmList = new List<GroupMember>();

            Map<String, Set<String>> posMemberSetMap = new Map<String, Set<String>>();
            for (Position_Member__c pm : newPosMemList) {
                posMemberSetMap.put(pm.Position__c, new Set<String>());
                GroupMember gm = new GroupMember();
                gm.UserOrGroupId = pm.User__c;
                gm.GroupId = pm.GroupId__c;
                insertGmList.add(gm);
            }

            if (!insertGmList.isEmpty()) {
                createMember(JSON.serialize(insertGmList));
            }

            // 新增客户小组成员
            for (Position_Permissions__c per : PositionPermissionsAccShopShareService.getPostionPermissionAcc(posMemberSetMap.keySet())) {
                posMemberSetMap.get(per.Position__c).add(per.Account__c);
            }

            if (posMemberSetMap.isEmpty()) {

                return;
            }

            List<AccountTeamMember> upsertAtmList = new List<AccountTeamMember>();
            for (Position_Member__c pm : newPosMemList) {
                if (!posMemberSetMap.containsKey(pm.Position__c)) {
                    continue;
                }

                for (String strAccId : posMemberSetMap.get(pm.Position__c)) {
                    AccountTeamMember atm = new AccountTeamMember();
                    atm.AccountAccessLevel = 'Edit';
                    atm.AccountId = strAccId;
                    atm.CaseAccessLevel = 'Read';
                    atm.ContactAccessLevel = 'Read';
                    atm.OpportunityAccessLevel = 'Read';
                    atm.UserId = pm.User__c;
                    atm.TeamMemberRole = 'Sales Rep';
                    atm.Position__c = pm.Position__c;
                    atm.External_Key_ID__c = pm.Position__c + '-' + pm.User__c + '-' + strAccId;
                    upsertAtmList.add(atm);
                }
            }

            if (!upsertAtmList.isEmpty()) {
                Database.upsert(upsertAtmList, AccountTeamMember.External_Key_ID__c);
            }
        }
    }

    @future
    public static void createMember(String insertGmListJson){
        Map<String, String> groupIdMap = new Map<String, String>();
        Map<String, String> groupErrorMap = new Map<String, String>();

        //更新的岗位成员
        List<Position_Member__c> updatePossitionMemList = new List<Position_Member__c>();
        List<GroupMember> insertGmList = (List<GroupMember>)JSON.deserialize(insertGmListJson, List<GroupMember>.class);
        List<Database.SaveResult> groupMemberSrList = Database.insert(insertGmList,false);
        System.debug(LoggingLevel.INFO, '*** groupMemberSrList: ' + groupMemberSrList);
    }

    public static Map<Id, Position__c> queryPosition(Set<String> posIdSet){
        return new Map<Id, Position__c>([SELECT GroupId__c,
                                                DeveloperName__c
                                        FROM Position__c 
                                        WHERE Id IN :posIdSet]);
    }
}