force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>岗位</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>岗位编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>启用</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>只能包含字母数字字符，必须以字母开头，不能以下划线字符结尾或包含两个连续的下划线字符，而且在所有岗位中必须是唯一的;</inlineHelpText>
    <label>岗位小组名</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position__c/fields/DoesIncludeBosses__c.field-meta.xml
<CustomField>
    <fullName>DoesIncludeBosses__c</fullName>
    <defaultValue>false</defaultValue>
    <label>授予使用层次结构的访问权限</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Grouo_Name__c.field-meta.xml
<CustomField>
    <fullName>Grouo_Name__c</fullName>
    <label>岗位名</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position_Member__c/Position_Member__c.object-meta.xml
<CustomObject>
    <label>岗位成员</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>岗位成员编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位成员</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_Member__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>岗位</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>岗位成员</relationshipLabel>
    <relationshipName>Position</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PositionCreateUserGroupHandlerTest.cls
/**
 * @description       : 
 * @author            : chenpeng@deloitte.com.cn
 * @group             : 
 * @last modified on  : 03-21-2022
 * @last modified by  : chenpeng@deloitte.com.cn
**/
@isTest
private class PositionCreateUserGroupHandlerTest {
    public static Position_Member__c pm;
    public static User user1;
    public static Group gro;
    public static  Position__c pos;

    private static void makeData(){

        Id profileId = [SELECT Id FROM profile WHERE Name = 'System Administrator' OR Name = '系统管理员'][0].Id;
        user1 = new User(alias = 'test1234', email='test123888@noemail.com',
        emailencodingkey='UTF-8', lastname='Testing123', languagelocalekey='en_US',
        localesidkey='en_US', profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='test123888@noemail.com');
        INSERT user1;
	
        pos = new Position__c();
        pos.DeveloperName__c = 'FU_GUAN_PATROLCLERKTEST';
        pos.Grouo_Name__c = '福关网格巡店员TEST';
        pos.Activity__c = true;
        pos.DoesIncludeBosses__c = false;
        INSERT pos;

        pos.DoesIncludeBosses__c = true;
        UPDATE pos; 
    }

    static testMethod void testHandle() {
        makeData();
        Test.startTest();
        DELETE pos;
        Test.stopTest();
    }

}