force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>岗位</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>岗位编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_Permissions__c/Position_Permissions__c.object-meta.xml
<CustomObject>
    <label>岗位权限</label>
    <nameField>
        <displayFormat>PER-{00000000}</displayFormat>
        <label>岗位权限编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位权限</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_Permissions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Account_Channel_Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>岗位</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Position_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Position_Permissions_Shop</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shop_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PositionPermissionsAccShopShareHandler.cls
/**
 * @description       : 
 * @author            : chenpeng@deloitte.com.cn
 * @group             : 
 * @last modified on  : 03-15-2022
 * @last modified by  : chenpeng@deloitte.com.cn
**/
public withOut sharing class PositionPermissionsAccShopShareHandler implements Triggers.Handler {
    public void handle() {
        // if (System.isFuture() || System.isBatch()) {
        //     return;
        // }
        if (Trigger.isAfter && (Trigger.isInsert || Trigger.isUpdate)) {

            Map<String, Set<String>> accPositionMap = new Map<String, Set<String>>();

            Map<String, Set<String>> shopPositionMap = new Map<String, Set<String>>();
            for (Position_Permissions__c posPer : (List<Position_Permissions__c>)Trigger.new) {
                if (String.isNotBlank(posPer.Account__c)) {
                    if (accPositionMap.containsKey(posPer.Position__c)) {
                        accPositionMap.get(posPer.Position__c).add(posPer.Account__c);
                    }else {
                        accPositionMap.put(posPer.Position__c, new Set<String>{posPer.Account__c});
                    }
                }

                // if (String.isNotBlank(posPer.Shop__c)) {
                //     if (shopPositionMap.containsKey(posPer.Position__c)) {
                //         shopPositionMap.get(posPer.Position__c).add(posPer.Shop__c);
                //     }else {
                //         shopPositionMap.put(posPer.Position__c, new Set<String>{posPer.Shop__c});
                //     }
                // }
            }

            if (!accPositionMap.isEmpty()) {
                PositionPermissionsAccShopShareService.shareAccountTeam(accPositionMap);
            }
        }

        if (Trigger.isAfter && Trigger.isDelete) {
            Map<String, Set<String>> accdPositionMap = new Map<String, Set<String>>();
            for (Position_Permissions__c posPer : (List<Position_Permissions__c>)Trigger.old) {
                if (String.isNotBlank(posPer.Account__c)) {
                    if (accdPositionMap.containsKey(posPer.Position__c)) {
                        accdPositionMap.get(posPer.Position__c).add(posPer.Account__c);
                    }else {
                        accdPositionMap.put(posPer.Position__c, new Set<String>{posPer.Account__c});
                    }
                }
            }

            if (!accdPositionMap.isEmpty()) {
                PositionPermissionsAccShopShareService.deleteShareAccountTeam(accdPositionMap);
            }
        }
    }

    // private static void deleteGroup(String deleteGroupListJSON){
    //     DELETE (List<Group>)JSON.deserialize(deleteGroupListJSON, List<Group>.class);
    // }

    // public
}