force-app/main/default/objects/ExpoAreaImage__c/ExpoAreaImage__c.object-meta.xml
<CustomObject>
    <label>ExpoAreaImage</label>
    <nameField>
        <label>Title CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpoAreaImages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoAreaImage__c/fields/ExpoId__c.field-meta.xml
<CustomField>
    <fullName>ExpoId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expo Id</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>ExpoAreaImages</relationshipLabel>
    <relationshipName>ExpoAreaImages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpoBannerImage__c/ExpoBannerImage__c.object-meta.xml
<CustomObject>
    <label>ExpoBannerImage</label>
    <nameField>
        <label>More Link</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpoBannerImages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoBannerImage__c/fields/ExpoId__c.field-meta.xml
<CustomField>
    <fullName>ExpoId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expo Id</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>ExpoBannerImages</relationshipLabel>
    <relationshipName>ExpoBannerImages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpoBrandPreference__c/ExpoBrandPreference__c.object-meta.xml
<CustomObject>
    <label>ExpoBrandPreference</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpoBrandPreferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoContact__c/ExpoContact__c.object-meta.xml
<CustomObject>
    <label>ExpoContact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpoContacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoContact__c/fields/AreaCN__c.field-meta.xml
<CustomField>
    <fullName>AreaCN__c</fullName>
    <label>Area CN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoContact__c/fields/ExpoId__c.field-meta.xml
<CustomField>
    <fullName>ExpoId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expo Id</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>ExpoContacts</relationshipLabel>
    <relationshipName>ExportContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpoContact__c/fields/FirstNameEN__c.field-meta.xml
<CustomField>
    <fullName>FirstNameEN__c</fullName>
    <label>First Name EN</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoContact__c/fields/LastNameCN__c.field-meta.xml
<CustomField>
    <fullName>LastNameCN__c</fullName>
    <label>Last Name CN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoContact__c/fields/LastNameEN__c.field-meta.xml
<CustomField>
    <fullName>LastNameEN__c</fullName>
    <label>Last Name EN</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoContact__c/fields/TitilCN__c.field-meta.xml
<CustomField>
    <fullName>TitilCN__c</fullName>
    <label>Titil CN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoContact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>展会联系人</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>大区联系人</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExpoCountrysBazaar__c/ExpoCountrysBazaar__c.object-meta.xml
<CustomObject>
    <label>ExpoCountrysBazaar</label>
    <nameField>
        <label>Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpoCountrysBazaars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoCountrysBazaar__c/fields/NameEN__c.field-meta.xml
<CustomField>
    <fullName>NameEN__c</fullName>
    <label>Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoHisImage__c/ExpoHisImage__c.object-meta.xml
<CustomObject>
    <label>ExpoHisImage</label>
    <nameField>
        <label>Title CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpoHisImages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoHisImage__c/fields/ExpoId__c.field-meta.xml
<CustomField>
    <fullName>ExpoId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expo Id</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>ExpoHisImages</relationshipLabel>
    <relationshipName>ExpoHisImages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/ExpoInfo__c.object-meta.xml
<CustomObject>
    <description>展会信息</description>
    <label>Exhibition Management</label>
    <nameField>
        <label>Exhibition Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Managements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoInfo__c/fields/DisplayInThePortal__c.field-meta.xml
<CustomField>
    <fullName>DisplayInThePortal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display in the Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/LastRegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>LastRegistrationDate__c</fullName>
    <label>Last Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/TitleEN__c.field-meta.xml
<CustomField>
    <fullName>TitleEN__c</fullName>
    <label>Exhibition Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoProductPreference__c/ExpoProductPreference__c.object-meta.xml
<CustomObject>
    <label>Expo Product Preference</label>
    <nameField>
        <label>Product Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expo Product Preferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoSchedule__c/ExpoSchedule__c.object-meta.xml
<CustomObject>
    <label>ExpoSchedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpoSchedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoSchedule__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/ExpoSchedule__c/fields/ExpoDay__c.field-meta.xml
<CustomField>
    <fullName>ExpoDay__c</fullName>
    <label>Expo Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpoSchedule__c/fields/ExpoId__c.field-meta.xml
<CustomField>
    <fullName>ExpoId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ExpoId</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>ExpoSchedules</relationshipLabel>
    <relationshipName>ExpoSchedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpoSchedule__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/ExpoCallBackTest.cls
@isTest
private class ExpoCallBackTest {
    static testMethod void testMethod1() {
    	ExpoProductPreference__c f1 = new ExpoProductPreference__c(Name =  '产品');
    	INSERT f1;
    	ExpoBrandPreference__c f2 = new ExpoBrandPreference__c(Name = '品牌');
    	INSERT f2;
    	ExpoCountrysBazaar__c f3 = new ExpoCountrysBazaar__c(Name = '中国', NameEN__c = 'China');
    	INSERT f3;

    	f1.Name = '产品1';
    	UPDATE f1;
    	f2.Name = 'Brand';
    	UPDATE f2;
    	f3.Name = '中 国';
    	UPDATE f3;

   		DELETE f1;


        ExpoInfo__c e1 = new ExpoInfo__c(
        	LastRegistrationDate__c = Date.today()+15, 
        	StartDate__c = Date.today()-1, 
        	EndDate__c = Date.today()+10,
        	Name = '展会信息',
        	TitleEN__c = 'Exhibition Informatino',
        	DisplayInThePortal__c = true
        	);
        INSERT e1;

        ExpoSchedule__c e2 = new ExpoSchedule__c(
        	ExpoId__c = e1.Id,
        	ExpoDay__c = Date.today()+1,
        	StartTime__c = Time.newInstance(7, 7, 7, 7),
        	EndTime__c = Time.newInstance(17, 7, 7, 7)
        	);
        INSERT e2;

        ExpoHisImage__c e3 = new ExpoHisImage__c(
        	ExpoId__c = e1.Id,
        	Name = '展会历史图片', 
        	TitleEN__c = 'His Image'
        	);
        INSERT e3;

        ExpoContact__c e4 = new ExpoContact__c(
        	ExpoId__c = e1.Id,
        	LastNameCN__c = '张', 
        	FirstNameCN__c = '三',
            LastNameEN__c = 'Zhang', 
            FirstNameEN__c = 'San',
        	Telephone__c = '18712345678',
        	TitilCN__c = '经理',
        	AreaCN__c = '亚太',
        	Email__c = 'reereewtwela@Hisense.com',
        	Type__c = '0'
        	);
        INSERT e4;

        ExpoAreaImage__c e5 = new ExpoAreaImage__c(
        	ExpoId__c = e1.Id,
        	Name = '区域图',
        	TitleEN__c = 'Area Image');
        INSERT e5;

        ExpoBannerImage__c e6 = new ExpoBannerImage__c(
        	ExpoId__c = e1.Id,
        	Name = 'test134.com');
        INSERT e6;









    }
}