force-app/main/default/objects/Week_Research__c/Week_Research__c.object-meta.xml
<CustomObject>
    <label>门店调查要求</label>
    <nameField>
        <displayFormat>WR-{YYYY}{MM}{DD}{000000}</displayFormat>
        <label>要求编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>门店调查要求</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Week_Research__c/fields/DuplicateRemark__c.field-meta.xml
<CustomField>
    <fullName>DuplicateRemark__c</fullName>
    <label>*判重标志</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Week_Research__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>起效后方可在促销员日报显示该问题</inlineHelpText>
    <label>是否起效</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WeekResearchTriggerTest.cls
@isTest
public class WeekResearchTriggerTest {
    static testMethod void testTriggerMethod(){
		// Week_Research__c wr = new Week_Research__c();
        // //wr.Start_Date__c = Date.valueOf('2022-02-07');
        // //wr.End_Date__c = Date.valueOf('2022-02-13') ;
        // wr.DuplicateRemark__c = 'test';
        // wr.IsActive__c  = True;
		// test.startTest();
        // INSERT wr;
		// test.stopTest();  
    }
}