force-app/main/default/objects/ConsumerTraitResearch__c/ConsumerTraitResearch__c.object-meta.xml
<CustomObject>
    <label>Consumer Trait Research</label>
    <nameField>
        <label>Consumer Trait Research Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consumer Trait Research</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ConsumerTraitResearch__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consumer Trait Research</relationshipLabel>
    <relationshipName>ConsumerTraitResearch</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsumerTraitResearch__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Consumer Trait Research</relationshipLabel>
    <relationshipName>Consumer_Trait_Research</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsumerTraitResearch__c/fields/Research__c.field-meta.xml
<CustomField>
    <fullName>Research__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Research</label>
    <referenceTo>Research__c</referenceTo>
    <relationshipLabel>Consumer Trait Research</relationshipLabel>
    <relationshipName>Consumer_Trait_Research</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsumerTraitResearch__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Consumer Trait Research</relationshipLabel>
    <relationshipName>Consumer_Trait_Research</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Research__c/Research__c.object-meta.xml
<CustomObject>
    <label>Research</label>
    <nameField>
        <displayFormat>R-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>Research Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Researches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Research__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Researches</relationshipLabel>
    <relationshipName>Researches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shop_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>城市</description>
    <label>城市</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Shop_Level__c.field-meta.xml
<CustomField>
    <fullName>Shop_Level__c</fullName>
    <description>门店等级，分为S/A/B/C</description>
    <label>门店等级</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ShopLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ShopLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>PB</fullName>
    </customValue>
    <customValue>
        <fullName>SP</fullName>
    </customValue>
    <customValue>
        <fullName>W</fullName>
    </customValue>
    <customValue>
        <fullName>アンケート</fullName>
    </customValue>
    <customValue>
        <fullName>サンエー</fullName>
    </customValue>
    <customValue>
        <fullName>本部指定</fullName>
    </customValue>
    <customValue>
        <fullName>専売機</fullName>
    </customValue>
    <customValue>
        <fullName>拡販</fullName>
    </customValue>
    <customValue>
        <fullName>T01</fullName>
    </customValue>
    <customValue>
        <fullName>T02</fullName>
    </customValue>
    <customValue>
        <fullName>T03</fullName>
    </customValue>
    <customValue>
        <fullName>T04</fullName>
    </customValue>
    <customValue>
        <fullName>T05</fullName>
    </customValue>
    <customValue>
        <fullName>T06</fullName>
    </customValue>
    <customValue>
        <fullName>T07</fullName>
    </customValue>
    <customValue>
        <fullName>T08</fullName>
    </customValue>
    <customValue>
        <fullName>T09</fullName>
    </customValue>
    <customValue>
        <fullName>T10</fullName>
    </customValue>
    <customValue>
        <fullName>未知</fullName>
    </customValue>
    <customValue>
        <fullName>店格不明</fullName>
    </customValue>
    <customValue>
        <fullName>T61</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種BIC</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種KS</fullName>
    </customValue>
    <masterLabel>门店等级</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConsumerTraitResearchControllerTest.cls
@isTest
public class ConsumerTraitResearchControllerTest {
	@isTest
    static void testConsumerTraitResearchController(){
        Account customerTest = new Account();
        customerTest.Name = '测试ConsumerTraitResearch客户0628';
        Insert customerTest;

        Shop__c testShop = new Shop__c();
        testShop.name = '测试ConsumerTraitResearch门店0628(lookup)';
        testShop.City__c = '重庆';
        testShop.Account__c = customerTest.id;
        testShop.Shop_Level__c = 'A';
        Insert testShop;
        
        Research__c testResearch = new Research__c();
        // testResearch.Customer__c =  customerTest.id;
        testResearch.Shop__c = testShop.id;
        //testResearch.Name = '测试PromoterShare用';
        Insert testResearch;
        
        Product__c productTest = new Product__c();
       	productTest.Name = 'NTC-22E';
       	productTest.CurrencyIsoCode = 'USD';
       	productTest.Product_External_Id__c = 'NTC-22E-jp';
       	Insert productTest;
        
        ConsumerTraitResearch__c testConsumerTraitResearch = new ConsumerTraitResearch__c();
        testConsumerTraitResearch.Store__c = testShop.id;
        testConsumerTraitResearch.Name = '测试Consumer';
        testConsumerTraitResearch.Product__c = productTest.id;
        testConsumerTraitResearch.Research__c = testResearch.id;
        testConsumerTraitResearch.Quantity__c = 10;
        Insert testConsumerTraitResearch;
        
        Map<String,String> recordMap = new Map<String,String>();
        recordMap.put('Id',testConsumerTraitResearch.Id);
        recordMap.put('fieldsEdit','true');
        recordMap.put('Store__c',String.valueOf(testShop.id));
        recordMap.put('Name','测试Consumer');
        recordMap.put('Research__c',String.valueOf(testResearch.id));
        recordMap.put('CurrencyIsoCode','USD');
        recordMap.put('Product__c',String.valueOf(productTest.id));
        recordMap.put('Quantity__c',String.valueOf(10));
        
        Map<String,String> recordMap2 = new Map<String,String>();
        recordMap2.put('Store__c',String.valueOf(testShop.id));
        recordMap2.put('Name','测试Consumer');
        recordMap2.put('Research__c',String.valueOf(testResearch.id));
        recordMap2.put('CurrencyIsoCode','USD');
        recordMap2.put('Product__c',String.valueOf(productTest.id));
        recordMap2.put('Quantity__c',String.valueOf(10));
        
        List<Map<String,String>> recordList = new List<Map<String,String>>();
        recordList.add(recordMap);
        String recordDataJson = Json.serialize(recordList);
        
        List<Map<String,String>> recordList2 = new List<Map<String,String>>();
        recordList2.add(recordMap2);
        String recordDataJson2 = Json.serialize(recordList2);
        
        List<String> deleteList = new List<String>();
		deleteList.add(testConsumerTraitResearch.Id);  
        
        Test.startTest();
        ConsumerTraitResearchController.getInitData(testResearch.Id);
        ConsumerTraitResearchController.saveRecord(recordDataJson,deleteList,testResearch.id);
        ConsumerTraitResearchController.saveRecord(recordDataJson2,deleteList,testResearch.id);
        Test.stopTest();
        
    }
}