force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-ID-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>工单指派人</description>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>工单指派的部门</description>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>工单描述</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>工单到期日</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Histories_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Histories_Feedback__c</fullName>
    <description>工单的历史反馈记录</description>
    <label>Histories Feedback</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Newest_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Newest_Feedback__c</fullName>
    <label>Newest Feedback</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>工单优先级，分为High, Normal, Low三种</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/PromoterDailyReport__c.field-meta.xml
<CustomField>
    <fullName>PromoterDailyReport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>促销员日报编码（由促销员日报创建的工单有编码，否则为空）</description>
    <label>Promoter Daily Report</label>
    <referenceTo>Promoter_Daily_Report__c</referenceTo>
    <relationshipLabel>New Tickets</relationshipLabel>
    <relationshipName>New_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/ResponsibleDepartmentUserIds__c.field-meta.xml
<CustomField>
    <fullName>ResponsibleDepartmentUserIds__c</fullName>
    <label>Responsible Department User Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>工单状态，包括Open, Resolved, Closed三种</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>工单主题</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>指人员在分公司内部所属的部门</description>
    <label>Hisense Department</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>USA(OEM)</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense Malaysia</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>American Sales Department</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa Sales Department</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific Sales Department</fullName>
            </value>
            <value>
                <fullName>Key Account Sales Department</fullName>
            </value>
            <value>
                <fullName>Europe Sales Department</fullName>
            </value>
            <value>
                <fullName>Communications Sales Department</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Thailand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>Hisense Indonesia</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense West Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Hisense Vietnam</fullName>
            </value>
            <value>
                <fullName>Hisense Philippines</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Singapore</fullName>
            </value>
            <value>
                <fullName>Hisense International</fullName>
            </value>
            <value>
                <fullName>Hisense UK</fullName>
            </value>
            <value>
                <fullName>Hisense Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Supervisor</fullName>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Product Line Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>AfterSalesService</fullName>
        <label>After-Sales Service</label>
    </customValue>
    <customValue>
        <fullName>CTV</fullName>
    </customValue>
    <customValue>
        <fullName>WG</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WG&amp;AC</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <masterLabel>Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TicketResolvedButtonController.cls
public without sharing class TicketResolvedButtonController {
    @AuraEnabled
    public static ConResponse saveRecord(String recordId){

        System.debug('recordId：' + recordId);
        ConResponse resp = new ConResponse();
        Map<string, object> mso = new Map<string, object>();
        Ticket__c ticket = [SELECT Id, Name, Status__c, AssignedTo__c, DueDate__c, Description__c, Subject__c, Priority__c, 
                                    PromoterDailyReport__c, Newest_Feedback__c, Histories_Feedback__c
                                        FROM Ticket__c 
                                        WHERE Id = :recordId];
        
        System.Savepoint sp = Database.setSavepoint();
        try{  
            ticket.Status__c = 'Resolved';
            update ticket;

            resp.message = 'Success';
        }catch (Exception e) {
        	System.debug(LoggingLevel.ERROR, e.getMessage());
        	System.debug(LoggingLevel.ERROR, e.getStackTraceString());
        	Database.rollback(sp);
        	resp.message = e.getMessage() + '\n' + e.getStackTraceString();
        	resp.code = -1;
        }
        return resp;                             
    }

    @AuraEnabled
    public static ConResponse getInitData(String recordId){

        System.debug('recordId：' + recordId);
        ConResponse resp = new ConResponse();
        Map<string, object> mso = new Map<string, object>();
        Ticket__c ticket = [SELECT Id, Name, Status__c, AssignedTo__c, DueDate__c, Description__c, Subject__c, Priority__c, 
                                    PromoterDailyReport__c, Newest_Feedback__c, Histories_Feedback__c
                                        FROM Ticket__c 
                                        WHERE Id = :recordId];
        String message = 'Resolve this ticket.';
        Boolean notResolved = true;
        if(UserInfo.getUserId() != ticket.AssignedTo__c) {
            message = 'The ticket is not assigned to you and you cannot change its status to resolved.';
            notResolved = false;
        } else if (ticket.Status__c != 'Open') {
            message = 'This ticket has ' + ticket.Status__c + ' !';
            notResolved = false;
        }
        System.debug('message：' + message);
        mso.put('ticket', ticket);
        mso.put('message', message);
        mso.put('notResolved', notResolved);
        resp.data = mso;
        return resp;
        
    }

    @AuraEnabled
    public static ConResponse editGetInitData(String recordId){

        System.debug('recordId：' + recordId);
        ConResponse resp = new ConResponse();
        Map<string, object> mso = new Map<string, object>();
        Ticket__c ticket = [SELECT Id, Name, Status__c, AssignedTo__c, DueDate__c, Description__c, Subject__c, Priority__c, Department__c,
                                    PromoterDailyReport__c, Newest_Feedback__c, Histories_Feedback__c, OwnerId, ResponsibleDepartmentUserIds__c
                                FROM Ticket__c 
                                WHERE Id = :recordId];
        // List<String> userIdList = String.isBlank(ticket.ResponsibleDepartmentUserIds__c) ? new List<String>() : ticket.ResponsibleDepartmentUserIds__c.split(';');
        
        String userId = UserInfo.getUserId();        
        List<User> currentUser = [SELECT Id, Name, Profile.Name, Email, Sales_Region__c FROM User WHERE Id = :userId ];
        Boolean isChile = (currentUser[0].Sales_Region__c == 'Hisense Chile');
        mso.put('isChile', isChile);

        // Department User
        List<User> departmentUserList = [SELECT Id, Sales_Region__c, Department__c FROM User WHERE Department__c != NULL AND Sales_Region__c = :currentUser[0].Sales_Region__c AND IsActive = true];
        LisqContainer lc = new LisqContainer(departmentUserList);
        Map<String, LisqContainer> userGroupByDepartment = lc.GroupByS('Department__c');
        for(String item : userGroupByDepartment.keySet()) {
            mso.put(item, (new Map<Id, Sobject>(userGroupByDepartment.get(item).ToSobjectList())).keySet());
        }

        
        Boolean isOwner = (userId == ticket.OwnerId);
        Boolean isAssigned = (userId == ticket.AssignedTo__c);
        Boolean isFelipe = ((currentUser[0].Name == 'Felipe Aedo') || (currentUser[0].Email == 'felipe.aedo@hisense.com'));
    
        Set<Id> userIdList = new Set<Id>();
        if((!String.isBlank(ticket.Department__c)) && userGroupByDepartment.containsKey(ticket.Department__c)) {
            userIdList = (new Map<Id, Sobject>(userGroupByDepartment.get(ticket.Department__c).ToSobjectList())).keySet();
        }

        Boolean departmentTicket = false;
        if((ticket.AssignedTo__c == null) && (userIdList.contains(userId))) {
            isAssigned = true;
            departmentTicket = true;
            ticket.AssignedTo__c = userId;
        }
        mso.put('ticket', ticket);
        mso.put('isOwner', isOwner);
        mso.put('isAssigned', isAssigned);
        mso.put('departmentTicket', departmentTicket);
        mso.put('isFelipe', isFelipe);
        mso.put('fields', SObjectHelper.getFieldLabelMap('Ticket__c'));
        resp.data = mso;
        return resp;
    }

    @AuraEnabled
    public static ConResponse editSaveRecord(String recordJson){

        System.debug('recordJson: ' + recordJson);

        ConResponse resp = new ConResponse();
        Map<string, object> mso = new Map<string, object>();

        Ticket__c ticket = (Ticket__c)JSON.deserialize(recordJson, Ticket__c.class);

        User user = [SELECT Name FROM User WHERE Id = :UserInfo.getUserId()][0];
        // if((ticket.ResponsibleDepartmentUserIds__c != null) && ((assignedTo == null) || (assignedTo == ''))) {
        //     assignedTo = user.Id;
        // }

        if(!String.isBlank(ticket.Newest_Feedback__c)) {
            String editInfo = user.Name + '&emsp;&emsp;' + datetime.now() + '&emsp; :  <br>' + ticket.Newest_Feedback__c;
            if(ticket.Histories_Feedback__c == null) {
                ticket.Histories_Feedback__c = editInfo;
            } else {
                ticket.Histories_Feedback__c += editInfo;
            }
            ticket.Newest_Feedback__c = null;
        }   

        System.Savepoint sp = Database.setSavepoint();
        try{              

            update ticket;

            resp.message = 'Success';
        }catch (Exception e) {
        	System.debug(LoggingLevel.ERROR, e.getMessage());
        	System.debug(LoggingLevel.ERROR, e.getStackTraceString());
        	Database.rollback(sp);
        	resp.message = e.getMessage() + '\n' + e.getStackTraceString();
        	resp.code = -1;
        }
        return resp;                             
    }
    

}