force-app/main/default/objects/Learning_Platform_Management__c/Learning_Platform_Management__c.object-meta.xml
<CustomObject>
    <label>Learning Platform Management</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Platform Management</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Platform_Management__c/fields/Email_Notification__c.field-meta.xml
<CustomField>
    <fullName>Email_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Learning_Platform_Management__c/fields/Extra_Person__c.field-meta.xml
<CustomField>
    <fullName>Extra_Person__c</fullName>
    <label>Extra Person</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Learning_Platform_Management__c/fields/Person_Type__c.field-meta.xml
<CustomField>
    <fullName>Person_Type__c</fullName>
    <label>Person Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Learning_Platform_Management__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <label>Role Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Role_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>USA(OEM)</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense Malaysia</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>American Sales Department</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa Sales Department</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific Sales Department</fullName>
            </value>
            <value>
                <fullName>Key Account Sales Department</fullName>
            </value>
            <value>
                <fullName>Europe Sales Department</fullName>
            </value>
            <value>
                <fullName>Communications Sales Department</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Thailand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>Hisense Indonesia</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense West Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Hisense Vietnam</fullName>
            </value>
            <value>
                <fullName>Hisense Philippines</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Singapore</fullName>
            </value>
            <value>
                <fullName>Hisense International</fullName>
            </value>
            <value>
                <fullName>Hisense UK</fullName>
            </value>
            <value>
                <fullName>Hisense Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Role_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Promoter</fullName>
    </customValue>
    <customValue>
        <fullName>Floorwalker</fullName>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Training Manager</fullName>
    </customValue>
    <masterLabel>Role Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hisense USA</fullName>
    </customValue>
    <customValue>
        <fullName>USA(OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense South Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Japan</fullName>
    </customValue>
    <customValue>
        <fullName>American Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and Africa Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Asia-Pacific Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Key Account Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Europe Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Communications Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Home Appliances Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense India</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Panama</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Peru</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Saudi</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Vietnam</fullName>
    </customValue>
    <customValue>
        <fullName>ASEAN</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense West Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Sales Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LearningPlatformManagementHandler.cls
/*
 * @Author: WFC
 * @Date: 2024-04-26 10:00:12
 * @LastEditors: WFC
 * @LastEditTime: 2024-06-21 14:47:53
 * @Description: Learning_Platform_Management__c表trigger
 * @FilePath: \HisenseAll20240426\force-app\main\default\classes\LearningPlatformManagementHandler.cls
 */
public class LearningPlatformManagementHandler implements Triggers.Handler{
    public void handle(){
        // 同步删除关联的文件
        if (Trigger.isBefore && Trigger.isDelete){
            List<String> idList = LisqHelper.ToIds((List<Learning_Platform_Management__c>)Trigger.old);
            List<ContentDocumentLink> cdlList = [SELECT ContentDocumentId
                                                 FROM ContentDocumentLink
                                                 WHERE LinkedEntityId IN:idList];
            if (cdlList != null && cdlList.size() > 0){
                List<String> deleteSet = new LisqContainer(cdlList).SelectSField('ContentDocumentId');
                Database.delete (deleteSet);
            }
        }

        // 新建勾选发送邮件时
        if (Trigger.isAfter && Trigger.isInsert){
            Map<Learning_Platform_Management__c, List<User>> emailMap = new Map<Learning_Platform_Management__c, List<User>>();
            for (Learning_Platform_Management__c lpm : ((list<Learning_Platform_Management__c>)Trigger.new )){
                if (!lpm.Email_Notification__c){
                    continue;
                }
                String salesRegion = lpm.Sales_Region__c;
                String personType = lpm.Person_Type__c;
                String extraPerson = lpm.Extra_Person__c;
                // sql
                String sql = ' SELECT Id, Email, Name, LanguageLocaleKey From User WHERE IsActive = TRUE AND ( ';
                String sqlSalesRegion = '';
                String sqlPersonType = '';
                List<String> salesRegionList = salesRegion.split(';');
                List<String> personTypeList = personType.split(';');
                Set<String> extraPersonSet = new Set<String>();
                for (String str : salesRegionList){
                    sqlSalesRegion += '\'' + str + '\',';
                }
                for (String str : personTypeList){
                    sqlPersonType += '\'' + str + '\',';
                }
                sqlSalesRegion = sqlSalesRegion.substring(0, sqlSalesRegion.length() - 1);
                sqlPersonType = sqlPersonType.substring(0, sqlPersonType.length() - 1);

                sql += ' ( Sales_Region__c IN ( ' + sqlSalesRegion + ' ) AND Role_Type__c INCLUDES ( ' + sqlPersonType + ' ) )';
                // 特殊用户
                if (String.isNotBlank(extraPerson)){
                    extraPersonSet.addAll(extraPerson.split(','));
                    sql += ' OR Username IN :extraPersonSet ';
                }
                sql += ' ) ';
                emailMap.put(lpm, Database.query(sql));
            }
            List<Messaging.SingleEmailMessage> sendEmailList = new List<Messaging.SingleEmailMessage>();
            for (Learning_Platform_Management__c lpm : emailMap.keySet()){
                List<User> userList = emailMap.get(lpm);
                for (User u : userList){
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    // mail.setToAddresses(new List<String>{ u.Email });
                    mail.setTargetObjectId(u.Id);
                    mail.setSaveAsActivity(false);
                    mail.setSubject(lpm.Name);
                    mail.setSenderDisplayName(lpm.Author_Email__c);
                    String html = '';
                    html = '<html>' + '<head>' + '</head>' + '<body>' + '<div">';
                    html += '<P>' + String.format(Label.get('', 'Learning_Platform_Email_One', u.LanguageLocaleKey), new List<Object>{ u.Name }) + '</p>';
                    html += '<P>' + String.format(Label.get('', 'Learning_Platform_Email_Two', u.LanguageLocaleKey), new List<Object>{ lpm.Name }) + '</p>';
                    html += '</div>' + '</body>' + '</html>';
                    mail.setHtmlBody(html);
                    sendEmailList.add(mail);
                }
            }

            if (sendEmailList.size() > 0){
                if (!Test.isRunningTest()){
                    Messaging.sendEmail(sendEmailList);
                }
            }
        }
    }

}