force-app/main/default/objects/Send_Email_User__c/Send_Email_User__c.object-meta.xml
<CustomObject>
    <label>Send Email User</label>
    <nameField>
        <displayFormat>SEU-{000000}</displayFormat>
        <label>Send Email User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Send Email Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Send_Email_User__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UserControllerTest.cls
@isTest
private class UserControllerTest {
    
    static testMethod void testMethod1() {
        Profile p = [SELECT Id,Name FROM Profile WHERE Name = 'System Administrator'];
        User user1 = new User(
            Alias = 'test01', Email='test-0-01@hisensetest.com',
            EmailEncodingKey='UTF-8', LastName='sales representative', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='Asia/Kuala_Lumpur',
            UserName='test-0-01@hisensetest.com'
        );
        Database.insert(user1);

        List<String> userEmailList = new List<String>();
        userEmailList.add('test-001@test001.com');
        userEmailList.add('test-0-01@hisensetest.com');

        Send_Email_User__c seu1 = new Send_Email_User__c();
        seu1.Username__c = 'test-0-01';
        seu1.Address__c = 'test-001@test001.com';
        insert seu1;

        Send_Email_User__c seu2 = new Send_Email_User__c();
        seu2.Username__c = 'test-0-02';
        seu2.Address__c = 'test-0-01@hisensetest.com';
        insert seu2;

    	Test.startTest();
        UserController.insertUser(userEmailList);
        Test.stopTest();
    }
}