force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Application No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Login_History__c/Login_History__c.object-meta.xml
<CustomObject>
    <label>Login History</label>
    <nameField>
        <label>Login History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login Historys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Login_History__c/fields/CipherSuite__c.field-meta.xml
<CustomField>
    <fullName>CipherSuite__c</fullName>
    <label>CipherSuite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/CountryIso__c.field-meta.xml
<CustomField>
    <fullName>CountryIso__c</fullName>
    <label>CountryIso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/LoginId__c.field-meta.xml
<CustomField>
    <fullName>LoginId__c</fullName>
    <externalId>true</externalId>
    <label>LoginId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/LoginTime__c.field-meta.xml
<CustomField>
    <fullName>LoginTime__c</fullName>
    <label>LoginTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/LoginType__c.field-meta.xml
<CustomField>
    <fullName>LoginType__c</fullName>
    <label>LoginType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/LoginUrl__c.field-meta.xml
<CustomField>
    <fullName>LoginUrl__c</fullName>
    <label>LoginUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Login_Historys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>In Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LoginHistoryBatch.cls
/**************************************************************************************************
 * Name:LoginHistoryBatch
 * Purpose: 登录历史记录
 * Author: WFC
 * Create Date: 2021-02-24
 * 执行方法 Database.executeBatch(new LoginHistoryBatch(0),200);
***************************************************************************************************/
global class LoginHistoryBatch implements Database.Batchable<sObject> {
    public String query;
    public Integer type;
    public String year;
    public String month;
    public Datetime currentTime;
    public Datetime lastMonth;
    public String apiId = '0050o00000VK8f1AAD';

    global LoginHistoryBatch (Integer type, String year, String month) {
        if(type == 0){
            this.year = year;
            this.month = month;
            if (Integer.valueOf(this.month) < 10) {
                this.month = '0'+this.month;
            }
            this.currentTime = Datetime.valueOf(this.year + '-' + this.month + '-01 00:00:00');
            this.lastMonth = currentTime.addMonths(-1);
            this.query = 'SELECT id,LoginType,SourceIp,LoginTime,UserId,Application, Browser, CipherSuite, status, CountryIso, Platform,LoginUrl ' +
            'from LoginHistory where loginTime < YESTERDAY and loginTime <:currentTime and loginTime >=:lastMonth and UserId != :apiId';
        }else {
            this.query = 'SELECT id,LoginType,SourceIp,LoginTime,UserId,Application, Browser, CipherSuite, status, CountryIso, Platform,LoginUrl ' +
            'from LoginHistory where loginTime >= YESTERDAY and UserId != :apiId';
        }
        
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<LoginHistory> loginHistoryList) {
        List<Login_History__c> addList = new List<Login_History__c>();
        try{
            for(LoginHistory loginHistory : loginHistoryList){
                // LoginHistory loginHistory = (LoginHistory)so;
                Login_History__c lh = new Login_History__c();
                lh.UserId__c = loginHistory.UserId;
                lh.LoginId__c = loginHistory.id;
                lh.LoginTime__c = loginHistory.LoginTime;
                lh.LoginType__c = loginHistory.LoginType;
                lh.SourceIp__c = loginHistory.SourceIp;
                lh.Application__c = loginHistory.Application;
                lh.Browser__c = loginHistory.Browser;
                lh.CipherSuite__c = loginHistory.CipherSuite;
                lh.Status__c = loginHistory.Status;
                lh.CountryIso__c = loginHistory.CountryIso;
                lh.Platform__c = loginHistory.Platform;
                lh.LoginUrl__c = loginHistory.LoginUrl;
                addList.add(lh);
                
            }
           
            Database.insert(addList, false);
        }catch(Exception e){
            system.debug('www error message: '+e.getMessage());
            system.debug('www line number: '+e.getLineNumber());
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
  
}