force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Application No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promoter_Attendance_Rule__c/Promoter_Attendance_Rule__c.object-meta.xml
<CustomObject>
    <label>Promoter Attendance Rule</label>
    <nameField>
        <label>Promoter Attendance Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoter Attendance Rule</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Responsible_Person__c/Responsible_Person__c.object-meta.xml
<CustomObject>
    <label>Responsible person</label>
    <nameField>
        <displayFormat>RP-{YYYY}{MM}{0000}</displayFormat>
        <label>门店负责人编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsible persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Responsible_Person__c/fields/Promoter_Attendance_Rule__c.field-meta.xml
<CustomField>
    <fullName>Promoter_Attendance_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>考勤规则</label>
    <referenceTo>Promoter_Attendance_Rule__c</referenceTo>
    <relationshipName>Responsible_Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SchedulingPlan__c/SchedulingPlan__c.object-meta.xml
<CustomObject>
    <label>SchedulingPlan</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>SchedulingPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SchedulingPlan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SchedulingPlan__c/fields/Responsible_person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible person</label>
    <referenceTo>Responsible_Person__c</referenceTo>
    <relationshipLabel>SchedulingPlan</relationshipLabel>
    <relationshipName>SchedulingPlan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/SchedulingTask__c.object-meta.xml
<CustomObject>
    <label>SchedulingTask</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>SchedulingTask Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SchedulingTask</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SchedulingTask__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>SchedulingTask</relationshipLabel>
    <relationshipName>SchedulingTask</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Check_In_Attendance_Information__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Attendance_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check In Attendance Information</label>
    <referenceTo>Promoter_Attendance_Information__c</referenceTo>
    <relationshipLabel>SchedulingTask</relationshipLabel>
    <relationshipName>SchedulingTask</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Check_In_Distance__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Distance__c</fullName>
    <formula>Check_In_Attendance_Information__r.Distance__c</formula>
    <label>Check In Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Check_In_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Status__c</fullName>
    <formula>TEXT(Check_In_Attendance_Information__r.Status__c)</formula>
    <label>Check In Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Check_In_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Time__c</fullName>
    <formula>Check_In_Attendance_Information__r.CheckIn_Time__c</formula>
    <label>Check In Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Check_In_Type__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Type__c</fullName>
    <formula>TEXT(Check_In_Attendance_Information__r.Check_in_out_Type__c)</formula>
    <label>Check In Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Check_Out_Attendance_Information__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Attendance_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check Out Attendance Information</label>
    <referenceTo>Promoter_Attendance_Information__c</referenceTo>
    <relationshipLabel>SchedulingTask (Check Out Attendance Information)</relationshipLabel>
    <relationshipName>SchedulingTask1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Check_Out_Distance__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Distance__c</fullName>
    <formula>Check_Out_Attendance_Information__r.Distance__c</formula>
    <label>Check Out Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Check_Out_Status__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Status__c</fullName>
    <formula>TEXT(Check_Out_Attendance_Information__r.Status__c)</formula>
    <label>Check Out Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Check_Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Time__c</fullName>
    <formula>Check_Out_Attendance_Information__r.CheckIn_Time__c</formula>
    <label>Check Out Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Check_Out_Type__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Type__c</fullName>
    <formula>TEXT(Check_Out_Attendance_Information__r.Check_in_out_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Check Out Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/IsAbstained__c.field-meta.xml
<CustomField>
    <fullName>IsAbstained__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Abstained</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/IsImport__c.field-meta.xml
<CustomField>
    <fullName>IsImport__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Import</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/IsNormalF__c.field-meta.xml
<CustomField>
    <fullName>IsNormalF__c</fullName>
    <formula>IF(TODAY() &lt;  Scheduling_Date__c, Application__c == NULL,  
     IF( TODAY() ==  Scheduling_Date__c,  Check_In_Status__c != &apos;Late Check in&apos; &amp;&amp;  Check_Out_Status__c == &apos;Early Check out&apos;,  
        Check_In_Status__c == &apos;Check in&apos; &amp;&amp;  Check_Out_Status__c == &apos;Check out&apos; ) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Normal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Promoter_Attendance_Rule__c.field-meta.xml
<CustomField>
    <fullName>Promoter_Attendance_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promoter Attendance Rule</label>
    <referenceTo>Promoter_Attendance_Rule__c</referenceTo>
    <relationshipLabel>SchedulingTask</relationshipLabel>
    <relationshipName>SchedulingTask</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Responsible_person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible person</label>
    <referenceTo>Responsible_Person__c</referenceTo>
    <relationshipLabel>SchedulingTask</relationshipLabel>
    <relationshipName>SchedulingTask</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Scheduling_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduling_Date__c</fullName>
    <label>Scheduling Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/SchedulingPlan__c.field-meta.xml
<CustomField>
    <fullName>SchedulingPlan__c</fullName>
    <label>SchedulingPlan</label>
    <referenceTo>SchedulingPlan__c</referenceTo>
    <relationshipLabel>SchedulingTask</relationshipLabel>
    <relationshipName>SchedulingTask</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>unscheduled</fullName>
                <default>true</default>
                <label>unscheduled</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>OnLeave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>SchedulingTask</relationshipLabel>
    <relationshipName>SchedulingTask</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SchedulingTask</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店员</label>
    <referenceTo>User</referenceTo>
    <relationshipName>shops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;USA(OEM)&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Thailand&apos;) , &apos;Hisense Thailand&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense India&apos;) , &apos;Hisense India&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Dubai&apos;) , &apos;Hisense Dubai&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;American Sales Department&apos;) , &apos;American Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Middle East and Africa Sales Department&apos;) , &apos;Middle East and Africa Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Asia-Pacific Sales Department&apos;) , &apos;Asia-Pacific Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Key Account Sales Department&apos;) , &apos;Key Account Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Europe Sales Department&apos;) , &apos;Europe Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Colombia&apos;) , &apos;Hisense Colombia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Argentina&apos;) , &apos;Hisense Argentina&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <description>销售区域</description>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>In Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hisense USA</fullName>
    </customValue>
    <customValue>
        <fullName>USA(OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense South Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Japan</fullName>
    </customValue>
    <customValue>
        <fullName>American Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and Africa Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Asia-Pacific Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Key Account Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Europe Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Communications Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Home Appliances Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense India</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Panama</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Peru</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Saudi</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Vietnam</fullName>
    </customValue>
    <customValue>
        <fullName>ASEAN</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense West Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Sales Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SchedulingTaskStatusBatch.cls
global without sharing class SchedulingTaskStatusBatch extends LinkedListBatch {
    
    String salesRegion;
    Date dt = null;
    global SchedulingTaskStatusBatch() {
        dt = System.today().addDays(-1);
    }
    
    global SchedulingTaskStatusBatch(String salesRegion) {
        this();
        this.salesRegion = salesRegion;
    }

    global SchedulingTaskStatusBatch(String salesRegion, Date dt) {
        this.salesRegion = salesRegion;
        if(dt != null) {
            this.dt = dt.addDays(-1);
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('GeneratePersonalCommissionBatch ' + salesRegion + ' start');
        string query = 'SELECT Id,IsNormalF__c,IsDeleted,Name,CurrencyIsoCode,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,SystemModstamp,LastActivityDate,SchedulingPlan__c,Scheduling_Date__c,Promoter_Attendance_Rule__c,Responsible_person__c,Status__c,ExternalId__c,Application__c,Store__c,User__c,IsImport__c,Check_In_Attendance_Information__c,Check_Out_Attendance_Information__c,Check_In_Status__c,Check_In_Type__c,Check_In_Time__c,Check_In_Distance__c,Check_Out_Distance__c,Check_Out_Status__c,Check_Out_Time__c,Check_Out_Type__c';
        query += ' FROM SchedulingTask__c ';
        query += 'WHERE IsAbstained__c = false AND Application__c = NULL AND Check_In_Attendance_Information__c = NULL AND Check_Out_Attendance_Information__c = NULL';
        if(!String.isblank(salesRegion)) {
            query += ' AND Store__r.Sales_Region__c = :salesRegion ';
        }
        if (dt == null) {
            query += ' AND Scheduling_Date__c <= TODAY ';
        } else {
            query += ' AND Scheduling_Date__c = :dt ';
        }
        System.debug('query=' + query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<SchedulingTask__c> sobjectList) {
        System.debug('SchedulingTaskStatusBatch ' + salesRegion + ' start');
        for (SchedulingTask__c task : sobjectList) {
            task.IsAbstained__c	= true;
        }

        update sobjectList;
    }
}