force-app/main/default/objects/Sell_out_Inventory__c/Sell_out_Inventory__c.object-meta.xml
<CustomObject>
    <label>Sell out Inventory</label>
    <nameField>
        <displayFormat>SOI-{00000000}</displayFormat>
        <label>Sell out Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sell out Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sell_out_Inventory__c/fields/create_dt__c.field-meta.xml
<CustomField>
    <fullName>create_dt__c</fullName>
    <label>Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SetActQtyBatchSchedulable.cls
global class SetActQtyBatchSchedulable implements Schedulable {

    public String schedulable_name;

    global SetActQtyBatchSchedulable (String schedulable_name){
        this.schedulable_name = schedulable_name;
    }


    global void execute(SchedulableContext sc) {
        try {

            // 删除定时任务
            GetSellOutInventorySchedulable.deleteSchedulable(schedulable_name);

            list<Sell_out_Inventory__c> maxAr= [select create_dt__c from Sell_out_Inventory__c order by create_dt__c desc limit 1];
            String create_dt = maxAr[0].create_dt__c;

            SetActQtyBatch sqb  = new SetActQtyBatch(create_dt);
		    Database.executeBatch(sqb);

        } catch (Exception e) {
            system.debug('error message'+e.getMessage());
            Utility.insertLog('SetActQtyBatchSchedulable', '0', null,  '-----' + schedulable_name);
        }
    }
}