force-app/main/default/objects/Promoter_Attendance__c/Promoter_Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>PA-{YYYY}{MM}{0000}</displayFormat>
        <label>考勤编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Attendance__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>OwnerId + &apos;_&apos; + CheckIn_Date__c</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Promoter_Attendance__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>签到门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Promoter_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Attendance_Information__c/Promoter_Attendance_Information__c.object-meta.xml
<CustomObject>
    <label>Promoter Attendance Information</label>
    <nameField>
        <displayFormat>PAF-{0000}</displayFormat>
        <label>Promoter Attendance Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoter Attendance Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Attendance_Information__c/fields/Promoter_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Promoter_Attendance__c</fullName>
    <label>Promoter Attendance</label>
    <referenceTo>Promoter_Attendance__c</referenceTo>
    <relationshipLabel>Promoter Attendance Information</relationshipLabel>
    <relationshipName>Promoter_Attendance_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Promoter_Attendance_Information__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Promoter Attendance Information</relationshipLabel>
    <relationshipName>Promoter_Attendance_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Attendance_Information__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Check in</fullName>
            </value>
            <value>
                <fullName>Check out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promoter_Attendance_Rule__c/Promoter_Attendance_Rule__c.object-meta.xml
<CustomObject>
    <label>Promoter Attendance Rule</label>
    <nameField>
        <label>Promoter Attendance Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoter Attendance Rule</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Attendance_Rule__c/fields/End_time__c.field-meta.xml
<CustomField>
    <fullName>End_time__c</fullName>
    <label>End time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/Responsible_Person__c.object-meta.xml
<CustomObject>
    <label>Responsible person</label>
    <nameField>
        <displayFormat>RP-{YYYY}{MM}{0000}</displayFormat>
        <label>门店负责人编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsible persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Responsible_Person__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>负责人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Responsible_Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Promoter_Attendance_Rule__c.field-meta.xml
<CustomField>
    <fullName>Promoter_Attendance_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>考勤规则</label>
    <referenceTo>Promoter_Attendance_Rule__c</referenceTo>
    <relationshipName>Responsible_Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>负责人类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>巡店员</fullName>
            </value>
            <value>
                <fullName>促销员</fullName>
            </value>
            <value>
                <fullName>Regional Manager</fullName>
                <label>区域经理</label>
            </value>
            <value>
                <fullName>Backup Floorwalker</fullName>
                <isActive>false</isActive>
                <label>Backup Floorwalker</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>门店名称</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Responsible_Person</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/SchedulingTask__c.object-meta.xml
<CustomObject>
    <label>SchedulingTask</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>SchedulingTask Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SchedulingTask</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SchedulingTask__c/fields/Promoter_Attendance_Rule__c.field-meta.xml
<CustomField>
    <fullName>Promoter_Attendance_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promoter Attendance Rule</label>
    <referenceTo>Promoter_Attendance_Rule__c</referenceTo>
    <relationshipLabel>SchedulingTask</relationshipLabel>
    <relationshipName>SchedulingTask</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SchedulingTask__c/fields/Responsible_person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible person</label>
    <referenceTo>Responsible_Person__c</referenceTo>
    <relationshipLabel>SchedulingTask</relationshipLabel>
    <relationshipName>SchedulingTask</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店员</label>
    <referenceTo>User</referenceTo>
    <relationshipName>shops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;USA(OEM)&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Thailand&apos;) , &apos;Hisense Thailand&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense India&apos;) , &apos;Hisense India&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Dubai&apos;) , &apos;Hisense Dubai&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;American Sales Department&apos;) , &apos;American Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Middle East and Africa Sales Department&apos;) , &apos;Middle East and Africa Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Asia-Pacific Sales Department&apos;) , &apos;Asia-Pacific Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Key Account Sales Department&apos;) , &apos;Key Account Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Europe Sales Department&apos;) , &apos;Europe Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Colombia&apos;) , &apos;Hisense Colombia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Argentina&apos;) , &apos;Hisense Argentina&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <description>销售区域</description>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Hiper,Retail,Service,Carrier类型为阿根廷专用</description>
    <label>Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hiper</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>ChainStort</fullName>
            </value>
            <value>
                <fullName>TraditionalStore</fullName>
            </value>
            <value>
                <fullName>ChainStore</fullName>
            </value>
            <value>
                <fullName>ShopInShop</fullName>
            </value>
            <value>
                <fullName>FlagshipStore</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>USA(OEM)</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense Malaysia</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>American Sales Department</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa Sales Department</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific Sales Department</fullName>
            </value>
            <value>
                <fullName>Key Account Sales Department</fullName>
            </value>
            <value>
                <fullName>Europe Sales Department</fullName>
            </value>
            <value>
                <fullName>Communications Sales Department</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Thailand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>Hisense Indonesia</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense West Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Hisense Vietnam</fullName>
            </value>
            <value>
                <fullName>Hisense Philippines</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Singapore</fullName>
            </value>
            <value>
                <fullName>Hisense International</fullName>
            </value>
            <value>
                <fullName>Hisense UK</fullName>
            </value>
            <value>
                <fullName>Hisense Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sales_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hisense USA</fullName>
    </customValue>
    <customValue>
        <fullName>USA(OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense South Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Japan</fullName>
    </customValue>
    <customValue>
        <fullName>American Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and Africa Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Asia-Pacific Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Key Account Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Europe Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Communications Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Home Appliances Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense India</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Panama</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Peru</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Saudi</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Vietnam</fullName>
    </customValue>
    <customValue>
        <fullName>ASEAN</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense West Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Sales Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AutoCheckOutBatch.cls
public without sharing class AutoCheckOutBatch implements Database.Batchable<sObject> {

    // private Date today = System.today();
    private Date today = getSouthAfricaDate();
    private Boolean isAutoCheckOut = true;

    // 自动签退
    public AutoCheckOutBatch() {}
    // 指定日期签退
    public AutoCheckOutBatch(Date today, Boolean isAutoCheckOut) {
        this.today = today;
        this.isAutoCheckOut = isAutoCheckOut;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Shop_Name__c, Principal__c, Promoter_Attendance_Rule__c, RecordType__c  FROM Responsible_Person__c WHERE Principal__r.Sales_Region__c = \'Hisense South Africa\' AND RecordType__c =\'促销员\' AND Principal__r.IsActive = true ';
        System.debug('AutoCheckOutBatch -> query: ' + query);

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Responsible_Person__c> scope) {
        System.debug('AutoCheckOutBatch -> today: ' + today);
        System.debug('AutoCheckOutBatch -> isAutoCheckOut: ' + isAutoCheckOut);
        try {
            List<String> ruleIdList = new List<String>();
            List<String> promoterResIdList = new List<String>();
            for (Responsible_Person__c item : scope) {
                promoterResIdList.add(item.Id);
                ruleIdList.add(item.Promoter_Attendance_Rule__c);
            }

            // 考勤规则
            List<Promoter_Attendance_Rule__c> ruleList = [SELECT Id, End_time__c FROM Promoter_Attendance_Rule__c WHERE Id IN :ruleIdList];
            Map<Id, Promoter_Attendance_Rule__c> ruleMap = new Map<Id, Promoter_Attendance_Rule__c>(ruleList);
            System.debug('AutoCheckOutBatch -> ruleList: ' + ruleList.size());

            // 已签到还未签退的考勤记录
            List<Promoter_Attendance__c> attendanceList = [SELECT Id, Shop__c, ExternalId__c, Check_in_Status__c, CreatedBy.Name, Owner.Name, CheckOutShop__c, CheckIn_Date__c, SignOutTime__c, Check_out_Status__c, CheckInStatus__c FROM Promoter_Attendance__c WHERE CheckInStatus__c = '已签到' AND CheckIn_Date__c = :today AND RecordType.Name = '促销员考勤'];
            Map<String, Promoter_Attendance__c> attendanceExternalAndRecordMap = new Map<String, Promoter_Attendance__c>();
            for (Promoter_Attendance__c item : attendanceList) {
                String attExternalStr = item.ExternalId__c.split('_').size() > 2 ? item.ExternalId__c.substringBeforeLast('_') : item.ExternalId__c;
                attendanceExternalAndRecordMap.put(attExternalStr, item);
            }
            System.debug('AutoCheckOutBatch -> attendanceList: ' + attendanceList.size());

            // 排班信息
            List<SchedulingTask__c> scheduledList = [SELECT Id, Check_Out_Attendance_Information__c, Responsible_person__c FROM SchedulingTask__c WHERE Scheduling_Date__c = :today AND Responsible_person__c IN :promoterResIdList];
            Map<String, SchedulingTask__c> promoterIdAndScheduledMap = new Map<String, SchedulingTask__c>();
            for (SchedulingTask__c item : scheduledList) {
                promoterIdAndScheduledMap.put(item.Responsible_person__c, item);
            }
            System.debug('AutoCheckOutBatch -> scheduledList: ' + scheduledList.size());

            List<Promoter_Attendance__c> updateAttendanceList = new List<Promoter_Attendance__c>();
            List<Promoter_Attendance_Information__c> checkOutList = new List<Promoter_Attendance_Information__c>();
            List<SchedulingTask__c> updateScheduledList = new List<SchedulingTask__c>();
            Map<String, Promoter_Attendance_Information__c> promoterIdAndCheckOutRecordMap = new Map<String, Promoter_Attendance_Information__c>();
            Set<String> promoterIdSet = new Set<String>();
            System.debug('AutoCheckOutBatch -> ruleMap: ' + ruleMap);
            System.debug('AutoCheckOutBatch -> attendanceExternalAndRecordMap: ' + attendanceExternalAndRecordMap.keySet());
            for (Responsible_Person__c item : scope) {
                String externalId = item.Principal__c + '_' + String.valueOf(today);
                System.debug('AutoCheckOutBatch -> externalId: ' + externalId);
                if (ruleMap.containsKey(item.Promoter_Attendance_Rule__c) && attendanceExternalAndRecordMap.containsKey(externalId)) {
                    Promoter_Attendance_Rule__c rule = ruleMap.get(item.Promoter_Attendance_Rule__c);
                    Promoter_Attendance__c attendance = attendanceExternalAndRecordMap.get(externalId);
                    // 多门店负责人下避免生成多条签退记录, 自动生成的签退记录门店与签到的门店保持一致
                    if (item.Shop_Name__c != attendance.Shop__c) {
                        System.debug('AutoCheckOutBatch -> store mismatch!');
                        
                        continue;
                    }
                    Time southAfricaTime = getSouthAfricaTime();
                    System.debug('AutoCheckOutBatch -> southAfricaTime: ' + southAfricaTime);
                    System.debug('AutoCheckOutBatch -> rule.End_time__c: ' + rule.End_time__c);
                    // 补签 
                    if (!isAutoCheckOut) {
                        southAfricaTime =  rule.End_time__c;
                    }
                    // 还未到签退时间
                    if ((southAfricaTime < rule.End_time__c) && !Test.isRunningTest()) {
                        System.debug('AutoCheckOutBatch -> Earlier than sign-out time!');

                        continue;
                    }

                    // 更新考勤信息
                    attendance.CheckOutShop__c = item.Shop_Name__c;
                    attendance.CheckIn_Date__c = today;
                    attendance.SignOutTime__c = southAfricaTime;
                    attendance.Check_out_Status__c = 'Check out';
                    if(attendance.CheckInStatus__c == '已签到' || attendance.CheckInStatus__c == '已签到签退'){
                        attendance.CheckInStatus__c = '已签到签退';
                    } else {
                        attendance.CheckInStatus__c = '已签退';
                    }
                    updateAttendanceList.add(attendance);
                    System.debug('AutoCheckOutBatch -> attendance: ' + attendance);

                    // insert签退信息
                    Promoter_Attendance_Information__c checkOutItem = new Promoter_Attendance_Information__c(
                        Promoter_Attendance__c = attendance.Id,
                        Shop__c = item.Shop_Name__c,
                        CheckIn_Date__c = today,
                        CheckIn_Time__c = southAfricaTime,
                        IsSystemAuto__c = true,
                        Type__c = 'Check out',
                        Status__c = 'Check out'
                    );
                    checkOutList.add(checkOutItem);
                    System.debug('AutoCheckOutBatch -> checkOutItem: ' + checkOutItem);

                    // 关联促销员与签退记录, 方便后续更新排班任务上的签退信息
                    promoterIdAndCheckOutRecordMap.put(item.Principal__c, checkOutItem);

                    // 自动签退通知人员
                    promoterIdSet.add(item.Principal__c);
                }
            }
            Database.update(updateAttendanceList);
            Database.insert(checkOutList);

            for (Responsible_Person__c item : scope) {
                if (promoterIdAndScheduledMap.containsKey(item.Id) && promoterIdAndCheckOutRecordMap.containsKey(item.Principal__c)) {
                    SchedulingTask__c scheduledTask = promoterIdAndScheduledMap.get(item.Id);
                    // 更新排班表
                    scheduledTask.Check_Out_Attendance_Information__c = promoterIdAndCheckOutRecordMap.get(item.Principal__c).Id;
                    updateScheduledList.add(scheduledTask);
                    System.debug('AutoCheckOutBatch -> scheduledTask: ' + scheduledTask);
                }
            }
            Database.update(updateScheduledList);

            // 发送自动打卡成功提醒
            System.debug('AutoCheckOutBatch -> promoterIdSet: ' + promoterIdSet);
            sendNotification('Auto Check out Successfully!', 'Thanks for your hard work!', promoterIdSet);
        }
        catch (Exception e) {
            System.debug('AutoCheckOutBatch Error : '+ e.getMessage() + e.getLineNumber());
        } 
    }

    public void finish(Database.BatchableContext bc){

    }


    public static Time getSouthAfricaTime() {
        // Africa/Johannesburg
        Date myDate = System.now().dateGMT();
        Time myTime = System.now().timeGmt();
        DateTime GMTDate = DateTime.newInstanceGMT(myDate, myTime);
        String strConvertedTime = GMTDate.format('yyyy-yy-dd HH:mm:ss:ms', 'Africa/Johannesburg').split(' ')[1];
        System.debug('getSouthAfricaTime -> : ' + GMTDate.format('yyyy-yy-dd HH:mm:ss:ms', 'Asia/Shanghai'));
        System.debug('getSouthAfricaTime -> strConvertedTime: ' + strConvertedTime);
        List<String> timeSplitList = strConvertedTime.split(':');
        Time convertTime = Time.newInstance(Integer.valueOf(timeSplitList[0]), Integer.valueOf(timeSplitList[1]), Integer.valueOf(timeSplitList[2]), Integer.valueOf(timeSplitList[3]));
        System.debug('getSouthAfricaTime -> convertTime: ' + convertTime);

        return convertTime;
    }

    public static Date getSouthAfricaDate() {
        Date myDate = System.now().dateGMT();
        Time myTime = System.now().timeGmt();
        DateTime GMTDate = DateTime.newInstanceGMT(myDate, myTime);
        String strConvertedTime = GMTDate.format('yyyy-MM-dd', 'Africa/Johannesburg');
        System.debug(strConvertedTime);
        System.debug(Date.valueOf(strConvertedTime));

        return Date.valueOf(strConvertedTime);
    }

    public static void sendNotification(String title, String body, Set<String> userIdSet) {

        Messaging.CustomNotification currNotification = new Messaging.CustomNotification();
        // Set the contents for the delinking notification
        currNotification.setTitle(title);
        currNotification.setBody(body);

        // Set the notification type and target
        currNotification.setNotificationTypeId([SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName='Custom_Notification'].Id);
        // currNotification.setTargetId('000000000000000AAA');
        // String pageRef = 
        // '' +
        // '{' +
        // '       type: \'standard__navItemPage\',' +
        // '       attributes: {' +
        // '           apiName: \'New_Promoter_Daily_Report\'' +
        // '       }' +
        // '}';
        // currNotification.setTargetPageRef(pageRef);
        
        // Send the notification
        try {
            currNotification.send(userIdSet);
        }
        catch (Exception ex) {
            string msg = 'Notification Failed: ' + ex.getMessage();
            System.debug(msg);
        }
    }
}