force-app/main/default/objects/Promoter_Attendance__c/Promoter_Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>PA-{YYYY}{MM}{0000}</displayFormat>
        <label>考勤编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Attendance__c/fields/CheckIn_Date__c.field-meta.xml
<CustomField>
    <fullName>CheckIn_Date__c</fullName>
    <label>打卡日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promoter_Attendance__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>OwnerId + &apos;_&apos; + CheckIn_Date__c</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Promoter_Attendance__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>签到门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Promoter_Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PromoterAttendanceHandler.cls
public without sharing class PromoterAttendanceHandler implements Triggers.Handler {
    public void handle() {
		if (Trigger.isBefore && (Trigger.isInsert||Trigger.isUpdate)) {
			for (Promoter_Attendance__c   paItem : (List<Promoter_Attendance__c  >)Trigger.new) {
				//date:2022/02/14 -change:促销员和巡店员都一天只有一条考勤
				//paItem.ExternalId__c = paItem.Shop__c + '_' + paItem.OwnerId + '_' + paItem.CheckIn_Date__c;
				// data:2023/12/01 -change:培训签到每个门店一个考勤 wfc
				if(String.isBlank(paItem.ExternalId__c)){
					paItem.ExternalId__c = paItem.OwnerId + '_' + String.valueOf(paItem.CheckIn_Date__c);
				}
			}	
		}
    }
}