force-app/main/default/objects/Account/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>黑电海信</fullName>
            </value>
            <value>
                <fullName>黑电东芝</fullName>
            </value>
            <value>
                <fullName>冰冷</fullName>
            </value>
            <value>
                <fullName>洗衣机小厨电</fullName>
            </value>
            <value>
                <fullName>空调</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gridding__c/Gridding__c.object-meta.xml
<CustomObject>
    <label>Gridding</label>
    <nameField>
        <label>网格名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Griddings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Gridding__c/fields/Gridding_Code__c.field-meta.xml
<CustomField>
    <fullName>Gridding_Code__c</fullName>
    <externalId>true</externalId>
    <label>网格编码</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gridding__c/fields/Gridding_Level__c.field-meta.xml
<CustomField>
    <fullName>Gridding_Level__c</fullName>
    <label>网格等级</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gridding__c/fields/Parent_Gridding__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gridding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>上级网格</label>
    <referenceTo>Gridding__c</referenceTo>
    <relationshipLabel>网格</relationshipLabel>
    <relationshipName>Parent_Gridding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>岗位</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>岗位编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>启用</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>只能包含字母数字字符，必须以字母开头，不能以下划线字符结尾或包含两个连续的下划线字符，而且在所有岗位中必须是唯一的;</inlineHelpText>
    <label>岗位小组名</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position__c/fields/Grouo_Name__c.field-meta.xml
<CustomField>
    <fullName>Grouo_Name__c</fullName>
    <label>岗位名</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/Position_Permissions__c.object-meta.xml
<CustomObject>
    <label>岗位权限</label>
    <nameField>
        <displayFormat>PER-{00000000}</displayFormat>
        <label>岗位权限编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位权限</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_Permissions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Account_Channel_Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/fields/Gridding__c.field-meta.xml
<CustomField>
    <fullName>Gridding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>网格</label>
    <referenceTo>Gridding__c</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Gridding_Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>岗位</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Position_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>产品线</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Position_Permissions_Shop</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shop_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>城市</description>
    <label>城市</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>网格名称，指门店所属网格划分</description>
    <label>网格</label>
    <referenceTo>Gridding__c</referenceTo>
    <relationshipLabel>Stores (网格)</relationshipLabel>
    <relationshipName>ShopRLg9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Shop_Level__c.field-meta.xml
<CustomField>
    <fullName>Shop_Level__c</fullName>
    <description>门店等级，分为S/A/B/C</description>
    <label>门店等级</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ShopLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ShopLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>PB</fullName>
    </customValue>
    <customValue>
        <fullName>SP</fullName>
    </customValue>
    <customValue>
        <fullName>W</fullName>
    </customValue>
    <customValue>
        <fullName>アンケート</fullName>
    </customValue>
    <customValue>
        <fullName>サンエー</fullName>
    </customValue>
    <customValue>
        <fullName>本部指定</fullName>
    </customValue>
    <customValue>
        <fullName>専売機</fullName>
    </customValue>
    <customValue>
        <fullName>拡販</fullName>
    </customValue>
    <customValue>
        <fullName>T01</fullName>
    </customValue>
    <customValue>
        <fullName>T02</fullName>
    </customValue>
    <customValue>
        <fullName>T03</fullName>
    </customValue>
    <customValue>
        <fullName>T04</fullName>
    </customValue>
    <customValue>
        <fullName>T05</fullName>
    </customValue>
    <customValue>
        <fullName>T06</fullName>
    </customValue>
    <customValue>
        <fullName>T07</fullName>
    </customValue>
    <customValue>
        <fullName>T08</fullName>
    </customValue>
    <customValue>
        <fullName>T09</fullName>
    </customValue>
    <customValue>
        <fullName>T10</fullName>
    </customValue>
    <customValue>
        <fullName>未知</fullName>
    </customValue>
    <customValue>
        <fullName>店格不明</fullName>
    </customValue>
    <customValue>
        <fullName>T61</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種BIC</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種KS</fullName>
    </customValue>
    <masterLabel>门店等级</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PositionCreateControllerTest.cls
@isTest
private class PositionCreateControllerTest {
    static testMethod void testController() {
        String recordId = 'a230T0000005hmGQAQ';

        Gridding__c gird = new Gridding__c();
        gird.Name = 'test001';
        gird.Gridding_Level__c = 'A';
        gird.Gridding_Code__c  = 'J01';
        //gird.Parent_Gridding__c = gird.Id; 
        INSERT gird;
        Gridding__c gird1 = new Gridding__c();
        gird1.Name = 'test002';
        gird1.Gridding_Level__c = 'B';
        gird1.Gridding_Code__c  = 'J01-J001';
        gird1.Parent_Gridding__c = gird.Id;
        INSERT gird1;

        Account acc = new Account();
        acc.Name = 'test';
        INSERT acc;

        Shop__c shop = new Shop__c();
        shop.Name = 'testName';
        shop.Account__c = acc.Id;
        shop.Shop_Level__c = 'A';
        shop.Grid__c = gird1.id;
        shop.City__c = '北京市';
        INSERT shop;

        Position__c pos = new Position__c();
        pos.DeveloperName__c = 'FU_GUAN_PATROLCLERKTEST';
        pos.Grouo_Name__c = '福关网格巡店员TEST';
        pos.Activity__c = true;
        INSERT pos;

        Position_Permissions__c position = new Position_Permissions__c();
        position.Account__c = acc.Id;
        position.Position__c = pos.Id;
        position.Gridding__c = gird1.Id;
        position.Product_Line__c = 'Mobile';
        INSERT position;

        PositionCreateController.ProductLine pp = new PositionCreateController.ProductLine();
        pp.label = '1';
        pp.value = 'test';
        pp.isTrue = false;
        pp.isDisable = true;
        pp.accProductLineKey = acc.Id + '_' + position.Product_Line__c;
        List<PositionCreateController.ProductLine> productLineList = new List<PositionCreateController.ProductLine>();
        productLineList.add(pp);

        PositionCreateController.AccProductLine accProductLine = new PositionCreateController.AccProductLine();
        accProductLine.accId = acc.Id;
        accProductLine.productLineList = productLineList;
        List<PositionCreateController.AccProductLine> aplList = new List<PositionCreateController.AccProductLine>();
        aplList.add(accProductLine);

        String objStr =JSON.serialize(aplList);
        Map<String, String> shopSearchMap  = new Map<String, String>();
        shopSearchMap.put('shopName', shop.Name);
        shopSearchMap.put('accountName', acc.Name);
        shopSearchMap.put('griddingName', gird1.Name);
        

        List<String> noIncludingGridIdList = new List<String> ();
        noIncludingGridIdList.add(gird1.Id);

        PositionCreateController.shopWrapper shopWrapper = new PositionCreateController.shopWrapper();
        shopWrapper.accountName = acc.Name;
        shopWrapper.griddingName = gird1.Name;
        shopWrapper.positionPermissionId = position.Id;
        shopWrapper.shopExternalKeyID = shop.Id;
        shopWrapper.shopName = shop.Name;

        List<PositionCreateController.shopWrapper>  shopSearchList = new List<PositionCreateController.shopWrapper>();
        shopSearchList.add(shopWrapper);
        String shopSearchListJSON = JSON.serialize(shopSearchList);
        String shopListJSON = JSON.serialize(shopSearchList);

        PositionCreateController.shopGriddingWrapper shopGriddingWrapper = new PositionCreateController.shopGriddingWrapper();
        shopGriddingWrapper.name = 'test';
        shopGriddingWrapper.recordId = gird.Id;
        shopGriddingWrapper.parentId = gird.Id;
        shopGriddingWrapper.griExternalId = gird.Id;
        List<PositionCreateController.shopGriddingWrapper> posList = new List<PositionCreateController.shopGriddingWrapper>();
        posList.add(shopGriddingWrapper);
        String currentgridNewColumnsJson = JSON.serialize(posList);
        

        Test.startTest();
        PositionCreateController.initGridding(recordId);
        PositionCreateController.addNewRow(objStr);
        PositionCreateController.changeAccoutFunction(acc.Id,objStr,recordId);
        PositionCreateController.checkProductLine(true,pp.accProductLineKey,aplList,pos.Id);
        PositionCreateController.checkProductLine(false,pp.accProductLineKey,aplList,pos.Id);
        PositionCreateController.deleteRowLine(acc.Id,pos.Id);
        PositionCreateController.searchActionFunction(shopSearchMap,noIncludingGridIdList);
        PositionCreateController.chooseShopFunction(shop.Id, pos.Id, shopSearchListJSON, shopListJSON);
        PositionCreateController.unChooseShopFunction(shop.Id, pos.Id, shopSearchListJSON, shopListJSON, shopSearchMap);
        PositionCreateController.openOrCloseGridding(currentgridNewColumnsJson, gird.Id, 'utility:chevrondown', 'currentName');
        PositionCreateController.openOrCloseGridding(currentgridNewColumnsJson, gird.Id, 'utility:chevronright', 'currentName');
        
        PositionCreateController.checkGriddingFunction(currentgridNewColumnsJSON, true, gird.Id, pos.Id);
        PositionCreateController.checkGriddingFunction(currentgridNewColumnsJSON, false, gird.Id, pos.Id);
        //PositionCreateController.hiddenNextGridding(gird.Id,posList);
        Test.stopTest();
    }

}