force-app/main/default/objects/Account/fields/Active_Flag__c.field-meta.xml
<CustomField>
    <fullName>Active_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <defaultValue>IF(CONTAINS( $Profile.Name, &apos;Australia&apos;)  &amp;&amp;  $RecordType.DeveloperName  = &apos;Sub_Account&apos;, &apos;Approved&apos;, &apos;Draft&apos;)</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hisense_Entity__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Entity__c</fullName>
    <inlineHelpText>Financial required</inlineHelpText>
    <label>Hisense Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Hisense_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Version__c.field-meta.xml
<CustomField>
    <fullName>Latest_Version__c</fullName>
    <label>Latest Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;NA OEM Sales Dept.&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Thailand&apos;) , &apos;Hisense Thailand&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense India&apos;) , &apos;Hisense India&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Dubai&apos;) , &apos;Hisense Dubai&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Columbia&apos;) , &apos;Hisense Columbia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>NA OEM Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Hisense Panama</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Brazil</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Egypt Office</fullName>
            </value>
            <value>
                <fullName>West Africa Office</fullName>
            </value>
            <value>
                <fullName>East Africa Office</fullName>
            </value>
            <value>
                <fullName>Algeria Office</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense New Zealand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>South Asia Office</fullName>
            </value>
            <value>
                <fullName>East Asia Office</fullName>
            </value>
            <value>
                <fullName>Israel Office</fullName>
            </value>
            <value>
                <fullName>Europe Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Hisense Russia - Direct Sales</fullName>
            </value>
            <value>
                <fullName>HA Sales Dept.</fullName>
            </value>
            <value>
                <fullName>AC Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Banks__c/Customer_Banks__c.object-meta.xml
<CustomObject>
    <label>Customer Banks</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>BANKS No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Banks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Banks__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Processes_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Banks__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <length>38</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Banks__c/fields/Bank_Country__c.field-meta.xml
<CustomField>
    <fullName>Bank_Country__c</fullName>
    <label>Bank Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Banks__c/fields/Bank_name_local_language__c.field-meta.xml
<CustomField>
    <fullName>Bank_name_local_language__c</fullName>
    <description>MDG主数据：银行名称（当地语言）</description>
    <label>Bank name (local language)</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Banks__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Banks</relationshipLabel>
    <relationshipName>Customer_Banks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Extend__c/Customer_Extend__c.object-meta.xml
<CustomObject>
    <label>Customer Extend</label>
    <nameField>
        <label>Customer Extend Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Extends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Extend__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Extends</relationshipLabel>
    <relationshipName>Customer_Extends</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Extend__c/fields/Show_Sales__c.field-meta.xml
<CustomField>
    <fullName>Show_Sales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Sales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Extend_Tax_category__c/Customer_Extend_Tax_category__c.object-meta.xml
<CustomObject>
    <label>Customer Extend Tax category</label>
    <nameField>
        <displayFormat>ETC-{00000}</displayFormat>
        <label>Extend tax category No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Extend Tax category</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Extend_Tax_category__c/fields/Customer_Extend__c.field-meta.xml
<CustomField>
    <fullName>Customer_Extend__c</fullName>
    <label>Customer Extend</label>
    <referenceTo>Customer_Extend__c</referenceTo>
    <relationshipLabel>Customer Extend Tax category</relationshipLabel>
    <relationshipName>Customer_Extend_Tax_category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TaxCountryMapping__c/TaxCountryMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TaxCountryMapping</label>
</CustomObject>

force-app/main/default/globalValueSets/Approval_Processes_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>流程审批状态</description>
    <masterLabel>Approval Processes Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerHistoryQueueableTest.cls
@isTest
public with sharing class CustomerHistoryQueueableTest{
    static testMethod void testMethod1(){
        TaxCountryMapping__c tcm = new TaxCountryMapping__c();
        tcm.name = '8500';
        tcm.Country__c = 'US';
        insert tcm;

        Account acc = new Account(
            Name = 'Test Account001', 
            SAP_Customer_Code__c = '1234567890', 
            External_Key__c = '1234567890', 
            Sales_Region__c = 'Hisense USA', 
            Hisense_Entity__c = '8500', 
            Approval_Status__c = 'Approved',
            Type = 'Management', 
            Active_Flag__c = false,
            Latest_Version__c = '1111'
        );
        insert acc;

        Customer_Extend__c ce1 = new Customer_Extend__c();
        ce1.Customer__c = acc.id;
        ce1.Show_Company__c = true;
        ce1.Show_Sales__c = false;
        insert ce1;

        Customer_Extend__c ce2 = new Customer_Extend__c();
        ce2.Customer__c = acc.id;
        ce2.Show_Company__c = false;
        ce2.Show_Sales__c = true;
        insert ce2;

        Customer_Banks__c cb = new Customer_Banks__c();
        cb.Customer__c = acc.id;
        cb.Bank_Country__c = 'US';
        cb.Bank_Account__c = '123';
        cb.Approval_Status__c = 'Draft';
        cb.Bank_name_local_language__c = '123';
        insert cb;

        Customer_Extend_Tax_category__c teax = new Customer_Extend_Tax_category__c();
        teax.Customer_Extend__c = ce1.Id;
        insert teax;

        String jobID = System.enqueueJob(new CustomerHistoryQueueable(acc.Id));
    }

}