force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <inlineHelpText>If the address information is not in English, please convert to the English alphabet. Thank you.</inlineHelpText>
    <label>Address (English)</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/City_CN__c.field-meta.xml
<CustomField>
    <fullName>City_CN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_State__c.BelongTo_CNProvince__c</field>
            <operation>equals</operation>
            <valueField>$Source.Province_State__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Country_State__c</referenceTo>
    <relationshipLabel>Customers (City)</relationshipLabel>
    <relationshipName>Customers_CNCity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/District_CN__c.field-meta.xml
<CustomField>
    <fullName>District_CN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_State__c.BelongTo_CNCity__c</field>
            <operation>equals</operation>
            <valueField>$Source.City_CN__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Country_State__c</referenceTo>
    <relationshipLabel>Customers (District)</relationshipLabel>
    <relationshipName>Customers_CNDistrict</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Guarantor_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Guarantor_Country_Code__c</fullName>
    <label>Country/Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hisense_Entity__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Entity__c</fullName>
    <inlineHelpText>Financial required</inlineHelpText>
    <label>Hisense Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Hisense_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Tax Info required; 
----G216:Month end +30days----  
----G007:TT00 ,Paid----
----G005:OA60 ,Within 60 days Due net----
----G011:OA75 ,Within 75 days Due net----
----G006:OA90 ,Within 90 days Due net----
----0001: Pay immediately w/o deduction----
----G498: End of month+60 days,Cut off 25th----</inlineHelpText>
    <label>Payment Term</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>((1 AND 2) OR (3 AND 4)) OR 5</booleanFilter>
        <filterItems>
            <field>Payment_Term__c.Scope__c</field>
            <operation>equals</operation>
            <value>Oversea Company</value>
        </filterItems>
        <filterItems>
            <field>$Source.Sales_Region__c</field>
            <operation>equals</operation>
            <value>Hisense USA, Hisense Mexico, Hisense Australia, Hisense Malaysia, Hisense South Africa</value>
        </filterItems>
        <filterItems>
            <field>Payment_Term__c.Scope__c</field>
            <operation>equals</operation>
            <value>Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Source.Sales_Region__c</field>
            <operation>equals</operation>
            <value>USA(OEM), American Sales Department, Middle East and Africa Sales Department, Asia-Pacific Sales Department, Key Account Sales Department, Europe Sales Department, Communications Sales Department</value>
        </filterItems>
        <filterItems>
            <field>$Source.Sales_Region__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Term__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Cus_Payment_Term</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Province_State__c.field-meta.xml
<CustomField>
    <fullName>Province_State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Province/State</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Country_State__c.Belong_To__c</field>
            <operation>equals</operation>
            <valueField>$Source.Guarantor_Country_Code__c</valueField>
        </filterItems>
        <filterItems>
            <field>Country_State__c.Id</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <infoMessage>You can only  select the Province under this Country</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Country_State__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;NA OEM Sales Dept.&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Thailand&apos;) , &apos;Hisense Thailand&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense India&apos;) , &apos;Hisense India&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Dubai&apos;) , &apos;Hisense Dubai&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Columbia&apos;) , &apos;Hisense Columbia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>NA OEM Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Hisense Panama</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Brazil</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Egypt Office</fullName>
            </value>
            <value>
                <fullName>West Africa Office</fullName>
            </value>
            <value>
                <fullName>East Africa Office</fullName>
            </value>
            <value>
                <fullName>Algeria Office</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense New Zealand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>South Asia Office</fullName>
            </value>
            <value>
                <fullName>East Asia Office</fullName>
            </value>
            <value>
                <fullName>Israel Office</fullName>
            </value>
            <value>
                <fullName>Europe Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Hisense Russia - Direct Sales</fullName>
            </value>
            <value>
                <fullName>HA Sales Dept.</fullName>
            </value>
            <value>
                <fullName>AC Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Conditions__c</fullName>
    <inlineHelpText>Financial required</inlineHelpText>
    <label>Shipping Conditions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Customer Picking up Own Goods</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Warehouse Delivery Hisense Pay</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Parts Special Use</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Warehouse Delivery Customer Pay</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Fedex Ground</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Fedex Economy</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Fedex 2Day</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Fedex Standard Overn</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Fedex Priority Overn</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Fedex First Overnigh</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>UPS Ground</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>UPS 3 Day Select</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>UPS 2nd Day Air</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>UPS 2nd Day Air AM</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>UPS Next Day Air Sav</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>UPS UPS Next Day Air</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Purolator Ground</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Purolator Express</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Dispatchbythirdparty</label>
            </value>
            <value>
                <fullName>Z1</fullName>
                <label>Hisense Assign</label>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>33</fullName>
            </value>
            <value>
                <fullName>Customer Picking up Own Goods</fullName>
                <isActive>false</isActive>
                <label>Customer Picking up Own Goods</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Township_CN__c.field-meta.xml
<CustomField>
    <fullName>Township_CN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Township</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Country_State__c.BelongTo_CNDistrict__c</field>
            <operation>equals</operation>
            <valueField>$Source.District_CN__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Country_State__c</referenceTo>
    <relationshipLabel>Customers (Township)</relationshipLabel>
    <relationshipName>Customers_CNTownship</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Term__c/Payment_Term__c.object-meta.xml
<CustomObject>
    <label>付款条件</label>
    <nameField>
        <label>Payment Term No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Term__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MDGNewSubAccountController.cls
/**
 * 新建分户控制器
 * @author: Ardbert Wang
 * @date: 2024-11-14
 */
public without sharing class MDGNewSubAccountController {
    @AuraEnabled
    public static String getRecordTypeIdByDeveloperName(String developerName) {
        // 查询RecordTypeId
        RecordType rt = [SELECT Id FROM RecordType 
                         WHERE SObjectType = 'Account' 
                         AND DeveloperName = :developerName
                         LIMIT 1];
        return rt.Id;
    }
    
    /**
     * 获取默认值
     */
    @AuraEnabled
    public static Account getParentFields(String recordId) {
        // 查询RecordTypeId
        Account parentAccount = [SELECT Id, Guarantor_Country_Code__c, Hisense_Entity__c, Payment_Term__c, 
            Province_State__c, City__c, City_CN__c, District_CN__c, Township_CN__c, Address__c, Sales_Region__c,
            Shipping_Conditions__c,Reconciliation_Customer__c,Buyer_English_Name__c,Customer_Group2__c,
            VAT_Tax_type__c,Hisense_Entity_Sales__c, Payment_Term_Sales__c,
            Customer_Short_Name__c, Credit_Management__c FROM Account WHERE Id = :recordId LIMIT 1];
        return parentAccount;
    }
}