force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <defaultValue>IF(CONTAINS( $Profile.Name, &apos;Australia&apos;)  &amp;&amp;  $RecordType.DeveloperName  = &apos;Sub_Account&apos;, &apos;Approved&apos;, &apos;Draft&apos;)</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MDG_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Customer_Code__c</fullName>
    <label>MDG Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Address__c/Customer_Address__c.object-meta.xml
<CustomObject>
    <label>Customer Address</label>
    <nameField>
        <label>Customer Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Address__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Address__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>sold-to</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.SAP_Customer_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Addresses</relationshipLabel>
    <relationshipName>Customer_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Address__c/fields/MDG_Code__c.field-meta.xml
<CustomField>
    <fullName>MDG_Code__c</fullName>
    <label>MDG Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerAddressButtonHandlerController.cls
/**************************************************************************************************
 * CustomerButtonHandlerController
 * Purpose:客户按钮处理逻辑
 * Author: Deloitte Johnson
 * Create Date: 2019-04-09
***************************************************************************************************/
global  without sharing class CustomerAddressButtonHandlerController{
    public static User currentUser = [SELECT Id,Name,Profile.Name FROM User WHERE Id =:UserInfo.getUserId()]; 
    public class ReturnResult{
        public String code; //code "0" means success, and other codes means failure
        public String msg;  //result message
    }
    @AuraEnabled 
    //同步客户到SAP
    public static String syncCustomerToSAP(String customerId){
        ReturnResult result = new ReturnResult();
        result.code = '0';
        result.msg = 'Sync to SAP!';
        System.debug('currentUser: ' +currentUser);
        Customer_Address__c customer = [SELECT Id, MDG_Code__c, Approval_Status__c,Customer__r.MDG_Customer_Code__c FROM Customer_Address__c WHERE Id=:customerId];
        if(String.isBlank(customer.Customer__r.MDG_Customer_Code__c)){
            result.code = '1';
            if(!Test.isRunningTest()){
                result.msg = Label.Customer_Address_Check_Sold_to_MDG_Code;
                return JSON.serialize(result);
            }
        }
        // if(!currentUser.Profile.Name.contains('Sales Manager')
        // && !currentUser.Profile.Name.contains('Sales Director')
        // && !currentUser.Profile.Name.contains('System Administrator')){
        //     result.code = '1';
        //     //result.msg = 'You do not have permission to operate, please contact the administrator';
        //     result.msg = Label.Common_No_Permission;
        //     return JSON.serialize(result);
        // }
        // if(!customer.Approval_Status__c.equals('Approved')){
        //     result.code = '1';
        //     //result.msg = 'Only an Approved customer can synchronize to SAP';
        //     result.msg = Label.Customer_Sync_To_SAP_With_Error_Status;
        //     return JSON.serialize(result);
        // }
        // if(String.isNotBlank(customer.MDG_Code__c)){
        //     result.code = '1';
        //     //result.msg = 'The customer has been synchronized to SAP';
        //     result.msg = Label.Customer_Synchronized_To_SAP;
        //     return JSON.serialize(result);
        // }
        // MDG客户主数据 20241114
        String responseMsg = SyncCustomerInfoToMDG.postCustomerInfomationToMDG(customerId);
        // String responseMsg = SyncCustomerInfoToSAP.postCustomerInfomationToSAP(customerId);
        if(!responseMsg.equals('SUCCESS')){
            result.code = '1';
            result.msg = responseMsg;
            return JSON.serialize(result);
        }
        return JSON.serialize(result);
    }
}