force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <defaultValue>IF(CONTAINS( $Profile.Name, &apos;Australia&apos;)  &amp;&amp;  $RecordType.DeveloperName  = &apos;Sub_Account&apos;, &apos;Approved&apos;, &apos;Draft&apos;)</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hisense_Entity__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Entity__c</fullName>
    <inlineHelpText>Financial required</inlineHelpText>
    <label>Hisense Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Hisense_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hisense_Entity_Sales__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Entity_Sales__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Hisense_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trader_Type__c.field-meta.xml
<CustomField>
    <fullName>Trader_Type__c</fullName>
    <label>Trader Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>H001</fullName>
                <label>H001 集团内业务伙伴</label>
            </value>
            <value>
                <fullName>H002</fullName>
                <label>H002 集团外业务伙伴</label>
            </value>
            <value>
                <fullName>H003</fullName>
                <label>H003 一次性业务伙伴</label>
            </value>
            <value>
                <fullName>H004</fullName>
                <label>H004 员工类业务伙伴</label>
            </value>
            <value>
                <fullName>H005</fullName>
                <label>H005 门店地址业务伙伴</label>
            </value>
            <value>
                <fullName>H006</fullName>
                <label>H006 非注册实体业务伙伴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Address__c/Customer_Address__c.object-meta.xml
<CustomObject>
    <label>Customer Address</label>
    <nameField>
        <label>Customer Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Address__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Address__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>sold-to</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.SAP_Customer_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Addresses</relationshipLabel>
    <relationshipName>Customer_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Address__c/fields/Hisense_Entity__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Entity__c</fullName>
    <inlineHelpText>Financial required</inlineHelpText>
    <label>Hisense Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Hisense_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Address__c/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Address__c/fields/Trader_Type__c.field-meta.xml
<CustomField>
    <fullName>Trader_Type__c</fullName>
    <label>Trader Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>H001</fullName>
                <label>H001 集团内业务伙伴</label>
            </value>
            <value>
                <fullName>H002</fullName>
                <label>H002 集团外业务伙伴</label>
            </value>
            <value>
                <fullName>H003</fullName>
                <label>H003 一次性业务伙伴</label>
            </value>
            <value>
                <fullName>H004</fullName>
                <label>H004 员工类业务伙伴</label>
            </value>
            <value>
                <fullName>H005</fullName>
                <label>H005 门店地址业务伙伴</label>
            </value>
            <value>
                <fullName>H006</fullName>
                <label>H006 非注册实体业务伙伴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Email__c/Customer_Email__c.object-meta.xml
<CustomObject>
    <label>Customer Email</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Email__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Emails</relationshipLabel>
    <relationshipName>Customer_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Email__c/fields/Customer_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Address</label>
    <referenceTo>Customer_Address__c</referenceTo>
    <relationshipLabel>Customer Emails</relationshipLabel>
    <relationshipName>Customer_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Email__c/fields/External_key__c.field-meta.xml
<CustomField>
    <fullName>External_key__c</fullName>
    <label>External key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Email__c/fields/No__c.field-meta.xml
<CustomField>
    <fullName>No__c</fullName>
    <label>No</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_tax_category__c/National_tax_category__c.object-meta.xml
<CustomObject>
    <label>税分类国家</label>
    <nameField>
        <label>National Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_tax_category__c/fields/National_code__c.field-meta.xml
<CustomField>
    <fullName>National_code__c</fullName>
    <label>National code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_tax_category__c/fields/sort__c.field-meta.xml
<CustomField>
    <fullName>sort__c</fullName>
    <label>sort</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_tax_category__c/fields/Tax_category__c.field-meta.xml
<CustomField>
    <fullName>Tax_category__c</fullName>
    <label>Tax category</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_category__c/Tax_category__c.object-meta.xml
<CustomObject>
    <label>Tax category</label>
    <nameField>
        <label>Tax code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaxCountryMapping__c/TaxCountryMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TaxCountryMapping</label>
</CustomObject>

force-app/main/default/objects/Trader_Type__c/Trader_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>客商类型，sap对应关系</description>
    <label>Trader Type</label>
</CustomObject>

force-app/main/default/objects/Trader_Type__c/fields/Trader_Type__c.field-meta.xml
<CustomField>
    <fullName>Trader_Type__c</fullName>
    <label>Trader Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerAddressTriggerHandlerTest.cls
@isTest
private class CustomerAddressTriggerHandlerTest {
    
    static testmethod void test() {

        TaxCountryMapping__c tcm = new TaxCountryMapping__c();
        tcm.name = '8300';
        tcm.Country__c = 'US';
        insert tcm;

        TaxCountryMapping__c tcm1 = new TaxCountryMapping__c();
        tcm1.name = '8110';
        tcm1.Country__c = 'USA';
        insert tcm1;

        TaxCountryMapping__c tcm2 = new TaxCountryMapping__c();
        tcm2.name = '8200';
        tcm2.Country__c = 'AU';
        insert tcm2;

        National_tax_category__c ntc = new National_tax_category__c();
        ntc.National_code__c = 'US';
        ntc.sort__c = 1;
        ntc.Tax_category__c = 'UTXJ';
        insert ntc;

        National_tax_category__c ntc1 = new National_tax_category__c();
        ntc1.National_code__c = 'USA';
        ntc1.sort__c = 2;
        ntc1.Tax_category__c = 'UTXJ';
        insert ntc1;

        National_tax_category__c ntc2 = new National_tax_category__c();
        ntc2.National_code__c = 'AU';
        ntc2.sort__c = 2;
        ntc2.Tax_category__c = 'UTXJ';
        insert ntc2;

        National_tax_category__c ntc3 = new National_tax_category__c();
        ntc3.National_code__c = 'AU';
        ntc3.sort__c = 2;
        ntc3.Tax_category__c = '1';
        insert ntc3;

        Test.startTest();

        Account acc1 = new Account();
    	acc1.Name = 'Test Account002Test Account002Test Account002Test Account002Test Account00';
        acc1.SAP_Customer_Code__c = '1772378988';
        acc1.External_Key__c = '1772378988';
        acc1.Hisense_Entity__c = '8110';
        acc1.Trader_Type__c = 'H002';
        insert(acc1);

        Customer_Address__c ca = new Customer_Address__c();
        ca.Name = 'testca';
        ca.Customer__c = acc1.Id;
        ca.Email__c = '3333@qq.com';
        ca.Hisense_Entity_Sales__c = '8300';
        ca.Approval_Status__c = 'Draft';
        insert ca;

        ca.Approval_Status__c = 'Approved';
        ca.Hisense_Entity_Sales__c = '8110';
        update ca;


        delete ca;

        Test.stopTest();
    }

    static testmethod void test1() {

        Account acc1 = new Account();
    	acc1.Name = 'Test Account002Test Account002Test Account002Test Account002Test Account00';
        acc1.SAP_Customer_Code__c = '1772378988';
        acc1.External_Key__c = '1772378988';
        acc1.Hisense_Entity__c = '8110';
        acc1.Trader_Type__c = 'H002';
        insert(acc1);

        Customer_Address__c ca = new Customer_Address__c();
        ca.Name = 'testca';
        ca.Customer__c = acc1.Id;
        insert ca;

        Test.startTest();
        Customer_Email__c ce = new Customer_Email__c();
        ce.Email__c = '123@qq.com';
        ce.Customer_Address__c = ca.Id;
        insert ce;

        Customer_Email__c ce1 = new Customer_Email__c();
        ce1.Email__c = '123456@qq.com';
        ce1.Customer_Address__c = ca.Id;
        insert ce1;

        ce1.No__c  = 1;
        update ce1;

        ce1.No__c = 2;
        update ce1;

        delete ce1;

        Test.stopTest();

        
    }
 
}