force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <defaultValue>IF(CONTAINS( $Profile.Name, &apos;Australia&apos;)  &amp;&amp;  $RecordType.DeveloperName  = &apos;Sub_Account&apos;, &apos;Approved&apos;, &apos;Draft&apos;)</defaultValue>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Category__c</fullName>
    <label>Customer Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Department store</fullName>
            </value>
            <value>
                <fullName>High-end department store</fullName>
            </value>
            <value>
                <fullName>High-end commercial channel</fullName>
            </value>
            <value>
                <fullName>Supermarket</fullName>
            </value>
            <value>
                <fullName>Club</fullName>
            </value>
            <value>
                <fullName>Electrical chains</fullName>
            </value>
            <value>
                <fullName>Furniture store</fullName>
            </value>
            <value>
                <fullName>Franchisees</fullName>
            </value>
            <value>
                <fullName>Supermarket chains</fullName>
            </value>
            <value>
                <fullName>Buying group</fullName>
            </value>
            <value>
                <fullName>Single store</fullName>
            </value>
            <value>
                <fullName>Outlets</fullName>
            </value>
            <value>
                <fullName>Pure on-line</fullName>
            </value>
            <value>
                <fullName>Specialty</fullName>
            </value>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Wholesaler</fullName>
            </value>
            <value>
                <fullName>Returned product resale partner</fullName>
            </value>
            <value>
                <fullName>Operator</fullName>
            </value>
            <value>
                <fullName>Open market</fullName>
            </value>
            <value>
                <fullName>Professional AC</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Manufacturer &amp; Dealer</fullName>
            </value>
            <value>
                <fullName>Cash customer</fullName>
            </value>
            <value>
                <fullName>others</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>TV shopping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_SF_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_SF_Code__c</fullName>
    <displayFormat>C-{00000}</displayFormat>
    <label>Customer SF Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Undeveloped</fullName>
                <default>true</default>
                <label>Undeveloped</label>
            </value>
            <value>
                <fullName>Developing</fullName>
            </value>
            <value>
                <fullName>Collaborated</fullName>
            </value>
            <value>
                <fullName>Eliminated</fullName>
            </value>
            <value>
                <fullName>FD32</fullName>
                <label>Credit Block (SAP)</label>
            </value>
            <value>
                <fullName>XD05</fullName>
                <label>Business Block (SAP)</label>
            </value>
            <value>
                <fullName>XD06</fullName>
                <label>Logic Deleted (SAP)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/isGoFinApprove__c.field-meta.xml
<CustomField>
    <fullName>isGoFinApprove__c</fullName>
    <label>goApproveStep</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>fin_approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>黑电海信</fullName>
            </value>
            <value>
                <fullName>黑电东芝</fullName>
            </value>
            <value>
                <fullName>冰冷</fullName>
            </value>
            <value>
                <fullName>洗衣机小厨电</fullName>
            </value>
            <value>
                <fullName>空调</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;NA OEM Sales Dept.&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Thailand&apos;) , &apos;Hisense Thailand&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense India&apos;) , &apos;Hisense India&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Dubai&apos;) , &apos;Hisense Dubai&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Columbia&apos;) , &apos;Hisense Columbia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>NA OEM Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Hisense Panama</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Brazil</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Egypt Office</fullName>
            </value>
            <value>
                <fullName>West Africa Office</fullName>
            </value>
            <value>
                <fullName>East Africa Office</fullName>
            </value>
            <value>
                <fullName>Algeria Office</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense New Zealand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>South Asia Office</fullName>
            </value>
            <value>
                <fullName>East Asia Office</fullName>
            </value>
            <value>
                <fullName>Israel Office</fullName>
            </value>
            <value>
                <fullName>Europe Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Hisense Russia - Direct Sales</fullName>
            </value>
            <value>
                <fullName>HA Sales Dept.</fullName>
            </value>
            <value>
                <fullName>AC Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>销售姓名</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>Salesperson No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GetSalesPeriodicityTest.cls
@isTest
private class GetSalesPeriodicityTest {

    private static String url = '/services/apexrest/GetCustomers';

    public static void init(){
        Integer n = 20;
        List<Account> accs = new List<Account>();
        for(Integer i=0;i<n;i++){
            Account acc = new Account(
                SAP_Customer_Code__c = 'test'+i,
                //Customer_SF_Code__c = 'test'+i,
                Sales_Region__c = 'China',
                Customer_Status__c = 'XD06',
                Customer_Category__c='B2B',
                Name = 'Test James'+i,
                External_Key__c = 'sap1000000'+i,
                Approval_Status__c = 'Approved',
                isGoFinApprove__c = 'fin_approved'
            );
            accs.add(acc);
        }
        insert accs;

        List<Sales__c> saleses = new List<Sales__c>();
        for(Integer i=0;i<n;i++){
            Sales__c sales = new Sales__c(
                Product_Line__c = 'TV',
                Customer__c = accs.get(i).Id
            );
            saleses.add(sales);
        }
        insert saleses;
    }

    @isTest
    static void testDoPost() {
        init();
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI =  GetSalesPeriodicityTest.url;
        req.httpMethod = 'POST';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res;

        req.requestBody = Blob.valueOf('');
        GetSalesPeriodicity.doPost();
        String resbody = res.responseBody.toString();
        GetSalesPeriodicity.SFOutputResult rvo = (GetSalesPeriodicity.SFOutputResult)JSON.deserialize(resbody,
            GetSalesPeriodicity.SFOutputResult.class);
        System.assertEquals(false, rvo.IsSuccess);

        GetSalesPeriodicity.SFInput vo = new GetSalesPeriodicity.SFInput();
        req.requestBody = Blob.valueOf(JSON.serialize(vo));
        GetSalesPeriodicity.doPost();
        resbody = res.responseBody.toString();
        rvo = (GetSalesPeriodicity.SFOutputResult)JSON.deserialize(resbody,
            GetSalesPeriodicity.SFOutputResult.class);
        System.assertEquals(false, rvo.IsSuccess);

        vo.salesRegion = 'China';
        vo.productLine = 'TV';
        vo.startDate = System.today().format();
        vo.endDate = System.today().addDays(2).format();
        req.requestBody = Blob.valueOf(JSON.serialize(vo));
        GetSalesPeriodicity.doPost();
        resbody = res.responseBody.toString();
        rvo = (GetSalesPeriodicity.SFOutputResult)JSON.deserialize(resbody,GetSalesPeriodicity.SFOutputResult.class);
        System.assertEquals(true, rvo.IsSuccess);

        vo.salesRegion = 'TEST';
        vo.productLine = 'Freezer';
        req.requestBody = Blob.valueOf(JSON.serialize(vo));
        GetSalesPeriodicity.doPost();
        resbody = res.responseBody.toString();
        rvo = (GetSalesPeriodicity.SFOutputResult)JSON.deserialize(resbody,GetSalesPeriodicity.SFOutputResult.class);
        System.assertEquals(true, rvo.IsSuccess);
        Test.stopTest();
    }

    @isTest
    static void testValidateInput() {
        
        Test.startTest();
        GetSalesPeriodicity.SFInput vo = new GetSalesPeriodicity.SFInput();
        GetSalesPeriodicity.SFOutputResult re = GetSalesPeriodicity.validateInput(vo);
        System.assertEquals(false, re.IsSuccess);

        re = GetSalesPeriodicity.validateInput(null);
        System.assertEquals(false, re.IsSuccess);

        vo.salesRegion = 'test';
        vo.startDate = '2019-09-09';
        vo.endDate = '2019-09-01';
        re = GetSalesPeriodicity.validateInput(vo);
        System.assertEquals(false, re.IsSuccess);
        Test.stopTest();
    }
}