force-app/main/default/objects/Account/fields/Channel_Level__c.field-meta.xml
<CustomField>
    <fullName>Channel_Level__c</fullName>
    <inlineHelpText>Mid-high level channel mainly sells high-end products with a large store area and high-grade decoration</inlineHelpText>
    <label>Channel Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mid-High Level</fullName>
            </value>
            <value>
                <fullName>Non Mid-High Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Category__c.field-meta.xml
<CustomField>
    <fullName>Customer_Category__c</fullName>
    <label>Customer Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Department store</fullName>
            </value>
            <value>
                <fullName>High-end department store</fullName>
            </value>
            <value>
                <fullName>High-end commercial channel</fullName>
            </value>
            <value>
                <fullName>Supermarket</fullName>
            </value>
            <value>
                <fullName>Club</fullName>
            </value>
            <value>
                <fullName>Electrical chains</fullName>
            </value>
            <value>
                <fullName>Furniture store</fullName>
            </value>
            <value>
                <fullName>Franchisees</fullName>
            </value>
            <value>
                <fullName>Supermarket chains</fullName>
            </value>
            <value>
                <fullName>Buying group</fullName>
            </value>
            <value>
                <fullName>Single store</fullName>
            </value>
            <value>
                <fullName>Outlets</fullName>
            </value>
            <value>
                <fullName>Pure on-line</fullName>
            </value>
            <value>
                <fullName>Specialty</fullName>
            </value>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Wholesaler</fullName>
            </value>
            <value>
                <fullName>Returned product resale partner</fullName>
            </value>
            <value>
                <fullName>Operator</fullName>
            </value>
            <value>
                <fullName>Open market</fullName>
            </value>
            <value>
                <fullName>Professional AC</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Manufacturer &amp; Dealer</fullName>
            </value>
            <value>
                <fullName>Cash customer</fullName>
            </value>
            <value>
                <fullName>others</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>TV shopping</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Professional channels</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Man Rep</fullName>
            </value>
            <value>
                <fullName>Spec Rep</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>黑电海信</fullName>
            </value>
            <value>
                <fullName>黑电东芝</fullName>
            </value>
            <value>
                <fullName>冰冷</fullName>
            </value>
            <value>
                <fullName>洗衣机小厨电</fullName>
            </value>
            <value>
                <fullName>空调</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Store_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Store_Quantity__c</fullName>
    <label>Total Store Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Information__c/Customer_Information__c.object-meta.xml
<CustomObject>
    <description>客户信息</description>
    <label>Customer Information</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Customer Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Information__c/fields/Actual_Sales_Income_Ratio_21_Year__c.field-meta.xml
<CustomField>
    <fullName>Actual_Sales_Income_Ratio_21_Year__c</fullName>
    <label>21 Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Information__c/fields/Actual_Sales_Income_Ratio_22_Year__c.field-meta.xml
<CustomField>
    <fullName>Actual_Sales_Income_Ratio_22_Year__c</fullName>
    <label>22 Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Information__c/fields/Annual_sales_scale__c.field-meta.xml
<CustomField>
    <fullName>Annual_sales_scale__c</fullName>
    <label>Annual sales scale ($10K)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Information__c/fields/Channel_Level__c.field-meta.xml
<CustomField>
    <fullName>Channel_Level__c</fullName>
    <label>Channel Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Information__c/fields/Cooperation_Level__c.field-meta.xml
<CustomField>
    <fullName>Cooperation_Level__c</fullName>
    <label>Cooperation Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Information__c/fields/Cooperative_Brand__c.field-meta.xml
<CustomField>
    <fullName>Cooperative_Brand__c</fullName>
    <label>Cooperative Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Information__c/fields/Industry_Position__c.field-meta.xml
<CustomField>
    <fullName>Industry_Position__c</fullName>
    <label>Industry Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Information__c/fields/Industry_Rank__c.field-meta.xml
<CustomField>
    <fullName>Industry_Rank__c</fullName>
    <label>Industry Rank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Information__c/fields/Market_share_in_customer_s_home_country__c.field-meta.xml
<CustomField>
    <fullName>Market_share_in_customer_s_home_country__c</fullName>
    <label>Market share in customer&apos;s home country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Information__c/fields/Store_Number__c.field-meta.xml
<CustomField>
    <fullName>Store_Number__c</fullName>
    <label>Store Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/Customer_Product_Line__c.object-meta.xml
<CustomObject>
    <label>Customer Product Line</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product_Line__c/fields/Annual_Sales_Scale__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Scale__c</fullName>
    <label>Annual Sales Scale($10K)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Cooperation_Level__c.field-meta.xml
<CustomField>
    <fullName>Cooperation_Level__c</fullName>
    <label>Cooperation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Strategic customer</fullName>
            </value>
            <value>
                <fullName>Advance customer</fullName>
            </value>
            <value>
                <fullName>Ordinary customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <formula>TEXT(Customer__r.Type)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Industry_Position__c.field-meta.xml
<CustomField>
    <fullName>Industry_Position__c</fullName>
    <inlineHelpText>TOP channel refers to the channel with a market share of not less than 5%</inlineHelpText>
    <label>Industry Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Top Channel</fullName>
            </value>
            <value>
                <fullName>Non-Top Channel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Industry_Rank__c.field-meta.xml
<CustomField>
    <fullName>Industry_Rank__c</fullName>
    <label>Industry Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>&gt;10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Market_Share__c.field-meta.xml
<CustomField>
    <fullName>Market_Share__c</fullName>
    <label>Market Share</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <label>Product Line Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>Small Domestic Home Appliances</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>Sound Bar</fullName>
            </value>
            <value>
                <fullName>Hitachi Commercial AC</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>B-Monitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateCustomerProductLineBatch.cls
/**
 * Customer_Product_Line__c,Customer_Information__c
 * 插入数据时跑一次
 * 更新客户产品线
 */
 
//UpdateCustomerProductLineBatch
//Customer_Information__c



global class UpdateCustomerProductLineBatch implements Database.Batchable<sObject> {
    public String query;
    // public String year;
    // public String month;


    global UpdateCustomerProductLineBatch() {
        this.query = 'select Id,Customer__r.Id,Customer__r.SAP_Customer_Code__c,Product_Line_Name__c from Customer_Product_Line__c '+
                     ' where Customer__c != null and Customer__r.SAP_Customer_Code__c != null';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Customer_Product_Line__c> cplList) {

        //更新产品线
        List<Customer_Product_Line__c> updateList = new List<Customer_Product_Line__c>();
        List<Account> accountList = new List<Account>();
        Set<String> cplKeys = new Set<String>();
        Set<String> accountKeys = new Set<String>();

        try {
            //产品线
            Map<String,String> pl = new Map<String,String>();

            pl.put('电视','TV'); //与translate不同 多媒体-电视(LED)
            pl.put('家空','AC'); //与translate不同 多媒体-电视(LED)
            pl.put('洗衣机','WM'); //与translate不同 多媒体-电视(LED)
            pl.put('手机','Mobile');
            pl.put('冰箱','Refrigerator'); //与translate不同 多媒体-电视(LED)
            pl.put('冷柜','Freezer'); //与translate不同 多媒体-电视(LED)
            pl.put('激光影院','Laser TV');
            pl.put('轻商','LCAC');
            pl.put('小家电','Small Domestic Home Appliances');
            pl.put('炉灶具','Cooking');
            pl.put('洗碗机','Dishwasher');
            pl.put('Sound Bar','Sound Bar');
            pl.put('Hitachi Commercial AC','Hitachi Commercial AC');
            pl.put('Medical Device','Medical Device');
            pl.put('商用显示器','B-Monitor');

            Map<String,String> industryPositionMap = new Map<String,String>();
            industryPositionMap.put('TOP客户','Top Channel');
            industryPositionMap.put('非TOP客户','Non-Top Channel');

            Map<String,String> cooperationLevelMap = new Map<String,String>();
            cooperationLevelMap.put('战略客户','Strategic customer');
            cooperationLevelMap.put('优质客户','Advance customer');
            cooperationLevelMap.put('普通客户','Ordinary customer');

            Map<String,String> customerCategoryMap = new Map<String,String>();
            customerCategoryMap.put('电器连锁','Electrical chains');
            customerCategoryMap.put('电商','eCommerce');
            customerCategoryMap.put('超市大卖场/杂货店','Supermarket');
            customerCategoryMap.put('其他','others');
            customerCategoryMap.put('专业渠道','Professional channels');
            customerCategoryMap.put('百货','Department store');
            customerCategoryMap.put('品牌代理','Agent');
            customerCategoryMap.put('OEM','OEM');
            customerCategoryMap.put('Brand Agents','Agent');
            customerCategoryMap.put('独立客户','Independent');
            customerCategoryMap.put('采购集团','Buying group');
            customerCategoryMap.put('批发商','Wholesaler');

            Map<String,String> channelLevelMap = new Map<String,String>();
            channelLevelMap.put('中高端渠道','Mid-High Level');
            channelLevelMap.put('非中高端渠道','Non Mid-High Level');

            List<String> brandList = new List<String>();
            brandList.add('Hisense');
            brandList.add('TOSHIBA');
            brandList.add('SHARP');
            brandList.add('Gorenje');
            brandList.add('ASKO');
            brandList.add('KELON');
            brandList.add('Other（OEM）');
            brandList.add('HITACHI');
            brandList.add('Ronshen');
            brandList.add('YORK');
            brandList.add('Vidda');
            brandList.add('SANDEN');
            brandList.add('聚好看');
            brandList.add('赛维');
            brandList.add('VIDAA');

            //客户管理名称和产品线为key
            Map<String,Customer_Product_Line__c> plMap = new Map<String,Customer_Product_Line__c>();
            
            for(Customer_Product_Line__c cpl : cplList){
                String key = cpl.Customer__r.SAP_Customer_Code__c + cpl.Product_Line_Name__c;
                plMap.put(key, cpl);
            }

            List<Customer_Information__c> ciList = [select Id,Customer_Code__c,Product_Line__c,Customer_Type__c,Channel_Level__c,Store_Number__c,Cooperative_Brand__c,
                    Market_share_in_customer_s_home_country__c,Industry_Position__c,Industry_Rank__c,Cooperation_Level__c,Annual_sales_scale__c,
                    Actual_Sales_Income_Ratio_21_Year__c,Actual_Sales_Income_Ratio_22_Year__c
                    from Customer_Information__c where Customer_Code__c != null];

            for(Customer_Information__c ci : ciList){

                List<String> sapCodes = ci.Customer_Code__c.split('/');

                for(String sapCode : sapCodes){
                    
                    Customer_Product_Line__c cpl = plMap.get(sapCode + pl.get(ci.Product_Line__c));
                    if(cpl != null){
                        //更新客户/客户产品线赋值

                        Account c = new Account();
                        c.Id = cpl.Customer__r.Id;
                        if(customerCategoryMap.get(ci.Customer_Type__c) != null){
                            c.Customer_Category__c = customerCategoryMap.get(ci.Customer_Type__c);
                        }
                        if(channelLevelMap.get(ci.Channel_Level__c) != null){
                            c.Channel_Level__c = channelLevelMap.get(ci.Channel_Level__c);
                        }
                        if(ci.Store_Number__c != null){
                            c.Total_Store_Quantity__c = Integer.valueOf(ci.Store_Number__c);
                        }

                        if(accountKeys.add(c.Id)){
                            accountList.add(c);
                        }

                        if(ci.Industry_Rank__c != null){
                            cpl.Industry_Rank__c = ci.Industry_Rank__c;
                        }
                        if(ci.Market_share_in_customer_s_home_country__c != null){
                            cpl.Market_Share__c = Double.valueOf(ci.Market_share_in_customer_s_home_country__c.replace('%', ''));
                        }
                        if(industryPositionMap.get(ci.Industry_Position__c) != null){
                            cpl.Industry_Position__c = industryPositionMap.get(ci.Industry_Position__c);
                        }
                        if(ci.Annual_sales_scale__c != null){
                            cpl.Annual_sales_scale__c = Double.valueOf(ci.Annual_sales_scale__c);
                        }
                        if(ci.Cooperative_Brand__c != null){
                            List<String> brands = ci.Cooperative_Brand__c.split(';');
                            String b = '';
                            for(String brand : brands){
                                if(containsIgnoreCase(brand,brandList)){
                                    b += brand + ';';
                                }else{
                                    b += 'Other（OEM）;';
                                }
                            }
                            cpl.Brand_work_with_Hisense__c = b.substring(0,b.length() - 1);
                        }


                        if(cooperationLevelMap.get(ci.Cooperation_Level__c) != null){
                            cpl.Cooperation_Level__c = cooperationLevelMap.get(ci.Cooperation_Level__c);
                        }
                        if(ci.Actual_Sales_Income_Ratio_21_Year__c != null){
                            cpl.Actual_Sales_Income_Ratio_N_1_Year__c = Double.valueOf(ci.Actual_Sales_Income_Ratio_21_Year__c.replace('%', ''));
                        }

                        if(ci.Actual_Sales_Income_Ratio_22_Year__c != null){
                            cpl.Actual_Sales_Income_Ratio_N_Year__c = Double.valueOf(ci.Actual_Sales_Income_Ratio_22_Year__c.replace('%', ''));
                        }

                        if(cplKeys.add(cpl.Id)){
                            updateList.add(cpl);
                        }
                    }
                }
            }
            System.debug('更新数据：' + accountList);
            System.debug('更新条数：' + accountList.size());
            Database.update(accountList);

            System.debug('更新数据：' + updateList);
            System.debug('更新条数：' + updateList.size());
            Database.update(updateList);
        }catch (Exception e) {
            //日志内容
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'UpdateCustomerProductLineBatch';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '0';
            ic.Req_Json__c = '出错:' + updateList;
            insert ic;
            System.debug('出错：'+e.getMessage()+e.getLineNumber());
        }
    }

    private boolean containsIgnoreCase(String s, List<String> l){
        for (String str : l){
           if (str.equalsIgnoreCase(s)){
               return true;
            }
        }
       return false;
     }

    global void finish(Database.BatchableContext BC) {
    }
}