force-app/main/default/objects/Account/fields/channel__c.field-meta.xml
<CustomField>
    <fullName>channel__c</fullName>
    <description>渠道23.9.28</description>
    <label>channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>零售</fullName>
            </value>
            <value>
                <fullName>综合</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/Daily_Inspection_Report__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>DIR-{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>巡店员日报编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>门店渠道名称</description>
    <formula>Store__r.Channel_item__r.Name</formula>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Inspection_Shop_Plan__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Shop_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店计划</label>
    <referenceTo>Inspection_Shop_Plan__c</referenceTo>
    <relationshipName>Daily_Inspection_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Task__c/Inspection_Shop_Task__c.object-meta.xml
<CustomObject>
    <label>Inspection Task</label>
    <nameField>
        <displayFormat>IST-{YYYY}{MM}{0000}</displayFormat>
        <label>任务编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Shop_Task__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Inspection_Shop_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promoter_Cost__c/Promoter_Cost__c.object-meta.xml
<CustomObject>
    <label>Promoter Cost</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Promoter Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoter Cost</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Cost__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Promoter Cost</relationshipLabel>
    <relationshipName>Promoter_Cost</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Revenue__c/Promoter_Revenue__c.object-meta.xml
<CustomObject>
    <label>Promoter Revenue</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Promoter Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoter Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Revenue__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Promoter Revenue</relationshipLabel>
    <relationshipName>Promoter_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/Retail_Number__c.object-meta.xml
<CustomObject>
    <label>Daily Sales</label>
    <nameField>
        <displayFormat>RN-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>零售业绩编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Number__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>产品</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND (5 OR 6)) OR 7</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ALL_Product_Japan</value>
        </filterItems>
        <filterItems>
            <field>$User.Country__c</field>
            <operation>notEqual</operation>
            <value>South Africa, Indonesia, Chile</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>notEqual</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RegionalProduct</value>
        </filterItems>
        <filterItems>
            <field>$User.Country__c</field>
            <operation>equals</operation>
            <value>South Africa, Indonesia, Chile,Thailand,Singapore</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile, Hisense Argentina, Hisense West Africa, Hisense Saudi, Hisense Canada, Hisense USA, Hisense Mexico, Hisense Thailand, Hisense Vietnam, Hisense Malaysia,Hisense Philippines,Hisense Peru</value>
        </filterItems>
        <filterItems>
            <field>$Profile.ManageUsers</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Daily Sales (产品)</relationshipLabel>
    <relationshipName>ProductdalH</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Retail_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Condition__c/Sampling_Condition__c.object-meta.xml
<CustomObject>
    <label>Sampling Condition</label>
    <nameField>
        <displayFormat>SCN-{YYYY}{MM}{0000}</displayFormat>
        <label>Sampling Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sampling Condition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Condition__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>渠道名称</description>
    <inlineHelpText>This field needs to be checked for consistency with channel name in the system</inlineHelpText>
    <label>Channel</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sampling_Detail__c/Sampling_Detail__c.object-meta.xml
<CustomObject>
    <label>Sampling Detail</label>
    <nameField>
        <displayFormat>SD{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>出样明细编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sampling Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Detail__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>出样明细</relationshipLabel>
    <relationshipName>Sampling_Detail_Shop</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/Sampling_Inspection__c.object-meta.xml
<CustomObject>
    <label>Sampling Inspection</label>
    <nameField>
        <displayFormat>SI-{YYYY}{MM}{0000}</displayFormat>
        <label>出样检查编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sampling Inspection</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Inspection__c/fields/Inspection_Shop_Task__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Shop_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店任务</label>
    <referenceTo>Inspection_Shop_Task__c</referenceTo>
    <relationshipName>Task_Sampling_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Sampling_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Target__c/Sampling_Target__c.object-meta.xml
<CustomObject>
    <label>Sampling Target</label>
    <nameField>
        <label>Sampling Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sampling Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Target__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>渠道名称（和Customer_Management__c表中的客户管理名称Management_Name__c一致）</description>
    <label>Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendRecordTotalNumberToBigData.cls
/**********************************************************************
 * function:将Channel推送给大数据
 * @author:lizunxing
 * @url: /services/apexrest
 * @data: 
 * date:2024-01-31
*************************************************************************/
@RestResource(urlMapping='/SendRecordTotalNumberToBigData')
global with sharing class SendRecordTotalNumberToBigData {  

    global class AppInput{
        //public String startTime; 
        public String endTime; 
    }
    global class AppOutPut{
        public String channelTotalNumber;
        public String samplingDetailTotalNumber;
        public String samplingConditionTotalNumber;
        public String userTotalNumber;
        public String dailySalesTotalNumber;
        public String samplingTargetTotalNumber;
        public String inspectionPlanTotalNumber;
        public String inspectionTaskTotalNumber;
        public String samplingInspectionTotalNumber;
        public String storeTotalNumber;
        public String productTotalNumber;
        public String customerTotalNumber;
        public String promotersTotalNumber;
        public String dailyInspectionReportTotalNumber;
        public String ticketTotalNumber;
        public String customerManagementTotalNumber;
        public String promoterRevenueTotalNumber;
        public String promoterCostTotalNumber;
        public String storeProductlineTotalNumber;
    }

    @HttpPost
    global static SendRecordTotalNumberToBigData.AppOutPut adoPost() {

        RestRequest req = RestContext.request;
        String reqBody = req.requestBody.tostring(); 
        //String reqBody = '{"startTime":"2024-01-09 00:00:00","endTime":"2024-01-10 00:00:00"}'; 
        SendRecordTotalNumberToBigData.AppInput appInput = new SendRecordTotalNumberToBigData.AppInput();
        
        SendRecordTotalNumberToBigData.AppOutPut result = new SendRecordTotalNumberToBigData.AppOutPut();
        
        try{
            appInput = (SendRecordTotalNumberToBigData.AppInput)JSON.deserialize(reqBody, SendRecordTotalNumberToBigData.AppInput.class);

            if(String.isBlank(appInput.endTime)){
                return result;
            }

            //Datetime startTime = Datetime.valueOf(appInput.startTime);
            Datetime endTime = Datetime.valueOf(appInput.endTime).addHours(8);

            List<AggregateResult> c = [select count(id) totalNumber from Channel__c where LastModifiedDate <= :endTime];
            result.channelTotalNumber = c.get(0).get('totalNumber') + '';

            List<AggregateResult> sd = [select count(id) totalNumber from Sampling_Detail__c where LastModifiedDate <= :endTime];
            result.samplingDetailTotalNumber = sd.get(0).get('totalNumber') + '';

            List<AggregateResult> sc = [select count(id) totalNumber from Sampling_Condition__c where LastModifiedDate <= :endTime];
            result.samplingConditionTotalNumber = sc.get(0).get('totalNumber') + '';

            List<AggregateResult> user = [select count(id) totalNumber from user where LastModifiedDate <= :endTime];
            result.userTotalNumber = user.get(0).get('totalNumber') + '';

            List<AggregateResult> ru = [select count(id) totalNumber from Retail_Number__c where LastModifiedDate <= :endTime];
            result.dailySalesTotalNumber = ru.get(0).get('totalNumber') + '';

            List<AggregateResult> st = [select count(id) totalNumber from Sampling_Target__c where LastModifiedDate <= :endTime];
            result.samplingTargetTotalNumber = st.get(0).get('totalNumber') + '';

            List<AggregateResult> isp = [select count(id) totalNumber from Inspection_Shop_Plan__c where LastModifiedDate <= :endTime];
            result.inspectionPlanTotalNumber = isp.get(0).get('totalNumber') + '';

            List<AggregateResult> ist = [select count(id) totalNumber from Inspection_Shop_Task__c where LastModifiedDate <= :endTime];
            result.inspectionTaskTotalNumber = ist.get(0).get('totalNumber') + '';

            List<AggregateResult> si = [select count(id) totalNumber from Sampling_Inspection__c where LastModifiedDate <= :endTime];
            result.samplingInspectionTotalNumber = si.get(0).get('totalNumber') + '';
            
            List<AggregateResult> store = [select count(id) totalNumber from Shop__c where LastModifiedDate <= :endTime];
            result.storeTotalNumber = store.get(0).get('totalNumber') + '';

            List<AggregateResult> p = [select count(id) totalNumber from Product__c where LastModifiedDate <= :endTime];
            result.productTotalNumber = p.get(0).get('totalNumber') + '';

            List<AggregateResult> customer = [select count(id) totalNumber from Account where LastModifiedDate <= :endTime];
            result.customerTotalNumber = customer.get(0).get('totalNumber') + '';

            List<AggregateResult> rp = [select count(id) totalNumber from Responsible_Person__c where LastModifiedDate <= :endTime];
            result.promotersTotalNumber = rp.get(0).get('totalNumber') + '';

            List<AggregateResult> dir = [select count(id) totalNumber from Daily_Inspection_Report__c where LastModifiedDate <= :endTime];
            result.dailyInspectionReportTotalNumber = dir.get(0).get('totalNumber') + '';

            List<AggregateResult> ticket = [select count(id) totalNumber from Ticket__c where LastModifiedDate <= :endTime];
            result.ticketTotalNumber = ticket.get(0).get('totalNumber') + '';

            List<AggregateResult> cm = [select count(id) totalNumber from Customer_Management__c where LastModifiedDate <= :endTime];
            result.customerManagementTotalNumber = cm.get(0).get('totalNumber') + '';

            List<AggregateResult> pr = [select count(id) totalNumber from Promoter_Revenue__c where LastModifiedDate <= :endTime];
            result.promoterRevenueTotalNumber = pr.get(0).get('totalNumber') + '';

            List<AggregateResult> pc = [select count(id) totalNumber from Promoter_Cost__c where LastModifiedDate <= :endTime];
            result.promoterCostTotalNumber = pc.get(0).get('totalNumber') + '';

            List<AggregateResult> spl = [select count(id) totalNumber from Store_Product_Line__c where LastModifiedDate <= :endTime];
            result.storeProductlineTotalNumber = spl.get(0).get('totalNumber') + '';

            System.debug('result :' + result);
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendRecordTotalNumberToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '1';
            ic.Req_Json__c = reqBody;
            insert ic;

            return result; 
        }catch(Exception e){
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendRecordTotalNumberToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '0';
            ic.Req_Json__c = reqBody;
            ic.ErrorMsg__c = e.getMessage();
            insert ic;

            return result; 
        }
    }

    public static String checkNull(String str){
        if(String.isBlank(str)){
            return '';
        }else if('null'.equals(str)){
            return '';
        }else{
            return str;
        }
    }
}