force-app/main/default/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Undeveloped</fullName>
                <default>true</default>
                <label>Undeveloped</label>
            </value>
            <value>
                <fullName>Developing</fullName>
            </value>
            <value>
                <fullName>Collaborated</fullName>
            </value>
            <value>
                <fullName>Eliminated</fullName>
            </value>
            <value>
                <fullName>FD32</fullName>
                <label>Credit Block (SAP)</label>
            </value>
            <value>
                <fullName>XD05</fullName>
                <label>Business Block (SAP)</label>
            </value>
            <value>
                <fullName>XD06</fullName>
                <label>Logic Deleted (SAP)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>黑电海信</fullName>
            </value>
            <value>
                <fullName>黑电东芝</fullName>
            </value>
            <value>
                <fullName>冰冷</fullName>
            </value>
            <value>
                <fullName>洗衣机小厨电</fullName>
            </value>
            <value>
                <fullName>空调</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Industry Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>&gt;20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/Customer_Product_Line__c.object-meta.xml
<CustomObject>
    <label>Customer Product Line</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product_Line__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Expected_Development_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Development_Date__c</fullName>
    <label>Expected Development Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Key_Sales__c.field-meta.xml
<CustomField>
    <fullName>Key_Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Key Sales</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <label>Product Line Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>Small Domestic Home Appliances</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>Sound Bar</fullName>
            </value>
            <value>
                <fullName>Hitachi Commercial AC</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>B-Monitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Strategy Customer</fullName>
            </value>
            <value>
                <fullName>Quality Customer</fullName>
            </value>
            <value>
                <fullName>Normal Customer</fullName>
            </value>
            <value>
                <fullName>Eliminated Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Recent_Evaluated_Rank__c.field-meta.xml
<CustomField>
    <fullName>Recent_Evaluated_Rank__c</fullName>
    <label>Recent Evaluated Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Strategy Customer</fullName>
            </value>
            <value>
                <fullName>Quality Customer</fullName>
            </value>
            <value>
                <fullName>Normal Customer</fullName>
            </value>
            <value>
                <fullName>Inferior Customer</fullName>
            </value>
            <value>
                <fullName>Potential Eliminated Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>销售姓名</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>Salesperson No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/IsKeyUser__c.field-meta.xml
<CustomField>
    <fullName>IsKeyUser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If there are multiple sales in the same product line, select one sales person as the key user for reports and statistics</inlineHelpText>
    <label>IsKeyUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductLineTriggerHandler.cls
/**************************************************************************************************
 * ProductLineTriggerHandler
 * Purpose:Score Sheet Trigger处理逻辑
 * Author: Deloitte xiaowei
 * Create Date: 2019-02-13  Last modified by johnson2019-09-12
***************************************************************************************************/
public class ProductLineTriggerHandler extends TriggerHandler{
    //获取客户产品线的Sales字段的field set 
    public static List<Schema.FieldSetMember> plSalesFieldSet = SObjectType.Customer_Product_Line__c.FieldSets.All_Sales_Fields.getFields();
	public override void afterInsert(){
        List<Account> accUp = new List<Account>();

        List<Sales__c> sales = new List<Sales__c>();
        for(Customer_Product_Line__c cpl : ((list<Customer_Product_Line__c>)Trigger.new)){
            //录入产品线计划开发完成时间录入时更新客户状态
            if(cpl.Expected_Development_Date__c != null){
                Account acc = new Account();
                acc.Customer_Status__c = 'Developping';
                acc.id = cpl.Customer__c;
                accUp.add(acc);
            }

            //根据填写的每个sales字段自动创建sales数据
            for(Schema.FieldSetMember plSales : plSalesFieldSet) {
                //System.debug('plSales: '+plSales);
                if(cpl.get(plSales.getFieldPath()) != null){
                    Sales__c sc1 = new Sales__c();
                    sc1.Sales__c = cpl.get(plSales.getFieldPath()) + '';
                    sc1.Customer__c= cpl.Customer__c;
                    sc1.Product_Line__c = cpl.Product_Line_Name__c;
                    sc1.IsKeyUser__c = plSales.getFieldPath().contains('Key_Sales__c') ? true : false;
                    sales.add(sc1);
                }
            }
            
        }
        update accUp;
        Database.insert(sales,false);
    }

    public override void beforeUpdate(){
        List<Account> accUp = new List<Account>();
        //需要新增的Sales
        List<Sales__c> insertSales = new List<Sales__c>();
        //需要删除的Sales的Key指向Account ID的Map
        Map<String,String> deleteSalesKeyMap = new Map<String,String>();

        for(Customer_Product_Line__c cpl : ((list<Customer_Product_Line__c>)Trigger.new)){
            Customer_Product_Line__c oCpl = (Customer_Product_Line__c)Trigger.oldMap.get(cpl.Id);
            //Rank字段更新，则将old值存到Last Rank中
            if(cpl.Rank__c != oCpl.Rank__c){
                cpl.Recent_Evaluated_Rank__c = oCpl.Rank__c;
            }
            //录入产品线计划开发完成时间录入时更新客户状态
            if(cpl.Expected_Development_Date__c != oCpl.Expected_Development_Date__c 
            && cpl.Expected_Development_Date__c != null){
                Account acc = new Account();
                acc.Customer_Status__c = 'Developping';
                acc.id = cpl.Customer__c;
                accUp.add(acc);
            }

            //根据填写的每个sales字段自动创建sales数据
            for(Schema.FieldSetMember plSales : plSalesFieldSet) {
                if(cpl.get(plSales.getFieldPath()) != oCpl.get(plSales.getFieldPath())){
                    //如果Sales字段值修改后不为空则将自动创建Sales数据
                    if(cpl.get(plSales.getFieldPath()) != null){
                        Sales__c sc1 = new Sales__c();
                        sc1.Sales__c = cpl.get(plSales.getFieldPath())+'';
                        sc1.Customer__c= cpl.Customer__c;
                        sc1.Product_Line__c = cpl.Product_Line_Name__c;
                        sc1.IsKeyUser__c = plSales.getFieldPath().contains('Key_Sales__c') ? true : false;
                        insertSales.add(sc1);
                    }
                    //如果Sales字段修改前值不为空则许将相关Sales数据删除
                    if(oCpl.get(plSales.getFieldPath()) != null){
                        deleteSalesKeyMap.put(cpl.Customer__c + cpl.Product_Line_Name__c + oCpl.get(plSales.getFieldPath()),cpl.Customer__c);
                    }
                }
            }
        }
        deleteSalesBySalesKeyMap(deleteSalesKeyMap);
        Database.insert(insertSales,false);
        update accUp;
    }

    public override void afterUpdate(){
        List<String> accEIDs = new List<String>();

        for(Customer_Product_Line__c cpl : ((list<Customer_Product_Line__c>)Trigger.new)){
            //变更为淘汰时需要查询的客户
            if(cpl.Rank__c == 'Eliminated Customer'){
                accEIDs.add(cpl.Customer__c);
            }
        }

        //查询客户产品线
        List<Customer_Product_Line__c> cples = [select Customer__c,Rank__c from Customer_Product_Line__c where Customer__c in:accEIDs];

        //组装客户与产品线的关系
        Map<String, List<Customer_Product_Line__c>> eAccMap = new Map<String, List<Customer_Product_Line__c>>();
        for (Customer_Product_Line__c  cple: cples) {
            if(eAccMap.containsKey(cple.Customer__c)){
                List<Customer_Product_Line__c> cplesTmp = eAccMap.get(cple.Customer__c);
                cplesTmp.add(cple);
                eAccMap.put(cple.Customer__c,cplesTmp);
            }else{
                List<Customer_Product_Line__c> cplesTmp = new List<Customer_Product_Line__c>();
                cplesTmp.add(cple);
                eAccMap.put(cple.Customer__c,cplesTmp);
            }
        }

        List<Account> upAccs = new List<Account>();
        Boolean isUpdate = true;
        for(String accId : eAccMap.keySet()){
            Account tempAcc = new Account();
            tempAcc.id = accId;
            for (Customer_Product_Line__c cpl : eAccMap.get(accId)) {
               //如果有不为淘汰的pl则不更新客户
               if(cpl.Rank__c != 'Eliminated Customer'){
                   isUpdate = false;
               }
            }
            if(isUpdate){
                tempAcc.Customer_Status__c = 'Eliminated';
                upAccs.add(tempAcc);
            }
        }
        update upAccs;
    }
    public override void afterDelete(){
        //需要删除的Sales的Key指向Account ID的Map
        Map<String,String> deleteSalesKeyMap = new Map<String,String>();
        for(Customer_Product_Line__c oCpl : ((list<Customer_Product_Line__c>)Trigger.old)){
             //根据填写的每个sales字段自动删除sales数据
            for(Schema.FieldSetMember plSales : plSalesFieldSet) {
                //如果Sales字段修改前值不为空则许将相关Sales数据删除
                if(oCpl.get(plSales.getFieldPath()) != null){
                    deleteSalesKeyMap.put(oCpl.Customer__c + oCpl.Product_Line_Name__c + oCpl.get(plSales.getFieldPath()),oCpl.Customer__c);
                }
            }
        }
        deleteSalesBySalesKeyMap(deleteSalesKeyMap);
    }
    /**
     方法名: deleteSalesBySalesKeyMap
     功能说明: 根据删除的deleteSalesKeyMap删除相关Sales数据 
     参数说明: Map<String,String> deleteSalesKeyMap Customer ID + Product Line + Sales Person ID => Customer ID
     返回值: 
     作者: Johnson
     日期: 2019-09-12
    */
    public void deleteSalesBySalesKeyMap(Map<String,String> deleteSalesKeyMap){
        if(deleteSalesKeyMap.keySet().size() > 0){
            //需要删除的Sales
            List<Sales__c> deleteSales = new List<Sales__c>();
            Map<String,Sales__c> deleteSalesMap = new Map<String,Sales__c>();
            for(Sales__c sales : [SELECT Id,Customer__c,Sales__c,Product_Line__c FROM Sales__c 
                                  WHERE Customer__c IN:deleteSalesKeyMap.values()]){
                String salesKey = sales.Customer__c + sales.Product_Line__c + sales.Sales__c;
                if(deleteSalesKeyMap.containsKey(salesKey)){
                    deleteSales.add(sales);
                }
            }
            delete deleteSales;
        }
    }
}