force-app/main/default/objects/Account/fields/Customer_Management_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Management_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The name is used to clarify the affiliation of different customers, so as to conduct a unified analysis of the customer&apos;s business situation.</inlineHelpText>
    <label>Customer Management Name</label>
    <referenceTo>Customer_Management__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Management__c/Customer_Management__c.object-meta.xml
<CustomObject>
    <description>客户管理名称</description>
    <label>Customer Management</label>
    <nameField>
        <label>Customer Management Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendCustomerInfoToBigDataTest.cls
@isTest
private class SendCustomerInfoToBigDataTest {
    static testMethod void testMethod1() {
        Test.startTest();
        Account a = new Account();
        a.SAP_Customer_Code__c = 'aaaa';
        a.Name = 'test001';
        insert a;
        SendCustomerInfoToBigData.adoPost() ; 
        Test.stopTest();
    }

    static testMethod void testMethod2() {
        Test.startTest();
        Account a = new Account();
        a.SAP_Customer_Code__c = '0000';
        a.Name = 'test001';
        insert a;
        SendCustomerInfoToBigData.adoPost() ; 
        Test.stopTest();
    }

    static testMethod void testMethod3() {
        Test.startTest();
        Customer_Management__c c = new Customer_Management__c();
        c.Name = 'Test';
        insert c;
        List<Customer_Management__c> cm = [select Id from Customer_Management__c];
        
        Account a = new Account();
        a.SAP_Customer_Code__c = '0000';
        a.Name = 'test001';
        a.Customer_Management_Name__c = cm[0].Id;
        insert a;
        SendCustomerInfoToBigData.adoPost() ; 
        Test.stopTest();
    }
}