force-app/main/default/objects/Account/fields/Ecss_Flag__c.field-meta.xml
<CustomField>
    <fullName>Ecss_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>true:跳过</description>
    <label>Ecss Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ecss_Result__c.field-meta.xml
<CustomField>
    <fullName>Ecss_Result__c</fullName>
    <label>Ecss Result</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hisense_Entity__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Entity__c</fullName>
    <inlineHelpText>Financial required</inlineHelpText>
    <label>Hisense Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Hisense_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hisense_Entity_Sales__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Entity_Sales__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Hisense_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trader_Type__c.field-meta.xml
<CustomField>
    <fullName>Trader_Type__c</fullName>
    <label>Trader Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>H001</fullName>
                <label>H001 集团内业务伙伴</label>
            </value>
            <value>
                <fullName>H002</fullName>
                <label>H002 集团外业务伙伴</label>
            </value>
            <value>
                <fullName>H003</fullName>
                <label>H003 一次性业务伙伴</label>
            </value>
            <value>
                <fullName>H004</fullName>
                <label>H004 员工类业务伙伴</label>
            </value>
            <value>
                <fullName>H005</fullName>
                <label>H005 门店地址业务伙伴</label>
            </value>
            <value>
                <fullName>H006</fullName>
                <label>H006 非注册实体业务伙伴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Address__c/Customer_Address__c.object-meta.xml
<CustomObject>
    <label>Customer Address</label>
    <nameField>
        <label>Customer Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Address__c/fields/Customer_Name_Local_Language_1__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name_Local_Language_1__c</fullName>
    <label>Customer Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Address__c/fields/Hisense_Entity__c.field-meta.xml
<CustomField>
    <fullName>Hisense_Entity__c</fullName>
    <inlineHelpText>Financial required</inlineHelpText>
    <label>Hisense Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Hisense_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Address__c/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Address__c/fields/Trader_Type__c.field-meta.xml
<CustomField>
    <fullName>Trader_Type__c</fullName>
    <label>Trader Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>H001</fullName>
                <label>H001 集团内业务伙伴</label>
            </value>
            <value>
                <fullName>H002</fullName>
                <label>H002 集团外业务伙伴</label>
            </value>
            <value>
                <fullName>H003</fullName>
                <label>H003 一次性业务伙伴</label>
            </value>
            <value>
                <fullName>H004</fullName>
                <label>H004 员工类业务伙伴</label>
            </value>
            <value>
                <fullName>H005</fullName>
                <label>H005 门店地址业务伙伴</label>
            </value>
            <value>
                <fullName>H006</fullName>
                <label>H006 非注册实体业务伙伴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/National_tax_category__c/National_tax_category__c.object-meta.xml
<CustomObject>
    <label>税分类国家</label>
    <nameField>
        <label>National Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_tax_category__c/fields/National_code__c.field-meta.xml
<CustomField>
    <fullName>National_code__c</fullName>
    <label>National code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/National_tax_category__c/fields/sort__c.field-meta.xml
<CustomField>
    <fullName>sort__c</fullName>
    <label>sort</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/National_tax_category__c/fields/Tax_category__c.field-meta.xml
<CustomField>
    <fullName>Tax_category__c</fullName>
    <label>Tax category</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_category__c/Tax_category__c.object-meta.xml
<CustomObject>
    <label>Tax category</label>
    <nameField>
        <label>Tax code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaxCountryMapping__c/TaxCountryMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TaxCountryMapping</label>
</CustomObject>

force-app/main/default/objects/Trader_Type__c/Trader_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>客商类型，sap对应关系</description>
    <label>Trader Type</label>
</CustomObject>

force-app/main/default/objects/Trader_Type__c/fields/Trader_Type__c.field-meta.xml
<CustomField>
    <fullName>Trader_Type__c</fullName>
    <label>Trader Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerAddressToAccountBatchTest.cls
@isTest
public with sharing class CustomerAddressToAccountBatchTest{
    @isTest
    static void methodTest1(){
        TestDataUtility.createCustomSettings();

        TaxCountryMapping__c tcm = new TaxCountryMapping__c();
        tcm.name = '8110';
        tcm.Country__c = 'USA';
        insert tcm;

        National_tax_category__c ntc = new National_tax_category__c();
        ntc.National_code__c = 'US';
        ntc.sort__c = 1;
        ntc.Tax_category__c = 'UTXJ';
        insert ntc;


        Account acc1 = new Account();
        acc1.Name = 'Test Account002Test';
        acc1.SAP_Customer_Code__c = '1772378988';
        acc1.External_Key__c = '1772378988';
        acc1.Trader_Type__c = 'H002';
        acc1.Ecss_Flag__c = true;
        acc1.Ecss_Result__c = '123';
        insert (acc1);

        Customer_Address__c ca = new Customer_Address__c();
        ca.Name = 'testca';
        ca.SAP_Customer_Code__c = '0001110001';
        ca.Email__c = '3333@qq.com';
        ca.Customer_Name_Local_Language_1__c = 'name-01';
        ca.Hisense_Entity__c = '8110';
        ca.Hisense_Entity_Sales__c = '8110';
        insert ca;

        Test.startTest();

        CustomerAddressToAccountBatch ss = new CustomerAddressToAccountBatch();
        Database.executeBatch(ss);

        CustomerAddressToAccountBatch ss1 = new CustomerAddressToAccountBatch('NoEntity');
        Database.executeBatch(ss1);

        CustomerAddressToAccountBatch ss2 = new CustomerAddressToAccountBatch(new List<String>{'0001110001'});
        Database.executeBatch(ss2);

        Test.stopTest();
    }

}