force-app/main/default/objects/Account/fields/Eliminate_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Eliminate_Approval_Status__c</fullName>
    <label>Eliminate Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Processes_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/InterfaceLog__c.object-meta.xml
<CustomObject>
    <label>InterfaceLog</label>
    <nameField>
        <label>No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InterfaceLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InterfaceLog__c/fields/ErrorMsg__c.field-meta.xml
<CustomField>
    <fullName>ErrorMsg__c</fullName>
    <label>ErrorMsg</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/Req_Json__c.field-meta.xml
<CustomField>
    <fullName>Req_Json__c</fullName>
    <label>Req Json</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/ReturnCode__c.field-meta.xml
<CustomField>
    <fullName>ReturnCode__c</fullName>
    <label>ReturnCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Approval_Processes_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>流程审批状态</description>
    <masterLabel>Approval Processes Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EliminateCustomerController.cls
/*
 * @Author: WFC
 * @Date: 2022-07-06 11:12:54
 * @LastEditors: WFC
 * @LastEditTime: 2022-07-25 10:33:32
 * @Description: 
 * @FilePath: \Hitest\force-app\main\default\classes\EliminateCustomerController.cls
 */

public without sharing class EliminateCustomerController{
    
    public static User currentUser = [SELECT Id,Name,Username,Profile.name FROM User WHERE Id =:UserInfo.getUserId()]; 

    @AuraEnabled
    public static OutPut saveData(String comments, Id recordId, String approvalName){
        OutPut out = new OutPut();
        try {
            // 验证淘汰流程和重启流程
            Account acc = [SELECT Eliminate_Approval_Status__c FROM Account WHERE Id =:recordId LIMIT 1];
            // 淘汰审批没有完成 点击重启流程按钮
            if(acc.Eliminate_Approval_Status__c != 'Approved' && approvalName == 'RestoreCustomer'){
                out.isSucess = false;
                out.errorMsg = Label.No_applicable_approval_process;
                return out; 
            }else if(acc.Eliminate_Approval_Status__c == 'Approved' && approvalName == 'EliminateCustomer'){
                // 淘汰审批通过 点击淘汰按钮
                out.isSucess = false;
                out.errorMsg = Label.No_applicable_approval_process;
                return out; 
            }
            
            // 客户淘汰流程
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest(); 
            req1.setComments(comments); 
            req1.setObjectId(recordId); 
            // Submit on behalf of a specific submitter 
            req1.setSubmitterId(currentUser.id); 
            // Submit the record to specific process and skip the criteria evaluation 
            req1.setSkipEntryCriteria(false); // Submit the approval request for the account 
            Approval.ProcessResult result = Approval.process(req1); // Verify the result 
            System.assert(result.isSuccess());

            out.isSucess = true;

            //日志内容
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'EliminateCustomerController';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '1';
            ic.Req_Json__c = 'approvalName:' + approvalName + '———comments:' + comments + '———recordId:' + recordId + '———currentUser:' + currentUser.id;
            insert ic;

        } catch (Exception e) {
            out.isSucess = false;
            out.errorMsg = Label.No_applicable_approval_process;
            //日志内容
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'EliminateCustomerController';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '0';
            ic.Req_Json__c = 'approvalName:' + approvalName + '———comments:' + comments + '———recordId:' + recordId + '———currentUser:' + currentUser.id;
            ic.ErrorMsg__c = e.getMessage() + '————' +  e.getLineNumber();
            insert ic;
        }
        return out; 

    }

    public class OutPut {

        @AuraEnabled
		public Boolean isSucess {get; set;}

		@AuraEnabled
		public String errorMsg {get; set;}

       
    } 
}