force-app/main/default/objects/Account/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <inlineHelpText>Please confirm the correct postal code format, otherwise an error will occur when synchronizing customer information to the SAP system! Thank you!</inlineHelpText>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>HVAC region</description>
    <inlineHelpText>HVAC region</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Southeast</fullName>
            </value>
            <value>
                <fullName>Northwest</fullName>
            </value>
            <value>
                <fullName>Southwest</fullName>
            </value>
            <value>
                <fullName>Midwest</fullName>
            </value>
            <value>
                <fullName>Eastern Canada</fullName>
            </value>
            <value>
                <fullName>Western Canada</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
                <isActive>false</isActive>
                <label>Central</label>
            </value>
            <value>
                <fullName>North</fullName>
                <isActive>false</isActive>
                <label>North</label>
            </value>
            <value>
                <fullName>South</fullName>
                <isActive>false</isActive>
                <label>South</label>
            </value>
            <value>
                <fullName>West</fullName>
                <isActive>false</isActive>
                <label>West</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Group__c.field-meta.xml
<CustomField>
    <fullName>Sales_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PickList__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Master Data(Team)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PickList__c</referenceTo>
    <relationshipLabel>Customers (Sales Group)</relationshipLabel>
    <relationshipName>CustomersSales_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Office</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2 AND 4</booleanFilter>
        <filterItems>
            <field>PickList__c.belong_to_he__c</field>
            <operation>equals</operation>
            <valueField>$Source.Hisense_Entity_Sales__c</valueField>
        </filterItems>
        <filterItems>
            <field>PickList__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Master Data(Office)</value>
        </filterItems>
        <filterItems>
            <field>PickList__c.belong_to_he__c</field>
            <operation>equals</operation>
            <valueField>$Source.Hisense_Entity__c</valueField>
        </filterItems>
        <filterItems>
            <field>PickList__c.Freeze__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PickList__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>CustomersSales_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PO__c/PO__c.object-meta.xml
<CustomObject>
    <label>PO</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>PO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PO__c/fields/Category_of_Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Category_of_Delivery_Address__c</fullName>
    <label>Category of Delivery Address</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
                <default>true</default>
                <label>Store</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PO__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PO</relationshipLabel>
    <relationshipName>PO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PO__c/fields/PO__c.field-meta.xml
<CustomField>
    <fullName>PO__c</fullName>
    <formula>HYPERLINK(
&quot;/lightning/cmp/c__lwcWrapper?c__lwcName=uploadStorePicturesLWC&amp;c__versionId=&quot; &amp; CoverImgVersionId__c &amp; &quot;&amp;c__fileType=&quot;&amp; CoverImgFileType__c &amp; &quot;&amp;c__contentBodyId=&quot;&amp; CoverImgContentBodyId__c &amp; &quot;&amp;c__recordId=&quot;&amp; Id &amp; &quot;&amp;c__versionIdField=CoverImgVersionId__c&amp;c__contentBodyIdField=CoverImgContentBodyId__c&amp;c__fileTypeField=CoverImgFileType__c&amp;c__isImgManagement=true&quot;,
IF (
ISBLANK( CoverImgVersionId__c ),
IMAGE(&quot;/logos/Custom/Plus_Primary/logo.png&quot;, &quot;Review&quot;, 20, 20),
IMAGE(&quot;/sfc/servlet.shepherd/version/renditionDownload?rendition=thumb120by90&amp;versionId=&quot; &amp; CoverImgVersionId__c &amp; &quot;&amp;operationContext=CHATTER&amp;contentId=&quot; &amp; CoverImgContentBodyId__c, &quot;Preview is generating, please refresh later&quot;, 90, 120)
),
&quot;_parent&quot;
)</formula>
    <label>PO</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Model</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PO</relationshipLabel>
    <relationshipName>PO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PO__c/fields/Sample_Display__c.field-meta.xml
<CustomField>
    <fullName>Sample_Display__c</fullName>
    <label>Sample Display</label>
    <referenceTo>Sample_Display__c</referenceTo>
    <relationshipLabel>PO</relationshipLabel>
    <relationshipName>PO</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sony</fullName>
            </value>
            <value>
                <fullName>Daikin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/Sample_Display__c.object-meta.xml
<CustomObject>
    <label>Sample Display</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Sample Display Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Display</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Display__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sample Display</relationshipLabel>
    <relationshipName>Sample_Display</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Model</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>$Source.Sales_Region__c</field>
            <operation>equals</operation>
            <valueField>Product__c.sales_region__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sample Display</relationshipLabel>
    <relationshipName>Sample_Display</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Sample Display</relationshipLabel>
    <relationshipName>Sample_Display</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Sum_Store_Details_Number__c.field-meta.xml
<CustomField>
    <fullName>Sum_Store_Details_Number__c</fullName>
    <description>拆分的store details数量和</description>
    <label>*Sum Store Details Number</label>
    <summarizedField>Store_Detail__c.Number__c</summarizedField>
    <summaryForeignKey>Store_Detail__c.Sample_Display__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Task_Level__c.field-meta.xml
<CustomField>
    <fullName>Task_Level__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <label>Task Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/SAP__c/SAP__c.object-meta.xml
<CustomObject>
    <label>SAP</label>
    <nameField>
        <displayFormat>SAP-{0000}</displayFormat>
        <label>SAP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP__c/fields/Sample_Display__c.field-meta.xml
<CustomField>
    <fullName>Sample_Display__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sample Display</label>
    <referenceTo>Sample_Display__c</referenceTo>
    <relationshipLabel>SAP</relationshipLabel>
    <relationshipName>SAP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP__c/fields/SAP_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Number__c</fullName>
    <label>SAP Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP__c/fields/Storage_Location_Description__c.field-meta.xml
<CustomField>
    <fullName>Storage_Location_Description__c</fullName>
    <label>Storage Location Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP__c/fields/ZD_Name__c.field-meta.xml
<CustomField>
    <fullName>ZD_Name__c</fullName>
    <label>ZD Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store_Detail__c/Store_Detail__c.object-meta.xml
<CustomObject>
    <label>Store Detail</label>
    <nameField>
        <displayFormat>SD-{0000}</displayFormat>
        <label>Store Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Detail__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store_Detail__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Model</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Store Detail</relationshipLabel>
    <relationshipName>Store_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Detail__c/fields/Sample_Display__c.field-meta.xml
<CustomField>
    <fullName>Sample_Display__c</fullName>
    <label>Sample Display</label>
    <referenceTo>Sample_Display__c</referenceTo>
    <relationshipLabel>Store Detail</relationshipLabel>
    <relationshipName>Store_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Detail__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Store Detail</relationshipLabel>
    <relationshipName>Store_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SampleDisplayDetailsController.cls
/*
 * @Author: WFC
 * @Date: 2024-10-10 16:45:01
 * @LastEditors: WFC
 * @LastEditTime: 2025-01-08 14:19:54
 * @Description:
 * @FilePath: \hisense005\force-app\main\default\classes\SampleDisplayDetailsController.cls
 */
public without sharing class SampleDisplayDetailsController{
    /**
     * @Param: SampleDisplay Id
     * @Return:
     * @Author: WFC
     * @Date: 2024-10-25 09:34:28
     * @Description: 查询sample display相关信息
     */
    @AuraEnabled
    public static Map<String, Object> searchSampleDisplay(String recordId){
        Map<String, Object> result = new Map<String, Object>();
        // 父级Sample_Display__c信息
        Sample_Display__c sampleDisplay = getSampleDisplayById(recordId);
        // 是否展示store details标签里面的submit按钮
        result.put('showSubmit', submitButtonShow(recordId));
        result.put('sampleDisplay', sampleDisplay);
        result.put('productModel', sampleDisplay.Product_Model__r.Name);
        result.put('customerName', sampleDisplay.Customer__r.Name);
        result.put('customerId', sampleDisplay.Customer__c);
        return result;
    }

    /**
     * @Param: base64Data：上传的图片
     * @Return:
     * @Author: WFC
     * @Date: 2024-10-25 09:35:50
     * @Description: 保存PO任务
     */
    @AuraEnabled
    public static Map<String, Object> saveCustomerDetail(String recordId, String productModel, String customerId, String numberData, String addressData, String fileName, String base64Data){
        Map<String, Object> result = new Map<String, Object>();
        try{
            // 创建 ContentVersion 实例
            ContentVersion contentVersion = new ContentVersion();
            contentVersion.Title = fileName;
            contentVersion.PathOnClient = fileName;
            contentVersion.VersionData = EncodingUtil.base64Decode(base64Data); // 解码 Base64 数据
            // 插入 ContentVersion
            insert contentVersion;

            ContentVersion cv = [SELECT Id, ContentBodyId, FileType, ContentDocumentId
                                 FROM ContentVersion
                                 WHERE Id = :contentVersion.Id
                                 LIMIT 1];

            PO__c sdcc = new PO__c();
            sdcc.Sample_Display__c = recordId;
            sdcc.Customer__c = customerId;
            sdcc.Product_Model__c = productModel;
            sdcc.Number__c = Decimal.valueOf(numberData);
            sdcc.Category_of_Delivery_Address__c = addressData;
            sdcc.CoverImgContentBodyId__c = cv.ContentBodyId;
            sdcc.CoverImgFileType__c = cv.FileType;
            sdcc.CoverImgVersionId__c = cv.Id;
            insert sdcc;

            //关联文件
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = cv.ContentDocumentId;
            cdl.LinkedEntityId = sdcc.Id;
            cdl.ShareType = 'V';
            insert cdl;
            result.put('isSuccess', true);
        } catch (Exception e){
            String errorMsg = e.getMessage().substring(e.getMessage().indexOf(',', e.getMessage().indexOf('first error:') + 12) + 1, e.getMessage().lastIndexOf(': ['));
            result.put('isSuccess', false);
            result.put('errorMsg', errorMsg);
        }
        return result;
    }

    /**
     * @Param:
     * @Return:
     * @Author: WFC
     * @Date: 2024-10-25 09:38:24
     * @Description: 保存store details
     */
    @AuraEnabled
    public static Map<String, Object> saveStoreDetail(String recordId, String productModel, String storeId, String numberData, Boolean priorityData){
        Map<String, Object> result = new Map<String, Object>();
        try{
            Store_Detail__c sdc = new Store_Detail__c();
            sdc.Sample_Display__c = recordId;
            sdc.Product_Model__c = productModel;
            sdc.Number__c = Decimal.valueOf(numberData);
            sdc.Store__c = storeId;
            sdc.Priority__c = priorityData;
            insert sdc;
            result.put('isSuccess', true);
        } catch (Exception e){
            String errorMsg = e.getMessage().substring(e.getMessage().indexOf(',', e.getMessage().indexOf('first error:') + 12) + 1, e.getMessage().lastIndexOf(': ['));
            result.put('isSuccess', false);
            result.put('errorMsg', errorMsg);
        }
        return result;
    }

    /**
     * @Param:
     * @Return:
     * @Author: WFC
     * @Date: 2024-12-16 13:43:49
     * @Description: 验证store details拆分是否与任务数量相等
     */
    @AuraEnabled
    public static Map<String, Object> verifyStoreDetailsNumber(String recordId){
        Map<String, Object> result = new Map<String, Object>();
        // 查询拆分的store details
        Sample_Display__c sampleDisplay = getSampleDisplayById(recordId);

        if (submitButtonShow(recordId)){
            result.put('showSubmit', true);
            if (sampleDisplay.Number__c != sampleDisplay.Sum_Store_Details_Number__c){
                result.put('isSuccess', false);
                result.put('msg', System.label.Store_Details_Number_Verify);
            } else{
                result.put('isSuccess', true);
            }
        } else{
            result.put('isSuccess', false);
            result.put('showSubmit', false);
            result.put('msg', 'Button is invalid.');
        }
        return result;
    }

    /**
     * @Param: SampleDisplay Id
     * @Return:
     * @Author: WFC
     * @Date: 2024-12-16 17:07:10
     * @Description: 查询sample display下SAP相关信息
     */
    @AuraEnabled
    public static Map<String, Object> searchSampleDisplaySAP(String recordId){
        Map<String, Object> result = new Map<String, Object>();
        // 父级Sample_Display__c信息
        List<SAP__c> sapList = [SELECT Id, SO__c, SAP_Number__c, City__c, Postal_Code__c, Region__c, Sales_Group__c, Sales_Office__c, Storage_Location__c, Storage_Location_Description__c, Street__c, ZD_Customer__c, ZD_Name__c
                                FROM SAP__c
                                WHERE Sample_Display__c = :recordId];
        if (sapList != null && sapList.size() > 0){
            result.put('sapData', sapList[0]);
            result.put('isHaveData', true);
        } else{
            result.put('sapData', null);
            result.put('isHaveData', false);
        }

        return result;
    }

    /**
     * @Param:
     * @Return:
     * @Author: WFC
     * @Date: 2024-12-18 14:55:11
     * @Description: store details 提交按钮
     */
    @AuraEnabled
    public static Map<String, Object> storeDetailsSubmit(String recordId){
        Map<String, Object> result = new Map<String, Object>();
        // 查询现在的流程信息
        List<ProcessInstanceWorkitem> piwList = [SELECT Id, CreatedDate, ActorId, ProcessInstanceId, ProcessInstance.TargetObject.name, ProcessInstance.TargetObjectId
                                                 FROM ProcessInstanceWorkitem
                                                 WHERE ProcessInstance.TargetObjectId = :recordId
                                                 ORDER BY CreatedDate DESC];
        if (piwList != null && piwList.size() > 0){
            ProcessInstanceWorkitem piw = piwList[0];
            // 启动流程
            Approval.ProcessWorkitemRequest pwr = new Approval.ProcessWorkitemRequest();
            pwr.setAction('Approve');
            pwr.setWorkitemId(piw.id);
            pwr.setComments('Approving request.');
            Approval.ProcessResult processResult = Approval.process(pwr);
            if (processResult.isSuccess()){
                result.put('isSuccess', true);
            } else{
                result.put('isSuccess', false);
            }
        } else{
            result.put('isSuccess', false);
        }

        // 是否展示store details标签里面的submit按钮
        result.put('showSubmit', submitButtonShow(recordId));

        return result;
    }

    /**
     * @Param:
     * @Return:
     * @Author: WFC
     * @Date: 2024-12-18 16:40:23
     * @Description: 是否显示store details模块里面的submit
     */
    public static Boolean submitButtonShow(String recordId){
        // 查询流程表信息
        List<ProcessInstanceWorkitem> piwList = [SELECT Id, ActorId
                                                 FROM ProcessInstanceWorkitem
                                                 WHERE ProcessInstance.TargetObjectId = :recordId
                                                 ORDER BY CreatedDate DESC];
        if (piwList != null && piwList.size() > 0){
            ProcessInstanceWorkitem piw = piwList[0];
            if (piw.ActorId == UserInfo.getUserId()){
                return true;
            }
        }
        return false;
    }

    /**
     * @Param: recordId
     * @Return: Sample_Display__c
     * @Author: WFC
     * @Date: 2025-01-08 14:16:16
     * @Description: 获取Sample_Display__c信息
     */
    public static Sample_Display__c getSampleDisplayById(String recordId){
        return [SELECT Id, Product_Model__c, Product_Model__r.Name, Task_Level__c, Customer__c, Customer__r.Name, Approval_Status__c, Path__c, Number__c, Sum_Store_Details_Number__c 
                FROM Sample_Display__c
                WHERE Id = :recordId
                LIMIT 1];
    }

}