force-app/main/default/objects/Account/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>黑电海信</fullName>
            </value>
            <value>
                <fullName>黑电东芝</fullName>
            </value>
            <value>
                <fullName>冰冷</fullName>
            </value>
            <value>
                <fullName>洗衣机小厨电</fullName>
            </value>
            <value>
                <fullName>空调</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/CheckItem__c.object-meta.xml
<CustomObject>
    <label>Check Item</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Check Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CheckItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/HasFile__c.field-meta.xml
<CustomField>
    <fullName>HasFile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HasFile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/MaximumScore__c.field-meta.xml
<CustomField>
    <fullName>MaximumScore__c</fullName>
    <defaultValue>TEXT(5)</defaultValue>
    <label>Maximum Score</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <label>Order Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>Booth and image</fullName>
            </value>
            <value>
                <fullName>Prototype</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>new</fullName>
                <isActive>false</isActive>
                <label>new</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/recordTypes/Chile.recordType-meta.xml
<RecordType>
    <fullName>Chile</fullName>
    <active>true</active>
    <label>Chile</label>
</RecordType>

force-app/main/default/objects/CheckResult__c/CheckResult__c.object-meta.xml
<CustomObject>
    <label>Check Result</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Check Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CheckResult__c/fields/CheckItem__c.field-meta.xml
<CustomField>
    <fullName>CheckItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check Item</label>
    <referenceTo>CheckItem__c</referenceTo>
    <relationshipLabel>Check Results</relationshipLabel>
    <relationshipName>Check_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CheckResult__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CheckResult__c/fields/InspectorDailyReport__c.field-meta.xml
<CustomField>
    <fullName>InspectorDailyReport__c</fullName>
    <label>InspectorDailyReport</label>
    <referenceTo>Daily_Inspection_Report__c</referenceTo>
    <relationshipLabel>Check Results</relationshipLabel>
    <relationshipName>Check_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CheckResult__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <formula>InspectorDailyReport__r.Report_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CheckResult__c/fields/Scores__c.field-meta.xml
<CustomField>
    <fullName>Scores__c</fullName>
    <label>Scores</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/Daily_Inspection_Report__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>DIR-{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>巡店员日报编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Inspection_Shop_Plan__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Shop_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店计划</label>
    <referenceTo>Inspection_Shop_Plan__c</referenceTo>
    <relationshipName>Daily_Inspection_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/NeedCheckIn__c.field-meta.xml
<CustomField>
    <fullName>NeedCheckIn__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Need Check In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <description>巡店日期</description>
    <label>报告日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>巡店报告状态，包括New和Submitted两种</description>
    <inlineHelpText>Status of inspection report, including new and submitted</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>门店ID（关联门店表）</description>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>DailyInspectionReports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/Inspection_Shop_Plan__c.object-meta.xml
<CustomObject>
    <label>Inspection Plan</label>
    <nameField>
        <displayFormat>ISP-{YYYY}{MM}{0000}</displayFormat>
        <label>计划编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Inspection_Month__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Month__c</fullName>
    <defaultValue>TEXT(MONTH( TODAY() ))</defaultValue>
    <label>计划月份</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Inspection_Year__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Year__c</fullName>
    <defaultValue>TEXT(YEAR( TODAY() ) )</defaultValue>
    <label>计划年份</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shop_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Shop_Level__c.field-meta.xml
<CustomField>
    <fullName>Shop_Level__c</fullName>
    <description>门店等级，分为S/A/B/C</description>
    <label>门店等级</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ShopLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>In Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ShopLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>PB</fullName>
    </customValue>
    <customValue>
        <fullName>SP</fullName>
    </customValue>
    <customValue>
        <fullName>W</fullName>
    </customValue>
    <customValue>
        <fullName>アンケート</fullName>
    </customValue>
    <customValue>
        <fullName>サンエー</fullName>
    </customValue>
    <customValue>
        <fullName>本部指定</fullName>
    </customValue>
    <customValue>
        <fullName>専売機</fullName>
    </customValue>
    <customValue>
        <fullName>拡販</fullName>
    </customValue>
    <customValue>
        <fullName>T01</fullName>
    </customValue>
    <customValue>
        <fullName>T02</fullName>
    </customValue>
    <customValue>
        <fullName>T03</fullName>
    </customValue>
    <customValue>
        <fullName>T04</fullName>
    </customValue>
    <customValue>
        <fullName>T05</fullName>
    </customValue>
    <customValue>
        <fullName>T06</fullName>
    </customValue>
    <customValue>
        <fullName>T07</fullName>
    </customValue>
    <customValue>
        <fullName>T08</fullName>
    </customValue>
    <customValue>
        <fullName>T09</fullName>
    </customValue>
    <customValue>
        <fullName>T10</fullName>
    </customValue>
    <customValue>
        <fullName>未知</fullName>
    </customValue>
    <customValue>
        <fullName>店格不明</fullName>
    </customValue>
    <customValue>
        <fullName>T61</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種BIC</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種KS</fullName>
    </customValue>
    <masterLabel>门店等级</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DailyInspectionReportTriggerTest.cls
@isTest
public class DailyInspectionReportTriggerTest {
	@isTest
    static void testMethod1(){
        String profileName = '促销员'; 
        Id profileId = [SELECT Id FROM profile WHERE Name = :profileName][0].Id; 
        User user1 = new User(alias = '促销员', email='TestC43423@noemail.com',
        emailencodingkey='UTF-8', lastname='TestC43423', languagelocalekey='en_US',
        localesidkey='en_US',profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='TestC43423@noemail.com');
        INSERT user1;
        
        Account acc = new Account();
        acc.Name = 'ceshis';
        insert acc;
        
        Shop__c shop4 = new Shop__c();
        shop4.Account__c = acc.Id;
        shop4.Shop_Level__c = 'A';
        shop4.Name = '测试店444';
        INSERT shop4;
        
        Inspection_Shop_Plan__c ispTest = new Inspection_Shop_Plan__c();
        ispTest.OwnerId = user1.id;
        ispTest.Status__c = 'New';
        ispTest.Inspection_Year__c = Date.today().year() + '';
        ispTest.Inspection_Month__c = Date.today().month() + '';
        INSERT ispTest;
        
		Daily_Inspection_Report__c testDIR6 = new Daily_Inspection_Report__c();
        testDIR6.Report_Date__c = System.today();
        testDIR6.Inspection_Shop_Plan__c = ispTest.id;
        testDIR6.Store__c = shop4.id;
        testDIR6.OwnerId = UserInfo.getUserId();
        testDIR6.Status__c = 'New';
        testDIR6.NeedCheckIn__c = true;
        Insert testDIR6;
        
        CheckItem__c testCI = new CheckItem__c();
		testCI.Description__c = 'old';
		testCI.Active__c = true;
        testCI.BussinessArea__c = 'Chile';
        testCI.MaximumScore__c = '5';
        //testCI.Product_Line__c = 'TV';
        testCI.Project__c = 'Booth and image';
        testCI.HasFile__c = false;
        testCI.RecordTypeId = Schema.SObjectType.CheckItem__c.getRecordTypeInfosByName().get('Chile').getRecordTypeId();
        testCI.OrderNumber__c = 10;
        Insert testCI;
        
        //test DailyInspectionReportTriggerHandHelper
        CheckResult__c testCR3 = new CheckResult__c();
		testCR3.CheckItem__c = testCI.Id;
        testCR3.Scores__c = 2;
        testCR3.Comments__c = '测试CR用';
        testCR3.Status__c = 'Draft';
        testCR3.InspectorDailyReport__c = testDIR6.id;
        Insert testCR3;
        
        Test.startTest();
        testDIR6.Status__c = 'Submitted';
        update testDIR6;
		Test.stopTest();
    }
}