force-app/main/default/objects/Account/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Industry Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>&gt;20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/Customer_Product_Line__c.object-meta.xml
<CustomObject>
    <label>Customer Product Line</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product_Line__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency Customer</fullName>
            </value>
            <value>
                <fullName>OEM Customer</fullName>
            </value>
            <value>
                <fullName>Customer of Oversea Company</fullName>
            </value>
            <value>
                <fullName>Agency + OEM Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Strategy Customer</fullName>
            </value>
            <value>
                <fullName>Quality Customer</fullName>
            </value>
            <value>
                <fullName>Normal Customer</fullName>
            </value>
            <value>
                <fullName>Eliminated Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Rank_Of_Last_Year__c.field-meta.xml
<CustomField>
    <fullName>Rank_Of_Last_Year__c</fullName>
    <label>Rank of Last Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Rank_Of_The_Year_Before_Last__c.field-meta.xml
<CustomField>
    <fullName>Rank_Of_The_Year_Before_Last__c</fullName>
    <label>Rank of the Year before Last</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Sales_member01__c.field-meta.xml
<CustomField>
    <fullName>Sales_member01__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales member01</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Product_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerProLineSalesChangeControllerTest.cls
@isTest
private class CustomerProLineSalesChangeControllerTest {
    
    static testMethod void testMethod1() {
        Test.startTest();

        List<User> userList = TestDataUtility.createUserList(true);
        System.runAs(userList[0]){
            User newUser = new User();
            newUser = userList[1];
            newUser.Username = 'sdcostteam001@hisense.com';
            newUser.Id = null;
            newUser.UserRoleId = [SELECT Id FROM UserRole WHERE DeveloperName =:Label.Role_Name_Sales_CE_Cost LIMIT 1].Id;
            insert newUser;

            User newUser2 = new User();
            newUser2.Alias = 'test';
            newUser2.Email = 'test@hisensetest.com';
            newUser2.EmailEncodingKey = 'UTF-8';
            newUser2.Username = 'sdcostteam002@hisense.com';
            newUser2.LastName='sales representative'; 
            newUser2.LanguageLocaleKey='en_US';
            newUser2.LocaleSidKey='en_US';
            newUser2.ProfileId = newUser.ProfileId; 
            newUser2.TimeZoneSidKey='Asia/Kuala_Lumpur';
            newUser2.Id = null;
            newUser2.UserRoleId = [SELECT Id FROM UserRole WHERE DeveloperName =:Label.Role_Name_Sales_CE_Cost LIMIT 1].Id;
            insert newUser2;
    
            List<Account> accList = TestDataUtility.createAccountList(true);
            Customer_Product_Line__c cpl = new Customer_Product_Line__c();
            cpl.Customer__c = accList[0].Id;
            cpl.Rank_Of_The_Year_Before_Last__c = 'Normal Customer';
            cpl.Rank_Of_Last_Year__c = 'Quality Customer';
            cpl.Rank__c = 'Strategy Customer';
            cpl.Classification__c = 'Customer of Oversea Company';
            cpl.Sales_member01__c = newUser.Id;
            insert cpl;
            CustomerProLineSalesChangeController.changeTwoSales('', '');
            CustomerProLineSalesChangeController.changeTwoSales(newUser2.Id, newUser.Id);
            String s1 = newUser.Id;
            String s2 = newUser2.Id;
            CustomerProLineSalesChangeController.changeTwoSales(s1.substring(0,15), s2.substring(0,15));
    	}
        Test.stopTest();
    }
}