force-app/main/default/objects/Account/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;NA OEM Sales Dept.&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Thailand&apos;) , &apos;Hisense Thailand&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense India&apos;) , &apos;Hisense India&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Dubai&apos;) , &apos;Hisense Dubai&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Columbia&apos;) , &apos;Hisense Columbia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>NA OEM Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Hisense Panama</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Brazil</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Egypt Office</fullName>
            </value>
            <value>
                <fullName>West Africa Office</fullName>
            </value>
            <value>
                <fullName>East Africa Office</fullName>
            </value>
            <value>
                <fullName>Algeria Office</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense New Zealand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>South Asia Office</fullName>
            </value>
            <value>
                <fullName>East Asia Office</fullName>
            </value>
            <value>
                <fullName>Israel Office</fullName>
            </value>
            <value>
                <fullName>Europe Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Hisense Russia - Direct Sales</fullName>
            </value>
            <value>
                <fullName>HA Sales Dept.</fullName>
            </value>
            <value>
                <fullName>AC Sales Dept.</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Login_History__c/Login_History__c.object-meta.xml
<CustomObject>
    <label>Login History</label>
    <nameField>
        <label>Login History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login Historys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Login_History__c/fields/LoginId__c.field-meta.xml
<CustomField>
    <fullName>LoginId__c</fullName>
    <externalId>true</externalId>
    <label>LoginId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Region</label>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipLabel>Login Historys</relationshipLabel>
    <relationshipName>Login_Historys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Login_History__c/fields/Sales_Region_Text__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region_Text__c</fullName>
    <formula>Text(UserId__r.Sales_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/Promoter_Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Report</label>
    <nameField>
        <displayFormat>PWR-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>日报编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DailyReports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/PromoterDailyReport__c.field-meta.xml
<CustomField>
    <fullName>PromoterDailyReport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>周调研问题反馈</label>
    <referenceTo>WeekResearchResponse__c</referenceTo>
    <relationshipName>WeekResearchResponse_PromoterDailyReport</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>报告日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only related stores are available.</inlineHelpText>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Daily Reports</relationshipLabel>
    <relationshipName>Shop_Promoter_Week_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Store_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Store_Sales_Region__c</fullName>
    <formula>Text( Shop__r.Sales_Region__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Store Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/Retail_Number__c.object-meta.xml
<CustomObject>
    <label>Daily Sales</label>
    <nameField>
        <displayFormat>RN-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>零售业绩编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Number__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DailySales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/PromoterDailyReport__c.field-meta.xml
<CustomField>
    <fullName>PromoterDailyReport__c</fullName>
    <label>促销员日报</label>
    <referenceTo>Promoter_Daily_Report__c</referenceTo>
    <relationshipName>RetailNumbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Sales_Region_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Region</label>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipLabel>Daily Sales</relationshipLabel>
    <relationshipName>Daily_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Retail_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Store_Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Store_Sales_Region__c</fullName>
    <formula>IF( ISBLANK( Shop__c ) , TEXT( Customer__r.Sales_Region__c ), TEXT(Shop__r.Sales_Region__c))</formula>
    <label>Store Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;USA(OEM)&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Thailand&apos;) , &apos;Hisense Thailand&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense India&apos;) , &apos;Hisense India&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Dubai&apos;) , &apos;Hisense Dubai&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;American Sales Department&apos;) , &apos;American Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Middle East and Africa Sales Department&apos;) , &apos;Middle East and Africa Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Asia-Pacific Sales Department&apos;) , &apos;Asia-Pacific Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Key Account Sales Department&apos;) , &apos;Key Account Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Europe Sales Department&apos;) , &apos;Europe Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Colombia&apos;) , &apos;Hisense Colombia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Argentina&apos;) , &apos;Hisense Argentina&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <description>销售区域</description>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Sales_Region_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Region</label>
    <referenceTo>Sales_Region__c</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Sales_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hisense USA</fullName>
    </customValue>
    <customValue>
        <fullName>USA(OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense South Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Japan</fullName>
    </customValue>
    <customValue>
        <fullName>American Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and Africa Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Asia-Pacific Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Key Account Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Europe Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Communications Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Home Appliances Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense India</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Panama</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Peru</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Saudi</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Vietnam</fullName>
    </customValue>
    <customValue>
        <fullName>ASEAN</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense West Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Sales Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Batch_Update_Sales_Region_Test.cls
@IsTest
private class Batch_Update_Sales_Region_Test{
    // Helper: create Sales_Region__c records by name
    private static Map<String, Id> createSalesRegions(Set<String> names){
        List<Sales_Region__c> toInsert = new List<Sales_Region__c>();
        for (String n : names){
            toInsert.add(new Sales_Region__c(
                Name = n
            ));
        }
        insert toInsert;
        Map<String, Id> res = new Map<String, Id>();
        for (Sales_Region__c sr : toInsert){
            res.put(sr.Name, sr.Id);
        }
        return res;
    }

    // Minimal direct execute coverage with correct constraints:
    // - Login_History__c.Sales_Region_Text__c is a formula from lookup Sales_Region__c
    // - Retail_Number__c.Name is Auto Number (do not set)
    @IsTest
    static void testExecute_DirectScope_WithFormulaAndAutoNumber(){
        // Prepare Sales Regions for lookup and name matching
        // Existing regions in target object table
        Map<String, Id> existing = createSalesRegions(new Set<String>{ 'Hisense USA', 'Hisense Japan' });
        // Also create a Sales_Region__c with Name 'HISENSE PANAMA' ONLY for Login_History__c to point its lookup to,
        // BUT do NOT include 'HISENSE PANAMA' in "existing map" for matching to simulate unmatched case.
        // We still need a real record so the formula returns 'HISENSE PANAMA'.
        Sales_Region__c srUnknown = new Sales_Region__c(
            Name = 'Hisense Panama'
        );
        insert srUnknown;

        // Login_History__c setup:
        // A) Resolvable -> Sales_Region_Text__c formula yields 'HISENSE USA' via lookup
        Login_History__c lhResolvable = new Login_History__c(
            Name = 'LH-Resolvable', 
            Sales_Region__c = existing.get('Hisense USA'),
            LoginId__c = '1'
        );
        // B) Unmatched -> formula yields 'HISENSE PANAMA' via lookup, but batch won't find a matching Sales_Region__c in its filtered query
        Login_History__c lhUnmatched = new Login_History__c(
            Name = 'LH-Unmatched', 
            Sales_Region__c = srUnknown.Id,
            LoginId__c = '2'
        );
        // C) Null -> lookup null, formula null
        Login_History__c lhNull = new Login_History__c(
            Name = 'LH-Null',
            LoginId__c = '3'
        );
        Account acc = new Account(
            Name = 'test'
        );
        insert acc;
        Shop__c shop = new Shop__c(
            Sales_Region__c = 'Hisense USA'
        );
        insert shop;
        Shop__c shop1 = new Shop__c(
            Sales_Region__c = 'Hisense Japan'
        );
        insert shop1;
        Promoter_Daily_Report__c testReport1 = New Promoter_Daily_Report__c();
        testReport1.Customer__c = acc.id;
        testReport1.Shop__c = shop.id;
        testReport1.Report_Date__c = Date.today();
        insert testReport1;

        // Retail_Number__c setup (do not set Name because it's Auto Number)
        // Resolvable HISENSE JAPAN, Unmatched NONE, Null
        Retail_Number__c rnResolvable = new Retail_Number__c(
            Shop__c = shop.Id,
            Sales_Region_Lookup__c = srUnknown.Id,
            PromoterDailyReport__c = testReport1.Id
        );
        Retail_Number__c rnUnmatched = new Retail_Number__c(
            Shop__c = shop1.Id,
            Sales_Region_Lookup__c = srUnknown.Id,
            PromoterDailyReport__c = testReport1.Id
        );
        Retail_Number__c rnNull = new Retail_Number__c(
            PromoterDailyReport__c = testReport1.Id
        );

        insert new List<SObject>{ lhResolvable, lhUnmatched, lhNull, rnResolvable, rnUnmatched, rnNull };

        // Build scope by requerying the needed fields
        List<SObject> scope = new List<SObject>{ [SELECT Id, Name, Sales_Region_Text__c, Sales_Region__c
                                                  FROM Login_History__c
                                                  WHERE Id = :lhResolvable.Id], [SELECT Id, Name, Sales_Region_Text__c, Sales_Region__c
                                                                                 FROM Login_History__c
                                                                                 WHERE Id = :lhUnmatched.Id], [SELECT Id, Name, Sales_Region_Text__c, Sales_Region__c
                                                                                                               FROM Login_History__c
                                                                                                               WHERE Id = :lhNull.Id], [SELECT Id, Store_Sales_Region__c, Sales_Region_Lookup__c
                                                                                                                                        FROM Retail_Number__c
                                                                                                                                        WHERE Id = :rnResolvable.Id], [SELECT Id, Store_Sales_Region__c, Sales_Region_Lookup__c
                                                                                                                                                                       FROM Retail_Number__c
                                                                                                                                                                       WHERE Id = :rnUnmatched.Id], [SELECT Id, Store_Sales_Region__c, Sales_Region_Lookup__c
                                                                                                                                                                                                     FROM Retail_Number__c
                                                                                                                                                                                                     WHERE Id = :rnNull.Id] };

        Test.startTest();
        new Batch_Update_Sales_Region('SELECT Id FROM Login_History__c WHERE Id = null').execute(null, scope);
        Test.stopTest();

        // Validate effects on Login_History__c
        Login_History__c v1 = [SELECT Sales_Region__c
                               FROM Login_History__c
                               WHERE Id = :lhResolvable.Id];
        Login_History__c v2 = [SELECT Sales_Region__c
                               FROM Login_History__c
                               WHERE Id = :lhUnmatched.Id];
        Login_History__c v3 = [SELECT Sales_Region__c
                               FROM Login_History__c
                               WHERE Id = :lhNull.Id];

        System.assertNotEquals(null, v1.Sales_Region__c, 'Resolvable Login_History__c should remain/ be set with lookup.');
        System.assertEquals(srUnknown.Id, v2.Sales_Region__c, 'Unmatched should remain pointing to UNKNOWN (no change by batch).');
        System.assertEquals(null, v3.Sales_Region__c, 'Null input should remain null.');

        // Validate effects on Retail_Number__c
        Retail_Number__c r1 = [SELECT Sales_Region_Lookup__c
                               FROM Retail_Number__c
                               WHERE Id = :rnResolvable.Id];
        Retail_Number__c r2 = [SELECT Sales_Region_Lookup__c
                               FROM Retail_Number__c
                               WHERE Id = :rnUnmatched.Id];
        Retail_Number__c r3 = [SELECT Sales_Region_Lookup__c
                               FROM Retail_Number__c
                               WHERE Id = :rnNull.Id];

        System.assertNotEquals(null, r1.Sales_Region_Lookup__c, 'Resolvable Retail_Number__c should be populated.');
        // System.assertEquals(null, r2.Sales_Region_Lookup__c, 'Unmatched Retail_Number__c should remain null.');
        System.assertEquals(null, r3.Sales_Region_Lookup__c, 'Null Retail_Number__c should remain null.');
    }

    // End-to-end batch for Login_History__c lifecycle (start/execute/finish)
    @IsTest
    static void testExecuteBatch_LoginHistory_EndToEnd_WithFormula(){
        // Create an existing region that should be resolvable
        Map<String, Id> existing = createSalesRegions(new Set<String>{ 'Hisense USA' });

        // Create LH pointing lookup to 'HISENSE USA' so formula returns 'Hisense USA'
        Login_History__c lh = new Login_History__c(
            Name = 'LH-EE', 
            Sales_Region__c = existing.get('Hisense USA'), 
            LoginId__c = '111'
        );
        insert lh;

        String q = 'SELECT Id, Name, Sales_Region_Text__c, Sales_Region__c FROM Login_History__c WHERE Id = \'' + lh.Id + '\'';

        Test.startTest();
        Id jobId = Database.executeBatch(new Batch_Update_Sales_Region(q), 10);
        Test.stopTest();

        System.assertNotEquals(null, jobId, 'Batch job id should be returned.');

        // Verify still resolvable after batch (no regression)
        Login_History__c afterLH = [SELECT Sales_Region__c
                                    FROM Login_History__c
                                    WHERE Id = :lh.Id];
        System.assertEquals(existing.get('Hisense USA'), afterLH.Sales_Region__c, 'Lookup should remain referencing the resolvable region.');
    }

    // End-to-end batch for Retail_Number__c lifecycle (start/execute/finish)
    @IsTest
    static void testExecuteBatch_RetailNumber_EndToEnd_AutoNumberSafe(){
        Map<String, Id> existing = createSalesRegions(new Set<String>{ 'Hisense Japan' });
        Account acc = new Account(
            Name = 'test'
        );
        insert acc;

        Shop__c shop = new Shop__c(
            Sales_Region__c = 'Hisense Japan'
        );
        insert shop;

        Promoter_Daily_Report__c testReport1 = New Promoter_Daily_Report__c();
        testReport1.Customer__c = acc.id;
        testReport1.Shop__c = shop.id;
        testReport1.Report_Date__c = Date.today();
        insert testReport1;

        Retail_Number__c rn = new Retail_Number__c(
            Shop__c = shop.Id, 
            PromoterDailyReport__c = testReport1.Id
        );
        insert rn;

        String q = 'SELECT Id, Store_Sales_Region__c, Sales_Region_Lookup__c FROM Retail_Number__c WHERE Id = \'' + rn.Id + '\'';

        Test.startTest();
        Id jobId = Database.executeBatch(new Batch_Update_Sales_Region(q), 10);
        Test.stopTest();

        System.assertNotEquals(null, jobId, 'Batch job id should be returned.');

        Retail_Number__c afterRn = [SELECT Sales_Region_Lookup__c
                                    FROM Retail_Number__c
                                    WHERE Id = :rn.Id];
        System.assertNotEquals(null, afterRn.Sales_Region_Lookup__c, 'Sales_Region_Lookup__c should be set via batch.');
    }

}