force-app/main/default/objects/Account/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gridding__c/Gridding__c.object-meta.xml
<CustomObject>
    <label>Gridding</label>
    <nameField>
        <label>网格名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Griddings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Gridding__c/fields/Gridding_Code__c.field-meta.xml
<CustomField>
    <fullName>Gridding_Code__c</fullName>
    <externalId>true</externalId>
    <label>网格编码</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gridding__c/fields/Gridding_Level__c.field-meta.xml
<CustomField>
    <fullName>Gridding_Level__c</fullName>
    <label>网格等级</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gridding__c/fields/Parent_Gridding__c.field-meta.xml
<CustomField>
    <fullName>Parent_Gridding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>上级网格</label>
    <referenceTo>Gridding__c</referenceTo>
    <relationshipLabel>网格</relationshipLabel>
    <relationshipName>Parent_Gridding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>产品等级</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/recordTypes/ALL_Product_Japan.recordType-meta.xml
<RecordType>
    <fullName>ALL_Product_Japan</fullName>
    <active>true</active>
    <label>ALL Product RecordType - Japan</label>
</RecordType>

force-app/main/default/objects/Sampling_Detail__c/Sampling_Detail__c.object-meta.xml
<CustomObject>
    <label>Sampling Detail</label>
    <nameField>
        <displayFormat>SD{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>出样明细编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sampling Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>产品</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND (5 OR 6)) OR 7</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ALL_Product_Japan</value>
        </filterItems>
        <filterItems>
            <field>$User.Country</field>
            <operation>notEqual</operation>
            <value>South Africa, Indonesia, Chile, Thailand, Vietnam,Malaysia,Argentina,West Africa,Saudi,Canada,Colombia,Philippines,Peru,USA,Mexico</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>notEqual</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile, Hisense Thailand, Hisense Vietnam,Hisense Malaysia,Hisense Colombia,Hisense Argentina,Hisense West Africa,Hisense Saudi,Hisense Canada,Hisense Philippines,Hisense Peru,Hisense USA,Hisense Mexico</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RegionalProduct</value>
        </filterItems>
        <filterItems>
            <field>$User.Country</field>
            <operation>equals</operation>
            <value>South Africa, Indonesia, Chile, Thailand, Vietnam,Malaysia,Argentina,West Africa,Saudi,Canada,Colombia,Philippines,Peru,USA,Mexico</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <valueField>Product__c.sales_region__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.ManageUsers</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sampling Detail</relationshipLabel>
    <relationshipName>Sampling_Detail_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Detail__c/fields/Sampling_Standard__c.field-meta.xml
<CustomField>
    <fullName>Sampling_Standard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>出样标准</label>
    <referenceTo>Sampling_Standard__c</referenceTo>
    <relationshipLabel>出样明细</relationshipLabel>
    <relationshipName>Sampling_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Detail__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>出样明细</relationshipLabel>
    <relationshipName>Sampling_Detail_Shop</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Detail__c/fields/Shop_Level__c.field-meta.xml
<CustomField>
    <fullName>Shop_Level__c</fullName>
    <description>门店等级</description>
    <formula>TEXT( Shop__r.Shop_Level__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>门店等级</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sampling_Mapping__c/Sampling_Mapping__c.object-meta.xml
<CustomObject>
    <label>Sampling Mapping</label>
    <nameField>
        <displayFormat>M{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>出样等级映射表编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sampling Mapping</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>M002M</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Mapping__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <inlineHelpText>每个定番等级在每个客户中仅允许存在一条出样等级映射</inlineHelpText>
    <label>出样等级</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sampling_Mapping__c/fields/Shop_Level__c.field-meta.xml
<CustomField>
    <fullName>Shop_Level__c</fullName>
    <label>门店等级</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ShopLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sampling_Standard__c/Sampling_Standard__c.object-meta.xml
<CustomObject>
    <label>Sampling Standard</label>
    <nameField>
        <displayFormat>SS-{YYYY}{MM}{0000}</displayFormat>
        <label>出样标准编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sampling Standard</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Standard__c/fields/Channel_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sampling_Standard_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Standard__c/fields/Is_Add_ByReport__c.field-meta.xml
<CustomField>
    <fullName>Is_Add_ByReport__c</fullName>
    <defaultValue>false</defaultValue>
    <label>巡店日报新建的出样标准</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sampling_Standard__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>出样等级</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sampling_Standard__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>每个出样产品在每个客户中仅允许存在一条出样标准记录</inlineHelpText>
    <label>产品</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND (5 OR 6)) OR 7</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ALL_Product_Japan</value>
        </filterItems>
        <filterItems>
            <field>$User.Country</field>
            <operation>notEqual</operation>
            <value>South Africa, Indonesia, Chile, Thailand, Vietnam,Malaysia,Argentina,West Africa,Saudi,Canada,Colombia,Philippines,Peru,USA,Mexico</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>notEqual</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile, Hisense Thailand, Hisense Vietnam,Hisense Malaysia,Hisense Colombia,Hisense Argentina,Hisense West Africa,Hisense Saudi,Hisense Canada,Hisense Philippines,Hisense Peru,Hisense USA,Hisense Mexico</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RegionalProduct</value>
        </filterItems>
        <filterItems>
            <field>$User.Country__c</field>
            <operation>equals</operation>
            <value>South Africa, Indonesia, Chile, Thailand, Vietnam,Malaysia,Argentina,West Africa,Saudi,Canada,Colombia,Philippines,Peru,USA,Mexico</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <valueField>Product__c.sales_region__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.ManageUsers</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sampling Standard</relationshipLabel>
    <relationshipName>Sampling_Standard_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Standard__c/fields/Sampling_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Sampling_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>出样等级映射表</label>
    <referenceTo>Sampling_Mapping__c</referenceTo>
    <relationshipName>Sampling_Standard_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Standard__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>出样状态</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
            </value>
            <value>
                <fullName>False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shop_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Channel_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Name__c</fullName>
    <formula>Channel_item__r.Name</formula>
    <label>Channel Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>城市</description>
    <label>城市</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>网格名称，指门店所属网格划分</description>
    <label>网格</label>
    <referenceTo>Gridding__c</referenceTo>
    <relationshipLabel>Stores (网格)</relationshipLabel>
    <relationshipName>ShopRLg9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Shop_Level__c.field-meta.xml
<CustomField>
    <fullName>Shop_Level__c</fullName>
    <description>门店等级，分为S/A/B/C</description>
    <label>门店等级</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ShopLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Store_No_from_Account__c.field-meta.xml
<CustomField>
    <fullName>Store_No_from_Account__c</fullName>
    <description>渠道给门店的编号</description>
    <inlineHelpText>Store ID created by customer</inlineHelpText>
    <label>门店渠道编号</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>PB</fullName>
    </customValue>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>SP</fullName>
    </customValue>
    <customValue>
        <fullName>T01</fullName>
    </customValue>
    <customValue>
        <fullName>T02</fullName>
    </customValue>
    <customValue>
        <fullName>T04</fullName>
    </customValue>
    <customValue>
        <fullName>T06</fullName>
    </customValue>
    <customValue>
        <fullName>T08</fullName>
    </customValue>
    <customValue>
        <fullName>T10</fullName>
    </customValue>
    <customValue>
        <fullName>W</fullName>
    </customValue>
    <customValue>
        <fullName>アンケート</fullName>
    </customValue>
    <customValue>
        <fullName>サンエー</fullName>
    </customValue>
    <customValue>
        <fullName>本部指定</fullName>
    </customValue>
    <customValue>
        <fullName>専売機</fullName>
    </customValue>
    <customValue>
        <fullName>拡販</fullName>
    </customValue>
    <customValue>
        <fullName>未知</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>店格不明</fullName>
    </customValue>
    <customValue>
        <fullName>T61</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種BIC</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種KS</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種EDION</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種JOSHIN</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種NOJIMA</fullName>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <isActive>false</isActive>
        <label>Y</label>
    </customValue>
    <masterLabel>定番等级</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ShopLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>PB</fullName>
    </customValue>
    <customValue>
        <fullName>SP</fullName>
    </customValue>
    <customValue>
        <fullName>W</fullName>
    </customValue>
    <customValue>
        <fullName>アンケート</fullName>
    </customValue>
    <customValue>
        <fullName>サンエー</fullName>
    </customValue>
    <customValue>
        <fullName>本部指定</fullName>
    </customValue>
    <customValue>
        <fullName>専売機</fullName>
    </customValue>
    <customValue>
        <fullName>拡販</fullName>
    </customValue>
    <customValue>
        <fullName>T01</fullName>
    </customValue>
    <customValue>
        <fullName>T02</fullName>
    </customValue>
    <customValue>
        <fullName>T03</fullName>
    </customValue>
    <customValue>
        <fullName>T04</fullName>
    </customValue>
    <customValue>
        <fullName>T05</fullName>
    </customValue>
    <customValue>
        <fullName>T06</fullName>
    </customValue>
    <customValue>
        <fullName>T07</fullName>
    </customValue>
    <customValue>
        <fullName>T08</fullName>
    </customValue>
    <customValue>
        <fullName>T09</fullName>
    </customValue>
    <customValue>
        <fullName>T10</fullName>
    </customValue>
    <customValue>
        <fullName>未知</fullName>
    </customValue>
    <customValue>
        <fullName>店格不明</fullName>
    </customValue>
    <customValue>
        <fullName>T61</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種BIC</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種KS</fullName>
    </customValue>
    <masterLabel>门店等级</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ShopTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : chenpeng@deloitte.com.cn
 * @group             : 
 * @last modified on  : 03-29-2022
 * @last modified by  : chenpeng@deloitte.com.cn
**/
@isTest
private class ShopTriggerHandlerTest {
    static testMethod void testHandler() {
        Account acc = new Account();
        acc.Name = 'KS';
        acc.SAP_Customer_Code__c = 'sapcode01';
		INSERT acc;
        Product__c pro = new Product__c();
        pro.Level__c = 'A';
        pro.RecordTypeId = Schema.getGlobalDescribe().get('Product__c').getDescribe().getRecordTypeInfosByDeveloperName().get('ALL_Product_Japan').getRecordTypeId();
        INSERT pro;
        Gridding__c gird1 = new Gridding__c();
        gird1.Name = 'test002';
        gird1.Gridding_Level__c = 'B';
        gird1.Gridding_Code__c  = 'J01-J001';
        INSERT gird1;
        Gridding__c gird2 = new Gridding__c();
        gird2.Name = 'test003';
        gird2.Gridding_Level__c = 'C';
        gird2.Gridding_Code__c  = 'J01-J001-J0001';
        gird2.Parent_Gridding__c = gird1.Id;
        INSERT gird2;
        Shop__c shop = new Shop__c();
        shop.Name = 'test001';
        shop.Account__c = acc.Id;
        shop.Shop_Level__c = 'A';
        shop.Grid__c = gird2.id;
        shop.Store_No_from_Account__c = '01';
        shop.City__c = '北京市';
        Shop__c shop2 = new Shop__c();
        shop2.Name = 'test002';
        shop2.Account__c = acc.Id;
        shop2.Shop_Level__c = 'A';
        shop2.Grid__c = gird2.id;
        shop2.Store_No_from_Account__c = '02';
        
        //Set<String> shopLevelSet2 = new Set<String>();
        ///shopLevelSet2.add(shop.Shop_Level__c);
        Sampling_Mapping__c sm = new Sampling_Mapping__c();
        sm.Account__c = shop.Account__c;
        sm.Shop_Level__c = 'A;B';
        sm.Level__c = 'A';
        //sm.Shop_Level__c = 'A';
        INSERT sm;
		Sampling_Standard__c ss = new Sampling_Standard__c();
        ss.Sampling_Mapping__c = sm.Id;
        ss.Channel_Name__c = acc.Id;
        ss.Status__c = 'True';
        ss.Is_Add_ByReport__c = true;
        ss.Is_Added__c = '是';
        ss.Level__c = 'A';
        ss.Product__c = pro.Id;
       
        INSERT ss; 
		Sampling_Detail__c sd = new Sampling_Detail__c();
		sd.Sampling_Standard__c = ss.Id;
        sd.Is_Add__c = '是';
        INSERT sd;
        test.startTest();
        INSERT shop;
        INSERT shop2;
        shop.Shop_Level__c = 'B';
        shop.Store_No_from_Account__c = '';
        shop.City__c = '青岛市';
        UPDATE shop;
        shop.City__c = '';
        UPDATE shop;
        shop2.Name = 'test001';
        update shop2;
		test.stopTest();
    }
}