force-app/main/default/objects/Account/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Model_Product__c/Customer_Model_Product__c.object-meta.xml
<CustomObject>
    <label>产品客户型号</label>
    <nameField>
        <label>Customer Product Model</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Model_Product__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Product Name + Country</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/Customer_Product_Line__c.object-meta.xml
<CustomObject>
    <label>Customer Product Line</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product_Line__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Product_Line_External_Key__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_External_Key__c</fullName>
    <externalId>true</externalId>
    <label>Product Line External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <label>Product Line Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>Small Domestic Home Appliances</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>Sound Bar</fullName>
            </value>
            <value>
                <fullName>Hitachi Commercial AC</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>B-Monitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Order__c/Delivery_Order__c.object-meta.xml
<CustomObject>
    <label>交付订单</label>
    <nameField>
        <displayFormat>DN{0000000000}</displayFormat>
        <label>Delivery Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Order</relationshipLabel>
    <relationshipName>Delivery_Order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Order__c/fields/SAP_Delivery_Order_No__c.field-meta.xml
<CustomField>
    <fullName>SAP_Delivery_Order_No__c</fullName>
    <externalId>true</externalId>
    <label>SAP Delivery Order No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>SAP发票</label>
    <nameField>
        <displayFormat>I{0000000000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SAP_Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>SAP_Invoice_No__c</fullName>
    <externalId>true</externalId>
    <label>SAP Invoice No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mapping__c/Mapping__c.object-meta.xml
<CustomObject>
    <label>对应关系</label>
    <nameField>
        <label>Original Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mapping__c/fields/Mapping_Code__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Code__c</fullName>
    <label>Mapping Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>SO{0000000000}</displayFormat>
        <label>SF Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/Order_Product__c.object-meta.xml
<CustomObject>
    <label>Order Product</label>
    <nameField>
        <displayFormat>OP{0000000000}</displayFormat>
        <label>Order Line No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Product__c/fields/Customer_Model_Product__c.field-meta.xml
<CustomField>
    <fullName>Customer_Model_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Model Product</label>
    <referenceTo>Customer_Model_Product__c</referenceTo>
    <relationshipLabel>Order Product</relationshipLabel>
    <relationshipName>Order_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Product</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/External_key__c.field-meta.xml
<CustomField>
    <fullName>External_key__c</fullName>
    <externalId>true</externalId>
    <label>External key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetActualSalesInfoFromSAPTest.cls
/*
 * @Author: WFC
 * @Date: 2022-07-12 10:45:58
 * @LastEditors: WFC
 * @LastEditTime: 2022-07-12 12:07:18
 * @Description: 
 * @FilePath: \Hitest\force-app\main\default\classes\GetActualSalesInfoFromSAPTest.cls
 */
@isTest
private class GetActualSalesInfoFromSAPTest {
    static testMethod void testMethod1() {
        Test.startTest();
        Account acc = new Account(
                            Name = 'testname',
                            SAP_Customer_Code__c = '0005001234');
        insert acc;

        Mapping__c mp1 = new Mapping__c();
        mp1.Name = '14';
        mp1.Mapping_Code__c = 'TV';
        mp1.RecordTypeId = Schema.SObjectType.Mapping__c.getRecordTypeInfosByName().get('SAP Product Line and Product Line Mapping').getRecordTypeId();
        insert mp1;

        Mapping__c mp2 = new Mapping__c();
        mp2.Name = '001';
        mp2.Mapping_Code__c = 'USA';
        mp2.RecordTypeId = Schema.SObjectType.Mapping__c.getRecordTypeInfosByName().get('Business Orgnization and Name Mapping').getRecordTypeId();
        insert mp2;

        Customer_Model_Product__c cmp = new Customer_Model_Product__c();
        cmp.name = 'cmp001';
        cmp.ExternalId__c = 'cmp001001';
        insert cmp;

        Customer_Product_Line__c cpl = new Customer_Product_Line__c();
        cpl.Product_Line_Name__c = 'TV';
        cpl.Customer__c = acc.Id;
        cpl.Product_Line_External_Key__c = '0005001234TV';
        insert cpl;

        Product__c pd = new Product__c();
        pd.name = 'pd001';
        insert pd;

        Order__c order = new Order__c();
    	order.Customer__c = acc.Id;
    	insert(order);
        Order_Product__c op = new Order_Product__c();
        op.External_Key__c = 'po001on0010005001234';
        op.Order__c = order.Id;
        insert op;

        Delivery_Order__c deo = new Delivery_Order__c();
        deo.Customer__c = acc.Id;
        deo.SAP_Delivery_Order_No__c = 'do001';
        insert deo;

        Invoice__c ic = new Invoice__c();
        ic.SAP_Invoice_No__c = 'io001';
        ic.Customer__c = acc.Id;
        insert ic;

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String jsonStr = '{"ActualSalesInfoList":[{"CustomerModel": "cmp001","CustomerSAPCode": "0005001234","FactoryModel": "pd001","ExportModel": "pd002","OrderCategory": "E","PONo": "po001","OrderItemNo": "on001","DNNo": "do001","InvoiceNo": "io001","ProductLineCode": "14","SalesOrganization": "001","SFCurrency": "USDD","UnitPrice": "100","SOQty": "10","BackOrderAmount": "10","BackOrderQty": "10" '+
                        ' ,"DNQty": "10","ShipAmount": "10","PendingDNQty": "10","PendingDNAmount": "10","PODNumber": "10","InvoicedQty": "10","InvoicedAmount": "10","DNNetIncome": "10","Cost": "10","BackOrderNetIncome": "10","PendingDNNetIncome": "10","InvoiceNetIncome": "10","InvoiceDate": "2022-01-01","DeliveryOrderPostingDate": "2022-01-01"}]}';
     
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        req.requestBody = Blob.valueOf(jsonStr);

        GetActualSalesInfoFromSAP.adoPost(); 
        Test.stopTest();
    }

    static testMethod void testMethod2() {
        Test.startTest();
        Account acc = new Account(
                            Name = 'testname',
                            SAP_Customer_Code__c = '0005001234');
        insert acc;

        Mapping__c mp1 = new Mapping__c();
        mp1.Name = '14';
        mp1.Mapping_Code__c = 'TV';
        mp1.RecordTypeId = Schema.SObjectType.Mapping__c.getRecordTypeInfosByName().get('SAP Product Line and Product Line Mapping').getRecordTypeId();
        insert mp1;

        Mapping__c mp2 = new Mapping__c();
        mp2.Name = '001';
        mp2.Mapping_Code__c = 'USA';
        mp2.RecordTypeId = Schema.SObjectType.Mapping__c.getRecordTypeInfosByName().get('Business Orgnization and Name Mapping').getRecordTypeId();
        insert mp2;

        Customer_Model_Product__c cmp = new Customer_Model_Product__c();
        cmp.name = 'cmp001';
        cmp.ExternalId__c = 'cmp001001';
        insert cmp;

        Customer_Product_Line__c cpl = new Customer_Product_Line__c();
        cpl.Product_Line_Name__c = 'TV';
        cpl.Customer__c = acc.Id;
        cpl.Product_Line_External_Key__c = '0005001234TV';
        insert cpl;

        Product__c pd = new Product__c();
        pd.name = 'pd001';
        insert pd;

        Order__c order = new Order__c();
    	order.Customer__c = acc.Id;
    	insert(order);
        Order_Product__c op = new Order_Product__c();
        op.External_Key__c = 'po001on0010005001234';
        op.Order__c = order.Id;
        insert op;

        Delivery_Order__c deo = new Delivery_Order__c();
        deo.Customer__c = acc.Id;
        deo.SAP_Delivery_Order_No__c = 'do001';
        insert deo;

        Invoice__c ic = new Invoice__c();
        ic.SAP_Invoice_No__c = 'io001';
        ic.Customer__c = acc.Id;
        insert ic;

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String jsonStr = '{"ActualSalesInfoList":[{"CustomerModel": "cmp001","CustomerSAPCode": "0005001234","FactoryModel": "pd001","ExportModel": "pd002","OrderCategory": "S","PONo": "po001","OrderItemNo": "on001","DNNo": "do001","InvoiceNo": "io001","ProductLineCode": "14","SalesOrganization": "001","SFCurrency": "USD","UnitPrice": "100","SOQty": "10","BackOrderAmount": "10","BackOrderQty": "10" '+
                        ' ,"DNQty": "10","ShipAmount": "10","PendingDNQty": "10","PendingDNAmount": "10","PODNumber": "10","InvoicedQty": "10","InvoicedAmount": "10","DNNetIncome": "10","Cost": "10","BackOrderNetIncome": "10","PendingDNNetIncome": "10","InvoiceNetIncome": "10","InvoiceDate": "0","DeliveryOrderPostingDate": "0"}]}';
     
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        req.requestBody = Blob.valueOf(jsonStr);

        GetActualSalesInfoFromSAP.adoPost(); 
        Test.stopTest();
    }
    

    static testMethod void testMethod7() {
        Test.startTest();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String jsonStr = '{"ActualSalesInfoList":[{"CustomerModel": "cmp001","CustomerSAPCode": "0005001234","FactoryModel": "pd001","ExportModel": "pd002","OrderCategory": "S","PONo": "po001","OrderItemNo": "on001","DNNo": "do001","InvoiceNo": "io001","ProductLineCode": "14","SalesOrganization": "001","SFCurrency": "USD","UnitPrice": "100","SOQty": "10","BackOrderAmount": "10","BackOrderQty": "10" '+
        ' ,"DNQty": "10","ShipAmount": "10","PendingDNQty": "10","PendingDNAmount": "10","PODNumber": "10","InvoicedQty": "10","InvoicedAmount": "10","DNNetIncome": "10","Cost": "10","BackOrderNetIncome": "10","PendingDNNetIncome": "10","InvoiceNetIncome": "10","InvoiceDate": "0","DeliveryOrderPostingDate": ""}]}';
     
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        req.requestBody = Blob.valueOf(jsonStr);

        GetActualSalesInfoFromSAP.adoPost(); 
        Test.stopTest();
    }

    
    static testMethod void testMethod8() {
        Test.startTest();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String jsonStr = '{"ActualSalesInfoList":[]}';
     
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        req.requestBody = Blob.valueOf(jsonStr);

        GetActualSalesInfoFromSAP.adoPost(); 
        Test.stopTest();
    }

    static testMethod void testMethod9() {
        Test.startTest();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String jsonStr = '{"ActualSalesInfo":[{]}';
     
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        req.requestBody = Blob.valueOf(jsonStr);

        GetActualSalesInfoFromSAP.adoPost(); 
        Test.stopTest();
    }
   
}