force-app/main/default/objects/Account/fields/SAP_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Code__c</fullName>
    <description>客户SAP编码</description>
    <label>SAP Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/Sales_Target_Branch_Company_Use__c.object-meta.xml
<CustomObject>
    <label>Sales Target(Branch Company Use)</label>
    <nameField>
        <label>Sales Target(Branch Company Use) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Target(Branch Company Use)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Target</relationshipLabel>
    <relationshipName>ForecastsC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Customer_Name_Import__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name_Import__c</fullName>
    <label>Customer Name Import</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesTargetTriggerHandler.cls
/**************************************************************************************************
 * SalesTargetTriggerHandler
 * Purpose: Sales_Target_Branch_Company_Use__c 上传SAP_Customer_Code__c 转换成id
 * Author: wfc
 * Create Date: 2020-09-17 
***************************************************************************************************/
public class SalesTargetTriggerHandler extends TriggerHandler{
    
    public override void beforeInsert(){
        for(Sales_Target_Branch_Company_Use__c cpl : ((list<Sales_Target_Branch_Company_Use__c>)Trigger.new)){
            // year赋值
            if(String.isBlank(cpl.Year__c)){
                cpl.Year__c = (Date.today() + '').subString(0,4);
            }
            // 查询customer表赋值
            if(String.isNotBlank(cpl.Customer_Name_Import__c)){
                String customerNameImport = cpl.Customer_Name_Import__c;
                // 补充‘0’
                Integer num = 10 - customerNameImport.length();
                if(customerNameImport.length() < 10){
                    for (Integer i = 0; i < num; i++) {
                        customerNameImport = '0' + customerNameImport;
                    }
                }

                List<Account> customerList= [select id from Account where SAP_Customer_Code__c =: customerNameImport];
                for(Account account : customerList){
                    cpl.Customer_Name__c = account.id;
                }


            }
        }
    }

}