force-app/main/default/objects/Report_Custom__c/Report_Custom__c.object-meta.xml
<CustomObject>
    <label>Report Custom</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Report Custom Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Custom__c/fields/Batch_Class__c.field-meta.xml
<CustomField>
    <fullName>Batch_Class__c</fullName>
    <description>报表执行batch class名称</description>
    <label>Batch Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Report_Custom__c/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <description>No:显示 Yes:不显示</description>
    <formula>ISPICKVAL( Report_Status__c , &apos;Updating&apos;)  ||  ISPICKVAL( Report_Status__c , &apos;No need to update&apos;)</formula>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Report_Custom__c/fields/Last_Update_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Update_Time__c</fullName>
    <label>Last Update Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Report_Custom__c/fields/Parameter__c.field-meta.xml
<CustomField>
    <fullName>Parameter__c</fullName>
    <description>参数 类型String，多个参数用“;”隔开</description>
    <inlineHelpText>参数 类型String，多个参数用“;”隔开</inlineHelpText>
    <label>Parameter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Report_Custom__c/fields/Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Report_Status__c</fullName>
    <label>Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not updated</fullName>
                <default>true</default>
                <label>Not updated</label>
            </value>
            <value>
                <fullName>Updating</fullName>
            </value>
            <value>
                <fullName>Update complete</fullName>
            </value>
            <value>
                <fullName>No need to update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Report_Custom__c/fields/Report_Url__c.field-meta.xml
<CustomField>
    <fullName>Report_Url__c</fullName>
    <label>Report Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Report_Custom__c/fields/Text_Class__c.field-meta.xml
<CustomField>
    <fullName>Text_Class__c</fullName>
    <formula>CASE( Report_Status__c , 
&apos;Updating&apos;, &apos;slds-text-color_error&apos;, 
&apos;Not updated&apos;, &apos;slds-text-color_default&apos;,
&apos;slds-text-color_success&apos;)</formula>
    <label>Text Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReportCustomeController.cls
/*
 * @Author: WFC
 * @Date: 2024-03-19 16:52:43
 * @LastEditors: WFC
 * @LastEditTime: 2024-05-09 14:15:06
 * @Description:
 * @FilePath: \HisenseAll20240426\force-app\main\default\classes\ReportCustomeController.cls
 */
public without sharing class ReportCustomeController{
    @AuraEnabled(cacheable = true)
    public static List<Report_Custom__c> getReportCustomData(){
        return [SELECT Id, Report_Name__c, Last_Update_Time__c, Report_Url__c, Report_Status__c, Batch_Class__c, Disabled__c, Text_Class__c, Parameter__c
                FROM Report_Custom__c
                ORDER BY CreatedDate];
    }

    @AuraEnabled
    public static Boolean updateReportCustom(Report_Custom__c row){
        Savepoint sp = Database.setSavepoint();
        try{
            row.Report_Status__c = 'Updating';
            update row;

            System.debug('wwww---' + row.Parameter__c);

            String batchClassName = row.Batch_Class__c;
            List<String> params = new List<String>();
            // 参数不为空
            if (String.isNotBlank(row.Parameter__c)){
                String parameter = row.Parameter__c;
                params = parameter.split(';');
            }
            if (batchClassName.equals('CustomerProductSalesReportDelBatch')){
                if(params.size() < 2){
                    return false;
                }
                CustomerProductSalesReportDelBatch ss = new CustomerProductSalesReportDelBatch(params[0], params[1]);
                Database.executeBatch(ss);
            } else{
                // 方法根据 Apex Batch 类的名称执行 Batch 方法
                Database.Batchable<Object> batchInstance = (Database.Batchable<Object>)Type.forName(batchClassName).newInstance();
                Database.executeBatch(batchInstance);
            }
            return true;
        } catch (Exception e){
            Database.rollback(sp);
            return false;
        }
    }

}