force-app/main/default/objects/Promoter_Attendance_Rule__c/Promoter_Attendance_Rule__c.object-meta.xml
<CustomObject>
    <label>Promoter Attendance Rule</label>
    <nameField>
        <label>Promoter Attendance Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoter Attendance Rule</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Attendance_Rule__c/fields/End_time__c.field-meta.xml
<CustomField>
    <fullName>End_time__c</fullName>
    <label>End time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Promoter_Attendance_Rule__c/fields/Need_Check_Distance__c.field-meta.xml
<CustomField>
    <fullName>Need_Check_Distance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Don&apos;t allow off-site check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promoter_Attendance_Rule__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <label>Start time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Promoter_Attendance_Rule__c/fields/Time_buffer__c.field-meta.xml
<CustomField>
    <fullName>Time_buffer__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Check-in Time buffer (min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/Responsible_Person__c.object-meta.xml
<CustomObject>
    <label>Responsible person</label>
    <nameField>
        <displayFormat>RP-{YYYY}{MM}{0000}</displayFormat>
        <label>门店负责人编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsible persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Responsible_Person__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>负责人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Responsible_Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Promoter_Attendance_Rule__c.field-meta.xml
<CustomField>
    <fullName>Promoter_Attendance_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>考勤规则</label>
    <referenceTo>Promoter_Attendance_Rule__c</referenceTo>
    <relationshipName>Responsible_Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>门店名称</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Responsible_Person</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店员</label>
    <referenceTo>User</referenceTo>
    <relationshipName>shops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PromoterAttendanceRuleTriggerHandler.cls
public without sharing class PromoterAttendanceRuleTriggerHandler extends TriggerHandler{

    public override void beforeInsert() {

        for (Promoter_Attendance_Rule__c par : ((list<Promoter_Attendance_Rule__c>)Trigger.new)) {
            String startTime = String.valueOf(par.Start_time__c).substring(0,5);
            String endTime = String.valueOf(par.End_time__c).substring(0,5);

            par.Name = startTime + '-' + endTime;

            if (par.Time_buffer__c != 0 && par.Time_buffer__c != null) {
                String timeBuffer = String.valueOf(par.Time_buffer__c);
                par.Name += ' Buffer-' + timeBuffer + 'min';
            }

            if (par.Distance__c != null) {
                String distance = String.valueOf(par.Distance__c);
                par.Name += ' Distance-' + distance + 'm';
            }

            if (par.Need_Check_Distance__c) {
                par.Name += ' Donot allow off-site check';
            }
            
            par.ExternalId__c = par.Name;
        }
    }

    public override void beforeUpdate() {

        for (Promoter_Attendance_Rule__c par : ((list<Promoter_Attendance_Rule__c>)Trigger.new)) {
            String startTime = String.valueOf(par.Start_time__c).substring(0,5);
            String endTime = String.valueOf(par.End_time__c).substring(0,5);

            par.Name = startTime + '-' + endTime;

            if (par.Time_buffer__c != 0 && par.Time_buffer__c != null) {
                String timeBuffer = String.valueOf(par.Time_buffer__c);
                par.Name += ' Buffer-' + timeBuffer + 'min';
            }

            if (par.Distance__c != null) {
                String distance = String.valueOf(par.Distance__c);
                par.Name += ' Distance-' + distance + 'm';
            }

            if (par.Need_Check_Distance__c) {
                par.Name += ' Donot allow off-site check';
            }

            par.ExternalId__c = par.Name;
        }
    }

    public override void afterUpdate() {

        Map<String, Promoter_Attendance_Rule__c> oldMap = new Map<String, Promoter_Attendance_Rule__c>();
        for (Promoter_Attendance_Rule__c par : ((list<Promoter_Attendance_Rule__c>)Trigger.old)) {
            oldMap.put(par.Id, par);
        }

        System.debug('oldMap--->'+oldMap);
        Set<Id> parIds = new Set<Id>();
        for (Promoter_Attendance_Rule__c par : ((list<Promoter_Attendance_Rule__c>)Trigger.new)) {
            if (par.Name != oldMap.get(par.Id).Name) {
                parIds.add(par.Id);
            }
        }

        List<Responsible_Person__c> rpList = [SELECT 
                                                    Id, 
                                                    Promoter_Attendance_Rule__c, 
                                                    Promoter_Attendance_Rule__r.Name,
                                                    Principal__c, 
                                                    Principal__r.Name, 
                                                    Shop_Name__c, 
                                                    Shop_Name__r.Name 
                                                FROM Responsible_Person__c 
                                                WHERE Promoter_Attendance_Rule__c = : parIds
                                                AND Principal__r.IsActive = true];
        Map<String, Responsible_Person__c> parIdRp = new Map<String, Responsible_Person__c>();

        system.debug('rpList===============>'+rpList);
        CustomNotificationType notificationType = [SELECT Id, DeveloperName 
                                                    FROM CustomNotificationType 
                                                    WHERE DeveloperName='Custom_Notification'];
        for (Responsible_Person__c rp : rpList) {
            Messaging.CustomNotification notification = new Messaging.CustomNotification();
            String title = rp.Shop_Name__r.Name + ' rule changed';
            String body = rp.Promoter_Attendance_Rule__r.Name;
            Set<String> userIds = new Set<String>();
            userIds.add(rp.Principal__c);

            notification.setTitle(title);
            notification.setBody(body);
            notification.setNotificationTypeId(notificationType.Id);
            notification.setTargetId(rp.Promoter_Attendance_Rule__c);
            notification.send(userIds);
        }
    }

}