force-app/main/default/objects/Interface_Url__c/Interface_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Interface_Url</label>
</CustomObject>

force-app/main/default/objects/Interface_Url__c/fields/Basic_Url__c.field-meta.xml
<CustomField>
    <fullName>Basic_Url__c</fullName>
    <label>Basic Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAvailableInventorySchedulableTest.cls
@isTest
private class GetAvailableInventorySchedulableTest {
    static testMethod void testMethod1() {
        Interface_Url__c newurl = new Interface_Url__c(
                                    Name = 'SAP',
                                    Basic_Url__c ='testbasic',
                                    User_Name__c = 'username',
                                    Password__c = 'password');
        insert newurl;
        GetAvailableInventorySchedulable cis = new GetAvailableInventorySchedulable('111');
        SchedulableContext sc;
        cis.execute(sc);
    }
}