force-app/main/default/objects/CheckItem__c/CheckItem__c.object-meta.xml
<CustomObject>
    <label>Check Item</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Check Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CheckItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.sales_region__c</field>
            <operation>equals</operation>
            <valueField>$User.Sales_Region__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Check Items (Product)</relationshipLabel>
    <relationshipName>Check_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/recordTypes/Canada.recordType-meta.xml
<RecordType>
    <fullName>Canada</fullName>
    <active>true</active>
    <label>Canada</label>
</RecordType>

force-app/main/default/objects/CheckItem__c/recordTypes/International.recordType-meta.xml
<RecordType>
    <fullName>International</fullName>
    <active>true</active>
    <label>International</label>
</RecordType>

force-app/main/default/objects/CheckItem__c/recordTypes/Mexico.recordType-meta.xml
<RecordType>
    <fullName>Mexico</fullName>
    <active>true</active>
    <label>Mexico</label>
</RecordType>

force-app/main/default/objects/CheckItem__c/recordTypes/Peru.recordType-meta.xml
<RecordType>
    <fullName>Peru</fullName>
    <active>true</active>
    <label>Peru</label>
</RecordType>

force-app/main/default/objects/CheckItem__c/recordTypes/USA.recordType-meta.xml
<RecordType>
    <fullName>USA</fullName>
    <active>true</active>
    <label>USA</label>
</RecordType>

force-app/main/default/objects/CheckResult__c/CheckResult__c.object-meta.xml
<CustomObject>
    <label>Check Result</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Check Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CheckResult__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <formula>TEXT(CheckItem__r.Sales_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CheckResult__c/fields/Sampling_Inspection__c.field-meta.xml
<CustomField>
    <fullName>Sampling_Inspection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sampling Inspection</label>
    <referenceTo>Sampling_Inspection__c</referenceTo>
    <relationshipLabel>Check Results</relationshipLabel>
    <relationshipName>Check_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Image_Ai_Interface__c/Image_Ai_Interface__c.object-meta.xml
<CustomObject>
    <label>Image Ai Interface</label>
    <nameField>
        <label>Interface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Image Ai Interface</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Image_Ai_Interface__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Image_Ai_Interface__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <externalId>true</externalId>
    <label>Url</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/sales_region__c.field-meta.xml
<CustomField>
    <fullName>sales_region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;USA(OEM)&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;American Sales Department&apos;) , &apos;American Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Middle East and Africa Sales Department&apos;) , &apos;Middle East and Africa Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Asia-Pacific Sales Department&apos;) , &apos;Asia-Pacific Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Key Account Sales Department&apos;) , &apos;Key Account Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Europe Sales Department&apos;) , &apos;Europe Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Colombia&apos;) , &apos;Hisense Colombia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Argentina&apos;) , &apos;Hisense Argentina&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Saudi&apos;) , &apos;Hisense Saudi&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Vietnam&apos;) , &apos;Hisense Vietnam&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Peru&apos;) , &apos;Hisense Peru&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>USA(OEM)</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense Malaysia</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>American Sales Department</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa Sales Department</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific Sales Department</fullName>
            </value>
            <value>
                <fullName>Key Account Sales Department</fullName>
            </value>
            <value>
                <fullName>Europe Sales Department</fullName>
            </value>
            <value>
                <fullName>Communications Sales Department</fullName>
            </value>
            <value>
                <fullName>Hisense Indonesia</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Thailand</fullName>
            </value>
            <value>
                <fullName>Hisense Vietnam</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense West Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Philippines</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Singapore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/Sampling_Inspection__c.object-meta.xml
<CustomObject>
    <label>Sampling Inspection</label>
    <nameField>
        <displayFormat>SI-{YYYY}{MM}{0000}</displayFormat>
        <label>出样检查编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sampling Inspection</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Inspection__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <formula>Text(Shop__r.Sales_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>USA(OEM)</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense Malaysia</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>American Sales Department</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa Sales Department</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific Sales Department</fullName>
            </value>
            <value>
                <fullName>Key Account Sales Department</fullName>
            </value>
            <value>
                <fullName>Europe Sales Department</fullName>
            </value>
            <value>
                <fullName>Communications Sales Department</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Thailand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>Hisense Indonesia</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense West Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Hisense Vietnam</fullName>
            </value>
            <value>
                <fullName>Hisense Philippines</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Singapore</fullName>
            </value>
            <value>
                <fullName>Hisense International</fullName>
            </value>
            <value>
                <fullName>Hisense UK</fullName>
            </value>
            <value>
                <fullName>Hisense Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTriggerHandler.cls
/**************************************************************************************************
 * ContentDocumentLinkTriggerHandler
 * Purpose:ContentDocumentLinkTrigger处理逻辑
 * Author: lizunxing
 * Create Date: 2025-03-30
 ***************************************************************************************************/
public class ContentDocumentLinkTriggerHandler implements Triggers.Handler{
    public static User currentUser = [SELECT Id, Sales_Region__c
                                      FROM User
                                      WHERE Id = :UserInfo.getUserId()];
    public void handle(){
        if (Trigger.isAfter && Trigger.isInsert){
            System.debug('======ContentDocumentLinkTriggerHandler======');

            for (ContentDocumentLink cdl : ((list<ContentDocumentLink>)Trigger.new )){
                String[] salesRegions = new String[]{ 'Hisense Canada', 'Hisense USA', 'Hisense Peru', 'Hisense International', 'Hisense Mexico' };

                if (salesRegions.contains(currentUser.sales_region__c)){
                    Id recordId = (Id) cdl.LinkedEntityId;
                    SObjectType objectType = recordId.getSObjectType();
                    Schema.DescribeSObjectResult describeResult = objectType.getDescribe();

                    List<Image_Ai_Interface__c> imageAis = [Select Name, Type__c, Url__c
                                                            from Image_Ai_Interface__c];
                    Map<String, Image_Ai_Interface__c> mapImageAi = new Map<String, Image_Ai_Interface__c>();
                    for (Image_Ai_Interface__c imageAi : imageAis){
                        mapImageAi.put(imageAi.Name, imageAi);
                    }

                    if ('Sampling_Inspection__c'.equals(describeResult.getName())){
                        Sampling_Inspection__c si = [Select id, Product__r.Product_line__c
                                                     from Sampling_Inspection__c
                                                     where id = :recordId];
                        if ('TV'.equals(si.Product__r.Product_line__c)){
                            String base64Code = convertFileToBase64(cdl.ContentDocumentId);

                            List<String> interfaceNames = new List<String>{ '电视黑屏检核', '品类检核' };
                            for (String interfaceName : interfaceNames){
                                Image_Ai_Interface__c imageAi = mapImageAi.get(interfaceName);
                                if (imageAi != null){
                                    Image image = new Image(
                                        Name = interfaceName, 
                                        Record_Id__c = recordId, 
                                        ContentDocumentId = cdl.ContentDocumentId
                                    );
                                    insert image;

                                    Rest_ImageAI.imageAi(image.Id, imageAi.Type__c, imageAi.Url__c, base64Code);
                                }

                            }
                        }
                    }

                    if ('CheckResult__c'.equals(describeResult.getName())){
                        CheckResult__c cr = [select id, CheckItem__r.Has_Image_AI__c, CheckItem__r.Image_AI__c
                                             from CheckResult__c
                                             where id = :recordId];
                        if (cr.CheckItem__r.Has_Image_AI__c && String.isNotBlank(cr.CheckItem__r.Image_AI__c)){
                            String base64Code = convertFileToBase64(cdl.ContentDocumentId);
                            for (String imageAiName : cr.CheckItem__r.Image_AI__c.split(';')){

                                if (imageAiName.equals('打卡图像相似度检测')){

                                } else{
                                    Image_Ai_Interface__c imageAi = mapImageAi.get(imageAiName);
                                    if (imageAi != null){
                                        Image image = new Image(
                                            Name = imageAiName, 
                                            Record_Id__c = recordId, 
                                            ContentDocumentId = cdl.ContentDocumentId
                                        );
                                        insert image;
                                        Rest_ImageAI.imageAi(image.Id, imageAi.Type__c, imageAi.Url__c, base64Code);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    public static String convertFileToBase64(String fileId){
        // 查询 ContentVersion 记录
        ContentVersion contentVersion = [SELECT VersionData
                                         FROM ContentVersion
                                         WHERE ContentDocumentId = :fileId
                                         LIMIT 1];
        if (contentVersion != null && contentVersion.VersionData != null){
            // 将文件内容转换为 Base64 编码
            return EncodingUtil.base64Encode(contentVersion.VersionData);
        }
        return null;
    }

    //异步调用图片AI接口
    // public class AsyncCallImageAi implements Queueable{
    //     public ContentDocumentLink cdl { get; set; }
    //     public AsyncCallImageAi(ContentDocumentLink cdl){
    //         this.cdl = cdl;
    //     }
    //     public void execute(QueueableContext context) {
    //     }
    // }
}