force-app/main/default/objects/CheckItem__c/CheckItem__c.object-meta.xml
<CustomObject>
    <label>Check Item</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Check Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CheckItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes/No</fullName>
                <default>true</default>
                <label>Yes/No</label>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Multiple Selection</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Score</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Informational-photo</fullName>
            </value>
            <value>
                <fullName>Informational</fullName>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/recordTypes/Australia.recordType-meta.xml
<RecordType>
    <fullName>Australia</fullName>
    <active>true</active>
    <label>Australia</label>
</RecordType>

force-app/main/default/objects/CheckResult__c/CheckResult__c.object-meta.xml
<CustomObject>
    <label>Check Result</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Check Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CheckResult__c/fields/CheckItem__c.field-meta.xml
<CustomField>
    <fullName>CheckItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Check Item</label>
    <referenceTo>CheckItem__c</referenceTo>
    <relationshipLabel>Check Results</relationshipLabel>
    <relationshipName>Check_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CheckResult__c/fields/InspectorDailyReport__c.field-meta.xml
<CustomField>
    <fullName>InspectorDailyReport__c</fullName>
    <label>InspectorDailyReport</label>
    <referenceTo>Daily_Inspection_Report__c</referenceTo>
    <relationshipLabel>Check Results</relationshipLabel>
    <relationshipName>Check_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CheckResult__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <formula>InspectorDailyReport__r.Report_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CheckResult__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <formula>TEXT(CheckItem__r.Sales_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/Daily_Inspection_Report__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>DIR-{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>巡店员日报编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Owner_text__c.field-meta.xml
<CustomField>
    <fullName>Owner_text__c</fullName>
    <label>Owner_text</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <description>巡店日期</description>
    <label>报告日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <description>销售区域</description>
    <formula>TEXT(Store__r.Sales_Region__c)</formula>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>巡店报告状态，包括New和Submitted两种</description>
    <inlineHelpText>Status of inspection report, including new and submitted</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Floorwalk_Training_Plan__c/Floorwalk_Training_Plan__c.object-meta.xml
<CustomObject>
    <label>AU Training Completion Report</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AU Training Completion Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floorwalk_Training_Plan__c/fields/Actual_number_of_trainees__c.field-meta.xml
<CustomField>
    <fullName>Actual_number_of_trainees__c</fullName>
    <label>Actual number of trainees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Floorwalk_Training_Plan__c/fields/ExternalKey__c.field-meta.xml
<CustomField>
    <fullName>ExternalKey__c</fullName>
    <description>天+人（同店其他日报作为归拢指标）</description>
    <externalId>true</externalId>
    <label>ExternalKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Floorwalk_Training_Plan__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Floorwalk_Training_Plan__c/fields/Target_number_of_trainees__c.field-meta.xml
<CustomField>
    <fullName>Target_number_of_trainees__c</fullName>
    <description>预期指标</description>
    <label>Target number of trainees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Floorwalk_Training_Plan__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Floorwalk_Training_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>USA(OEM)</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense Malaysia</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>American Sales Department</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa Sales Department</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific Sales Department</fullName>
            </value>
            <value>
                <fullName>Key Account Sales Department</fullName>
            </value>
            <value>
                <fullName>Europe Sales Department</fullName>
            </value>
            <value>
                <fullName>Communications Sales Department</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Thailand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>Hisense Indonesia</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense West Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Hisense Vietnam</fullName>
            </value>
            <value>
                <fullName>Hisense Philippines</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Singapore</fullName>
            </value>
            <value>
                <fullName>Hisense International</fullName>
            </value>
            <value>
                <fullName>Hisense UK</fullName>
            </value>
            <value>
                <fullName>Hisense Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General Check List</fullName>
    </customValue>
    <customValue>
        <fullName>Sampling Product Check</fullName>
        <default>true</default>
        <label>Sample Display</label>
    </customValue>
    <customValue>
        <fullName>Prototype</fullName>
    </customValue>
    <customValue>
        <fullName>Material</fullName>
    </customValue>
    <customValue>
        <fullName>Booth and image</fullName>
    </customValue>
    <customValue>
        <fullName>Personnel</fullName>
    </customValue>
    <customValue>
        <fullName>Speak With the Store Leader</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly Asks</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Feedback</fullName>
        <label>Hisense Feedback</label>
    </customValue>
    <customValue>
        <fullName>Sample Condition</fullName>
    </customValue>
    <customValue>
        <fullName>Material Display</fullName>
    </customValue>
    <customValue>
        <fullName>Booth</fullName>
    </customValue>
    <customValue>
        <fullName>Competing Goods</fullName>
    </customValue>
    <customValue>
        <fullName>Photo</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Display</fullName>
    </customValue>
    <customValue>
        <fullName>Competitive Display</fullName>
    </customValue>
    <customValue>
        <fullName>Material X</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense X Sample</fullName>
    </customValue>
    <customValue>
        <fullName>Competitive X Sample</fullName>
    </customValue>
    <customValue>
        <fullName>Competitive Feedback</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket</fullName>
    </customValue>
    <customValue>
        <fullName>Promotions</fullName>
    </customValue>
    <customValue>
        <fullName>Activities of Competitors</fullName>
    </customValue>
    <customValue>
        <fullName>Brand Image Reinforcement</fullName>
    </customValue>
    <customValue>
        <fullName>Relationships on the Sales Floor</fullName>
    </customValue>
    <customValue>
        <fullName>Always Do What Is Right</fullName>
    </customValue>
    <customValue>
        <fullName>Needs on the Sales Floor</fullName>
    </customValue>
    <customValue>
        <fullName>Sample Inspection Img</fullName>
    </customValue>
    <masterLabel>Category Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateFloorWalkerTraining.cls
global class CreateFloorWalkerTraining implements Database.Batchable<sObject> {
    /* 用于判断“今天” */
    private final Date currentDate = Date.today();
    private final Integer currentYear = currentDate.year();
    private final Integer currentMonth = currentDate.month();

    private Integer year;
    private Integer month;

    // 默认构造函数，使用当前日期的年和月
    global CreateFloorWalkerTraining() {
        this.year = currentYear;
        this.month = currentMonth;
    }

    // 带参数的构造函数，允许传入年和月
    global CreateFloorWalkerTraining(Integer year, Integer month) {
        this.year = year;
        this.month = month;
    }

    public static Date getFirstDayOfMonth(Integer year, Integer month) {
        return Date.newInstance(year, month, 1);
    }

    public static Date getLastDayOfMonth(Integer year, Integer month) {
        if (month == 12) {
            return Date.newInstance(year + 1, 1, 1).addDays(-1);
        } else {
            return Date.newInstance(year, month + 1, 1).addDays(-1);
        }
    }

    /* 起始：拉所有明细 */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date firstDay = getFirstDayOfMonth(this.year, this.month);
        Date lastDay = getLastDayOfMonth(this.year, this.month);
        return Database.getQueryLocator([
			 SELECT Id,InspectorDailyReport__r.Store_Name__c, InspectorDailyReport__r.Status__c, Report_Date__c,
             CreatedById,InspectorDailyReport__r.Owner_text__c, CheckItem__r.Description__c, Response__c 
			 FROM CheckResult__c 
			 WHERE InspectorDailyReport__r.Status__c = 'Submitted' 
			 AND Sales_Region__c = 'Hisense Australia' 
			 AND CheckItem__r.Item_Type__c = 'Training' 
			 AND CheckItem__r.Question_Type__c = 'Integer'
			 AND InspectorDailyReport__r.Report_Date__c >= : firstDay
			 AND InspectorDailyReport__r.Report_Date__c <= : lastDay
			 ORDER BY CreatedDate
        ]);
    }

    /* Max:100SQL;50000rows */
    public void execute(Database.BatchableContext bc, List<CheckResult__c> scope) {
        System.debug('数据量' + scope.size());
        List<User> users = [SELECT Id, Name, IsActive FROM User WHERE Profile.Name = 'Australia Floorwalker' and IsActive = true];
        Integer days = Date.daysInMonth(Integer.valueOf(this.year), Integer.valueOf(this.month));
        List<Floorwalk_Training_Plan__c> newPlans = new List<Floorwalk_Training_Plan__c>();
        Map<String, Map<String, List<Decimal>>> summaryMap = new Map<String, Map<String, List<Decimal>>>();
        
        // 遍历查询结果，汇总数据
        for (CheckResult__c result : scope) {
            String createdBy = result.CreatedById;
            Date reportDate = result.Report_Date__c;
            DateTime reportDateTime = DateTime.newInstance(reportDate.year(), reportDate.month(), reportDate.day());
            String reportDateStr = reportDateTime.format('yyyy-MM-dd');
            Decimal responseValue = (result.Response__c != null) ? Decimal.valueOf(result.Response__c) : null;
        
            if (responseValue != null) {
                // 如果用户不存在于 Map 中，初始化
                if (!summaryMap.containsKey(createdBy)) {
                    summaryMap.put(createdBy, new Map<String, List<Decimal>>());
                }
            
                // 如果日期不存在于用户 Map 中，初始化
                if (!summaryMap.get(createdBy).containsKey(reportDateStr)) {
                    summaryMap.get(createdBy).put(reportDateStr, new List<Decimal>());
                }
            
                // 添加响应值到列表
                summaryMap.get(createdBy).get(reportDateStr).add(responseValue);
            }
        }
    
        for (User user : users) {
            for (Integer j = 1; j <= days; j++) {
                Date dtDate = Date.newInstance(Integer.valueOf(this.year), Integer.valueOf(this.month), j);
                Datetime dtDatetime = Datetime.newInstanceGmt(dtDate.year(), dtDate.month(), dtDate.day(), 0, 0, 0);
                Integer week = Integer.valueOf(dtDatetime.format('u'));
                String dtDateStr = dtDatetime.format('yyyy-MM-dd');
            
                Floorwalk_Training_Plan__c newPlan = new Floorwalk_Training_Plan__c(
                    User__c = user.Id,
                    Report_Date__c = dtDate,
                    ExternalKey__c = dtDateStr + '-' + user.Id
                );
            
                if (week == 6 || week == 7) {
                    // 不计算
                    newPlan.Target_number_of_trainees__c = 0;
                    System.debug('周六周天: ' + dtDateStr);
                } else {
                    newPlan.Target_number_of_trainees__c = 5;
                    System.debug('工作日: ' + dtDateStr);
                }
            
                // 获取用户对应的 Map<String, List<Decimal>>
                Map<String, List<Decimal>> dateMap = summaryMap.get(user.Id);
            
                // 初始化响应列表
                List<Decimal> responses = new List<Decimal>();
            
                // 检查 dateMap 是否为空
                if (dateMap != null && dateMap.containsKey(dtDateStr)) {
                    responses = dateMap.get(dtDateStr);
                }
            
                Decimal total = 0;
                for (Decimal response : responses) {
                    total += response;
                }
            
                newPlan.Actual_number_of_trainees__c = total;
                newPlan.Name = dtDateStr + '-' + user.Name + '-' + newPlan.Target_number_of_trainees__c + '-' + total;
            
                newPlans.add(newPlan);
            }
        }
    
        // 插入新的任务记录
        try {
            upsert newPlans ExternalKey__c;
        } catch (Exception e) {
            // 记录异常信息
            System.debug('Error inserting tasks: ' + e.getMessage());
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}