force-app/main/default/objects/CheckItem__c/CheckItem__c.object-meta.xml
<CustomObject>
    <label>Check Item</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Check Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CheckItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/DescriptionT__c.field-meta.xml
<CustomField>
    <fullName>DescriptionT__c</fullName>
    <label>DescriptionT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/HasComment__c.field-meta.xml
<CustomField>
    <fullName>HasComment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Comment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/HasFile__c.field-meta.xml
<CustomField>
    <fullName>HasFile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HasFile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/IsYesOrNo__c.field-meta.xml
<CustomField>
    <fullName>IsYesOrNo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Yes Or No</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/MaximumScore__c.field-meta.xml
<CustomField>
    <fullName>MaximumScore__c</fullName>
    <defaultValue>TEXT(5)</defaultValue>
    <label>Maximum Score</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>Booth and image</fullName>
            </value>
            <value>
                <fullName>Prototype</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>new</fullName>
                <isActive>false</isActive>
                <label>new</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/ProjectT__c.field-meta.xml
<CustomField>
    <fullName>ProjectT__c</fullName>
    <label>ProjectT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/Require_Comment_Scores__c.field-meta.xml
<CustomField>
    <fullName>Require_Comment_Scores__c</fullName>
    <label>Require Comment Scores</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/RequireCommentOptions__c.field-meta.xml
<CustomField>
    <fullName>RequireCommentOptions__c</fullName>
    <label>Require Comment Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/RequireFileOptions__c.field-meta.xml
<CustomField>
    <fullName>RequireFileOptions__c</fullName>
    <label>Require File Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/Scores_require_file__c.field-meta.xml
<CustomField>
    <fullName>Scores_require_file__c</fullName>
    <label>Require File Scores</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CheckItemTriggerHandlerHelper.cls
public without sharing class CheckItemTriggerHandlerHelper {
    public static void duplicateCheck(List<CheckItem__c> oldList, List<CheckItem__c> newList){
        Map<Id, CheckItem__c> oldMap = new Map<Id, CheckItem__c>();
        Boolean isUpdate = false;
        if(oldList != null) {
            isUpdate = true;
            oldMap = new Map<Id, CheckItem__c>(oldList);
        }
        for(CheckItem__c item : newList) {
            if(isUpdate) {
                if(oldMap.get(item.Id).Description__c != item.Description__c) {
                    item.DescriptionT__c = item.Description__c;
                }
                 //ADD BY TIGER 
                if (oldMap.get(item.Id).Project__c != item.Project__c) {
                    item.ProjectT__c = item.Project__c;
                }
            } else {
                item.DescriptionT__c = item.Description__c;
                item.ProjectT__c = item.Project__c;//ADD BY TIGER 
            }

            if(item.IsYesOrNo__c && item.HasFile__c && item.RequireFileOptions__c != null) {
                if(item.RequireFileOptions__c.contains('No')) {
                    if(item.Scores_require_file__c == null) {
                       item.Scores_require_file__c = '0'; 
                    } else {
                        item.Scores_require_file__c += ';0'; 
                    }
                } 
                if(item.RequireFileOptions__c.contains('Yes')) {
                    if(item.Scores_require_file__c == null) {
                        item.Scores_require_file__c = item.MaximumScore__c;
                    } else {
                        item.Scores_require_file__c += ';' + item.MaximumScore__c;
                    }
                    
                }
                
            }

            if(item.IsYesOrNo__c && item.HasComment__c && item.RequireCommentOptions__c != null) {
                if(item.RequireCommentOptions__c.contains('No')) {
                    if(item.Require_Comment_Scores__c == null) {
                        item.Require_Comment_Scores__c = '0';
                    } else {
                        item.Require_Comment_Scores__c += ';0';
                    }
                    
                } 
                if(item.RequireCommentOptions__c.contains('Yes')) {
                    if(item.Require_Comment_Scores__c == null) {
                        item.Require_Comment_Scores__c = item.MaximumScore__c;
                    } else {
                        item.Require_Comment_Scores__c += ';' + item.MaximumScore__c;
                    }
                }
            }
        }
    }
}