force-app/main/default/objects/CheckItem__c/CheckItem__c.object-meta.xml
<CustomObject>
    <label>Check Item</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Check Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Check Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CheckItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/HasComment__c.field-meta.xml
<CustomField>
    <fullName>HasComment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Comment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/HasFile__c.field-meta.xml
<CustomField>
    <fullName>HasFile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HasFile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/IsYesOrNo__c.field-meta.xml
<CustomField>
    <fullName>IsYesOrNo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Yes Or No</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/MaximumScore__c.field-meta.xml
<CustomField>
    <fullName>MaximumScore__c</fullName>
    <defaultValue>TEXT(5)</defaultValue>
    <label>Maximum Score</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personnel</fullName>
            </value>
            <value>
                <fullName>Booth and image</fullName>
            </value>
            <value>
                <fullName>Prototype</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>new</fullName>
                <isActive>false</isActive>
                <label>new</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/RequireCommentOptions__c.field-meta.xml
<CustomField>
    <fullName>RequireCommentOptions__c</fullName>
    <label>Require Comment Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/fields/RequireFileOptions__c.field-meta.xml
<CustomField>
    <fullName>RequireFileOptions__c</fullName>
    <label>Require File Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CheckItem__c/recordTypes/Chile.recordType-meta.xml
<RecordType>
    <fullName>Chile</fullName>
    <active>true</active>
    <label>Chile</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CheckItemTriggerHandlerHelperTest.cls
/**
 * @description       : 
 * @author            : fausfeng@deloitte.com.cn
 * @group             : 
 * @last modified on  : 12-07-2023
 * @last modified by  : fausfeng@deloitte.com.cn
**/
@isTest
public class CheckItemTriggerHandlerHelperTest {
	@isTest
    static void testMethod1(){
        
        Test.startTest();
        CheckItem__c checkItem = new CheckItem__c();
		checkItem.Description__c = 'old';
		checkItem.Active__c = true;
        checkItem.Sales_Region__c = 'Hisense Chile';
        checkItem.Product_Line__c = 'TV';
        checkItem.Project__c = 'Booth and image';
        checkItem.RecordTypeId = Schema.SObjectType.CheckItem__c.getRecordTypeInfosByName().get('Chile').getRecordTypeId();
        insert checkItem;
        
        checkItem.Description__c = 'new';
        checkItem.Project__c = 'Material';
        update checkItem;
        
        CheckItem__c checkItem2 = new CheckItem__c();
		checkItem2.Description__c = 'old';
		checkItem2.Active__c = true;
        checkItem2.Sales_Region__c = 'Hisense Chile';
        checkItem2.Product_Line__c = 'TV';
        checkItem2.Project__c = 'Booth and image';
        checkItem2.MaximumScore__c = '1';
        checkItem2.IsYesOrNo__c = true;
        checkItem2.HasFile__c = true;
        checkItem2.RequireFileOptions__c = 'No;Yes';
        checkItem2.HasComment__c = true;
        checkItem2.RequireCommentOptions__c = 'Yes;No';
        checkItem2.RecordTypeId = Schema.SObjectType.CheckItem__c.getRecordTypeInfosByName().get('Chile').getRecordTypeId();
        insert checkItem2;
        
        
        Test.stopTest();
    }
}