force-app/main/default/objects/Event_Receipt__c/Event_Receipt__c.object-meta.xml
<CustomObject>
    <label>Event Receipt</label>
    <nameField>
        <displayFormat>SINV-{00000}</displayFormat>
        <label>Event Receipt Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Receipt__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event_Receipt__c/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <label>Paid</label>
    <summarizedField>Event_Payment__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Event_Payment__c.Charge_Today__c</field>
        <operation>notEqual</operation>
        <value>No</value>
    </summaryFilterItems>
    <summaryForeignKey>Event_Payment__c.Event_Receipt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Event_Receipt__c/fields/Event_Subject__c.field-meta.xml
<CustomField>
    <fullName>Event_Subject__c</fullName>
    <label>Event Subject</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Event Receipts</relationshipLabel>
    <relationshipName>Event_Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Receipt__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <formula>DATEVALUE(  LastModifiedDate )</formula>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event_Receipt__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <label>Mobile No</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Event_Receipt__c/fields/Outstanding_Balance__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance__c</fullName>
    <formula>Total__c - Deposit__c</formula>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event_Receipt__c/fields/Promoter_Note__c.field-meta.xml
<CustomField>
    <fullName>Promoter_Note__c</fullName>
    <label>Promoter Note</label>
    <length>25555</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event_Receipt__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <summarizedField>Event_Sales__c.Sub_Total__c</summarizedField>
    <summaryForeignKey>Event_Sales__c.Event_Receipt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Event_Sales__c/Event_Sales__c.object-meta.xml
<CustomObject>
    <label>Event Sales</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Event Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Sales__c/fields/Event_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Event_Receipt__c</fullName>
    <label>Event Receipt</label>
    <referenceTo>Event_Receipt__c</referenceTo>
    <relationshipLabel>Event Sales</relationshipLabel>
    <relationshipName>Event_Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Sales__c/fields/PDF_Index__c.field-meta.xml
<CustomField>
    <fullName>PDF_Index__c</fullName>
    <label>PDF Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Sales__c/fields/PDF_Item__c.field-meta.xml
<CustomField>
    <fullName>PDF_Item__c</fullName>
    <formula>IF( RecordType.DeveloperName == &apos;Discount&apos;, 

 IF( ISBLANK(  Product__c ), &apos;Discount：&apos; &amp;  Description__c  , &apos;Discount：&apos; &amp; Product_Show__r.Name ) ,  

IF( RecordType.DeveloperName == &apos;Warranty&apos;, &apos;Warranty：&apos; &amp; Product_Show__r.Name,Product_Show__r.Name ) )</formula>
    <label>PDF Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Sales__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event_Sales__c/fields/Warranty_price_increase__c.field-meta.xml
<CustomField>
    <fullName>Warranty_price_increase__c</fullName>
    <label>Warranty price increase</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event_Sales__c/recordTypes/Warranty.recordType-meta.xml
<RecordType>
    <fullName>Warranty</fullName>
    <active>true</active>
    <label>Warranty</label>
</RecordType>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Event Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Company_Information__c.field-meta.xml
<CustomField>
    <fullName>Company_Information__c</fullName>
    <label>Company Information</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST(%)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Terms_Condition__c.field-meta.xml
<CustomField>
    <fullName>Terms_Condition__c</fullName>
    <label>Terms &amp; Condition</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/EventReceiptPrintPDFController.cls
/*
 * @Author: WFC
 * @Date: 2025-03-05 09:38:23
 * @LastEditors: WFC
 * @LastEditTime: 2025-10-31 14:06:53
 * @Description: Event Receipt 打印PDF
 * @FilePath: \testuat\force-app\main\default\classes\EventReceiptPrintPDFController.cls
 */
public without sharing class EventReceiptPrintPDFController{
    public Event_Receipt__c eventReceipt{ get; set; }

    public Events__c events{ get; set; }

    public String dateFormatString{ get; set; }

    public List<Event_Sales__c> eventSalesList{ get; set; }

    public Decimal gst{ get; set; }

    public Decimal gstTotalShow{ get; set; }

    public Decimal totalShow{ get; set; }

    public Boolean nextPage{ get; set; }

    public Boolean showBalance{ get; set; }

    public static String warranty = Schema.SobjectType.Event_Sales__c.getRecordTypeInfosByDeveloperName().get('Warranty').getRecordTypeId();
    public EventReceiptPrintPDFController(){
        System.debug('wwww---EventReceiptPrintPDFController starts...');
        // 获取 id
        String eventReceiptId = ApexPages.CurrentPage().getParameters().get('ID');
        System.debug('wwww---eventReceiptId:' + eventReceiptId);
        Set<String> localeSet = new Set<String>{ 'zh_SG', 'fr_FR' };
        String userLocale = UserInfo.getLocale();
        System.debug('wwwwww-----' + userLocale);
        if (localeSet.contains(userLocale)){
            dateFormatString = 'dd-MM-yyyy';
        } else{
            dateFormatString = 'yyyy-MM-dd';
        }
        eventReceipt = [SELECT Id, Name, Event_Subject__c, Customer_Name__c, Invoice_date__c, Address__c, Mobile_Number__c, CurrencyIsoCode, Total__c, Event_Subject__r.GST__c, Promoter_Note__c, Deposit__c, Outstanding_Balance__c
                        FROM Event_Receipt__c
                        WHERE Id = :eventReceiptId
                        LIMIT 1];
        events = [SELECT Id, Company_Information__c, Terms_Condition__c
                  FROM Events__c
                  WHERE Id = :eventReceipt.Event_Subject__c
                  LIMIT 1];
        eventSalesList = [SELECT Id, Quantity__c, Unit_Price__c, Sub_Total__c, PDF_Index__c, PDF_Item__c, RecordTypeId, Warranty_price_increase__c
                          FROM Event_Sales__c
                          WHERE Event_Receipt__c = :eventReceiptId
                          ORDER BY Name];
        Integer i = 1;
        for (Event_Sales__c eventSales : eventSalesList){
            eventSales.PDF_Index__c = i;
            if (eventSales.RecordTypeId == warranty){
                eventSales.Unit_Price__c = eventSales.Warranty_price_increase__c;
            }
            i++;
        }
        if (eventReceipt.Total__c != null && eventReceipt.Event_Subject__r.GST__c != null){
            Decimal total = eventReceipt.Total__c;
            gst = eventReceipt.Event_Subject__r.GST__c;
            gstTotalShow = (total / (1 + gst / 100) * gst / 100).divide(1, 2);
            totalShow = total.divide(1, 2);
        }
        nextPage = false;
        showBalance = true;
        if(eventReceipt.Outstanding_Balance__c == 0){
            showBalance = false;
        }
        if (String.isNotBlank(events.Terms_Condition__c)){
            nextPage = true;
        }

        ApexPages.currentPage().getHeaders().put('content-disposition', '; filename=' + eventReceipt.Name + '_' + Datetime.now().format('yyyyMMdd') + '.pdf');
    }

    @AuraEnabled
    public static Map<String, String> downloadFile(String recordId){
        Map<String, String> resultMap = new Map<String, String>();

        Event_Receipt__c eventReceipt = [SELECT Id, Name, Event_Subject__c, Customer_Name__c, Invoice_date__c, Address__c, Mobile_Number__c, CurrencyIsoCode, Total__c, Event_Subject__r.GST__c, Promoter_Note__c
                                         FROM Event_Receipt__c
                                         WHERE Id = :recordId
                                         LIMIT 1];
        try{
            // 查询现有 ContentDocument 记录
            List<ContentDocument> cdList = [SELECT Id
                                            FROM ContentDocument
                                            WHERE LatestPublishedVersion.Download_Key__c = :recordId];
            // 删除ContentDocument数据
            if (cdList != null && cdList.size() > 0){
                delete cdList;
            }
            // 获取Visualforce Page的PDF内容
            PageReference pdfPage = Page.EventReceiptPDFPage;
            pdfPage.getParameters().put('ID', recordId);
            Blob pdfBlob;
            if (Test.isRunningTest()){
                pdfBlob = Blob.valueOf('Test');
            } else{
                pdfBlob = pdfPage.getContentAsPDF();
            }

            // 创建File对象
            ContentVersion file = new ContentVersion(
                Title = eventReceipt.Name + '_' + Datetime.now().format('yyyyMMdd'), 
                PathOnClient = eventReceipt.Name + '_' + Datetime.now().format('yyyyMMdd') + '.pdf', 
                VersionData = pdfBlob, 
                FirstPublishLocationId = recordId, 
                IsMajorVersion = true, 
                Download_Key__c = recordId
            );
            insert file;

            ContentVersion qrcv = [SELECT Id, ContentDocumentId
                                   FROM ContentVersion
                                   WHERE Id = :file.Id];

            resultMap.put('ContentDocumentId', qrcv.ContentDocumentId);
        } catch (Exception e){
            throw new AuraHandledException('PDF生成失败: ' + e.getMessage());
        }

        return resultMap;
    }

}