force-app/main/default/objects/Inspection_Shop_Plan__c/Inspection_Shop_Plan__c.object-meta.xml
<CustomObject>
    <label>Inspection Plan</label>
    <nameField>
        <displayFormat>ISP-{YYYY}{MM}{0000}</displayFormat>
        <label>计划编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <label>所有人Id（后台使用）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InspectionShopPlanrHandler.cls
/**********************************************************************
* 名称: InspectionShopPlanrHandler
* 功能: 
* 巡店计划trigger
* Author: Gerry
* Create Date: 2021-12-14
*************************************************************************/
public without sharing class InspectionShopPlanrHandler implements Triggers.Handler {
	public void handle() {
		if (Trigger.isBefore && (Trigger.isInsert||Trigger.isUpdate)) {
			System.debug('进入了');
			//赋值ownerId 供重复规则使用
			for (Inspection_Shop_Plan__c shopPlan : (List<Inspection_Shop_Plan__c>)Trigger.new) {
				shopPlan.OwnerId__c = shopPlan.OwnerId;		
			}	
		}
	}    
}