force-app/main/default/objects/Inspection_Shop_Plan__c/Inspection_Shop_Plan__c.object-meta.xml
<CustomObject>
    <label>Inspection Plan</label>
    <nameField>
        <displayFormat>ISP-{YYYY}{MM}{0000}</displayFormat>
        <label>计划编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Task__c/Inspection_Shop_Task__c.object-meta.xml
<CustomObject>
    <label>Inspection Task</label>
    <nameField>
        <displayFormat>IST-{YYYY}{MM}{0000}</displayFormat>
        <label>任务编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Shop_Task__c/fields/Inspection_Plan__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店计划</label>
    <referenceTo>Inspection_Shop_Plan__c</referenceTo>
    <relationshipLabel>Inspection Tasks</relationshipLabel>
    <relationshipName>Inspection_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>巡店计划的状态，包括已拜访、未拜访和计划外拜访三种</description>
    <inlineHelpText>Status of store visit, including visited, unvisited and unschedule visit.</inlineHelpText>
    <label>状态</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>已到访</fullName>
                <label>Visited</label>
            </value>
            <value>
                <fullName>未到访</fullName>
                <default>true</default>
                <label>Unvisited</label>
            </value>
            <value>
                <fullName>计划外到访</fullName>
                <label>Unscheduled Visit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>In Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InspectionShopTaskTriggerHandlerHelper.cls
/**********************************************************************
* Name: InspectionShopTaskTriggerHandlerHelper
* Object: Inspection_Shop_Task__c
* Purpose: InspectionShopTaskTriggerHandlerHelper
* Author: yong
* Create Date: 2023-07-17
*************************************************************************/
public with sharing class InspectionShopTaskTriggerHandlerHelper {
    /*
    * Name: insertLimits
    * Purpose: 巡店计划在审批中时不能创建巡店任务
    * Timing : before update
    * Author: yong
    * Create Date: 2023-07-17
    */
    public static void insertLimits(List<Inspection_Shop_Task__c> triggerOld,List<Inspection_Shop_Task__c> triggerNew){
        Set<String> planIdSet = new Set<String>();
        for(Inspection_Shop_Task__c ist:triggerNew){
            planIdSet.add(ist.Inspection_Plan__c);
        }
        for(Inspection_Shop_Plan__c isp : [SELECT Id,Name,Status__c FROM Inspection_Shop_Plan__c WHERE Id IN: planIdSet]){
            if(isp.Status__c != 'New' && isp.Status__c != 'Rejected' ){
                for(Inspection_Shop_Task__c ist:triggerNew){
                    if(ist.Inspection_Plan__c == isp.Id && ist.Status__c != '计划外到访'){
                        if(!Test.isRunningTest()){
                            ist.adderror(System.label.Inspection_Task_Create_Limits2);
                        }
                    }
                }
            }
        }
    }

    /*
    * Name: autoChangeOwner
    * Purpose: 巡店任务创建时，自动改变所有人为关联巡店计划所有人
    * Timing : before insert
    * Author: yong
    * Create Date: 2023-07-21
    */
    public static void autoChangeOwner(List<Inspection_Shop_Task__c> triggerOld,List<Inspection_Shop_Task__c> triggerNew){
        for(Inspection_Shop_Task__c ist:triggerNew){
            if(ist.Inspection_Plan__c != null  && ist.Inspection_Plan__r.OwnerId != null){
                ist.OwnerId = ist.Inspection_Plan__r.OwnerId;
            }
        }
    }
}