force-app/main/default/objects/Inspection_Shop_Plan__c/Inspection_Shop_Plan__c.object-meta.xml
<CustomObject>
    <label>Inspection Plan</label>
    <nameField>
        <displayFormat>ISP-{YYYY}{MM}{0000}</displayFormat>
        <label>计划编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Inspection_Month__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Month__c</fullName>
    <defaultValue>TEXT(MONTH( TODAY() ))</defaultValue>
    <label>计划月份</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Inspection_Year__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Year__c</fullName>
    <defaultValue>TEXT(YEAR( TODAY() ) )</defaultValue>
    <label>计划年份</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NatificationPlanSchedulableTest.cls
/**
 * @description       : 
 * @author            : chenpeng@deloitte.com.cn
 * @group             : 
 * @last modified on  : 03-29-2022
 * @last modified by  : chenpeng@deloitte.com.cn
**/
@isTest
public class NatificationPlanSchedulableTest {
    public static String CRON_EXP = '0 0 1 * * ?';
    static testMethod void stestNatificationPlanSchedulable(){
        String profileName = '巡店员'; 
        Id profileId = [SELECT Id FROM profile WHERE Name = :profileName][0].Id;
        User user1 = new User(alias = '巡店员', email='test123@noemail.com',
        emailencodingkey='UTF-8', lastname='Testing123', languagelocalekey='en_US',
        localesidkey='en_US', profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='test123@noemail.com');
        INSERT user1;
        
        Date today = System.today();
        today = today.addMonths(1);
        Inspection_Shop_Plan__c isp = new Inspection_Shop_Plan__c();
        isp.Inspection_Year__c = String.valueOf(today.year());
        isp.Inspection_Month__c = String.valueOf(today.month());
        isp.OwnerId = user1.Id;
        // INSERT isp;
        test.startTest();
        
        System.schedule('Test my class',CRON_EXP,new NatificationPlanSchedulable());
        test.stopTest();

    }
    
}