force-app/main/default/objects/Inspection_Shop_Plan__c/Inspection_Shop_Plan__c.object-meta.xml
<CustomObject>
    <label>Inspection Plan</label>
    <nameField>
        <displayFormat>ISP-{YYYY}{MM}{0000}</displayFormat>
        <label>计划编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Plan_Approver1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Plan_Approver2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Inspection_Month__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Month__c</fullName>
    <defaultValue>TEXT(MONTH( TODAY() ))</defaultValue>
    <label>计划月份</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Inspection_Year__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Year__c</fullName>
    <defaultValue>TEXT(YEAR( TODAY() ) )</defaultValue>
    <label>计划年份</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <label>所有人Id（后台使用）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <formula>TEXT( CreatedBy.Sales_Region__c )</formula>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Plan__c/fields/Submiter__c.field-meta.xml
<CustomField>
    <fullName>Submiter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submiter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>InspectionShopPlan_Submiter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/InterfaceLog__c.object-meta.xml
<CustomObject>
    <label>InterfaceLog</label>
    <nameField>
        <label>No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InterfaceLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InterfaceLog__c/fields/ErrorMsg__c.field-meta.xml
<CustomField>
    <fullName>ErrorMsg__c</fullName>
    <label>ErrorMsg</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/Req_Json__c.field-meta.xml
<CustomField>
    <fullName>Req_Json__c</fullName>
    <label>Req Json</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/ReturnCode__c.field-meta.xml
<CustomField>
    <fullName>ReturnCode__c</fullName>
    <label>ReturnCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>In Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendInspectionPlanToBigData.cls
/**********************************************************************
 * function:将Inspection Plan推送给大数据
 * @author:lizunxing
 * @url: /services/apexrest
 * @data: 
 * date:2024-01-31
*************************************************************************/
@RestResource(urlMapping='/SendInspectionPlanToBigData')
global with sharing class SendInspectionPlanToBigData{  

    global class AppInput{
        public String startTime; 
        public String endTime; 
        public String pageIndex;
        public String pageSize;
    }
    global class AppOutPut{
        public Integer totalPage;
        List<InspectionPlanInfo> inspectionPlanInfoList;
    }

    public class InspectionPlanInfo {
        public String id;
        public String Name;
        public String CreatedDate;
        public String LastModifiedDate;
        public String Approver1;
        public String Approver2;
        public String InspectionMonth;
        public String InspectionYear;
        public String IsExport;
        public String OwnerId;
        public String SalesRegion;
        public String Status;
        public String Submiter;
    }

    @HttpPost
    global static SendInspectionPlanToBigData.AppOutPut adoPost() {

        RestRequest req = RestContext.request;
        String reqBody = req.requestBody.tostring(); 
        //String reqBody = '{"startTime":"2024-01-09 00:00:00","endTime":"2024-01-10 00:00:00"}'; 
        SendInspectionPlanToBigData.AppInput appInput = new SendInspectionPlanToBigData.AppInput();
        
        SendInspectionPlanToBigData.AppOutPut result = new SendInspectionPlanToBigData.AppOutPut();
        
        try{
            appInput = (SendInspectionPlanToBigData.AppInput)JSON.deserialize(reqBody, SendInspectionPlanToBigData.AppInput.class);

            if(String.isBlank(appInput.startTime) || String.isBlank(appInput.endTime)){
                return result;
            }

            if(String.isBlank(appInput.pageIndex)){
                appInput.pageIndex = '1';
            }

            if(String.isBlank(appInput.pageSize) || Integer.valueOf(appInput.pageSize) < 200){
                appInput.pageSize = '200';
            }

            appInput.startTime = Utility.increaseHoursInStringDate(appInput.startTime,8).replace(' ','T') + '.000+0000';
            appInput.endTime = Utility.increaseHoursInStringDate(appInput.endTime,8).replace(' ','T') + '.000+0000';

            String sql = 'select '+
            'id,'+
            'Name,'+
            'CreatedDate,'+
            'LastModifiedDate,'+
            'Approver1__c,'+
            'Approver2__c,'+
            'Inspection_Month__c,'+
            'Inspection_Year__c,'+
            'Is_Export__c,'+
            'OwnerId__c,'+
            'Sales_Region__c,'+
            'Status__c,'+
            'Submiter__c'+

            ' from Inspection_Shop_Plan__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            //List<Inspection_Shop_Plan__c> InspectionPlanList = (List<Inspection_Shop_Plan__c>)Utility.getRecordListPage(sql, appInput.pageIndex, appInput.pageSize);
            List<Inspection_Shop_Plan__c> InspectionPlanList = Utility.apexPagination(Database.query(sql), Integer.valueOf(appInput.pageIndex), Integer.valueOf(appInput.pageSize));
            List<InspectionPlanInfo> InspectionPlanInfoList = new List<InspectionPlanInfo>();

            for(Inspection_Shop_Plan__c a : InspectionPlanList){
                InspectionPlanInfo c = new InspectionPlanInfo();
                c.id = checkNull(a.id + '');
                c.Name = a.Name;
                c.CreatedDate = checkNull(a.CreatedDate + '');
                c.LastModifiedDate = checkNull(a.LastModifiedDate + '');
                c.Approver1 = checkNull(a.Approver1__c + '');
                c.Approver2 = checkNull(a.Approver2__c + '');
                c.InspectionMonth = checkNull(a.Inspection_Month__c + '');
                c.InspectionYear = checkNull(a.Inspection_Year__c + '');
                c.IsExport = checkNull(a.Is_Export__c + '');
                c.OwnerId = checkNull(a.OwnerId__c + '');
                c.SalesRegion = checkNull(a.Sales_Region__c + '');
                c.Status = checkNull(a.Status__c + '');
                c.Submiter = checkNull(a.Submiter__c + '');

                InspectionPlanInfoList.add(c);
            }
            result.InspectionPlanInfoList = InspectionPlanInfoList;
            String sql1 = 'select count(id) totalNumber from Inspection_Shop_Plan__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            List<AggregateResult> c = Database.query(sql1);
            result.totalPage = (Integer.valueOf(c.get(0).get('totalNumber')) + Integer.valueOf(appInput.pageSize) - 1) / Integer.valueOf(appInput.pageSize);
           

            System.debug('result :' + result);
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendInspectionPlanToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '1';
            ic.Req_Json__c = reqBody;
            insert ic;

            return result; 
        }catch(Exception e){
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendInspectionPlanToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '0';
            ic.Req_Json__c = reqBody;
            ic.ErrorMsg__c = e.getMessage();
            insert ic;

            return result; 
        }
    }

    public static String checkNull(String str){
        if(String.isBlank(str)){
            return '';
        }else if('null'.equals(str)){
            return '';
        }else{
            return str;
        }
    }
}