force-app/main/default/objects/Actual_And_Same_Period_Report__c/Actual_And_Same_Period_Report__c.object-meta.xml
<CustomObject>
    <label>Actual And Same Period Report</label>
    <nameField>
        <displayFormat>APR{000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual And Same Period Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/IsChange__c.field-meta.xml
<CustomField>
    <fullName>IsChange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>*IsChange</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/Share_Account_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Share_Account_Product_Line__c</fullName>
    <formula>Customer__r.Customer_SF_Code__c + Product_Line__c</formula>
    <label>*Share Account Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/Daily_Inspection_Report__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>DIR-{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>巡店员日报编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>岗位</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>岗位编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>启用</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>只能包含字母数字字符，必须以字母开头，不能以下划线字符结尾或包含两个连续的下划线字符，而且在所有岗位中必须是唯一的;</inlineHelpText>
    <label>岗位小组名</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position__c/fields/Grouo_Name__c.field-meta.xml
<CustomField>
    <fullName>Grouo_Name__c</fullName>
    <label>岗位名</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/GroupId__c.field-meta.xml
<CustomField>
    <fullName>GroupId__c</fullName>
    <externalId>true</externalId>
    <label>岗位用户组ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Share_History__c/Share_History__c.object-meta.xml
<CustomObject>
    <label>Share History</label>
    <nameField>
        <displayFormat>SH-{YYYYMMDD}-{0000000000}</displayFormat>
        <label>Share History No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Share Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_History__c/fields/GroupId__c.field-meta.xml
<CustomField>
    <fullName>GroupId__c</fullName>
    <externalId>true</externalId>
    <label>GroupId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_History__c/fields/Is_New_Share__c.field-meta.xml
<CustomField>
    <fullName>Is_New_Share__c</fullName>
    <defaultValue>true</defaultValue>
    <label>*最新共享</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Share_History__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Share Histories</relationshipLabel>
    <relationshipName>Share_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Share_History__c/fields/Share_ID__c.field-meta.xml
<CustomField>
    <fullName>Share_ID__c</fullName>
    <externalId>true</externalId>
    <label>Share ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Share_History__c/fields/Share_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Share_Object_Name__c</fullName>
    <label>Share Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/Share_Object__c.object-meta.xml
<CustomObject>
    <label>共享对象</label>
    <nameField>
        <label>共享对象名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>共享对象</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_Object__c/fields/Account_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Account_Product_Line__c</fullName>
    <inlineHelpText>目标对象中的: 客户SF编码 + 产品线  类型:文本/公式文本</inlineHelpText>
    <label>客户产品线字段API名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Object_API__c.field-meta.xml
<CustomField>
    <fullName>Object_API__c</fullName>
    <inlineHelpText>要与用户共享的对象API名, 自定义对象需__c后缀</inlineHelpText>
    <label>共享对象API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Object_Share__c.field-meta.xml
<CustomField>
    <fullName>Object_Share__c</fullName>
    <description>填写该对象对应的Share对象名称</description>
    <externalId>true</externalId>
    <inlineHelpText>填写该对象对应的Share对象名称</inlineHelpText>
    <label>共享对象_ShareAPI</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Refresh_Query_Statement__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Query_Statement__c</fullName>
    <label>岗位刷新查询语句</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Share_Object__c/fields/Share_Type__c.field-meta.xml
<CustomField>
    <fullName>Share_Type__c</fullName>
    <label>共享类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Share_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Share_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>WhoId</fullName>
    </customValue>
    <customValue>
        <fullName>WhatId</fullName>
    </customValue>
    <customValue>
        <fullName>ParentId</fullName>
    </customValue>
    <masterLabel>共享类型</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ShareInsertShareHistoryBatchTest.cls
/**
 * @description       : 
 * @author            : ryshen@deloitte.com.cn
 * @group             : 
 * @last modified on  : 03-18-2022
 * @last modified by  : chenpeng@deloitte.com.cn
**/
@isTest
public class ShareInsertShareHistoryBatchTest {
    public static Position__c pos;
    public static List<String> shareObjectList;
    public static List<String> shareObjectList2;
    public static User user1;

    private static void makedata(){
        Id profileId = [SELECT Id FROM profile WHERE Name = '系统管理员' OR Name = 'System Administrator'][0].Id;
        user1 = new User(alias = 'Admin', email='test123@noemail.com',
        emailencodingkey='UTF-8', lastname='Testing123', languagelocalekey='en_US',
        localesidkey='en_US', profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='test123@noemail.com');
        INSERT user1;

        pos = new Position__c();
        pos.DeveloperName__c = 'FU_GUAN_PATROLCLERKTEST';
        pos.Grouo_Name__c = '福关网格巡店员TEST';
        pos.Activity__c = true;
        INSERT pos;

        Share_Object__c shareObject = new Share_Object__c(Name = 'Actual And Same Period Report',
                                        Object_API__c = 'Actual_And_Same_Period_Report__c',
                                        Object_Share__c = 'Actual_And_Same_Period_Report__Share',
                                        Account_Product_Line__c = 'Share_Account_Product_Line__c',
                                        Share_Type__c = 'ParentId',
                                        Refresh_Query_Statement__c = 'SELECT IsNew__c,IsChange__c,Share_Account_Product_Line__c,Daily_Inspection_Report__c FROM Actual_And_Same_Period_Report__c '
        );
        INSERT shareObject;

        Actual_And_Same_Period_Report__c apr = new Actual_And_Same_Period_Report__c();
        INSERT apr;

        Actual_And_Same_Period_Report__Share aprShare = new Actual_And_Same_Period_Report__Share();
        aprShare.RowCause = 'Manual';
        aprShare.ParentId = apr.Id;
        aprShare.UserOrGroupId  = user1.Id;
        aprShare.AccessLevel = 'Read';
        INSERT aprShare;

        Position__c queryShareObj = [SELECT Id, GroupId__c FROM Position__c WHERE Id = :pos.Id];

        Share_History__c sh = new Share_History__c();
        sh.Position__c = pos.Id;
        sh.Share_Object_Name__c = shareObject.Object_API__c;
        sh.Is_New_Share__c = False;
        sh.Share_ID__c = pos.Id;
        sh.GroupId__c = user1.Id;
        INSERT sh;

        shareObjectList = new List<String>();
        shareObjectList.add(shareObject.Object_Share__c);

        shareObjectList2 = new List<String>();
        shareObjectList2.add(shareObject.Object_Share__c);
        shareObjectList2.add(shareObject.Object_Share__c);
    }
    @isTest
    static void testShareInsertShareHistoryBatch1(){
        makedata();
        Test.startTest();
        Position__c queryShareObj = [SELECT Id, GroupId__c FROM Position__c WHERE Id = :pos.Id];
        ShareInsertShareHistoryBatch theBatch = new ShareInsertShareHistoryBatch(
            queryShareObj.Id,
            user1.Id, 
            shareObjectList,
            false
        );
        Database.executeBatch(theBatch, 1);
        Test.stopTest();
    }

    @isTest
    static void testShareInsertShareHistoryBatch2(){
        makedata();
        Test.startTest();
        Position__c queryShareObj = [SELECT Id, GroupId__c FROM Position__c WHERE Id = :pos.Id];
        ShareInsertShareHistoryBatch theBatch = new ShareInsertShareHistoryBatch(
            queryShareObj.Id,
            user1.Id, 
            shareObjectList,
            true
        );
        Database.executeBatch(theBatch, 1);
        Test.stopTest();
    }

    // @isTest
    // static void testShareInsertShareHistoryBatch3(){
    //     makedata();
    //     Test.startTest();
    //     ShareInsertShareHistoryBatch batch2 = new ShareInsertShareHistoryBatch(pos.Id,pos.Id,shareObjectList2,false);
    //     Database.executeBatch(batch2);
    //     Test.stopTest();
        
    // }
}