force-app/main/default/objects/Actual_And_Same_Period_Report__c/Actual_And_Same_Period_Report__c.object-meta.xml
<CustomObject>
    <label>Actual And Same Period Report</label>
    <nameField>
        <displayFormat>APR{000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual And Same Period Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/Current_Gross__c.field-meta.xml
<CustomField>
    <fullName>Current_Gross__c</fullName>
    <label>MTD Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/Current_Gross_USD__c.field-meta.xml
<CustomField>
    <fullName>Current_Gross_USD__c</fullName>
    <label>MTD Gross Amount(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/Current_Net__c.field-meta.xml
<CustomField>
    <fullName>Current_Net__c</fullName>
    <label>MTD Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/Current_Net_USD__c.field-meta.xml
<CustomField>
    <fullName>Current_Net_USD__c</fullName>
    <label>MTD Net Amount(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/Current_Sales_Volume__c.field-meta.xml
<CustomField>
    <fullName>Current_Sales_Volume__c</fullName>
    <label>MTD Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Actual And Same Period Report</relationshipLabel>
    <relationshipName>Actual_And_Same_Period_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/N_Month_Gross_N_Year__c.field-meta.xml
<CustomField>
    <fullName>N_Month_Gross_N_Year__c</fullName>
    <label>Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/N_Month_Gross_USD_N_Year__c.field-meta.xml
<CustomField>
    <fullName>N_Month_Gross_USD_N_Year__c</fullName>
    <label>Gross Amount(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/N_Month_Net_N_Year__c.field-meta.xml
<CustomField>
    <fullName>N_Month_Net_N_Year__c</fullName>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/N_Month_Net_USD_N_Year__c.field-meta.xml
<CustomField>
    <fullName>N_Month_Net_USD_N_Year__c</fullName>
    <label>Net Amount(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/N_Month_Sales_Volume_N_Year__c.field-meta.xml
<CustomField>
    <fullName>N_Month_Sales_Volume_N_Year__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actual_And_Same_Period_Report__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>TEXT(Customer_Product_Line__r.Product_Line_Name__c)</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>SAP发票</label>
    <nameField>
        <displayFormat>I{0000000000}</displayFormat>
        <label>Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Posting_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Posting_Date__c</fullName>
    <label>Invoice Posting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>IL{0000000000}</displayFormat>
        <label>Invoice Line No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipName>Invoice_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Amount__c</fullName>
    <label>Invoice Amount(Ex Vat)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Invoice_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Quantity__c</fullName>
    <label>Invoice Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Total_Amount_After_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_After_Rebate__c</fullName>
    <label>Invoice Net Amount(After Rebate)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoiceSummaryBatch.cls
/**************************************************************************************************
 * Name:InvoiceSummaryBatch
 * Purpose: 发票数据汇总到实际同期报表上
 * Author: Deloitte Johnson
 * Create Date: 2019-07-31
***************************************************************************************************/
global class InvoiceSummaryBatch implements Database.Batchable<sObject> {
    public String query;
    public String year;
    public String month;
    public Date startDate;//当月第一天
    public Date endDate;//当月最后一天
    public static Map<String, Decimal> currencyRateMap = Utility.getCurrencyRateHistoryMap();
    //public Set<String> accIdSet = new Set<String>{'0010p000009o6X0AAI','0010p000009o5mbAAA','0010p000009o5lSAAQ'};

    global InvoiceSummaryBatch(String year,String month) {
        this.year = year;
        this.month = month;
        if (Integer.valueOf(this.month) < 10) {
            this.month = '0'+this.month;
        }
        //根据过账日期找出当月所有的发票行数据
        startDate = Date.valueOf(this.year + '-' + this.month + '-' + '01');
        endDate = startDate.addMonths(1);
        this.query = 'SELECT Invoice__r.Customer__c,Product_Line__c,CurrencyIsoCode,Invoice_Amount__c,Total_Amount_After_Rebate__c,Invoice_Quantity__c'+
                     ' FROM Invoice_Item__c WHERE Invoice__r.Invoice_Posting_Date__c >=:startDate AND Invoice__r.Invoice_Posting_Date__c <:endDate '+
                     ' AND Invoice__r.Customer__c !=null AND Product_Line__c != null';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('query： ' +query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Invoice_Item__c> invoiceItemList) {
        Set<String> aprExternalIDSet = new Set<String>();
        try{
            for(Invoice_Item__c invoiceItem : invoiceItemList){
                String aprExternalID = year + month + invoiceItem.Invoice__r.Customer__c + invoiceItem.Product_Line__c;
                aprExternalIDSet.add(aprExternalID);
            }
            String queryAPR = 'SELECT Id,External_ID__c,CurrencyIsoCode,Current_Net__c, Current_Gross__c, Current_Net_USD__c,Current_Gross_USD__c,Current_Sales_Volume__c,' +
                              ' N_Month_Gross_N_Year__c,N_Month_Net_N_Year__c,N_Month_Gross_USD_N_Year__c,N_Month_Net_USD_N_Year__c,N_Month_Sales_Volume_N_Year__c'+
                              ' FROM Actual_And_Same_Period_Report__c WHERE External_ID__c IN:aprExternalIDSet';
            List<Actual_And_Same_Period_Report__c> updateAPRList = Database.query(queryAPR);
            Map<String,Actual_And_Same_Period_Report__c> updateAPRMap = new Map<String,Actual_And_Same_Period_Report__c>();
            for(Actual_And_Same_Period_Report__c updateAPR : updateAPRList){
                updateAPRMap.put(updateAPR.External_ID__c, updateAPR);
            }
            for(Invoice_Item__c invoiceItem : invoiceItemList){
                String aprExternalID = year + month + invoiceItem.Invoice__r.Customer__c + invoiceItem.Product_Line__c;
                if(updateAPRMap.containsKey(aprExternalID)){
                    Actual_And_Same_Period_Report__c updateAPR = updateAPRMap.get(aprExternalID);
                    //根据年月+币种得到发票币种的汇率以及实际同期币种的汇率
                    String rateYearMonth = year + month;
                    //销售组织的汇率
                    Decimal rate = currencyRateMap.get(updateAPR.CurrencyIsoCode + rateYearMonth);
                    //发票币种的汇率
                    Decimal rate1 = currencyRateMap.get(invoiceItem.CurrencyIsoCode + rateYearMonth);
                    if(Test.isRunningTest()){
                        rate = 1;rate1 = 1;
                    }
                    //根据换算过后的收入成本数据更新实际同期字段
                    if(updateAPR.CurrencyIsoCode.equals(invoiceItem.CurrencyIsoCode)){
                        updateAPR.N_Month_Gross_N_Year__c = convertNull(updateAPR.N_Month_Gross_N_Year__c) + convertNull(invoiceItem.Invoice_Amount__c);
                        updateAPR.N_Month_Net_N_Year__c = convertNull(updateAPR.N_Month_Net_N_Year__c) + convertNull(invoiceItem.Total_Amount_After_Rebate__c);
                    }else{
                        updateAPR.N_Month_Gross_N_Year__c = convertNull(updateAPR.N_Month_Gross_N_Year__c) + convertNull(invoiceItem.Invoice_Amount__c) / rate1 * rate;
                        updateAPR.N_Month_Net_N_Year__c = convertNull(updateAPR.N_Month_Net_N_Year__c) + convertNull(invoiceItem.Total_Amount_After_Rebate__c) / rate1 * rate;
                    }
                    updateAPR.N_Month_Gross_USD_N_Year__c = convertNull(updateAPR.N_Month_Gross_USD_N_Year__c) + convertNull(invoiceItem.Invoice_Amount__c) / rate1;
                    updateAPR.N_Month_Net_USD_N_Year__c = convertNull(updateAPR.N_Month_Net_USD_N_Year__c) + convertNull(invoiceItem.Total_Amount_After_Rebate__c) / rate1;
                    updateAPR.N_Month_Sales_Volume_N_Year__c = convertNull(updateAPR.N_Month_Sales_Volume_N_Year__c) + convertNull(invoiceItem.Invoice_Quantity__c);
                }
                
            }
            //更新实际同期报表的相关字段数据
            update updateAPRMap.values();
        }catch(Exception e){
            system.debug('error message: '+e.getMessage());
            system.debug('line number: '+e.getLineNumber());
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
    //转换'' to 0
    private static Decimal convertNull(Decimal num) {
        Decimal strConvert;
        if(num == null) {
            strConvert = 0;
        }else{
            strConvert = num;
        } 
        return strConvert;
    }
}