force-app/main/default/objects/Customer_Address__c/Customer_Address__c.object-meta.xml
<CustomObject>
    <label>Customer Address</label>
    <nameField>
        <label>Customer Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Address__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>sold-to</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.SAP_Customer_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Addresses</relationshipLabel>
    <relationshipName>Customer_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Email__c/Customer_Email__c.object-meta.xml
<CustomObject>
    <label>Customer Email</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Email__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Emails</relationshipLabel>
    <relationshipName>Customer_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Email__c/fields/Customer_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Address</label>
    <referenceTo>Customer_Address__c</referenceTo>
    <relationshipLabel>Customer Emails</relationshipLabel>
    <relationshipName>Customer_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Email__c/fields/External_key__c.field-meta.xml
<CustomField>
    <fullName>External_key__c</fullName>
    <label>External key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Email__c/fields/No__c.field-meta.xml
<CustomField>
    <fullName>No__c</fullName>
    <label>No</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GlobalSetting__c/GlobalSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>全局设置</label>
</CustomObject>

force-app/main/default/classes/CustomerEmailTriggerHandler.cls
public class CustomerEmailTriggerHandler implements Triggers.Handler{
    
    public void handle() {
        List<Customer_Email__c> emailList = new List<Customer_Email__c>(); 

        if (Trigger.isBefore && Trigger.isInsert) {
            for (Customer_Email__c acc : ((list<Customer_Email__c>)Trigger.new)) {
                
                if(String.isNotBlank(acc.Customer__c)){
                    acc.External_key__c = acc.Customer__c + '_' + acc.Email__c;
                }else if(String.isNotBlank(acc.Customer_Address__c)){
                    acc.External_key__c = acc.Customer_Address__c + '_' + acc.Email__c;
                }else{
                    acc.addError('Customer cannot be empty.');
                    return;
                }
            }  
        }

        if (Trigger.isAfter && Trigger.isInsert) {
            for (Customer_Email__c acc : ((list<Customer_Email__c>)Trigger.new)) {
                
                if(String.isNotBlank(acc.Customer__c)){
                    emailList = [select id, No__c from  Customer_Email__c where Customer__c = :acc.Customer__c order by No__c asc, CreatedDate desc];
                }else{
                    emailList = [select id, No__c from  Customer_Email__c where Customer_Address__c =:acc.Customer_Address__c order by No__c asc, CreatedDate desc];
                }
                sortNo(emailList);
              
            }  
        }

        if (Trigger.isAfter && Trigger.isUpdate) {
            for (Customer_Email__c acc : ((list<Customer_Email__c>)Trigger.new)) {
                Customer_Email__c accOld = (Customer_Email__c)Trigger.oldMap.get(acc.Id);
                if(accOld.No__c != acc.No__c){
                    if(String.isNotBlank(acc.Customer__c)){
                        emailList = [select id, No__c from  Customer_Email__c where Customer__c = :acc.Customer__c order by No__c asc, CreatedDate desc];
                    }else{
                        emailList = [select id, No__c from  Customer_Email__c where Customer_Address__c =:acc.Customer_Address__c order by No__c asc, CreatedDate desc];
                    }
                    sortNo(emailList);
                }
            }  
        }

        if (Trigger.isAfter && Trigger.isDelete) {
        
            for (Customer_Email__c acc : ((list<Customer_Email__c>)Trigger.old)) {
                
                if(String.isNotBlank(acc.Customer__c)){
                    emailList = [select id, No__c from  Customer_Email__c where Customer__c = :acc.Customer__c order by No__c asc, CreatedDate desc];
                }else{
                    emailList = [select id, No__c from  Customer_Email__c where Customer_Address__c =:acc.Customer_Address__c order by No__c asc, CreatedDate desc];
                }

                sortNo(emailList);

            }
        }
    }

    public static void sortNo(List<Customer_Email__c> ceList){
        Integer index = 1;
        for(Customer_Email__c ce : ceList){
            ce.No__c = index++;
        }

        //忽略触发器更新
        GlobalSetting__c ignoreGs = Utility.IgnoreAction(true, true, true, 'CustomerEmailTriggerHandler');

        if(!Test.isRunningTest()){
            update ceList;
        }
        
        //恢复触发器
        Utility.IgnoreAction(false,false,false,'');


    }
}