force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <displayFormat>ST-{00000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Real_Time_Inventory__c/Real_Time_Inventory__c.object-meta.xml
<CustomObject>
    <label>Real Time Inventory</label>
    <nameField>
        <label>Real-time Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Real Time Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Real_Time_Inventory__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Real Time Inventory</relationshipLabel>
    <relationshipName>Real_Time_Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Real_Time_Inventory__c/fields/Inventory_Date__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Date__c</fullName>
    <label>Inventory Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Real_Time_Inventory__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>日期-客户-产品</description>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Real_Time_Inventory__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <formula>TEXT(Customer__r.Sales_Region__c )</formula>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Real_Time_Inventory__c/fields/Sell_In_Number__c.field-meta.xml
<CustomField>
    <fullName>Sell_In_Number__c</fullName>
    <label>Sell In Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Real_Time_Inventory__c/fields/Sell_In_Sub_Out__c.field-meta.xml
<CustomField>
    <fullName>Sell_In_Sub_Out__c</fullName>
    <formula>Sell_In_Number__c - Sell_Out_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sell In Sub Out</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Real_Time_Inventory__c/fields/Sell_Out_Number__c.field-meta.xml
<CustomField>
    <fullName>Sell_Out_Number__c</fullName>
    <label>Sell Out Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/RealTimeInventoryReportBatch.cls
/*
 * @Author: WFC
 * @Date: 2024-01-15 13:43:09
 * @LastEditors: WFC
 * @LastEditTime: 2024-01-17 10:33:27
 * @Description: Database.executeBatch(new RealTimeInventoryReportBatch('Hisense South Africa', '2023-01-01'), 10);
 * @FilePath: \hisenseall-231026\force-app\main\default\classes\RealTimeInventoryReportBatch.cls
 */
global class RealTimeInventoryReportBatch implements Database.Batchable<sObject> {

    public String salesRegion;// 国家
    public Date orderDate;// 日期
    public String query;

    global RealTimeInventoryReportBatch (String salesRegion, String orderDate) {
        this.salesRegion = salesRegion;
        this.orderDate = Date.valueOf(orderDate);
        this.query = 'SELECT id, Sell_In_Number__c, Sell_Out_Number__c, Sell_In_Sub_Out__c, Inventory__c, Inventory_Date__c,Product_Name__c,Customer__c, Key__c   '+
                        ' FROM Real_Time_Inventory__c '+
                        ' WHERE Sales_Region__c  = :salesRegion '+
                        ' AND Inventory_Date__c = :orderDate ';
    }


    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Real_Time_Inventory__c> rtiList) {
        List<Real_Time_Inventory__c> updateList = new List<Real_Time_Inventory__c>();
        for(Real_Time_Inventory__c rti : rtiList){
            String accId = rti.Customer__c;
            String productName = rti.Product_Name__c;
            // 第一天库存赋值
            rti.Inventory__c = rti.Sell_In_Sub_Out__c;
            updateList.add(rti);
            List<Real_Time_Inventory__c> otherList = [SELECT id, Sell_In_Number__c, Sell_Out_Number__c, Sell_In_Sub_Out__c, Inventory__c
                                                        FROM Real_Time_Inventory__c
                                                        WHERE Customer__c = :accId AND Product_Name__c = :productName
                                                        AND id != :rti.Id
                                                        ORDER BY Inventory_Date__c];
            for(Integer i = 0; otherList.size() > i; i++){
                if(i == 0){
                    otherList[i].Inventory__c = rti.Inventory__c + otherList[i].Sell_In_Sub_Out__c;
                }else{
                    otherList[i].Inventory__c = otherList[i - 1].Inventory__c + otherList[i].Sell_In_Sub_Out__c;
                }
                updateList.add(otherList[i]);
            }
        }
        
        Database.upsert(updateList);
    }

    global void finish(Database.BatchableContext BC) {
        Utility.insertLog('RealTimeInventoryReportBatch', '1', this.salesRegion + '-' + this.orderDate, String.valueOf(Datetime.now()));
    }
}