force-app/main/default/objects/Responsible_Person__c/Responsible_Person__c.object-meta.xml
<CustomObject>
    <label>Responsible person</label>
    <nameField>
        <displayFormat>RP-{YYYY}{MM}{0000}</displayFormat>
        <label>门店负责人编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsible persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Responsible_Person__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>负责人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Responsible_Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>负责人类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>巡店员</fullName>
            </value>
            <value>
                <fullName>促销员</fullName>
            </value>
            <value>
                <fullName>Regional Manager</fullName>
                <label>区域经理</label>
            </value>
            <value>
                <fullName>Backup Floorwalker</fullName>
                <isActive>false</isActive>
                <label>Backup Floorwalker</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>门店名称</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Responsible_Person</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/Retail_Number__c.object-meta.xml
<CustomObject>
    <label>Daily Sales</label>
    <nameField>
        <displayFormat>RN-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>零售业绩编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Number__c/fields/ResponsiblePerson__c.field-meta.xml
<CustomField>
    <fullName>ResponsiblePerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible Person</label>
    <referenceTo>Responsible_Person__c</referenceTo>
    <relationshipLabel>Daily Sales</relationshipLabel>
    <relationshipName>Daily_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Retail_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Target_Report__c/Sales_Target_Report__c.object-meta.xml
<CustomObject>
    <description>东盟销售目标报表</description>
    <label>Sales Target Report</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Sales Target Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Target Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Target_Report__c/fields/Daily_Sales__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales__c</fullName>
    <label>Daily Sales</label>
    <referenceTo>Retail_Number__c</referenceTo>
    <relationshipLabel>Sales Target Report</relationshipLabel>
    <relationshipName>Sales_Target_Report</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Report__c/fields/Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Report__c/fields/Store_Inspection_Manage__c.field-meta.xml
<CustomField>
    <fullName>Store_Inspection_Manage__c</fullName>
    <label>Store Inspection Manage</label>
    <referenceTo>Store_Inspection_Manage__c</referenceTo>
    <relationshipLabel>Sales Target Report</relationshipLabel>
    <relationshipName>Sales_Target_Report</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Report__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Target_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店员</label>
    <referenceTo>User</referenceTo>
    <relationshipName>shops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Inspection_Manage__c/Store_Inspection_Manage__c.object-meta.xml
<CustomObject>
    <label>Store Inspection Manage</label>
    <nameField>
        <displayFormat>SIMN-{00000000}</displayFormat>
        <label>Store Inspection Manage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Inspection Manage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Inspection_Manage__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>用户id + &apos;-&apos; + 年 + &apos;-&apos; + 月 + &apos;-&apos; + 任务类型</description>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store_Inspection_Manage__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Store_Inspection_Manage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Inspection_Manage_Daily_Sales__c/Store_Inspection_Manage_Daily_Sales__c.object-meta.xml
<CustomObject>
    <label>Store Inspection Manage Daily Sales</label>
    <nameField>
        <displayFormat>SIMDS-{00000000}</displayFormat>
        <label>Store Inspection Manage Daily Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Inspection Manage Daily Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Inspection_Manage_Daily_Sales__c/fields/Daily_Sales__c.field-meta.xml
<CustomField>
    <fullName>Daily_Sales__c</fullName>
    <label>Daily Sales</label>
    <referenceTo>Retail_Number__c</referenceTo>
    <relationshipLabel>Store Inspection Manage Daily Sales</relationshipLabel>
    <relationshipName>Store_Inspection_Manage_Daily_Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Inspection_Manage_Daily_Sales__c/fields/Store_Inspection_Manage__c.field-meta.xml
<CustomField>
    <fullName>Store_Inspection_Manage__c</fullName>
    <label>Store Inspection Manage</label>
    <referenceTo>Store_Inspection_Manage__c</referenceTo>
    <relationshipLabel>Store Inspection Manage Daily Sales</relationshipLabel>
    <relationshipName>Store_Inspection_Manage_Daily_Sales</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesTargetReportBatch.cls
/*
 * @Author: WFC
 * @Date: 2024-04-11 15:20:56
 * @LastEditors: WFC
 * @LastEditTime: 2024-04-11 17:20:19
 * @Description: 东盟报表
 SalesTargetReportBatch ss  = new SalesTargetReportBatch();
 Database.executeBatch(ss);
 * @FilePath: \hisenseall-231026\force-app\main\default\classes\SalesTargetReportBatch.cls
 */
global withOut sharing class SalesTargetReportBatch implements Database.Batchable<sObject>{
    public String query;

    global SalesTargetReportBatch(){
        this.query = 'SELECT id, CurrencyIsoCode, Total_Price__c, Store_Inspection_Manage__c, Daily_Sales__c, Daily_Sales__r.Status__c, Daily_Sales__r.Shop__c ' + 
                 ' FROM Store_Inspection_Manage_Daily_Sales__c ';
    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Store_Inspection_Manage_Daily_Sales__c> simdsList){
        List<Sales_Target_Report__c> addList = new List<Sales_Target_Report__c>();
        Set<Id> shopIdSet = new Set<Id>();
        Map<Id, List<Id>> rpMap = new Map<Id, List<Id>>();
        for (Store_Inspection_Manage_Daily_Sales__c simds : simdsList){
            shopIdSet.add(simds.Daily_Sales__r.Shop__c);
        }
        List<Responsible_Person__c> rpList = [SELECT Id, Shop_Name__c, Principal__c
                                              FROM Responsible_Person__c
                                              WHERE Shop_Name__c IN:shopIdSet AND RecordType__c IN ('巡店员', 'Backup Floorwalker')];
        for (Responsible_Person__c rp : rpList){
            if (rpMap.containsKey(rp.Shop_Name__c)){
                rpMap.get(rp.Shop_Name__c).add(rp.Principal__c);
            } else{
                rpMap.put(rp.Shop_Name__c, new List<Id>{ rp.Principal__c });
            }
        }

        for (Store_Inspection_Manage_Daily_Sales__c simds : simdsList){
            List<Id> userList = rpMap.get(simds.Daily_Sales__r.Shop__c);
            if (userList != null && userList.size() > 0){
                for (Id uId : userList){
                    Sales_Target_Report__c str = new Sales_Target_Report__c();
                    str.CurrencyIsoCode = simds.CurrencyIsoCode;
                    str.Daily_Sales__c = simds.Daily_Sales__c;
                    str.Inspection_Status__c = simds.Daily_Sales__r.Status__c;
                    str.Key__c = simds.Store_Inspection_Manage__c + '-' + simds.Daily_Sales__c + '-' + uId;
                    str.Store_Inspection_Manage__c = simds.Store_Inspection_Manage__c;
                    str.Total_Price__c = simds.Total_Price__c;
                    str.User__c = uId;
                    addList.add(str);
                }
            }
        }
        Database.upsert (addList, Sales_Target_Report__c.Fields.Key__c, false);
    }

    global void finish(Database.BatchableContext BC){
        Utility.refreshReportCustom('SalesTargetReportClearBatch');
    }

}