force-app/main/default/objects/Responsible_Person__c/Responsible_Person__c.object-meta.xml
<CustomObject>
    <label>Responsible person</label>
    <nameField>
        <displayFormat>RP-{YYYY}{MM}{0000}</displayFormat>
        <label>门店负责人编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsible persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Responsible_Person__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>负责人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Responsible_Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>负责人类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>巡店员</fullName>
            </value>
            <value>
                <fullName>促销员</fullName>
            </value>
            <value>
                <fullName>Regional Manager</fullName>
                <label>区域经理</label>
            </value>
            <value>
                <fullName>Backup Floorwalker</fullName>
                <isActive>false</isActive>
                <label>Backup Floorwalker</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>门店名称</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Responsible_Person</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/UserEmail__c.field-meta.xml
<CustomField>
    <fullName>UserEmail__c</fullName>
    <label>负责人邮箱</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/Retail_Number__c.object-meta.xml
<CustomObject>
    <label>Daily Sales</label>
    <nameField>
        <displayFormat>RN-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>零售业绩编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Number__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <formula>CASESAFEID(PromoterDailyReport__r.OwnerId)</formula>
    <label>OwnerId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/ResponsiblePerson__c.field-meta.xml
<CustomField>
    <fullName>ResponsiblePerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible Person</label>
    <referenceTo>Responsible_Person__c</referenceTo>
    <relationshipLabel>Daily Sales</relationshipLabel>
    <relationshipName>Daily_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Retail_Number</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店员</label>
    <referenceTo>User</referenceTo>
    <relationshipName>shops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RetailNumberTriggerHandlerHelper2.cls
public class RetailNumberTriggerHandlerHelper2 {
	
    /**
     * @description 同步数据字段
     * @param       newList     更改后数据
     * @param       oldList     更改前数据
     */
    public static void dailySalesfieldUpdate(List<Retail_Number__c> oldList, List<Retail_Number__c> newList){
        List<Responsible_Person__c> lrp = [select Shop_Name__c,Shop_Name__r.Name, Principal__c,Principal__r.Name,UserEmail__c from Responsible_Person__c where RecordType__c = '促销员'];
        Map<String, Responsible_Person__c> lrpMap = new Map<String, Responsible_Person__c>();
        for(Responsible_Person__c rp : lrp){
            lrpMap.put(rp.Shop_Name__c + '' + rp.Principal__c, rp);
        }
        for(Retail_Number__c rn : newList){
            if (rn.ResponsiblePerson__c == null && lrpMap.containsKey(rn.Shop__c + '' + rn.OwnerId__c)) {
                rn.ResponsiblePerson__c = lrpMap.get(rn.Shop__c + '' + rn.OwnerId__c).Id;
            }
        }
    }
}