force-app/main/default/objects/Daily_Inspection_Report__c/Daily_Inspection_Report__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>DIR-{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>巡店员日报编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <description>巡店日期</description>
    <label>报告日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Report_Detail__c.field-meta.xml
<CustomField>
    <fullName>Report_Detail__c</fullName>
    <label>报告内容</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mileage__c/Mileage__c.object-meta.xml
<CustomObject>
    <label>Mileage</label>
    <nameField>
        <displayFormat>MI{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>巡店里程编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mileages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mileage__c/fields/Amount_To__c.field-meta.xml
<CustomField>
    <fullName>Amount_To__c</fullName>
    <label>加油量</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mileage__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>结束时的里程</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mileage__c/fields/Gas_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Gas_Mileage__c</fullName>
    <label>加油里程</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mileage__c/fields/Report__c.field-meta.xml
<CustomField>
    <fullName>Report__c</fullName>
    <label>巡店员日报</label>
    <referenceTo>Daily_Inspection_Report__c</referenceTo>
    <relationshipLabel>巡店里程</relationshipLabel>
    <relationshipName>Mileage_Report</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mileage__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>出发时的里程</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>岗位</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>岗位编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>启用</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>只能包含字母数字字符，必须以字母开头，不能以下划线字符结尾或包含两个连续的下划线字符，而且在所有岗位中必须是唯一的;</inlineHelpText>
    <label>岗位小组名</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position__c/fields/Grouo_Name__c.field-meta.xml
<CustomField>
    <fullName>Grouo_Name__c</fullName>
    <label>岗位名</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/Position_Permissions__c.object-meta.xml
<CustomObject>
    <label>岗位权限</label>
    <nameField>
        <displayFormat>PER-{00000000}</displayFormat>
        <label>岗位权限编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位权限</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Position_Permissions__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>岗位</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Position_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>产品线</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position_Permissions__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>岗位权限</relationshipLabel>
    <relationshipName>Position_Permissions_Shop</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/Responsible_Person__c.object-meta.xml
<CustomObject>
    <label>Responsible person</label>
    <nameField>
        <displayFormat>RP-{YYYY}{MM}{0000}</displayFormat>
        <label>门店负责人编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsible persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Responsible_Person__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>负责人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Responsible_Person</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>负责品线</description>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>门店名称</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Responsible_Person</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Share_Relation_Object__c/Share_Relation_Object__c.object-meta.xml
<CustomObject>
    <label>共享关系对象</label>
    <nameField>
        <label>共享关系对象名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>共享关系对象</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_Relation_Object__c/fields/Object_Lookup_API__c.field-meta.xml
<CustomField>
    <fullName>Object_Lookup_API__c</fullName>
    <inlineHelpText>设置为共享对象LookUp的字段API名称, 自定义字段以__c后缀</inlineHelpText>
    <label>共享对象查找字段API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Relation_Object__c/fields/Object_Share__c.field-meta.xml
<CustomField>
    <fullName>Object_Share__c</fullName>
    <label>共享关系对象_ShareAPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Relation_Object__c/fields/Relation_Object_API__c.field-meta.xml
<CustomField>
    <fullName>Relation_Object_API__c</fullName>
    <inlineHelpText>设置为共享对象LookUp的主表对象名称, 自定义字段以__c后缀</inlineHelpText>
    <label>共享关系对象API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Share_Relation_Object__c/fields/Share_RowCause__c.field-meta.xml
<CustomField>
    <fullName>Share_RowCause__c</fullName>
    <label>共享原因</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店员</label>
    <referenceTo>User</referenceTo>
    <relationshipName>shops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Shop_Level__c.field-meta.xml
<CustomField>
    <fullName>Shop_Level__c</fullName>
    <description>门店等级，分为S/A/B/C</description>
    <label>门店等级</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sales_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ShopLevel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop_Message_Board__c/Shop_Message_Board__c.object-meta.xml
<CustomObject>
    <label>留言板</label>
    <nameField>
        <label>主题</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>留言板</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop_Message_Board__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>(&quot;有效&quot;)</defaultValue>
    <label>是否有效</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>有效</fullName>
            </value>
            <value>
                <fullName>过期</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop_Message_Board__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>留言</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Shop_Message_Board__c/fields/priority__c.field-meta.xml
<CustomField>
    <fullName>priority__c</fullName>
    <label>分类</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>大至急（全部）</fullName>
            </value>
            <value>
                <fullName>大至急</fullName>
            </value>
            <value>
                <fullName>A(☆☆☆)</fullName>
                <label>商品納品情報</label>
            </value>
            <value>
                <fullName>B(☆☆)</fullName>
                <label>カタログ＆POP納品情報</label>
            </value>
            <value>
                <fullName>C(☆)</fullName>
                <label>新商品発売情報</label>
            </value>
            <value>
                <fullName>キャンペンーン情報</fullName>
            </value>
            <value>
                <fullName>定番状況</fullName>
            </value>
            <value>
                <fullName>展示情報</fullName>
            </value>
            <value>
                <fullName>物流情報</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Week_Research__c/Week_Research__c.object-meta.xml
<CustomObject>
    <label>门店调查要求</label>
    <nameField>
        <displayFormat>WR-{YYYY}{MM}{DD}{000000}</displayFormat>
        <label>要求编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>门店调查要求</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Week_Research__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>起效后方可在促销员日报显示该问题</inlineHelpText>
    <label>是否起效</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Week_Research__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>门店调查要求</relationshipLabel>
    <relationshipName>Shop_Research</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ShopLevel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>PB</fullName>
    </customValue>
    <customValue>
        <fullName>SP</fullName>
    </customValue>
    <customValue>
        <fullName>W</fullName>
    </customValue>
    <customValue>
        <fullName>アンケート</fullName>
    </customValue>
    <customValue>
        <fullName>サンエー</fullName>
    </customValue>
    <customValue>
        <fullName>本部指定</fullName>
    </customValue>
    <customValue>
        <fullName>専売機</fullName>
    </customValue>
    <customValue>
        <fullName>拡販</fullName>
    </customValue>
    <customValue>
        <fullName>T01</fullName>
    </customValue>
    <customValue>
        <fullName>T02</fullName>
    </customValue>
    <customValue>
        <fullName>T03</fullName>
    </customValue>
    <customValue>
        <fullName>T04</fullName>
    </customValue>
    <customValue>
        <fullName>T05</fullName>
    </customValue>
    <customValue>
        <fullName>T06</fullName>
    </customValue>
    <customValue>
        <fullName>T07</fullName>
    </customValue>
    <customValue>
        <fullName>T08</fullName>
    </customValue>
    <customValue>
        <fullName>T09</fullName>
    </customValue>
    <customValue>
        <fullName>T10</fullName>
    </customValue>
    <customValue>
        <fullName>未知</fullName>
    </customValue>
    <customValue>
        <fullName>店格不明</fullName>
    </customValue>
    <customValue>
        <fullName>T61</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種BIC</fullName>
    </customValue>
    <customValue>
        <fullName>HJ推進機種KS</fullName>
    </customValue>
    <masterLabel>门店等级</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FlowTest.cls
/**
 * @description       : 
 * @author            : ryshen@deloitte.com.cn
 * @group             : 
 * @last modified on  : 04-02-2022
 * @last modified by  : ryshen@deloitte.com.cn
**/
@isTest
public class FlowTest {
    @IsTest
    static void test01(){
        Test.startTest();
        Share_Relation_Object__c sro = new Share_Relation_Object__c();
        sro.Name = '巡店员日报';
        sro.Relation_Object_API__c = 'Daily_Inspection_Report__c';
        sro.Object_Lookup_API__c = 'Daily_Inspection_Report__c';
        sro.Object_Share__c = 'Daily_Inspection_Report__Share';
        sro.Share_Type__c = 'ParentId';
        sro.Share_RowCause__c = 'Position_Share__c';
        INSERT sro;
        Test.stopTest();
        
    }
    @IsTest
    static void test02(){
        Test.startTest();
        Daily_Inspection_Report__c dir = new Daily_Inspection_Report__c();
        dir.Report_Detail__c = 'test';
        dir.Report_Date__c = System.today();
        INSERT dir;
        Mileage__c mileage = new Mileage__c();
        mileage.Start__c = 1;
        mileage.End__c = 222;
        mileage.Amount_To__c = 50;
        mileage.Gas_Mileage__c = 888;
        mileage.Report__c = dir.Id;
        INSERT mileage;
        Test.stopTest();
        
    }
    @IsTest
    static void test03(){
    Test.startTest();
    Position__c pos = new Position__c();
    pos.DeveloperName__c = 'FU_GUAN_PATROLCLERKTEST';
    pos.Grouo_Name__c = '福关网格巡店员TEST';
    pos.Activity__c = true;
    INSERT pos;
    Position_Permissions__c position = new Position_Permissions__c();
    position.Product_Line__c = 'Mobile';
    position.Position__c = pos.Id;
    INSERT position;
    Test.stopTest();
        
    }
    @IsTest
    static void test04(){
    Test.startTest();
    Shop_Message_Board__c smb = new Shop_Message_Board__c();
    smb.priority__c = 'A(☆☆☆)';
    smb.Message__c = 'test';
    INSERT smb;
    Test.stopTest();
        
    }
    @IsTest
    static void test05(){
    Test.startTest();
    Shop__c shop = new Shop__c();
    shop.Shop_Level__c = 'A';
    shop.Name = 'Homeplus本石町店';
    INSERT shop;
            
    Week_Research__c wr = new Week_Research__c();
    wr.Shop__c = shop.Id;
    wr.IsActive__c = TRUE;
    INSERT wr;
    Test.stopTest();
        
    }
    @IsTest
    static void test06(){
    Profile p = [SELECT Id,Name FROM Profile WHERE Name = 'System Administrator' OR Name = '系统管理员'];

    User user1 = new User(
            Alias = 'admin', Email='systemadmin@hisensetest.com',
            EmailEncodingKey='UTF-8', LastName='sales representative', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='Asia/Kuala_Lumpur',
            UserName='systemadmin@hisensetest.com'
        );
    INSERT user1;

    Shop__c shop = new Shop__c();
    shop.Shop_Level__c = 'A';
    shop.Name = 'Homeplus本石町店';
    INSERT shop;
    
    Test.startTest();
    Responsible_Person__c person = new Responsible_Person__c();
    person.Principal__c =user1.Id;
    person.Shop_Name__c = shop.Id;
    INSERT person;
    Test.stopTest();
        
    }
}