force-app/main/default/objects/Daily_Inspection_Report__c/Daily_Inspection_Report__c.object-meta.xml
<CustomObject>
    <label>Inspection</label>
    <nameField>
        <displayFormat>DIR-{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>巡店员日报编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Report_Type__c.field-meta.xml
<CustomField>
    <fullName>Report_Type__c</fullName>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Check_Item_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Inspection_Report__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <description>销售区域</description>
    <formula>TEXT(Store__r.Sales_Region__c)</formula>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>USA(OEM)</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>Sales Department(HA)</fullName>
            </value>
            <value>
                <fullName>Sales Department(TV)</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
            <value>
                <fullName>Saudi</fullName>
                <label>Saudi Arabia</label>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>West Africa</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>East Africa</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>USA(OEM)</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense Malaysia</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>American Sales Department</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa Sales Department</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific Sales Department</fullName>
            </value>
            <value>
                <fullName>Key Account Sales Department</fullName>
            </value>
            <value>
                <fullName>Europe Sales Department</fullName>
            </value>
            <value>
                <fullName>Communications Sales Department</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Thailand</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>Hisense Indonesia</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense West Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Hisense Vietnam</fullName>
            </value>
            <value>
                <fullName>Hisense Philippines</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Singapore</fullName>
            </value>
            <value>
                <fullName>Hisense International</fullName>
            </value>
            <value>
                <fullName>Hisense UK</fullName>
            </value>
            <value>
                <fullName>Hisense Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Check_Item_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>巡店</fullName>
        <default>true</default>
        <label>巡店</label>
    </customValue>
    <customValue>
        <fullName>客户拜访</fullName>
    </customValue>
    <customValue>
        <fullName>客户拓展</fullName>
    </customValue>
    <masterLabel>Check Item Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreatePromoterDailyReportCmpController.cls
/*
 * @Author: YYL
 * @LastEditors: WFC
 */
public without sharing class CreatePromoterDailyReportCmpController {

    @AuraEnabled
    public static Boolean isPhaseIIIUser(String recordId, String salesRegion) {
        if (recordId!=null) {
            return PhaseIIIUtility.isPhaseIIIData(recordId);
        } else {
            if(String.isNotBlank(salesRegion)){
                return PhaseIIIUtility.isPhaseIIIUserUpdate(salesRegion);
            }else {
                return PhaseIIIUtility.isPhaseIIIUser();
            }
        }
    }

    // 新增校验，判断是进美国加拿大还是其他
    @AuraEnabled
    public static Boolean isPhaseIIIIUser(String recordId, String salesRegion) {
        // 存在日报，根据日报的sales region显示
        if (recordId!=null) {
            return PhaseIIIUtility.isPhaseData(recordId);
        } else {
            // 不存在日报，根据前端选择的sales region
            if(String.isNotBlank(salesRegion)){
                return PhaseIIIUtility.isPhaseUserUpdate(salesRegion);
            }else {
                return PhaseIIIUtility.isPhaseUser();
            }
        }
    }

    @AuraEnabled
    public static String getReportType(String recordId) {
        List<Daily_Inspection_Report__c> reportList = [SELECT Id, Report_Type__c FROM Daily_Inspection_Report__c WHERE Id =:recordId];
        if(reportList != null && reportList.size() > 0){
            return reportList[0].Report_Type__c;
        }else{
            return null;
        }
        
    }

    @AuraEnabled
    public static String getSalesRegion() {
        User userinfo = [SELECT Id, Country__c,Sales_region__c,Profile.Name FROM User WHERE Id =: UserInfo.getUserId()];

        return userinfo.Sales_region__c;
    }
}