force-app/main/default/objects/Customer_Sales_Forecast__c/Customer_Sales_Forecast__c.object-meta.xml
<CustomObject>
    <description>HVAC SalesForecast table</description>
    <label>Customer Sales Forecast</label>
    <nameField>
        <displayFormat>SF-{00000000}</displayFormat>
        <label>Customer_Sales_Forecast_Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sales Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Forecast__c/fields/Actual__c.field-meta.xml
<CustomField>
    <fullName>Actual__c</fullName>
    <label>Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Forecast__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Sales Forecast</relationshipLabel>
    <relationshipName>Customer_Sales_Forecast</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Forecast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jan</fullName>
            </value>
            <value>
                <fullName>Feb</fullName>
            </value>
            <value>
                <fullName>Mar</fullName>
            </value>
            <value>
                <fullName>Apr</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>Jun</fullName>
            </value>
            <value>
                <fullName>Jul</fullName>
            </value>
            <value>
                <fullName>Aug</fullName>
            </value>
            <value>
                <fullName>Sept</fullName>
            </value>
            <value>
                <fullName>Oct</fullName>
            </value>
            <value>
                <fullName>Nov</fullName>
            </value>
            <value>
                <fullName>Dec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Sales_Forecast__c/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Forecast__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2023</fullName>
                <default>true</default>
                <label>2023</label>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <label>Forecast</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/Current_Month_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Current_Month_Forecast__c</fullName>
    <label>Current Month Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forecast</relationshipLabel>
    <relationshipName>Forecast1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Next_Month_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Next_Month_Forecast__c</fullName>
    <label>T+1 Month Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Next_Next_Month_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Next_Next_Month_Forecast__c</fullName>
    <label>T+2 Month Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/YTD_Actual__c.field-meta.xml
<CustomField>
    <fullName>YTD_Actual__c</fullName>
    <label>YTD Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>SO{0000000000}</displayFormat>
        <label>SF Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount__c</fullName>
    <label>Total Order Amount(EX VAT)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CustomerSalesForecastTriggerHandler.cls
/*
 * @Author: WFC
 * @Date: 2023-03-23 16:38:33
 * @LastEditors: WFC
 * @LastEditTime: 2023-03-31 16:07:32
 * @Description: 
 * @FilePath: \Hitest_2022\force-app\main\default\classes\CustomerExtendTriggerHandler.cls
 */
public class CustomerSalesForecastTriggerHandler implements Triggers.Handler{
    
    public void handle() {

        Map<String,Integer> monthMap = new Map<String,Integer>();
        monthMap.put('Jan',1);
        monthMap.put('Feb',2);
        monthMap.put('Mar',3);
        monthMap.put('Apr',4);
        monthMap.put('May',5);
        monthMap.put('Jun',6);
        monthMap.put('Jul',7);
        monthMap.put('Aug',8);
        monthMap.put('Sept',9);
        monthMap.put('Oct',10);
        monthMap.put('Nov',11);
        monthMap.put('Dec',12);

        if (Trigger.isBefore && Trigger.isInsert) {        
            System.debug('Customer_Sales_Forecast__c-----beforeInsert');
            
            for (Customer_Sales_Forecast__c csf : ((list<Customer_Sales_Forecast__c>)Trigger.new)) {

                Integer year = Integer.valueOf(csf.year__c);
                Integer month = monthMap.get(csf.month__c);

                List<AggregateResult> actualList = [select sum(Order_Amount__c)actual from Order__c where CALENDAR_YEAR(Order_Date__c) =:year 
                                                                                    and CALENDAR_month(Order_Date__c) =:month
                                                                                    and Customer__c =:csf.Customer__c];

                for(AggregateResult ar : actualList){
                    csf.Actual__c = Double.valueOf(ar.get('actual'));
                }

                csf.External_Key__c = csf.Customer__c + String.valueOf(year) + String.valueOf(month);

                list<Forecast__c> listF = [select id from Forecast__c where External_key__c =:csf.Customer__c];
                Forecast__c f = null;

                if(listF == null || listF.size() == 0){
                    f = new Forecast__c();
                    f.Customer__c = csf.Customer__c;
                    f.External_Key__c = csf.Customer__c;
                    List<AggregateResult> ytdActualList = [select sum(Order_Amount__c)ytd from Order__c where CALENDAR_YEAR(Order_Date__c) =:year and Customer__c =:csf.Customer__c];
                    f.YTD_Actual__c = Double.valueOf(ytdActualList.get(0).get('ytd'));
                }else{
                    f = listF.get(0);
                    List<AggregateResult> ytdActualList = [select sum(Order_Amount__c)ytd from Order__c where CALENDAR_YEAR(Order_Date__c) =:year and Customer__c =:csf.Customer__c];
                    f.YTD_Actual__c = Double.valueOf(ytdActualList.get(0).get('ytd'));
                }

                if(Date.today().month() == month && Date.today().year() == year){
                    f.Current_Month_Forecast__c = csf.Amount__c * csf.Probability__c / 100;
                }else if(Date.today().addMonths(1).month() == month && Date.today().year() == year){
                    f.Next_Month_Forecast__c = csf.Amount__c * csf.Probability__c / 100;
                }else if(Date.today().addMonths(2).month() == month && Date.today().year() == year){
                    f.Next_Next_Month_Forecast__c = csf.Amount__c * csf.Probability__c / 100;
                }
                

                Database.upsert(f);
            }
        }


        if (Trigger.isBefore && Trigger.isUpdate) {

            System.debug('Customer_Sales_Forecast__c-----beforeUpdate');

            for (Customer_Sales_Forecast__c csf : ((list<Customer_Sales_Forecast__c>)Trigger.new)) {

                Integer year = Date.today().year();
                Integer month = monthMap.get(csf.month__c);

                List<AggregateResult> actualList = [select sum(Order_Amount__c)actual from Order__c where CALENDAR_YEAR(Order_Date__c) =:year 
                                                                                    and CALENDAR_month(Order_Date__c) =:month
                                                                                    and Customer__c =:csf.Customer__c];

                for(AggregateResult ar : actualList){
                    csf.Actual__c = Double.valueOf(ar.get('actual'));
                }

                csf.External_Key__c = csf.Customer__c + String.valueOf(year) + String.valueOf(month);

                list<Forecast__c> listF = [select id from Forecast__c where External_key__c =:csf.Customer__c];
                Forecast__c f = null;

                if(listF == null || listF.size() == 0){
                    f = new Forecast__c();
                    f.Customer__c = csf.Customer__c;
                    f.External_Key__c = csf.Customer__c;
                    List<AggregateResult> ytdActualList = [select sum(Order_Amount__c)ytd from Order__c where CALENDAR_YEAR(Order_Date__c) =:year and Customer__c =:csf.Customer__c];
                    f.YTD_Actual__c = Double.valueOf(ytdActualList.get(0).get('ytd'));
                }else{
                    f = listF.get(0);
                    List<AggregateResult> ytdActualList = [select sum(Order_Amount__c)ytd from Order__c where CALENDAR_YEAR(Order_Date__c) =:year and Customer__c =:csf.Customer__c];
                    f.YTD_Actual__c = Double.valueOf(ytdActualList.get(0).get('ytd'));
                }

                if(Date.today().month() == month && Date.today().year() == year){
                    f.Current_Month_Forecast__c = csf.Amount__c * csf.Probability__c / 100;
                }else if(Date.today().addMonths(1).month() == month && Date.today().year() == year){
                    f.Next_Month_Forecast__c = csf.Amount__c * csf.Probability__c / 100;
                }else if(Date.today().addMonths(2).month() == month && Date.today().year() == year){
                    f.Next_Next_Month_Forecast__c = csf.Amount__c * csf.Probability__c / 100;
                }

                Database.upsert(f);
            }
        }

        if (Trigger.isBefore && (Trigger.isUpdate || Trigger.isInsert)) {

        }

    }
}