force-app/main/default/objects/SalesGoal__c/SalesGoal__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Sales Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesGoal__c/fields/Amounts__c.field-meta.xml
<CustomField>
    <fullName>Amounts__c</fullName>
    <label>Amounts</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesGoal__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Targets</relationshipLabel>
    <relationshipName>Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesGoal__c/fields/TargetDay__c.field-meta.xml
<CustomField>
    <fullName>TargetDay__c</fullName>
    <label>Target Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesGoal__c/recordTypes/Customer_Target.recordType-meta.xml
<RecordType>
    <fullName>Customer_Target</fullName>
    <active>true</active>
    <label>Customer Target</label>
</RecordType>

force-app/main/default/classes/SalesGoalCustomerTargetSchedulableTest.cls
@isTest
private with sharing class SalesGoalCustomerTargetSchedulableTest {

    public static string customerRecordTypeId = [SELECT Id, DeveloperName, SobjectType FROM RecordType WHERE SobjectType= 'SalesGoal__c' AND DeveloperName = 'Customer_Target'].Id;
    
    static testMethod void test(){
        Test.startTest();

        Account customer = new Account();
        customer.Name = 'Wal-mart';
        insert customer;

        SalesGoal__c salesGoal = new SalesGoal__c();
        salesGoal.Customer__c = customer.Id;
        salesGoal.Name = '2024-01-18_Cencosud Retail S.A.';
        
        // target.Amounts__c = Decimal.valueOf(10);
        salesGoal.Amounts__c = 6000;
        salesGoal.CurrencyIsoCode = 'USD';
        salesGoal.TargetDay__c = Date.valueOf('2024-01-18');
        salesGoal.RecordTypeId = customerRecordTypeId;
        insert salesGoal;

        String CRON_EXP = '0 0 12 * * ?';
        SalesGoalCustomerTargetSchedulable schedulable = new SalesGoalCustomerTargetSchedulable();
        System.schedule('SalesGoalCustomerTargetSchedulableTest', CRON_EXP, schedulable);
        Test.stopTest();
    }


}