force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training  Task</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Training Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training  Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Effective_Number__c.field-meta.xml
<CustomField>
    <fullName>Effective_Number__c</fullName>
    <label>Effective Number</label>
    <summaryFilterItems>
        <field>Training_Tasks__c.Status__c</field>
        <operation>equals</operation>
        <value>有效</value>
    </summaryFilterItems>
    <summaryForeignKey>Training_Tasks__c.Training__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Pre_effective_Number__c.field-meta.xml
<CustomField>
    <fullName>Pre_effective_Number__c</fullName>
    <label>Pre-effective Number</label>
    <summaryFilterItems>
        <field>Training_Tasks__c.Status__c</field>
        <operation>equals</operation>
        <value>预有效</value>
    </summaryFilterItems>
    <summaryForeignKey>Training_Tasks__c.Training__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Rate_of_Completion__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Completion__c</fullName>
    <formula>Effective_Number__c /  Task_Number__c</formula>
    <label>Rate of Completion</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <label>Task Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Classification__c.field-meta.xml
<CustomField>
    <fullName>Training_Classification__c</fullName>
    <label>Training Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Training_Classification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_New</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_Tasks__c/Training_Tasks__c.object-meta.xml
<CustomObject>
    <description>新培训任务</description>
    <label>Training</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Training Task Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Tasks__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>CreatedBy.Email</formula>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Tasks__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>TEXT(Training__r.Month__c )</formula>
    <label>Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Tasks__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>预有效</fullName>
            </value>
            <value>
                <fullName>有效</fullName>
            </value>
            <value>
                <fullName>无效</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_Tasks__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Training Tasks</relationshipLabel>
    <relationshipName>Training_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Tasks__c/fields/Training_Classification__c.field-meta.xml
<CustomField>
    <fullName>Training_Classification__c</fullName>
    <formula>TEXT(Training__r.Training_Classification__c )</formula>
    <label>Training Classification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Tasks__c/fields/Training_Theme__c.field-meta.xml
<CustomField>
    <fullName>Training_Theme__c</fullName>
    <formula>Training__r.Training_Theme__c</formula>
    <label>Training Theme</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Tasks__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>TEXT(Training__r.Year__c )</formula>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Tasks_Evaluate__c/Training_Tasks_Evaluate__c.object-meta.xml
<CustomObject>
    <description>新培训任务中考评</description>
    <label>Training Tasks Evaluate</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Training Tasks Evaluate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Tasks Evaluate</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Tasks_Evaluate__c/fields/Training_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Training_Tasks__c</fullName>
    <label>Training Tasks</label>
    <referenceTo>Training_Tasks__c</referenceTo>
    <relationshipLabel>Training Tasks Evaluate</relationshipLabel>
    <relationshipName>Training_Tasks_Evaluate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Month.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <masterLabel>Month</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Training_Classification.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense TV</fullName>
    </customValue>
    <customValue>
        <fullName>Toshiba TV</fullName>
    </customValue>
    <customValue>
        <fullName>Air Conditioner</fullName>
    </customValue>
    <customValue>
        <fullName>Washing Machine</fullName>
    </customValue>
    <customValue>
        <fullName>All Categories</fullName>
    </customValue>
    <masterLabel>Training Classification</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Year_New.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <masterLabel>年</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TrainingController.cls
/*
 * @Author: WFC
 * @Date: 2024-04-03 14:17:00
 * @LastEditors: WFC
 * @LastEditTime: 2024-05-06 15:37:48
 * @Description:
 * @FilePath: \HisenseAll20240426\force-app\main\default\classes\TrainingController.cls
 */
public without sharing class TrainingController{
    @AuraEnabled
    public static List<Training__c> getTrainingData(String valueYear, String valueMonth){
        String sql = 'SELECT Id, Name, Year__c, Month__c, Email__c, Training_Theme__c, Training_Classification__c, Task_Number__c, Pre_effective_Number__c, Effective_Number__c, Rate_of_Completion__c ' + 
                 ' FROM Training__c ' + 
                 ' WHERE Email__c = \'' + UserInfo.getUserName() + '\'';
        if (String.isNotBlank(valueYear)){
            sql = sql + ' AND Year__c = \'' + valueYear + '\'';
        }
        if (String.isNotBlank(valueMonth)){
            sql = sql + ' AND Month__c = \'' + valueMonth + '\'';
        }
        sql = sql + 'ORDER BY Name';
        return Database.query(sql);
    }

    @AuraEnabled(Cacheable = true)
    public static List<Map<String, String>> getPickList(String objectName, String fieldName){

        try{
            Map<String, String> temp = Utility.getPicklistValueMap(objectName, fieldName);
            List<Map<String, String>> result = new List<Map<String, String>>();
            result.add(new Map<String, String>{ 'label' => '--None--', 'value' => '' });
            for (String key : temp.keySet()){
                result.add(new Map<String, String>{ 'label' => temp.get(key), 'value' => key });
            }
            return result;
        } catch (Exception e){
            // throw new AuraHandledException(e.getMessage());
            return null;
        }
    }

    // // 附件上传
    // @AuraEnabled
    // public static void saveTrainingPicture(String recordId, String photoStream){
    //     System.debug('photoStream--->' + photoStream);
    //     if (recordId == null || photoStream == null || photoStream == ''){
    //         return;
    //     }
    //     String fileName = System.now().format('yyyyMMddHHmmss') + '.jpeg';
    //     ContentVersion cv = new ContentVersion();
    //     cv.VersionData = EncodingUtil.base64Decode(photoStream.substring(23, photoStream.length()));
    //     cv.Title = fileName;
    //     cv.PathOnClient = fileName;
    //     insert cv;
    //     ContentVersion qrcv = [SELECT Id, ContentDocumentId
    //                            FROM ContentVersion
    //                            WHERE Id = :cv.id];
    //     ContentDocumentLink cdl = new ContentDocumentLink();
    //     cdl.ContentDocumentId = qrcv.ContentDocumentId;
    //     cdl.LinkedEntityId = recordId;
    //     cdl.ShareType = 'V';
    //     insert cdl;
    // }
    @AuraEnabled
    public static List<ContentVersion> getPictureList(String recordId){
        Set<Id> idSet = new Set<Id>();
        // 查询与记录相关联的文件
        List<ContentDocumentLink> documentLinks = [SELECT ContentDocumentId, ContentDocument.Title, ContentDocument.FileType
                                                   FROM ContentDocumentLink
                                                   WHERE LinkedEntityId = :recordId];
        // 处理查询结果
        for (ContentDocumentLink link : documentLinks){
            idSet.add(link.ContentDocumentId);
        }
        // 检索文件详细信息
        List<ContentVersion> cvList = [SELECT Id, ContentBodyId, ContentDocumentId, FileType
                                       FROM ContentVersion
                                       WHERE ContentDocumentId IN:idSet
                                       ORDER BY ContentDocument.CreatedDate];
        return cvList;
    }

    @AuraEnabled
    public static Boolean deletePicture(String contentDocumentId){
        Database.delete (contentDocumentId);
        return true;
    }

    // 保存考评(trainingTaskEvaluateLwc)
    @AuraEnabled
    public static Boolean saveEvaluate(String recordId, String ratingDataJson){
        Map<String, Object> ratingMap = (Map<String, Object>)JSON.deserializeUntyped(ratingDataJson);
        Decimal score = 0;
        for (String index : ratingMap.keySet()){
            score += Decimal.valueOf(String.valueOf(ratingMap.get(index)));
        }
        Training_Tasks_Evaluate__c tte = new Training_Tasks_Evaluate__c();
        tte.Training_Tasks__c = recordId;
        tte.Score__c = score;
        tte.Answer__c = ratingDataJson;
        insert tte;
        return true;
    }

    // @AuraEnabled(Cacheable = true)
    // public static List<Training_Tasks_Evaluate_Question__c> getQuestions(){
    //     return [SELECT Id, Name, Topic__c, Score__c, Sort__c, IsActive__c
    //             FROM Training_Tasks_Evaluate_Question__c
    //             WHERE IsActive__c = true
    //             ORDER BY Sort__c];
    // }
    @AuraEnabled(Cacheable = true)
    public static Boolean getStatus(String recordId){

        Training_Tasks__c tt = [SELECT Status__c
                                FROM Training_Tasks__c
                                WHERE Id = :recordId
                                LIMIT 1];
        if (tt.Status__c == '预有效' || tt.Status__c == '有效'){
            return false;
        } else{
            return true;
        }
    }

    @AuraEnabled
    public static Boolean isCanUpload(){
        User currentUser = [SELECT Id, Profile.name
                            FROM User
                            WHERE Id = :UserInfo.getUserId()];
        if (currentUser.profile.name == 'Indonesia Store M and malaysia GM' || currentUser.profile.name == 'System Administrator'){
            return true;
        } else{
            return false;
        }
    }

}