force-app/main/default/objects/InterfaceLog__c/InterfaceLog__c.object-meta.xml
<CustomObject>
    <label>InterfaceLog</label>
    <nameField>
        <label>No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InterfaceLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InterfaceLog__c/fields/ErrorMsg__c.field-meta.xml
<CustomField>
    <fullName>ErrorMsg__c</fullName>
    <label>ErrorMsg</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/Req_Json__c.field-meta.xml
<CustomField>
    <fullName>Req_Json__c</fullName>
    <label>Req Json</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/ReturnCode__c.field-meta.xml
<CustomField>
    <fullName>ReturnCode__c</fullName>
    <label>ReturnCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/Promoter_Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Report</label>
    <nameField>
        <displayFormat>PWR-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>日报编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>考勤</label>
    <referenceTo>Promoter_Attendance__c</referenceTo>
    <relationshipName>Attendance_PromoterDailyReports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/CLKeyAccountManager__c.field-meta.xml
<CustomField>
    <fullName>CLKeyAccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CL Key Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DailyReports3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DailyReports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/FinishRemark__c.field-meta.xml
<CustomField>
    <fullName>FinishRemark__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>本日已完成</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/IDTrainingManager__c.field-meta.xml
<CustomField>
    <fullName>IDTrainingManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ID Training Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DailyReports4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Is_Today__c.field-meta.xml
<CustomField>
    <fullName>Is_Today__c</fullName>
    <formula>Report_Date__c == today()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Today</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/IsChange__c.field-meta.xml
<CustomField>
    <fullName>IsChange__c</fullName>
    <defaultValue>false</defaultValue>
    <description>非创建者请勿删除</description>
    <label>*IsChange</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/IsNew__c.field-meta.xml
<CustomField>
    <fullName>IsNew__c</fullName>
    <defaultValue>true</defaultValue>
    <description>非创建者请勿删除</description>
    <label>*IsNew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/IsPerformance__c.field-meta.xml
<CustomField>
    <fullName>IsPerformance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>在促销员，新增&quot;当日実績なし&quot;勾选项。勾选后不能“+”当日业绩。
勾选后，保存时，需要生成一条业绩为0的数据</description>
    <label>*IsPerformance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Owner_Email__c</fullName>
    <formula>Owner:User.Username</formula>
    <label>Owner Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Owner_text__c.field-meta.xml
<CustomField>
    <fullName>Owner_text__c</fullName>
    <label>Owner</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/PromoterDailyReport__c.field-meta.xml
<CustomField>
    <fullName>PromoterDailyReport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>周调研问题反馈</label>
    <referenceTo>WeekResearchResponse__c</referenceTo>
    <relationshipName>WeekResearchResponse_PromoterDailyReport</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/RecordLink__c.field-meta.xml
<CustomField>
    <fullName>RecordLink__c</fullName>
    <formula>HYPERLINK(LEFT($Api.Enterprise_Server_URL_540, FIND( &apos;.my.salesforce.com/services&apos;,$Api.Enterprise_Server_URL_540))+ &apos;lightning.force.com/lightning/r/Promoter_Daily_Report__c/&apos; +Id + &apos;/view&apos; , Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>*促销员日报链接</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Report_Content__c.field-meta.xml
<CustomField>
    <fullName>Report_Content__c</fullName>
    <label>报告内容</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>报告日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/ReportDateFormula__c.field-meta.xml
<CustomField>
    <fullName>ReportDateFormula__c</fullName>
    <formula>TEXT( Report_Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Suggest to submit report for the day. Submit past report will trigger approval workflow.</inlineHelpText>
    <label>*报告日期</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/ReportSubmittedDate__c.field-meta.xml
<CustomField>
    <fullName>ReportSubmittedDate__c</fullName>
    <label>Report Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/ReportSubmittedDelayJudgment__c.field-meta.xml
<CustomField>
    <fullName>ReportSubmittedDelayJudgment__c</fullName>
    <formula>ReportSubmittedDate__c  -  Report_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Report Submitted Delay Judgment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/SAOpsRegionalManager__c.field-meta.xml
<CustomField>
    <fullName>SAOpsRegionalManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SA Ops Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DailyReports2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/SARegionalManager__c.field-meta.xml
<CustomField>
    <fullName>SARegionalManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SA Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DailyReports1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Share_Gridding_Code__c.field-meta.xml
<CustomField>
    <fullName>Share_Gridding_Code__c</fullName>
    <description>非创建者请勿删除</description>
    <formula>Shop__r.Grid__r.Gridding_Code__c</formula>
    <label>*网格Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Share_Shop__c.field-meta.xml
<CustomField>
    <fullName>Share_Shop__c</fullName>
    <description>非创建者请勿删除</description>
    <formula>Shop__r.Shop_Code_Text__c</formula>
    <label>*门店Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only related stores are available.</inlineHelpText>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Daily Reports</relationshipLabel>
    <relationshipName>Shop_Promoter_Week_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Daily Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Is_Export__c.field-meta.xml
<CustomField>
    <fullName>Is_Export__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Export</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;USA(OEM)&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Thailand&apos;) , &apos;Hisense Thailand&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense India&apos;) , &apos;Hisense India&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Dubai&apos;) , &apos;Hisense Dubai&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;American Sales Department&apos;) , &apos;American Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Middle East and Africa Sales Department&apos;) , &apos;Middle East and Africa Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Asia-Pacific Sales Department&apos;) , &apos;Asia-Pacific Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Key Account Sales Department&apos;) , &apos;Key Account Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Europe Sales Department&apos;) , &apos;Europe Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Colombia&apos;) , &apos;Hisense Colombia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Argentina&apos;) , &apos;Hisense Argentina&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <description>销售区域</description>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>In Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sales_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hisense USA</fullName>
    </customValue>
    <customValue>
        <fullName>USA(OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense South Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Japan</fullName>
    </customValue>
    <customValue>
        <fullName>American Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East and Africa Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Asia-Pacific Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Key Account Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Europe Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Communications Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Home Appliances Sales Department</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense India</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Panama</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Peru</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Saudi</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Vietnam</fullName>
    </customValue>
    <customValue>
        <fullName>ASEAN</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Hisense West Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Sales Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendPromoterDailyReportToBigData.cls
/**********************************************************************
 * function:Promoter_Daily_Report__c
 * @author:lizunxing
 * @url: /services/apexrest
 * @data: 
 * date:2024-07-03
*************************************************************************/
@RestResource(urlMapping='/SendPromoterDailyReportToBigData')
global with sharing class SendPromoterDailyReportToBigData {  

    global class AppInput{
        public String startTime; 
        public String endTime; 
        public String pageIndex;
        public String pageSize;
    }
    global class AppOutPut{
        public Integer totalPage;
        List<PromoterDailyReportInfo> promoterDailyReportInfoList;
    }

    public class PromoterDailyReportInfo {

        public String id;
        public String Name;
        public String OwnerId;
        public String IsDeleted;
        public String CurrencyIsoCode;
        public String CreatedById;
        public String CreatedDate;
        public String LastModifiedById;
        public String LastModifiedDate;

        public String Attendance;
        public String CLKeyAccountManager;
        public String CreatedByRole;
        public String Customer;
        public String FinishRemark;
        public String IDTrainingManager;
        public String IsChange;
        public String IsNew;
        public String IsPerformance;
        public String IsExport;
        public String IsToday;
        public String OwnerEmail;
        public String Ownertext;
        public String PromoterDailyReport;
        public String RecordLink;
        public String ReportDateFormula;
        public String ReportSubmittedDate;
        public String ReportSubmittedDelayJudgment;
        public String ReportContent;
        public String ReportDate;
        public String SAOpsRegionalManager;
        public String SARegionalManager;
        public String SalesRegion;
        public String ShareGriddingCode;
        public String ShareShop;
        public String Shop;
        public String Status;

   


    }

    @HttpPost
    global static SendPromoterDailyReportToBigData.AppOutPut adoPost() {

        RestRequest req = RestContext.request;
        String reqBody = req.requestBody.tostring(); 
        //String reqBody = '{"startTime":"2024-01-09 00:00:00","endTime":"2024-01-10 00:00:00"}'; 
        SendPromoterDailyReportToBigData.AppInput appInput = new SendPromoterDailyReportToBigData.AppInput();
        
        SendPromoterDailyReportToBigData.AppOutPut result = new SendPromoterDailyReportToBigData.AppOutPut();
        
        try{
            appInput = (SendPromoterDailyReportToBigData.AppInput)JSON.deserialize(reqBody, SendPromoterDailyReportToBigData.AppInput.class);

            if(String.isBlank(appInput.startTime) || String.isBlank(appInput.endTime)){
                return result;
            }

            if(String.isBlank(appInput.pageIndex)){
                appInput.pageIndex = '1';
            }

            if(String.isBlank(appInput.pageSize) || Integer.valueOf(appInput.pageSize) < 200){
                appInput.pageSize = '200';
            }

            appInput.startTime = Utility.increaseHoursInStringDate(appInput.startTime,8).replace(' ','T') + '.000+0000';
            appInput.endTime = Utility.increaseHoursInStringDate(appInput.endTime,8).replace(' ','T') + '.000+0000';

            String sql = 'select '+
            'id,'+
            'Name,'+
            'OwnerId,'+
            'IsDeleted,'+
            'CurrencyIsoCode,'+
            'CreatedById,'+
            'CreatedDate,'+
            'LastModifiedById,'+
            'LastModifiedDate,'+
      

            'Attendance__c,'+
            'CLKeyAccountManager__c,'+
            'Created_By_Role__c,'+
            'Customer__c,'+
            'FinishRemark__c,'+
            'IDTrainingManager__c,'+
            'IsChange__c,'+
            'IsNew__c,'+
            'IsPerformance__c,'+
            'Is_Export__c,'+
            'Is_Today__c,'+
            'Owner_Email__c,'+
            'Owner_text__c,'+
            'PromoterDailyReport__c,'+
            'RecordLink__c,'+
            'ReportDateFormula__c,'+
            'ReportSubmittedDate__c,'+
            'ReportSubmittedDelayJudgment__c,'+
            'Report_Content__c,'+
            'Report_Date__c,'+
            'SAOpsRegionalManager__c,'+
            'SARegionalManager__c,'+
            'Sales_Region__c,'+
            'Share_Gridding_Code__c,'+
            'Share_Shop__c,'+
            'Shop__c,'+
            'Status__c'+
            
            ' from Promoter_Daily_Report__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            List<Promoter_Daily_Report__c> PromoterDailyReportList = (List<Promoter_Daily_Report__c>)Utility.getRecordListPage(sql, appInput.pageIndex, appInput.pageSize);

            List<PromoterDailyReportInfo> PromoterDailyReportInfoList = new List<PromoterDailyReportInfo>();

            for(Promoter_Daily_Report__c a : PromoterDailyReportList){
                PromoterDailyReportInfo c = new PromoterDailyReportInfo();
                c.id = a.id;
                c.Name = checkNull(a.Name);
                c.OwnerId = checkNull(a.OwnerId);
                c.IsDeleted = checkNull(a.IsDeleted + '');
                c.CurrencyIsoCode = checkNull(a.CurrencyIsoCode);
                c.CreatedById = checkNull(a.CreatedById);
                c.CreatedDate = checkNull(a.CreatedDate + '');
                c.LastModifiedById = checkNull(a.LastModifiedById);
                c.LastModifiedDate = checkNull(a.LastModifiedDate + '');

                c.Attendance = checkNull(a.Attendance__c + '');
                c.CLKeyAccountManager = checkNull(a.CLKeyAccountManager__c + '');
                c.CreatedByRole = checkNull(a.Created_By_Role__c + '');
                c.Customer = checkNull(a.Customer__c + '');
                c.FinishRemark = checkNull(a.FinishRemark__c + '');
                c.IDTrainingManager = checkNull(a.IDTrainingManager__c + '');
                c.IsChange = checkNull(a.IsChange__c + '');
                c.IsNew = checkNull(a.IsNew__c + '');
                c.IsPerformance = checkNull(a.IsPerformance__c + '');
                c.IsExport = checkNull(a.Is_Export__c + '');
                c.IsToday = checkNull(a.Is_Today__c + '');
                c.OwnerEmail = checkNull(a.Owner_Email__c + '');
                c.Ownertext = checkNull(a.Owner_text__c + '');
                c.PromoterDailyReport = checkNull(a.PromoterDailyReport__c + '');
                c.RecordLink = checkNull(a.RecordLink__c + '');
                c.ReportDateFormula = checkNull(a.ReportDateFormula__c + '');
                c.ReportSubmittedDate = checkNull(a.ReportSubmittedDate__c + '');
                c.ReportSubmittedDelayJudgment = checkNull(a.ReportSubmittedDelayJudgment__c + '');
                c.ReportContent = checkNull(a.Report_Content__c + '');
                c.ReportDate = checkNull(a.Report_Date__c + '');
                c.SAOpsRegionalManager = checkNull(a.SAOpsRegionalManager__c + '');
                c.SARegionalManager = checkNull(a.SARegionalManager__c + '');
                c.SalesRegion = checkNull(a.Sales_Region__c + '');
                c.ShareGriddingCode = checkNull(a.Share_Gridding_Code__c + '');
                c.ShareShop = checkNull(a.Share_Shop__c + '');
                c.Shop = checkNull(a.Shop__c + '');
                c.Status = checkNull(a.Status__c + '');
              
                PromoterDailyReportInfoList.add(c);

            }
            result.PromoterDailyReportInfoList = PromoterDailyReportInfoList;
            String sql1 = 'select count(id) totalNumber from Promoter_Daily_Report__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            List<AggregateResult> c = Database.query(sql1);
            result.totalPage = (Integer.valueOf(c.get(0).get('totalNumber')) + Integer.valueOf(appInput.pageSize) - 1) / Integer.valueOf(appInput.pageSize);

            System.debug('result :' + result);
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendPromoterDailyReportToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '1';
            ic.Req_Json__c = reqBody + '返回条数：' + Integer.valueOf(c.get(0).get('totalNumber'));
            insert ic;

            return result; 
        }catch(Exception e){
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendPromoterDailyReportToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '0';
            ic.Req_Json__c = reqBody;
            ic.ErrorMsg__c = e.getMessage();
            insert ic;

            return result; 
        }
    }

    public static String checkNull(String str){
        if(String.isBlank(str)){
            return '';
        }else if('null'.equals(str)){
            return '';
        }else{
            return str;
        }
    }
}