force-app/main/default/objects/InterfaceLog__c/InterfaceLog__c.object-meta.xml
<CustomObject>
    <label>InterfaceLog</label>
    <nameField>
        <label>No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InterfaceLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InterfaceLog__c/fields/ErrorMsg__c.field-meta.xml
<CustomField>
    <fullName>ErrorMsg__c</fullName>
    <label>ErrorMsg</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/Req_Json__c.field-meta.xml
<CustomField>
    <fullName>Req_Json__c</fullName>
    <label>Req Json</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/ReturnCode__c.field-meta.xml
<CustomField>
    <fullName>ReturnCode__c</fullName>
    <label>ReturnCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store_Product_Line__c/Store_Product_Line__c.object-meta.xml
<CustomObject>
    <label>Store Product Line</label>
    <nameField>
        <displayFormat>SPLC-{YYYY}{MM}{0000}</displayFormat>
        <label>Store Product Line Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product_Line__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Time Of Exit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store_Product_Line__c/fields/Entering_Status__c.field-meta.xml
<CustomField>
    <fullName>Entering_Status__c</fullName>
    <label>Entering Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entered</fullName>
            </value>
            <value>
                <fullName>Exited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store_Product_Line__c/fields/Stand_Amount__c.field-meta.xml
<CustomField>
    <fullName>Stand_Amount__c</fullName>
    <description>展台数量</description>
    <label>Booth Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store_Product_Line__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Store Product Lines</relationshipLabel>
    <relationshipName>Store_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Product_Line__c/fields/Time_Of_Entry__c.field-meta.xml
<CustomField>
    <fullName>Time_Of_Entry__c</fullName>
    <label>Time Of Entry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store_Product_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>HA</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>CTV</fullName>
                <isActive>false</isActive>
                <label>CTV</label>
            </value>
            <value>
                <fullName>WG</fullName>
                <isActive>false</isActive>
                <label>WG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendStoreProductlineToBigData.cls
/**********************************************************************
 * function:客户产品线表Store_Product_Line__c
 * @author:lizunxing
 * @url: /services/apexrest
 * @data: 
 * date:2024-01-31
*************************************************************************/
@RestResource(urlMapping='/SendStoreProductlineToBigData')
global with sharing class SendStoreProductlineToBigData {  

    global class AppInput{
        public String startTime; 
        public String endTime; 
        public String pageIndex;
        public String pageSize;
    }
    global class AppOutPut{
        public Integer totalPage;
        List<StoreProductlineInfo> storeProductlineInfoList;
    }

    public class StoreProductlineInfo {
        
        public String productLine;
        public String storeId;
        public String timeOfEntry;
        public String closeDate;
        public String EnteringStatus;

        public String id;
        public String Name;
        public String IsDeleted;
        public String CurrencyIsoCode;
        public String CreatedById;
        public String CreatedDate;
        public String LastModifiedById;
        public String LastModifiedDate;
        public String SystemModstamp;

        public String StandAmount;
        public String Type;
    }

    @HttpPost
    global static SendStoreProductlineToBigData.AppOutPut adoPost() {

        RestRequest req = RestContext.request;
        String reqBody = req.requestBody.tostring(); 
        //String reqBody = '{"startTime":"2024-01-09 00:00:00","endTime":"2024-01-10 00:00:00"}'; 
        SendStoreProductlineToBigData.AppInput appInput = new SendStoreProductlineToBigData.AppInput();
        
        SendStoreProductlineToBigData.AppOutPut result = new SendStoreProductlineToBigData.AppOutPut();
        
        try{
            appInput = (SendStoreProductlineToBigData.AppInput)JSON.deserialize(reqBody, SendStoreProductlineToBigData.AppInput.class);

            if(String.isBlank(appInput.startTime) || String.isBlank(appInput.endTime)){
                return result;
            }

            if(String.isBlank(appInput.pageIndex)){
                appInput.pageIndex = '1';
            }

            if(String.isBlank(appInput.pageSize) || Integer.valueOf(appInput.pageSize) < 200){
                appInput.pageSize = '200';
            }

            appInput.startTime = Utility.increaseHoursInStringDate(appInput.startTime,8).replace(' ','T') + '.000+0000';
            appInput.endTime = Utility.increaseHoursInStringDate(appInput.endTime,8).replace(' ','T') + '.000+0000';

            String sql = 'select '+
            'id,'+
            'Name,'+
            'IsDeleted,'+
            'CurrencyIsoCode,'+
            'CreatedById,'+
            'CreatedDate,'+
            'LastModifiedById,'+
            'LastModifiedDate,'+
            'SystemModstamp,'+
            
            'Stand_Amount__c,'+
            'Close_Date__c,'+
            'Product_Line__c,'+
            'Store__c,'+
            'Entering_Status__c,'+
            'Type__c,'+
            'Time_Of_Entry__c'+

            ' from Store_Product_Line__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            //List<Store_Product_Line__c> StoreProductlineList = (List<Store_Product_Line__c>)Utility.getRecordListPage(sql, appInput.pageIndex, appInput.pageSize);
            List<Store_Product_Line__c> StoreProductlineList = Utility.apexPagination(Database.query(sql), Integer.valueOf(appInput.pageIndex), Integer.valueOf(appInput.pageSize));

            List<StoreProductlineInfo> StoreProductlineInfoList = new List<StoreProductlineInfo>();

            for(Store_Product_Line__c a : StoreProductlineList){
                StoreProductlineInfo c = new StoreProductlineInfo();
                c.id = a.id;
                c.Name = checkNull(a.Name);
                c.IsDeleted = checkNull(a.IsDeleted + '');
                c.CurrencyIsoCode = checkNull(a.CurrencyIsoCode);
                c.CreatedById = checkNull(a.CreatedById);
                c.CreatedDate = checkNull(a.CreatedDate + '');
                c.LastModifiedById = checkNull(a.LastModifiedById);
                c.LastModifiedDate = checkNull(a.LastModifiedDate + '');
                c.SystemModstamp = checkNull(a.SystemModstamp + '');
              
                c.StandAmount = checkNull(a.Stand_Amount__c + '');
                c.closeDate = checkNull(a.Close_Date__c + '');
                c.productLine = checkNull(a.Product_Line__c + '');
                c.storeId = checkNull(a.Store__c + '');
                c.timeOfEntry = checkNull(a.Time_Of_Entry__c + '');
                c.EnteringStatus = checkNull(a.Entering_Status__c + '');

                c.Type = checkNull(a.Type__c + '');

                StoreProductlineInfoList.add(c);

            }
            result.StoreProductlineInfoList = StoreProductlineInfoList;
            String sql1 = 'select count(id) totalNumber from Store_Product_Line__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            List<AggregateResult> c = Database.query(sql1);
            result.totalPage = (Integer.valueOf(c.get(0).get('totalNumber')) + Integer.valueOf(appInput.pageSize) - 1) / Integer.valueOf(appInput.pageSize);

            System.debug('result :' + result);
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendStoreProductlineToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '1';
            ic.Req_Json__c = reqBody;
            insert ic;

            return result; 
        }catch(Exception e){
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendStoreProductlineToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '0';
            ic.Req_Json__c = reqBody;
            ic.ErrorMsg__c = e.getMessage();
            insert ic;

            return result; 
        }
    }

    public static String checkNull(String str){
        if(String.isBlank(str)){
            return '';
        }else if('null'.equals(str)){
            return '';
        }else{
            return str;
        }
    }
}