force-app/main/default/objects/Credit_Limit_Application__c/Credit_Limit_Application__c.object-meta.xml
<CustomObject>
    <label>Credit Limit Application</label>
    <nameField>
        <displayFormat>LA-{00000000}</displayFormat>
        <label>Credit Limit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Limit Application</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Buyer_English_Address__c.field-meta.xml
<CustomField>
    <fullName>Buyer_English_Address__c</fullName>
    <label>Buyer English Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Credit_Guarantee_Issuing_Bank_SWIFT__c.field-meta.xml
<CustomField>
    <fullName>Credit_Guarantee_Issuing_Bank_SWIFT__c</fullName>
    <label>Credit Guarantee Issuing Bank SWIFT</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Account.SAP_Customer_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Limit Application</relationshipLabel>
    <relationshipName>Credit_Limit_Application</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <defaultValue>(&quot;中信保&quot;)</defaultValue>
    <label>Insurance Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>中信保</fullName>
                <default>true</default>
                <label>中信保</label>
            </value>
            <value>
                <fullName>太保</fullName>
            </value>
            <value>
                <fullName>COFACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>OA</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>LC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>DP</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>DA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interface_Url__c/Interface_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Interface_Url</label>
</CustomObject>

force-app/main/default/objects/Interface_Url__c/fields/Basic_Url__c.field-meta.xml
<CustomField>
    <fullName>Basic_Url__c</fullName>
    <label>Basic Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SyncCustomerCreditInfoToRRTest.cls
@isTest
private class SyncCustomerCreditInfoToRRTest {
    static testMethod void testMethod1() {
        system.test.startTest();
        Interface_Url__c newurl = new Interface_Url__c(
                                    Name = 'RR',
                                    Basic_Url__c ='testbasic',
                                    User_Name__c = 'username',
                                    Password__c = 'password');
        insert newurl;
        system.Test.setMock(HttpCalloutMock.class, new SyncCustomerCreditInfoToRR_Mock());

        // 数据
        Account acc = new Account(
                            Name = 'testname');
        insert acc;      
        Credit_Limit_Application__c newCredit = new Credit_Limit_Application__c(
                                                Payment_Method__c = '1',
                                                Buyer_English_Address__c = 'testtheaddress',
                                                //Enterprise_internal_code__c = 'testcode',
                                                Credit_Guarantee_Issuing_Bank_SWIFT__c='A0000111',
                                                Customer__c = acc.Id,
                                                Insurance_Company__c = '中信保');
        insert newCredit;
        //ProcessSteps newsteps = new ProcessSteps();
        // AttachedContentDocuments NewFileAttachmentInput = new AttachedContentDocuments(
        //                                      );

        ContentVersion contentVersion = new ContentVersion(
          Title = 'Penguins',
          PathOnClient = 'Penguins.jpg',
          VersionData = Blob.valueOf('Test Content'),
          IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = newCredit.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;

        //
        SyncCustomerCreditInfoToRR.postInfomation(newCredit.Id);
        system.Test.stopTest();
    }
    static testMethod void testMethod2() {
        Test.startTest();
        Interface_Url__c newurl = new Interface_Url__c(
                                    Name = 'RR',
                                    Basic_Url__c ='testbasic',
                                    User_Name__c = 'username',
                                    Password__c = 'password');
        insert newurl;
        Account acc = new Account(
                            Name = 'testname');
        insert acc;      
        Credit_Limit_Application__c newCredit = new Credit_Limit_Application__c(
                                                Payment_Method__c = '1',
                                                Buyer_English_Address__c = 'testtheaddress',
                                                //Enterprise_internal_code__c = 'testcode',
                                                Credit_Guarantee_Issuing_Bank_SWIFT__c='A0000111',
                                                Customer__c = acc.Id,
                                                Insurance_Company__c = '中信保');
        insert newCredit;
        SyncCustomerCreditInfoToRR.postInfomation(newCredit.Id);
        Test.stopTest();
    }

    static testMethod void testMethod3() {
        Test.startTest();
        Interface_Url__c newurl = new Interface_Url__c(
            Name = 'RR',
            Basic_Url__c ='testbasic',
            User_Name__c = 'username',
            Password__c = 'password');
        insert newurl;
        Account acc = new Account(
            Name = 'testname');
        insert acc;      
        Credit_Limit_Application__c newCredit = new Credit_Limit_Application__c(
                                Payment_Method__c = '1',
                                Buyer_English_Address__c = 'testtheaddress',
                                //Enterprise_internal_code__c = 'testcode',
                                Credit_Guarantee_Issuing_Bank_SWIFT__c='A0000111',
                                Customer__c = acc.Id,
                                Insurance_Company__c = '中信保');
        insert newCredit;
        String json = '{"IsSuccess": "","FailReason": ""}';
        Test.setMock(HttpCalloutMock.class, new CalloutMock(json));
        SyncCustomerCreditInfoToRR.postInfomation(newCredit.Id);
        Test.stopTest();
    }
}