force-app/main/default/objects/Credit_Limit_Application__c/Credit_Limit_Application__c.object-meta.xml
<CustomObject>
    <label>Credit Limit Application</label>
    <nameField>
        <displayFormat>LA-{00000000}</displayFormat>
        <label>Credit Limit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Limit Application</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Buyer_English_Address__c.field-meta.xml
<CustomField>
    <fullName>Buyer_English_Address__c</fullName>
    <label>Buyer English Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Buyer_Phone__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Phone__c</fullName>
    <label>Buyer Phone</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Company_3_Years_Turnover__c.field-meta.xml
<CustomField>
    <fullName>Company_3_Years_Turnover__c</fullName>
    <label>Company 3 Years Turnover</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Credit_Application_Period_days__c.field-meta.xml
<CustomField>
    <fullName>Credit_Application_Period_days__c</fullName>
    <label>Customer Payment Term (days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Credit_Limit_for_Application_RAND__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_for_Application_RAND__c</fullName>
    <label>Credit Limit for Application</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>RAND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Current_Credit_Limits__c.field-meta.xml
<CustomField>
    <fullName>Current_Credit_Limits__c</fullName>
    <label>Current Credit Limits</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Account.SAP_Customer_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Limit Application</relationshipLabel>
    <relationshipName>Credit_Limit_Application</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Expected_This_Year_Total_Turnover__c.field-meta.xml
<CustomField>
    <fullName>Expected_This_Year_Total_Turnover__c</fullName>
    <label>Expected This Year Total Turnover</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Export_Goods_Name__c.field-meta.xml
<CustomField>
    <fullName>Export_Goods_Name__c</fullName>
    <label>Export Goods Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Last_3Years_Transaction_Amount_1_RAND__c.field-meta.xml
<CustomField>
    <fullName>Last_3Years_Transaction_Amount_1_RAND__c</fullName>
    <label>Last 3Years&apos; Transaction Amount 1 (RAND)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Latest_Shipping_Date__c.field-meta.xml
<CustomField>
    <fullName>Latest_Shipping_Date__c</fullName>
    <label>Latest Date of Shipment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Maximum_Turnover_Per_Order__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Turnover_Per_Order__c</fullName>
    <label>Maximum Turnover Per Order</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Order_Plan__c.field-meta.xml
<CustomField>
    <fullName>Order_Plan__c</fullName>
    <label>Order Plan</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <default>true</default>
                <label>OA</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>LC</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>DP</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>DA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Prospects_For_Cooperation_business__c.field-meta.xml
<CustomField>
    <fullName>Prospects_For_Cooperation_business__c</fullName>
    <label>Prospects For Cooperation/business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Limit_Application__c/fields/Trade_Background__c.field-meta.xml
<CustomField>
    <fullName>Trade_Background__c</fullName>
    <label>Trade Background</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CLAPrintPDFController.cls
public without sharing class CLAPrintPDFController {
    
    // public CLAPrintPDFController(ApexPages.StandardController controller){}
    public Credit_Limit_Application__c creditLimitApplication{get;set;}
    public Account customer{get;set;}
    public String customerName{get;set;}

    public String competitorTrends{get;set;}
    public String hisenseClientOperatingConditions{get;set;}
    public String hisenseStrategicProgramProgress{get;set;}
    public String problemsToBeSolvedByHisense{get;set;}
    //Status_Quo_of_Industry__c
    public String StatusQuoOfIndustry{get;set;}
    public String hisenseOtherIssues{get;set;}
    //Order
    public String order{get;set;}
    public String inventory{get;set;}
    //Promotion
    public String promotion{get;set;}
    //10
    public String SKUDisplay{get;set;}
    //11 Products Recommendation
    public String productsRecommendation{get;set;}
    //12 Rebate and Support
    public String rebateAndSupport{get;set;}

    public List<String[]> hisenseList{get;set;}
    public List<String[]> customerList{get;set;}

    public Boolean showVisitDetailInfo{get;set;}

    public CLAPrintPDFController() {
        System.debug('CLAPrintPDFController starts...');

        String customerVisitId = ApexPages.CurrentPage().getParameters().get('ID');
        creditLimitApplication = [SELECT Name,Customer__c, Credit_Limit_for_Application_RAND__c, Payment_Method__c ,
        CURRENT_CREDIT_LIMITS__c, EXPECTED_THIS_YEAR_TOTAL_TURNOVER__c, MAXIMUM_TURNOVER_PER_ORDER__c,
        Export_Goods_Name__c,Latest_Shipping_Date__c, Last_3Years_Transaction_Amount_1_RAND__c,
        ORDER_PLAN__c,Buyer_English_Address__c, Buyer_Phone__c,TRADE_BACKGROUND__c,Credit_Application_Period_days__c,
        COMPANY_3_YEARS_TURNOVER__c,PROSPECTS_FOR_COOPERATION_BUSINESS__c,CreatedBy.name,Currency__c
        from Credit_Limit_Application__c  
        WHERE id=: customerVisitId LIMIT 1];
        
        if (String.isNotBlank(creditLimitApplication.Customer__c)) {
            customer = [SELECT Name FROM Account WHERE id=: creditLimitApplication.Customer__c];
            if (customer <> null) {
                customerName = customer.Name;
            } else {
                customerName = '';
            }
        } else {
            customerName = '';
        }

        ApexPages.currentPage().getHeaders().put('content-disposition', 
            '; filename=Credit Limit Application Report-' + customerName + '-' + Datetime.now().format('yyyyMMdd')+'.pdf');

        
    }
}