force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sony</fullName>
            </value>
            <value>
                <fullName>Daikin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Model__c/Product_Model__c.object-meta.xml
<CustomObject>
    <label>Product Model</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Display__c/Sample_Display__c.object-meta.xml
<CustomObject>
    <label>Sample Display</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Sample Display Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Display</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Display__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sample Display</relationshipLabel>
    <relationshipName>Sample_Display</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Model</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>$Source.Sales_Region__c</field>
            <operation>equals</operation>
            <valueField>Product__c.sales_region__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sample Display</relationshipLabel>
    <relationshipName>Sample_Display</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Sample Display</relationshipLabel>
    <relationshipName>Sample_Display</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display_Confirm__c/Sample_Display_Confirm__c.object-meta.xml
<CustomObject>
    <label>Sample Display Confirm</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Subtask Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Display Confirm</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Display_Confirm__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sample Display Confirm</relationshipLabel>
    <relationshipName>Store_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display_Confirm__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <formula>Sample_Display__r.Deadline__c</formula>
    <label>Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sample_Display_Confirm__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sample_Display_Confirm__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Model</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <valueField>Product__c.sales_region__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sample Display Confirm</relationshipLabel>
    <relationshipName>Store_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display_Confirm__c/fields/Sample_Display__c.field-meta.xml
<CustomField>
    <fullName>Sample_Display__c</fullName>
    <label>Sample Display</label>
    <referenceTo>Sample_Display__c</referenceTo>
    <relationshipLabel>Sample Display Confirm</relationshipLabel>
    <relationshipName>Sample_Display_Confirm</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sample_Display_Confirm__c/fields/Sample_Display_Code__c.field-meta.xml
<CustomField>
    <fullName>Sample_Display_Code__c</fullName>
    <formula>Sample_Display__r.Name</formula>
    <label>Sample Display Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Display_Confirm__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uncompleted</fullName>
                <default>true</default>
                <label>Uncompleted</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Display_Confirm__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Store_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sample_Removal__c/Sample_Removal__c.object-meta.xml
<CustomObject>
    <label>Sample Removal</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Sample Removal Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Removal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Removal__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <label>Deadline</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sample_Removal__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Model</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <valueField>Product__c.sales_region__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sample Removal</relationshipLabel>
    <relationshipName>Sample_Removal</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Removal__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Sample Removal</relationshipLabel>
    <relationshipName>Sample_Removal</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Removal_Confirm__c/Sample_Removal_Confirm__c.object-meta.xml
<CustomObject>
    <label>Sample Removal Confirm</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Subtask Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Removal Confirm</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Removal_Confirm__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Model</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sample Removal Confirm</relationshipLabel>
    <relationshipName>Sample_Removal_Confirm</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Removal_Confirm__c/fields/Sample_Removal_Code__c.field-meta.xml
<CustomField>
    <fullName>Sample_Removal_Code__c</fullName>
    <label>Sample Removal Code</label>
    <referenceTo>Sample_Removal__c</referenceTo>
    <relationshipLabel>Sample Removal Confirm</relationshipLabel>
    <relationshipName>Sample_Removal_Confirm</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sample_Removal_Confirm__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Sample Removal Confirm</relationshipLabel>
    <relationshipName>Sample_Removal_Confirm</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SubUser__c/SubUser__c.object-meta.xml
<CustomObject>
    <label>SubUser</label>
    <nameField>
        <label>SubUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubUser_Device__c/SubUser_Device__c.object-meta.xml
<CustomObject>
    <label>SubUser Device</label>
    <nameField>
        <label>SubUser Device Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubUser Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubUser_Device__c/fields/DeviceID__c.field-meta.xml
<CustomField>
    <fullName>DeviceID__c</fullName>
    <label>DeviceID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubUser_Device__c/fields/LastUsedTime__c.field-meta.xml
<CustomField>
    <fullName>LastUsedTime__c</fullName>
    <label>LastUsedTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SubUser_Device__c/fields/SubUserID__c.field-meta.xml
<CustomField>
    <fullName>SubUserID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubUserID</label>
    <referenceTo>SubUser__c</referenceTo>
    <relationshipLabel>SubUser Devices</relationshipLabel>
    <relationshipName>SubUser_Devices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubUserLog__c/SubUserLog__c.object-meta.xml
<CustomObject>
    <label>SubUserLog</label>
    <nameField>
        <displayFormat>SULC-{YYYY}{MM}{0000}</displayFormat>
        <label>SubUserLog Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubUserLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubUserLog__c/fields/Action_Time__c.field-meta.xml
<CustomField>
    <fullName>Action_Time__c</fullName>
    <label>Action Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SubUserLog__c/fields/DeviceID__c.field-meta.xml
<CustomField>
    <fullName>DeviceID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DeviceID</label>
    <referenceTo>SubUser_Device__c</referenceTo>
    <relationshipLabel>SubUserLogs</relationshipLabel>
    <relationshipName>SubUserLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubUserLog__c/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>StoreId</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>SubUserLogs</relationshipLabel>
    <relationshipName>SubUserLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubUserLog__c/fields/SubUser__c.field-meta.xml
<CustomField>
    <fullName>SubUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubUser</label>
    <referenceTo>SubUser__c</referenceTo>
    <relationshipLabel>SubUserLogs</relationshipLabel>
    <relationshipName>SubUserLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SampleDisplayConfirmController.cls
/*
 * @Author: WFC
 * @Date: 2024-12-26 10:12:18
 * @LastEditors: WFC
 * @LastEditTime: 2024-12-26 17:22:52
 * @Description: 样机确认
 * @FilePath: \hisense005\force-app\main\default\classes\SampleDisplayConfirmController.cls
 */
public with sharing class SampleDisplayConfirmController{
    /**
     * @Param:
     * @Return:
     * @Author: WFC
     * @Date: 2024-12-25 11:02:05
     * @Description: 获取sample display confrim 列表信息
     */
    @AuraEnabled
    public static List<Map<String, Object>> getSampleDisplayConfirmData(String deviceId){
        List<Map<String, Object>> result = new List<Map<String, Object>>();

        // 根据设备信息返回对应的门店id信息
        List<String> storeIdList = getStoreByDeviceId(deviceId);
        List<Sample_Display_Confirm__c> sdcList = [SELECT Id, Sample_Display__r.Name, Name, Product_Model__r.Name, Customer__r.Name, Store__r.Name, Number__c, Status__c, Deadline__c
                                                   FROM Sample_Display_Confirm__c
                                                   WHERE Store__c IN:storeIdList];
        for (Sample_Display_Confirm__c sdc : sdcList){
            Map<String, Object> temp = new Map<String, Object>();
            temp.put('Sample_Display_Code__c', sdc.Sample_Display__r.Name);
            temp.put('Name', sdc.Name);
            temp.put('NameToUrl', System.URL.getOrgDomainUrl().toExternalForm() + '/' + sdc.Id);
            temp.put('Product_Model__c', sdc.Product_Model__r.Name);
            temp.put('Customer__c', sdc.Customer__r.Name);
            temp.put('Store__c', sdc.Store__r.Name);
            temp.put('Number__c', sdc.Number__c);
            temp.put('Status__c', sdc.Status__c);
            temp.put('Deadline__c', sdc.Deadline__c);

            result.add(temp);
        }
        return result;
    }

    /**
     * @Param:
     * @Return:
     * @Author: WFC
     * @Date: 2024-12-25 11:02:05
     * @Description: 获取sample removal confirm 列表信息
     */
    @AuraEnabled
    public static List<Map<String, Object>> getSampleRemovalConfirmData(String deviceId){
        List<Map<String, Object>> result = new List<Map<String, Object>>();

        // 根据设备信息返回对应的门店id信息
        List<String> storeIdList = getStoreByDeviceId(deviceId);
        List<Sample_Removal_Confirm__c> sdcList = [SELECT Id, Sample_Removal_Code__r.Name, Name, Product_Model__r.Name, Store__r.Name, Number__c, Status__c, Deadline__c
                                                   FROM Sample_Removal_Confirm__c
                                                   WHERE Store__c IN:storeIdList];
        for (Sample_Removal_Confirm__c sdc : sdcList){
            Map<String, Object> temp = new Map<String, Object>();
            temp.put('Sample_Removal_Code__c', sdc.Sample_Removal_Code__r.Name);
            temp.put('Name', sdc.Name);
            temp.put('NameToUrl', System.URL.getOrgDomainUrl().toExternalForm() + '/' + sdc.Id);
            temp.put('Product_Model__c', sdc.Product_Model__r.Name);
            temp.put('Store__c', sdc.Store__r.Name);
            temp.put('Number__c', sdc.Number__c);
            temp.put('Status__c', sdc.Status__c);
            temp.put('Deadline__c', sdc.Deadline__c);

            result.add(temp);
        }
        return result;
    }

    // 根据设备信息返回对应的门店id信息
    public static List<String> getStoreByDeviceId(String deviceId){
        List<String> storeIdList = new List<String>();
        // 通过设备唯一标识查询SubUser_Device__c表是否存在
        List<SubUser_Device__c> subUserDeviceList = getSubUserDeviceId(deviceId);
        if (subUserDeviceList != null && subUserDeviceList.size() > 0){
            // 获取SubUserDevice
            SubUser_Device__c subUserDevice = subUserDeviceList.get(0);
            // 根据SubUserDevice查询SubUserLog表
            List<SubUserLog__c> subUserLogList = getSubUserLog(subUserDevice.Id);
            // 获取对应的门店
            LisqContainer lc = new LisqContainer(subUserLogList);
            storeIdList = lc.SelectSField('StoreId__c');
        }
        return storeIdList;
    }

    // 根据DeviceID查询SubUserLog
    public static List<SubUserLog__c> getSubUserLog(String deviceId){
        return [SELECT Id, SubUser__c, StoreId__c, StoreId__r.Name, Action_Time__c, DeviceID__c
                FROM SubUserLog__c
                WHERE DeviceID__c = :deviceId];
    }

    // 根据设备信息获取SubUserDevice
    public static List<SubUser_Device__c> getSubUserDeviceId(String deviceId){
        return [SELECT Id, SubUserID__c, DeviceID__c, LastUsedTime__c, IsActive__c
                FROM SubUser_Device__c
                WHERE DeviceID__c = :deviceId];
    }

}