force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/Promoter_Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Report</label>
    <nameField>
        <displayFormat>PWR-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>日报编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DailyReports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/PromoterDailyReport__c.field-meta.xml
<CustomField>
    <fullName>PromoterDailyReport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>周调研问题反馈</label>
    <referenceTo>WeekResearchResponse__c</referenceTo>
    <relationshipName>WeekResearchResponse_PromoterDailyReport</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <label>报告日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only related stores are available.</inlineHelpText>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Daily Reports</relationshipLabel>
    <relationshipName>Shop_Promoter_Week_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReturnsAndCredit__c/ReturnsAndCredit__c.object-meta.xml
<CustomObject>
    <label>Returns And Credit</label>
    <nameField>
        <displayFormat>RC-{YYYY}{MM}{DD}{00000}</displayFormat>
        <label>Return No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returns And Credit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ReturnsAndCredit__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Returns And Credit</relationshipLabel>
    <relationshipName>ReturnsAndCredit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReturnsAndCredit__c/fields/IsAllPaperworkInOrder__c.field-meta.xml
<CustomField>
    <fullName>IsAllPaperworkInOrder__c</fullName>
    <label>Is All Paperwork In Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReturnsAndCredit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>$User.Country</field>
            <operation>equals</operation>
            <valueField>Product__c.sales_region__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <valueField>Product__c.sales_region__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.ManageUsers</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Returns And Credit</relationshipLabel>
    <relationshipName>Returns_And_Credit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReturnsAndCredit__c/fields/PromoterDailyReport__c.field-meta.xml
<CustomField>
    <fullName>PromoterDailyReport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promoter Daily Report</label>
    <referenceTo>Promoter_Daily_Report__c</referenceTo>
    <relationshipLabel>Returns And Credit</relationshipLabel>
    <relationshipName>Returns_And_Credit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReturnsAndCredit__c/fields/ProvideCreditNumber__c.field-meta.xml
<CustomField>
    <fullName>ProvideCreditNumber__c</fullName>
    <label>Provide  Credit Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReturnsAndCredit__c/fields/ProvideJobNumber__c.field-meta.xml
<CustomField>
    <fullName>ProvideJobNumber__c</fullName>
    <label>Provide Job Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReturnsAndCredit__c/fields/ReturnedQuantity__c.field-meta.xml
<CustomField>
    <fullName>ReturnedQuantity__c</fullName>
    <label>Returned Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReturnsAndCredit__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <valueField>Shop__c.Sales_Region__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Country</field>
            <operation>equals</operation>
            <valueField>Shop__c.Sales_Region__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.ManageUsers</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Returns And Credit</relationshipLabel>
    <relationshipName>Returns_And_Credit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReturnsAndCredit__c/fields/UserFeedbackSources__c.field-meta.xml
<CustomField>
    <fullName>UserFeedbackSources__c</fullName>
    <label>User Feedback Sources</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReturnsAndCredit__c/fields/WhatPaperworkIsMissing__c.field-meta.xml
<CustomField>
    <fullName>WhatPaperworkIsMissing__c</fullName>
    <label>What Paperwork Is Missing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shop_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReturnsAndCreditController.cls
public without sharing class ReturnsAndCreditController {
    @AuraEnabled
    public static ConResponse saveRecord(String recordDataJson, List<String> deleteRecordIdList, String fileMapJson, String recordId){
    	
        System.debug('ReturnsAndCreditController ——> saveRecord：');
        System.debug('ReturnsAndCreditController ——> recordDataJson：' + recordDataJson);
        ConResponse resp = new ConResponse();
        Map<string, object> mso = new Map<string, object>();
        Promoter_Daily_Report__c promoterReport = [SELECT Id, Name, Report_Date__c, Shop__c, Shop__r.Name FROM Promoter_Daily_Report__c WHERE Id = :recordId];
        Shop__c store = [SELECT Id, Account__c FROM Shop__c WHERE Id = :promoterReport.Shop__c];

        List<Map<String, String>> dataList = (List<Map<String, String>>)JSON.deserialize(recordDataJson, List<Map<String, String>>.class);
        
        List<ReturnsAndCredit__c> insertReturnsAndCreditList = new List<ReturnsAndCredit__c>();
        List<ReturnsAndCredit__c> updateReturnsAndCreditList = new List<ReturnsAndCredit__c>();
        List<ReturnsAndCredit__c> deleteReturnsAndCreditList = [SELECT Id FROM ReturnsAndCredit__c WHERE Id IN :deleteRecordIdList];
        
        if(dataList.size() > 0) {
            for(Map<String, String> data : dataList) {
                String dataJson = Json.serialize(data);
                System.debug('dataJson ==> ' + dataJson);
                ReturnsAndCredit__c returnsAndCredit = (ReturnsAndCredit__c)JSON.deserialize(dataJson, ReturnsAndCredit__c.class);
                System.debug('returnsAndCredit ==> ' + returnsAndCredit);
                if(data.containsKey('Id')) {
                	if(data.containsKey('fieldsEdit') && (data.get('fieldsEdit') == 'true')) {
                    	// 修改已有记录
                    	updateReturnsAndCreditList.add(returnsAndCredit);
                	}
                } else {
                	// 新建记录
                	returnsAndCredit.Store__c = promoterReport.Shop__c;
                	returnsAndCredit.PromoterDailyReport__c = recordId;
                    returnsAndCredit.Customer__c = store.Account__c;
                	insertReturnsAndCreditList.add(returnsAndCredit);
                }                 
            }
        }
        System.Savepoint sp = Database.setSavepoint();
        try{  

            if(insertReturnsAndCreditList.size() > 0) {
                insert insertReturnsAndCreditList;

                UploadFilesController.saveFiles(recordDataJson, fileMapJson, insertReturnsAndCreditList, recordId);
            }
            
            if(updateReturnsAndCreditList.size() > 0) {
                update updateReturnsAndCreditList;
            }
            
            if(deleteReturnsAndCreditList.size() > 0) {
                delete deleteReturnsAndCreditList;
            }

            List<ReturnsAndCredit__c> returnsAndCreditList = [SELECT Id, Name, UserFeedbackSources__c, Description__c, ReturnedQuantity__c, Product__c, 
                                                                        Quantity__c, Reason__c, Comments__c, ProvideJobNumber__c, Store__c, PromoterDailyReport__c, 
                                                                        ProvideCreditNumber__c, IsAllPaperworkInOrder__c, WhatPaperworkIsMissing__c 
                                                                    FROM ReturnsAndCredit__c
                                                                    WHERE PromoterDailyReport__c = :recordId ORDER BY CreatedDate ];
            Map<String, List<ReturnsAndCredit__c>> researchListGroupByNo = researchListGroupByNo(returnsAndCreditList);
            mso.put('researchListGroupByNo', researchListGroupByNo);
            resp.data = mso;
            resp.message = 'Save successfully！';

        }catch (Exception e) {
        	System.debug(LoggingLevel.ERROR, e.getMessage());
        	System.debug(LoggingLevel.ERROR, e.getStackTraceString());
        	Database.rollback(sp);
        	resp.message = e.getMessage() + '\n' + e.getStackTraceString();
        	resp.code = -1;
        }

        return resp;
    }

    @AuraEnabled
    public static ConResponse getInitData(String recordId){
        ConResponse resp = new ConResponse();
        Map<string, object> mso = new Map<string, object>();

        Promoter_Daily_Report__c promoterReport = [SELECT Id, Name, Report_Date__c, Shop__c, Shop__r.Name FROM Promoter_Daily_Report__c WHERE Id = :recordId];
        mso.put('reportDate', promoterReport.Report_Date__c);
        
        List<ReturnsAndCredit__c> returnsAndCreditList = [SELECT Id, Name, UserFeedbackSources__c, Description__c, ReturnedQuantity__c, Product__c, 
                                                                    Quantity__c, Reason__c, Comments__c, ProvideJobNumber__c, Store__c, PromoterDailyReport__c,
                                                                    ProvideCreditNumber__c, IsAllPaperworkInOrder__c, WhatPaperworkIsMissing__c 
                                                                FROM ReturnsAndCredit__c
                                                                WHERE PromoterDailyReport__c = :recordId ORDER BY CreatedDate ];
        mso.put('returnsAndCreditList', returnsAndCreditList);
        mso.put('fields', SObjectHelper.getFieldLabelMap('ReturnsAndCredit__c'));
        if(returnsAndCreditList.size() == 0) {
            system.debug('null');
            resp.data = mso; 
            return resp;
        }

        Map<String, List<ReturnsAndCredit__c>> researchListGroupByNo = researchListGroupByNo(returnsAndCreditList);
        mso.put('researchListGroupByNo', researchListGroupByNo);
        system.debug('researchListGroupByNo：' + researchListGroupByNo);
		resp.data = mso;        
        return resp;
    }

    static Map<String, List<ReturnsAndCredit__c>> researchListGroupByNo(List<ReturnsAndCredit__c> returnsAndCreditList) {
        Map<String, List<ReturnsAndCredit__c>> researchListGroupByNo = new Map<String, List<ReturnsAndCredit__c>>();
        for(ReturnsAndCredit__c item : returnsAndCreditList){
            system.debug('item :' + item);
            if(researchListGroupByNo.containsKey(item.Name)) {
                researchListGroupByNo.get(item.Name).add(item);
                system.debug('containsKey ——> researchListGroupByNo :' + researchListGroupByNo);
            } else {
                researchListGroupByNo.put(item.Name, new List<ReturnsAndCredit__c>{item});
                system.debug('not containsKey ——> researchListGroupByNo :' + researchListGroupByNo);
            }
        }
        return researchListGroupByNo;
    }
}