force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shop Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product</relationshipLabel>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>Small Domestic Home Appliances</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>Sound Bar</fullName>
            </value>
            <value>
                <fullName>Hitachi Commercial AC</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>B-Monitor</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/recordTypes/Gift.recordType-meta.xml
<RecordType>
    <fullName>Gift</fullName>
    <active>true</active>
    <label>Gift</label>
</RecordType>

force-app/main/default/objects/Retail_Number__c/Retail_Number__c.object-meta.xml
<CustomObject>
    <label>Daily Sales</label>
    <nameField>
        <displayFormat>RN-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>零售业绩编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Sales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Number__c/fields/Change_Daily_Sales_History__c.field-meta.xml
<CustomField>
    <fullName>Change_Daily_Sales_History__c</fullName>
    <label>*Change Daily Sales History</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Created_Email__c.field-meta.xml
<CustomField>
    <fullName>Created_Email__c</fullName>
    <formula>CreatedBy.Email</formula>
    <label>Created Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>DailySales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer__r.Name</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <formula>Product__r.Categorys__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gift</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Gift</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Gifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/GiftQuantity__c.field-meta.xml
<CustomField>
    <fullName>GiftQuantity__c</fullName>
    <label>Gift Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/HasGift__c.field-meta.xml
<CustomField>
    <fullName>HasGift__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Gift</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/IsSampling__c.field-meta.xml
<CustomField>
    <fullName>IsSampling__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sampling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/IsUpload__c.field-meta.xml
<CustomField>
    <fullName>IsUpload__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsUpload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Kiosk__c.field-meta.xml
<CustomField>
    <fullName>Kiosk__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kiosk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>销量</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <formula>PromoterDailyReport__r.Owner_text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <formula>CASESAFEID(PromoterDailyReport__r.OwnerId)</formula>
    <label>OwnerId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>产品</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND (5 OR 6)) OR 7</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ALL_Product_Japan</value>
        </filterItems>
        <filterItems>
            <field>$User.Country__c</field>
            <operation>notEqual</operation>
            <value>South Africa, Indonesia, Chile</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>notEqual</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RegionalProduct</value>
        </filterItems>
        <filterItems>
            <field>$User.Country__c</field>
            <operation>equals</operation>
            <value>South Africa, Indonesia, Chile,Thailand,Singapore</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile, Hisense Argentina, Hisense West Africa, Hisense Saudi, Hisense Canada, Hisense USA, Hisense Mexico, Hisense Thailand, Hisense Vietnam, Hisense Malaysia,Hisense Philippines,Hisense Peru</value>
        </filterItems>
        <filterItems>
            <field>$Profile.ManageUsers</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Daily Sales (产品)</relationshipLabel>
    <relationshipName>ProductdalH</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>Text(Product__r.Product_Line__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/ProductBrand__c.field-meta.xml
<CustomField>
    <fullName>ProductBrand__c</fullName>
    <formula>Text(Product__r.Product__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <formula>Product__r.Category__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>产品分类</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <label>Product Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/ProductSeries__c.field-meta.xml
<CustomField>
    <fullName>ProductSeries__c</fullName>
    <formula>Product__r.Series__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>产品系列</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Number__c/fields/PromoterDailyReport__c.field-meta.xml
<CustomField>
    <fullName>PromoterDailyReport__c</fullName>
    <label>促销员日报</label>
    <referenceTo>Promoter_Daily_Report__c</referenceTo>
    <relationshipName>RetailNumbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesGoal__c/SalesGoal__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Sales Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesGoal__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Targets</relationshipLabel>
    <relationshipName>Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesGoal__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Is_Export__c.field-meta.xml
<CustomField>
    <fullName>Is_Export__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Export</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendDailySalesToBigData.cls
/**********************************************************************
 * function:将Daily Sales推送给大数据
 * @author:lizunxing
 * @url: /services/apexrest
 * @data: 
 * date:2024-01-31
*************************************************************************/
@RestResource(urlMapping='/SendDailySalesToBigData')
global with sharing class SendDailySalesToBigData {  

    global class AppInput{
        public String startTime; 
        public String endTime; 
        public String pageIndex;
        public String pageSize;
    }
    global class AppOutPut{
        public Integer totalPage;
        List<DailySalesInfo> dailySalesInfoList;
    }

    public class DailySalesInfo {
        public String id;
        public String Name;
        public String CreatedDate;
        public String LastModifiedDate;  
        public String CurrencyIsoCode;
        public String Brand;
        public String ChangeDailySalesHistory;
        public String Comments;
        public String CreatedEmail;
        public String CustomerName;
        public String Customer;
        public String Description;
        public String District;
        public String GiftQuantity;
        public String Gift;
        public String HasGift;
        public String IsSampling;
        public String IsUpload;
        public String IsExport;
        public String Kiosk;
        public String ListPrice;
        public String Number1;
        public String OwnerId;
        public String Owner;
        public String Price;
        public String ProductBrand;
        public String ProductCategory;
        public String ProductLine;
        public String ProductSeries;
        public String Product_Category;
        public String Product_Line;
        public String Product;
        public String PromoterDailyReport;
        public String ReportDate;
        public String Reportmonth;
        public String Reportyear;
        public String SPIV;
        public String SalesGoal;
        public String SalesRegion;
        public String SameMonth;
        public String Shop;
        public String Status;
        public String StoreDelivery;
        public String StoreSalesRegion;
        public String TotalPrice;
    }

    @HttpPost
    global static SendDailySalesToBigData.AppOutPut adoPost() {

        RestRequest req = RestContext.request;
        String reqBody = req.requestBody.tostring(); 
        //String reqBody = '{"startTime":"2024-01-09 00:00:00","endTime":"2024-01-10 00:00:00"}'; 
        SendDailySalesToBigData.AppInput appInput = new SendDailySalesToBigData.AppInput();
        
        SendDailySalesToBigData.AppOutPut result = new SendDailySalesToBigData.AppOutPut();
        
        try{
            appInput = (SendDailySalesToBigData.AppInput)JSON.deserialize(reqBody, SendDailySalesToBigData.AppInput.class);

            if(String.isBlank(appInput.startTime) || String.isBlank(appInput.endTime)){
                return result;
            }

            if(String.isBlank(appInput.pageIndex)){
                appInput.pageIndex = '1';
            }

            if(String.isBlank(appInput.pageSize) || Integer.valueOf(appInput.pageSize) < 200){
                appInput.pageSize = '200';
            }

            appInput.startTime = Utility.increaseHoursInStringDate(appInput.startTime,8).replace(' ','T') + '.000+0000';
            appInput.endTime = Utility.increaseHoursInStringDate(appInput.endTime,8).replace(' ','T') + '.000+0000';

            String sql = 'select '+
            'id,'+
            'Name,'+
            'CreatedDate,'+
            'LastModifiedDate, '+
            'CurrencyIsoCode,'+
            'Brand__c,'+
            'Change_Daily_Sales_History__c,'+
            'Comments__c,'+
            'Created_Email__c,'+
            'Customer_Name__c,'+
            'Customer__c,'+
            'Description__c,'+
            'District__c,'+
            'GiftQuantity__c,'+
            'Gift__c,'+
            'HasGift__c,'+
            'IsSampling__c,'+
            'IsUpload__c,'+
            'Is_Export__c,'+
            'Kiosk__c,'+
            'List_Price__c,'+
            'Number__c,'+
            'OwnerId__c,'+
            'Owner__c,'+
            'Price__c,'+
            'ProductBrand__c,'+
            'ProductCategory__c,'+
            'ProductLine__c,'+
            'ProductSeries__c,'+
            'Product_Category__c,'+
            'Product_Line__c,'+
            'Product__c,'+
            'PromoterDailyReport__c,'+
            'ReportDate__c,'+
            'Reportmonth__c,'+
            'Reportyear__c,'+
            'SPIV__c,'+
            'SalesGoal__c,'+
            'Sales_Region__c,'+
            'SameMonth__c,'+
            'Shop__c,'+
            'Status__c,'+
            'StoreDelivery__c,'+
            'Store_Sales_Region__c,'+
            'TotalPrice__c'+

            ' from Retail_Number__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            List<Retail_Number__c> DailySalesList = (List<Retail_Number__c>)Utility.getRecordListPage(sql, appInput.pageIndex, appInput.pageSize);

            List<DailySalesInfo> DailySalesInfoList = new List<DailySalesInfo>();

            for(Retail_Number__c a : DailySalesList){
                DailySalesInfo c = new DailySalesInfo();
                c.id = a.id;
                c.Name = a.Name;
                c.CreatedDate = checkNull(a.CreatedDate + '');
                c.LastModifiedDate = checkNull(a.LastModifiedDate + '');
                c.CurrencyIsoCode = checkNull(a.CurrencyIsoCode + '');
                c.Brand = checkNull(a.Brand__c + '');
                c.ChangeDailySalesHistory = checkNull(a.Change_Daily_Sales_History__c + '');
                c.Comments = checkNull(a.Comments__c + '');
                c.CreatedEmail = checkNull(a.Created_Email__c + '');
                c.CustomerName = checkNull(a.Customer_Name__c + '');
                c.Customer = checkNull(a.Customer__c + '');
                c.Description = checkNull(a.Description__c + '');
                c.District = checkNull(a.District__c + '');
                c.GiftQuantity = checkNull(a.GiftQuantity__c + '');
                c.Gift = checkNull(a.Gift__c + '');
                c.HasGift = checkNull(a.HasGift__c + '');
                c.IsSampling = checkNull(a.IsSampling__c + '');
                c.IsUpload = checkNull(a.IsUpload__c + '');
                c.IsExport = checkNull(a.Is_Export__c + '');
                c.Kiosk = checkNull(a.Kiosk__c + '');
                c.ListPrice = checkNull(a.List_Price__c + '');
                c.Number1 = checkNull(a.Number__c + '');
                c.OwnerId = checkNull(a.OwnerId__c + '');
                c.Owner = checkNull(a.Owner__c + '');
                c.Price = checkNull(a.Price__c + '');
                c.ProductBrand = checkNull(a.ProductBrand__c + '');
                c.ProductCategory = checkNull(a.ProductCategory__c + '');
                c.ProductLine = checkNull(a.ProductLine__c + '');
                c.ProductSeries = checkNull(a.ProductSeries__c + '');
                c.Product_Category = checkNull(a.Product_Category__c + '');
                c.Product_Line = checkNull(a.Product_Line__c + '');
                c.Product = checkNull(a.Product__c + '');
                c.PromoterDailyReport = checkNull(a.PromoterDailyReport__c + '');
                c.ReportDate = checkNull(a.ReportDate__c + '');
                c.Reportmonth = checkNull(a.Reportmonth__c + '');
                c.Reportyear = checkNull(a.Reportyear__c + '');
                c.SPIV = checkNull(a.SPIV__c + '');
                c.SalesGoal = checkNull(a.SalesGoal__c + '');
                c.SalesRegion = checkNull(a.Sales_Region__c + '');
                c.SameMonth = checkNull(a.SameMonth__c + '');
                c.Shop = checkNull(a.Shop__c + '');
                c.Status = checkNull(a.Status__c + '');
                c.StoreDelivery = checkNull(a.StoreDelivery__c + '');
                c.StoreSalesRegion = checkNull(a.Store_Sales_Region__c + '');
                c.TotalPrice = checkNull(a.TotalPrice__c + '');
                DailySalesInfoList.add(c);
            }
            result.DailySalesInfoList = DailySalesInfoList;
            
            String sql1 = 'select count(id) totalNumber from Retail_Number__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            List<AggregateResult> c = Database.query(sql1);
            result.totalPage = (Integer.valueOf(c.get(0).get('totalNumber')) + Integer.valueOf(appInput.pageSize) - 1) / Integer.valueOf(appInput.pageSize);

            System.debug('result :' + result);
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendDailySalesToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '1';
            ic.Req_Json__c = reqBody + '---返回条数' + c.get(0).get('totalNumber');
            insert ic;

            return result; 
        }catch(Exception e){
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendDailySalesToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '0';
            ic.Req_Json__c = reqBody;
            ic.ErrorMsg__c = e.getMessage();
            insert ic;

            return result; 
        }
    }

    public static String checkNull(String str){
        if(String.isBlank(str)){
            return '';
        }else if('null'.equals(str)){
            return '';
        }else{
            return str;
        }
    }
}