force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sampling_Detail__c/Sampling_Detail__c.object-meta.xml
<CustomObject>
    <label>Sampling Detail</label>
    <nameField>
        <displayFormat>SD{yyyy}{mm}{dd}{000000}</displayFormat>
        <label>出样明细编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sampling Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Detail__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>外键</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sampling_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>产品</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND (5 OR 6)) OR 7</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ALL_Product_Japan</value>
        </filterItems>
        <filterItems>
            <field>$User.Country</field>
            <operation>notEqual</operation>
            <value>South Africa, Indonesia, Chile, Thailand, Vietnam,Malaysia,Argentina,West Africa,Saudi,Canada,Colombia,Philippines,Peru,USA,Mexico</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>notEqual</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile, Hisense Thailand, Hisense Vietnam,Hisense Malaysia,Hisense Colombia,Hisense Argentina,Hisense West Africa,Hisense Saudi,Hisense Canada,Hisense Philippines,Hisense Peru,Hisense USA,Hisense Mexico</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RegionalProduct</value>
        </filterItems>
        <filterItems>
            <field>$User.Country</field>
            <operation>equals</operation>
            <value>South Africa, Indonesia, Chile, Thailand, Vietnam,Malaysia,Argentina,West Africa,Saudi,Canada,Colombia,Philippines,Peru,USA,Mexico</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <valueField>Product__c.sales_region__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.ManageUsers</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sampling Detail</relationshipLabel>
    <relationshipName>Sampling_Detail_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Detail__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>出样明细</relationshipLabel>
    <relationshipName>Sampling_Detail_Shop</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/Sampling_Inspection__c.object-meta.xml
<CustomObject>
    <label>Sampling Inspection</label>
    <nameField>
        <displayFormat>SI-{YYYY}{MM}{0000}</displayFormat>
        <label>出样检查编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sampling Inspection</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Inspection__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>任务Id+机型属性Id</description>
    <externalId>true</externalId>
    <label>外键</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>产品</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5)) OR 6 OR 7</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ALL_Product_Japan</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>notEqual</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile, Hisense Thailand, Hisense Malaysia, Hisense Vietnam,Hisense Colombia,Hisense Argentina,Hisense West Africa,Hisense Saudi,Hisense Canada,Hisense Philippines,Hisense Peru,Hisense USA,Hisense Mexico</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RegionalProduct</value>
        </filterItems>
        <filterItems>
            <field>$User.Country__c</field>
            <operation>equals</operation>
            <value>South Africa, Indonesia, Chile, Thailand, Malaysia, Vietnam,Argentina,West Africa,Saudi,Canada,Colombia,Philippines,Peru, Mexico</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile, Hisense Thailand, Hisense Malaysia, Hisense Vietnam,Hisense Colombia,Hisense Argentina,Hisense West Africa,Hisense Saudi,Hisense Canada,Hisense Philippines,Hisense Peru, Hisense USA, Hisense Mexico</value>
        </filterItems>
        <filterItems>
            <field>$Profile.ManageUsers</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <value>Hisense International</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sampling Inspection</relationshipLabel>
    <relationshipName>Sampling_Inspection_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Sample_Item__c.field-meta.xml
<CustomField>
    <fullName>Sample_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>出样明细</label>
    <referenceTo>Sampling_Detail__c</referenceTo>
    <relationshipName>MVrr</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Sampling_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SamplingInspectionHandler.cls
public without sharing class SamplingInspectionHandler implements Triggers.Handler {
    public void handle() {
        
        if (Trigger.isBefore && (Trigger.isInsert || Trigger.isUpdate)) {

            List<String> keyList = new List<String>();

            for (Sampling_Inspection__c samplingInspection : (List<Sampling_Inspection__c>)Trigger.new) {
				// 出样明细为空
                if(samplingInspection.Sample_Item__c == null){
                    System.debug('wwww---' + samplingInspection.id);
                    // 门店的出样明细的外键
                    keyList.add(samplingInspection.Shop__c + '-' + samplingInspection.Product__c);
                }
			}
            System.debug('wwww---' + keyList);
            // 查询门店的出样明细
            List<Sampling_Detail__c> samplingDetailList = [SELECT id,ExternalID__c FROM Sampling_Detail__c WHERE ExternalID__c IN :keyList];
            Map<String, Id> samplingDetailMap = new Map<String, Id>();
            for (Sampling_Detail__c sd : samplingDetailList) {
                samplingDetailMap.put(sd.ExternalID__c, sd.Id);
            }
            System.debug('wwww---' + samplingDetailMap);

            for (Sampling_Inspection__c samplingInspection : (List<Sampling_Inspection__c>)Trigger.new) {
				// 出样明细为空
                if(samplingInspection.Sample_Item__c == null){
                    samplingInspection.Sample_Item__c = samplingDetailMap.get(samplingInspection.Shop__c + '-' + samplingInspection.Product__c);
                }
			}
        }
            
    }    
}