force-app/main/default/objects/Inspection_Shop_Task__c/Inspection_Shop_Task__c.object-meta.xml
<CustomObject>
    <label>Inspection Task</label>
    <nameField>
        <displayFormat>IST-{YYYY}{MM}{0000}</displayFormat>
        <label>任务编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Shop_Task__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>日期+门店</description>
    <externalId>true</externalId>
    <label>外键</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Task__c/fields/Inspection_Date__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Date__c</fullName>
    <description>计划巡店的日期</description>
    <inlineHelpText>Date of planned store visit</inlineHelpText>
    <label>巡店日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Task__c/fields/IsNew__c.field-meta.xml
<CustomField>
    <fullName>IsNew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>*IsNew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Task__c/fields/Share_Gridding_Code__c.field-meta.xml
<CustomField>
    <fullName>Share_Gridding_Code__c</fullName>
    <formula>Shop__r.Grid__r.Gridding_Code__c</formula>
    <label>*共享网格</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Task__c/fields/Share_Shop__c.field-meta.xml
<CustomField>
    <fullName>Share_Shop__c</fullName>
    <formula>Shop__r.External_Key_ID__c</formula>
    <label>*共享门店</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inspection_Shop_Task__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Inspection_Shop_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/InterfaceLog__c.object-meta.xml
<CustomObject>
    <label>InterfaceLog</label>
    <nameField>
        <label>No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InterfaceLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InterfaceLog__c/fields/ErrorMsg__c.field-meta.xml
<CustomField>
    <fullName>ErrorMsg__c</fullName>
    <label>ErrorMsg</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/Req_Json__c.field-meta.xml
<CustomField>
    <fullName>Req_Json__c</fullName>
    <label>Req Json</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InterfaceLog__c/fields/ReturnCode__c.field-meta.xml
<CustomField>
    <fullName>ReturnCode__c</fullName>
    <label>ReturnCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/Sampling_Inspection__c.object-meta.xml
<CustomObject>
    <label>Sampling Inspection</label>
    <nameField>
        <displayFormat>SI-{YYYY}{MM}{0000}</displayFormat>
        <label>出样检查编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sampling Inspection</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sampling_Inspection__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>任务Id+机型属性Id</description>
    <externalId>true</externalId>
    <label>外键</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Inspection_Date__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Date__c</fullName>
    <description>巡店检查日期</description>
    <label>检查日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Inspection_Shop_Task__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Shop_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店任务</label>
    <referenceTo>Inspection_Shop_Task__c</referenceTo>
    <relationshipName>Task_Sampling_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Is_Export__c.field-meta.xml
<CustomField>
    <fullName>Is_Export__c</fullName>
    <externalId>true</externalId>
    <label>Is_Export</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Placement_Status__c.field-meta.xml
<CustomField>
    <fullName>Placement_Status__c</fullName>
    <description>出样状态</description>
    <label>展出状态</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Placement_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>产品</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5)) OR 6 OR 7</booleanFilter>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>ALL_Product_Japan</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>notEqual</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile, Hisense Thailand, Hisense Malaysia, Hisense Vietnam,Hisense Colombia,Hisense Argentina,Hisense West Africa,Hisense Saudi,Hisense Canada,Hisense Philippines,Hisense Peru,Hisense USA,Hisense Mexico</value>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RegionalProduct</value>
        </filterItems>
        <filterItems>
            <field>$User.Country__c</field>
            <operation>equals</operation>
            <value>South Africa, Indonesia, Chile, Thailand, Malaysia, Vietnam,Argentina,West Africa,Saudi,Canada,Colombia,Philippines,Peru, Mexico</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <value>Hisense South Africa, Hisense Indonesia, Hisense Chile, Hisense Thailand, Hisense Malaysia, Hisense Vietnam,Hisense Colombia,Hisense Argentina,Hisense West Africa,Hisense Saudi,Hisense Canada,Hisense Philippines,Hisense Peru, Hisense USA, Hisense Mexico</value>
        </filterItems>
        <filterItems>
            <field>$Profile.ManageUsers</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <value>Hisense International</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sampling Inspection</relationshipLabel>
    <relationshipName>Sampling_Inspection_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/ReRe__c.field-meta.xml
<CustomField>
    <fullName>ReRe__c</fullName>
    <description>出样描述</description>
    <label>出样描述</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Sample_Images_Url__c.field-meta.xml
<CustomField>
    <fullName>Sample_Images_Url__c</fullName>
    <label>图片链接</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Sample_Item__c.field-meta.xml
<CustomField>
    <fullName>Sample_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>出样明细</label>
    <referenceTo>Sampling_Detail__c</referenceTo>
    <relationshipName>MVrr</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Share_Gridding_Code__c.field-meta.xml
<CustomField>
    <fullName>Share_Gridding_Code__c</fullName>
    <formula>Shop__r.Grid__r.Gridding_Code__c</formula>
    <label>*网格Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Sampling_Inspection</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Sort__c.field-meta.xml
<CustomField>
    <fullName>Sort__c</fullName>
    <formula>IF( Flag__c , 2, CASE( Placement_Status__c , &apos;展出&apos;, 1, 3))</formula>
    <label>Sort</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sampling_Inspection__c/fields/Unplanned_Sample__c.field-meta.xml
<CustomField>
    <fullName>Unplanned_Sample__c</fullName>
    <description>是否是计划外出样</description>
    <inlineHelpText>If it is unplanned sample</inlineHelpText>
    <label>Unplanned Sample</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Is_Export__c.field-meta.xml
<CustomField>
    <fullName>Is_Export__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Export</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unplanned_Sample__c/Unplanned_Sample__c.object-meta.xml
<CustomObject>
    <label>Unplanned Sample</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unplanned Samples</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Unplanned_Sample__c/fields/Placement_Status__c.field-meta.xml
<CustomField>
    <fullName>Placement_Status__c</fullName>
    <label>Display Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>展出</fullName>
            </value>
            <value>
                <fullName>未展出</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unplanned_Sample__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Unplanned Samples</relationshipLabel>
    <relationshipName>Unplanned_Samples</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Placement_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>展出</fullName>
        <label>Exhibited</label>
    </customValue>
    <customValue>
        <fullName>未展出</fullName>
        <default>true</default>
        <label>Unexhibited</label>
    </customValue>
    <customValue>
        <fullName>処分推進</fullName>
        <isActive>false</isActive>
        <label>処分推進</label>
    </customValue>
    <customValue>
        <fullName>Sampled</fullName>
        <isActive>false</isActive>
        <label>Sampled</label>
    </customValue>
    <customValue>
        <fullName>Not Sampled</fullName>
        <isActive>false</isActive>
        <label>Not Sampled</label>
    </customValue>
    <customValue>
        <fullName>Withdrawal</fullName>
        <isActive>false</isActive>
        <label>Withdrawal</label>
    </customValue>
    <masterLabel>展出状态</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendSamplingInspectionToBigData.cls
/**********************************************************************
 * function:将Sampling Inspection推送给大数据
 * @author:lizunxing
 * @url: /services/apexrest
 * @data: 
 * date:2024-01-31
*************************************************************************/
@RestResource(urlMapping='/SendSamplingInspectionToBigData')
global with sharing class SendSamplingInspectionToBigData {  

    global class AppInput{
        public String startTime; 
        public String endTime; 
        public String pageIndex;
        public String pageSize;
    }
    global class AppOutPut{
        public Integer totalPage;
        List<SamplingInspectionInfo> samplingInspectionInfoList;
    }

    public class SamplingInspectionInfo {
        public String id;	
        public String CreatedDate;	
        public String LastModifiedDate;	
        public String Name;	
        public String ExternalID;	
        public String Flag;	
        public String InspectionDate;	
        public String InspectionShopTask;	
        public String IsChange;	
        public String IsNew;	
        public String IsExport;	
        public String PlacementStatus;	
        public String Product;	
        public String ReRe;	
        public String SampleImagesUrl;	
        public String SampleItem;	
        public String ShareGriddingCode;	
        public String ShareShop;	
        public String Shop;	
        public String Sort1;	
        public String UnplannedSample;	
    }

    @HttpPost
    global static SendSamplingInspectionToBigData.AppOutPut adoPost() {

        RestRequest req = RestContext.request;
        String reqBody = req.requestBody.tostring(); 
        //String reqBody = '{"startTime":"2024-01-09 00:00:00","endTime":"2024-01-10 00:00:00"}'; 
        SendSamplingInspectionToBigData.AppInput appInput = new SendSamplingInspectionToBigData.AppInput();
        
        SendSamplingInspectionToBigData.AppOutPut result = new SendSamplingInspectionToBigData.AppOutPut();
        
        try{
            appInput = (SendSamplingInspectionToBigData.AppInput)JSON.deserialize(reqBody, SendSamplingInspectionToBigData.AppInput.class);

            if(String.isBlank(appInput.startTime) || String.isBlank(appInput.endTime)){
                return result;
            }

            if(String.isBlank(appInput.pageIndex)){
                appInput.pageIndex = '1';
            }

            if(String.isBlank(appInput.pageSize) || Integer.valueOf(appInput.pageSize) < 200){
                appInput.pageSize = '200';
            }

            appInput.startTime = Utility.increaseHoursInStringDate(appInput.startTime,8).replace(' ','T') + '.000+0000';
            appInput.endTime = Utility.increaseHoursInStringDate(appInput.endTime,8).replace(' ','T') + '.000+0000';

            String sql = 'select '+
            'id,'+
            'CreatedDate,'+
            'LastModifiedDate,'+
            'Name,'+
            'ExternalID__c,'+
            'Flag__c,'+
            'Inspection_Date__c,'+
            'Inspection_Shop_Task__c,'+
            'IsChange__c,'+
            'IsNew__c,'+
            'Is_Export__c,'+
            'Placement_Status__c,'+
            'Product__c,'+
            'ReRe__c,'+
            'Sample_Images_Url__c,'+
            'Sample_Item__c,'+
            'Share_Gridding_Code__c,'+
            'Share_Shop__c,'+
            'Shop__c,'+
            'Sort__c,'+
            'Unplanned_Sample__c'+

            ' from Sampling_Inspection__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            List<Sampling_Inspection__c> SamplingInspectionList = (List<Sampling_Inspection__c>)Utility.getRecordListPage(sql, appInput.pageIndex, appInput.pageSize);

            List<SamplingInspectionInfo> SamplingInspectionInfoList = new List<SamplingInspectionInfo>();

            for(Sampling_Inspection__c a : SamplingInspectionList){
                SamplingInspectionInfo c = new SamplingInspectionInfo();
                c.id = checkNull(a.id + '');
                c.CreatedDate = checkNull(a.CreatedDate + '');
                c.LastModifiedDate = checkNull(a.LastModifiedDate + '');
                c.Name = checkNull(a.Name + '');
                c.ExternalID = checkNull(a.ExternalID__c + '');
                c.Flag = checkNull(a.Flag__c + '');
                c.InspectionDate = checkNull(a.Inspection_Date__c + '');
                c.InspectionShopTask = checkNull(a.Inspection_Shop_Task__c + '');
                c.IsChange = checkNull(a.IsChange__c + '');
                c.IsNew = checkNull(a.IsNew__c + '');
                c.IsExport = checkNull(a.Is_Export__c + '');
                c.PlacementStatus = checkNull(a.Placement_Status__c + '');
                c.Product = checkNull(a.Product__c + '');
                c.ReRe = checkNull(a.ReRe__c + '');
                c.SampleImagesUrl = checkNull(a.Sample_Images_Url__c + '');
                c.SampleItem = checkNull(a.Sample_Item__c + '');
                c.ShareGriddingCode = checkNull(a.Share_Gridding_Code__c + '');
                c.ShareShop = checkNull(a.Share_Shop__c + '');
                c.Shop = checkNull(a.Shop__c + '');
                c.Sort1 = checkNull(a.Sort__c + '');
                c.UnplannedSample = checkNull(a.Unplanned_Sample__c + '');

                SamplingInspectionInfoList.add(c);
            }
            result.SamplingInspectionInfoList = SamplingInspectionInfoList;
            String sql1 = 'select count(id) totalNumber from Sampling_Inspection__c where LastModifiedDate >= '+appInput.startTime+' and LastModifiedDate <= '+appInput.endTime;
            List<AggregateResult> c = Database.query(sql1);
            result.totalPage = (Integer.valueOf(c.get(0).get('totalNumber')) + Integer.valueOf(appInput.pageSize) - 1) / Integer.valueOf(appInput.pageSize);
            System.debug('result :' + result);
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendSamplingInspectionToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '1';
            ic.Req_Json__c = reqBody;
            insert ic;

            return result; 
        }catch(Exception e){
            //log
            InterfaceLog__c ic = new InterfaceLog__c();
            ic.Class__c = 'SendSamplingInspectionToBigData';
            ic.Time__c = System.Now();
            ic.ReturnCode__c = '0';
            ic.Req_Json__c = reqBody;
            ic.ErrorMsg__c = e.getMessage();
            insert ic;

            return result; 
        }
    }

    public static String checkNull(String str){
        if(String.isBlank(str)){
            return '';
        }else if('null'.equals(str)){
            return '';
        }else{
            return str;
        }
    }
}