force-app/main/default/objects/Revenue_Statement_Report__c/Revenue_Statement_Report__c.object-meta.xml
<CustomObject>
    <label>Revenue Statement Report</label>
    <nameField>
        <label>Revenue Statement Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Statement Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Statement_Report__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Revenue_Statement_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>销售姓名</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>Salesperson No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RevenueStatementReportShareBatch.cls
global class RevenueStatementReportShareBatch implements Database.Batchable<sObject> {
    public String query;

    global RevenueStatementReportShareBatch() {
        this.query = 'SELECT Id,Customer__c,Product_Line__c FROM Revenue_Statement_Report__c';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Revenue_Statement_Report__c> sObjList) {
        System.debug('sObjList.size(): '+sObjList.size());
        Set<String> accIdSet = new Set<String>();
        Map<String,List<Revenue_Statement_Report__c>> rspMap = new Map<String,List<Revenue_Statement_Report__c>>();
        for(Revenue_Statement_Report__c sObj : sObjList){
            accIdSet.add(sObj.Customer__c);
            if(rspMap.containsKey(sObj.Customer__c)){
                rspMap.get(sObj.Customer__c).add(sObj);
            }else{
                rspMap.put(sObj.Customer__c,new List<Revenue_Statement_Report__c>{sObj});
            }
        }
        List<Sales__c> salesList = [SELECT Customer__c,Product_Line__c,Sales__c FROM Sales__c 
                                    WHERE Customer__c IN:accIdSet AND Sales__r.IsActive = TRUE];
        Integer count = 0;
        for(Sales__c sales : salesList){
            for(Revenue_Statement_Report__c sObj : rspMap.get(sales.Customer__c)){
                if(sales.Product_Line__c.contains(sObj.Product_Line__c)){
                    sObj.OwnerId = sales.Sales__c;
                    count ++;
                }
            }
        }
        System.debug('count : '+ count);
        try{
            update sObjList;
        }catch(Exception e){
            system.debug('error message: '+e.getMessage());
            system.debug('line number: '+e.getLineNumber());    
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
}