force-app/main/default/objects/Promoter_Revenue__c/Promoter_Revenue__c.object-meta.xml
<CustomObject>
    <label>Promoter Revenue</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Promoter Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoter Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Revenue__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendPromoterRevenueToBigDataTest.cls
@isTest
private class SendPromoterRevenueToBigDataTest {
    static testMethod void testMethod1() {
        Test.startTest();

        Promoter_Revenue__c c = new Promoter_Revenue__c(
            Product_Line__c = '1'
        );

        insert c;

        RestRequest req = new RestRequest();
		req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = Blob.valueOf('{"startTime":"2023-12-01 00:00:00","endTime":"2050-02-10 00:00:00"}');
		SendPromoterRevenueToBigData.adoPost();
        req.requestBody = Blob.valueOf('{"startTime":"2023-12-01 00:00:00","en');
        SendPromoterRevenueToBigData.adoPost();
        Test.stopTest();
    }
}