force-app/main/default/objects/Customer_Product_Line__c/Customer_Product_Line__c.object-meta.xml
<CustomObject>
    <label>Customer Product Line</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product_Line__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency Customer</fullName>
            </value>
            <value>
                <fullName>OEM Customer</fullName>
            </value>
            <value>
                <fullName>Customer of Oversea Company</fullName>
            </value>
            <value>
                <fullName>Agency + OEM Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Management_Customer__c.field-meta.xml
<CustomField>
    <fullName>Management_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Management Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CustomerProductLineForMangeToCustomer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <label>Product Line Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>Small Domestic Home Appliances</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>Sound Bar</fullName>
            </value>
            <value>
                <fullName>Hitachi Commercial AC</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>B-Monitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Strategy Customer</fullName>
            </value>
            <value>
                <fullName>Quality Customer</fullName>
            </value>
            <value>
                <fullName>Normal Customer</fullName>
            </value>
            <value>
                <fullName>Eliminated Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Rank_Of_Last_Year__c.field-meta.xml
<CustomField>
    <fullName>Rank_Of_Last_Year__c</fullName>
    <label>Rank of Last Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Target__c/Sales_Target__c.object-meta.xml
<CustomObject>
    <label>Sales Target</label>
    <nameField>
        <displayFormat>SN-{00000}</displayFormat>
        <label>Sales Target No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Target__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Forecasts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target__c/fields/Customer_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Product Line</label>
    <referenceTo>Customer_Product_Line__c</referenceTo>
    <relationshipName>Sales_Target</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target__c/fields/Management_Customer__c.field-meta.xml
<CustomField>
    <fullName>Management_Customer__c</fullName>
    <formula>Customer_Product_Line__r.Management_Customer__r.Name</formula>
    <label>Management Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Target__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Target__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QualityCustomerReprotBatchTest.cls
@isTest
private class QualityCustomerReprotBatchTest {
	@testSetup 
    static void setup() {
        ID accId = TestDataUtility.createAccount('BatchTest', '0000504263', '0000504263', 'Hisense USA');
        Customer_Product_Line__c customerProductLine = new Customer_Product_Line__c();
        customerProductLine.Product_Line_Name__c = 'TV';
        customerProductLine.Customer__c = accId;
        customerProductLine.Management_Customer__c = accId;
        customerProductLine.Rank__c = 'Quality Customer';
        customerProductLine.Rank_Of_Last_Year__c = 'Quality Customer';
        customerProductLine.Classification__c = 'Customer of Oversea Company';
        Database.insert(customerProductLine);
        Sales_Target__c salesTarget = new Sales_Target__c();
        salesTarget.Customer_Name__c = accId;
        salesTarget.Product_Line__c = 'TV';
        salesTarget.Year__c = '2020';
        Database.insert(salesTarget);
        Sales_Target__c salesTarget1 = new Sales_Target__c();
        salesTarget1.Customer_Name__c = accId;
        salesTarget1.Product_Line__c = 'TV';
        salesTarget1.Year__c = '2019';
        Database.insert(salesTarget1); 
    }
    static testMethod void testMethod1() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','1');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod2() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','2');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod3() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','3');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod4() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','4');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod5() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','5');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod6() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','6');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod7() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','7');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod8() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','8');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod9() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','9');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod10() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','10');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod11() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','11');
        Database.executeBatch(qcr,200);
    }
    static testMethod void testMethod12() {
        QualityCustomerReportBatch qcr = new QualityCustomerReportBatch('2020','12');
        Database.executeBatch(qcr,200);
    }
}