force-app/main/default/objects/Customer_Product_Line__c/Customer_Product_Line__c.object-meta.xml
<CustomObject>
    <label>Customer Product Line</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product_Line__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Management_Customer_Branch_Company__c.field-meta.xml
<CustomField>
    <fullName>Management_Customer_Branch_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Management Customer(Branch Company)</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Parent_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product_Line__c</fullName>
    <formula>IF( TEXT(Customer__r.Hisense_Entity__c) == &apos;8500&apos; || TEXT(Customer__r.Hisense_Entity__c) == &apos;8510&apos; || TEXT(Customer__r.Hisense_Entity__c) == &apos;8400&apos;,
	IF( CONTAINS(&apos;TV,Laser TV&apos;, TEXT(Product_Line_Name__c)), &apos;CE&apos;, 
	IF( CONTAINS(&apos;AC,LCAC&apos;,TEXT(Product_Line_Name__c)),&apos;AC&apos;,
	IF( TEXT(Product_Line_Name__c) == &apos;Mobile&apos;,&apos;Mobile&apos;,
	IF( CONTAINS(&apos;Refrigerator,Freezer,WM,Small Domestic Home Appliances,Cooking,Dishwasher&apos;,TEXT(Product_Line_Name__c)),&apos;HA&apos;,null )))),	
	IF( CONTAINS(&apos;8000,8010,8040,8050,8060,8070,8080,80B0,80A0,8090,8999,8110,8140&apos;,TEXT(Customer__r.Hisense_Entity__c)),TEXT(Product_Line_Name__c),
		IF( TEXT(Customer__r.Hisense_Entity__c) == &apos;8200&apos;,
			IF( CONTAINS(&apos;TV,Laser TV&apos;, TEXT(Product_Line_Name__c)), &apos;BG&apos;,
			IF( CONTAINS(&apos;AC,LCAC,Refrigerator,Freezer,WM,Small Domestic Home Appliances,Cooking,Dishwasher&apos;, TEXT(Product_Line_Name__c)), &apos;WG&apos;,null)),TEXT(Product_Line_Name__c))
	)

)</formula>
    <label>Parent Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <label>Product Line Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>Small Domestic Home Appliances</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>Sound Bar</fullName>
            </value>
            <value>
                <fullName>Hitachi Commercial AC</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>B-Monitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>销售姓名</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>Salesperson No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/IsKeyUser__c.field-meta.xml
<CustomField>
    <fullName>IsKeyUser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If there are multiple sales in the same product line, select one sales person as the key user for reports and statistics</inlineHelpText>
    <label>IsKeyUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/Sales_Target_Branch_Company_Use__c.object-meta.xml
<CustomObject>
    <label>Sales Target(Branch Company Use)</label>
    <nameField>
        <label>Sales Target(Branch Company Use) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Target(Branch Company Use)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Target</relationshipLabel>
    <relationshipName>ForecastsC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Customer_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Product Line</label>
    <referenceTo>Customer_Product_Line__c</referenceTo>
    <relationshipLabel>Sales Target</relationshipLabel>
    <relationshipName>Sales_TargetC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>HA</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>WG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SalesTargetBranchCompanyUseShareBatch.cls
/**********************************************************************
* Name: SalesTargetBranchCompanyUseShareBatch
* Object: Sales_Target_Branch_Company_Use__c 
* Purpose: 
* Sales_Target_Branch_Company_Use__c权限共享batch
* Author: Gerry
* Create Date: 2019-11-13
*************************************************************************/
global class SalesTargetBranchCompanyUseShareBatch implements Database.Batchable<sObject> {
    public String query;
    public String year;

    global SalesTargetBranchCompanyUseShareBatch(String inputYear) {
        this.year = inputYear;
        this.query = 'SELECT ID,Customer_Name__c,Product_Line__c,OwnerId,Year__c FROM Sales_Target_Branch_Company_Use__c WHERE Year__c=:year';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sales_Target_Branch_Company_Use__c> salesTargetBranchCompanyUseList) {
        Set<String> accIdSet = new Set<String>();

        for (Sales_Target_Branch_Company_Use__c stb : salesTargetBranchCompanyUseList) {
            accIdSet.add(stb.Customer_Name__c);
        }

        List<Sales__c> salesList = [SELECT id, Customer__c, Sales__c, Sales__r.IsActive,IsKeyUser__c ,Product_Line__c FROM Sales__c WHERE Customer__c IN : accIdSet AND Sales__r.IsActive = TRUE];
        Map<String, List<Sales__c>> salesMap = new Map<String, List<Sales__c>>();
        for (Sales__c salesData : salesList) {
            if(salesMap.containsKey(salesData.Customer__c)){
                salesMap.get(salesData.Customer__c).add(salesData);
            }else{
                salesMap.put(salesData.Customer__c,new List<Sales__c>{salesData});
            }
        }

        //查询所有客户产品线
        //通过客户加上粗的产品线指向细的产品线 例如：CustomerA + HA => Refrigerator，Freezer，WM，，，
        Map<String,Set<String>> summaryProductLineMap = new Map<String,Set<String>>();
        for(Customer_Product_Line__c cProLine : [SELECT Id,Name,Management_Customer_Branch_Company__c,Product_Line_Name__c,Parent_Product_Line__c 
                                                 FROM Customer_Product_Line__c WHERE Management_Customer_Branch_Company__c IN:accIdSet]){
            String key = cProLine.Management_Customer_Branch_Company__c + cProLine.Parent_Product_Line__c;
            if(summaryProductLineMap.containsKey(key)){
                summaryProductLineMap.get(key).add(cProLine.Product_Line_Name__c);
            }else{
                summaryProductLineMap.put(key,new Set<String>{cProLine.Product_Line_Name__c});
            }
        }

        List<Sales_Target_Branch_Company_Use__Share> insertstbcList = new List<Sales_Target_Branch_Company_Use__Share>();

        //设置Share
        Map<String, Sales_Target_Branch_Company_Use__Share> insertstbcMap = new Map<String, Sales_Target_Branch_Company_Use__Share>();
        for (Sales_Target_Branch_Company_Use__c stbc : salesTargetBranchCompanyUseList) {
            List<Sales__c> salescList = salesMap.get(stbc.Customer_Name__c);
            //通过客户加上粗的产品线对应找到细的产品线有哪几条 例如：CustomerA + HA => Refrigerator，Freezer，WM，，，
            Set<String> stbcProductLineSet = summaryProductLineMap.get(stbc.Customer_Name__c + stbc.Product_Line__c);
            List<Sales__c> productLineSalesList = new List<Sales__c>();
            Boolean flag = false;
            if (salescList == null || stbcProductLineSet == null) {
                continue;
            }
            for (Sales__c salesme : salescList) {
                for(String stbcProductLine : stbcProductLineSet){
                    if (Utility.isExistProductLine(salesme.Product_Line__c,stbcProductLine)) {
                        Sales_Target_Branch_Company_Use__Share stbcShare = new Sales_Target_Branch_Company_Use__Share();
                        stbcShare.RowCause = 'Manual';
                        stbcShare.ParentId = stbc.Id;
                        stbcShare.UserOrGroupId  = salesme.Sales__c;
                        stbcShare.AccessLevel = 'Read';
                        String idKeyString = String.valueOf(stbc.Id)+String.valueOf(salesme.Sales__c);
                        insertstbcMap.put(idKeyString, stbcShare);
                        productLineSalesList.add(salesme);
                        //如果为keyuser，设置为owner
                        if (salesme.IsKeyUser__c) {
                            stbc.OwnerId = salesme.Sales__c;
                            flag = true;
                        }
                        break;//只要销售负责其中一条产品线即可Share，因此跳出该层循环
                    }
                }
                
            }
            if (flag == false && productLineSalesList.size() > 0) {
                stbc.OwnerId = productLineSalesList[0].Sales__c;
                
            }
            String mapString = String.valueOf(stbc.Id)+String.valueOf(stbc.OwnerId);
            if (insertstbcMap.containsKey(mapString)) {
                insertstbcMap.remove(mapString);
            }
            
        }
        
        
        try{
            update salesTargetBranchCompanyUseList;
        }catch(Exception e){
            system.debug('error message'+e.getMessage());
            system.debug('line number'+e.getLineNumber());
        }

        if(insertstbcMap.size() > 0){
            insertstbcList = insertstbcMap.values();
            try{
                Database.upsert(insertstbcList);
            }catch(Exception e){
                system.debug('error message'+e.getMessage());
                system.debug('line number'+e.getLineNumber());
            }
        }

    }

    global void finish(Database.BatchableContext BC) {

    }
}