force-app/main/default/objects/Customer_Product_Line__c/Customer_Product_Line__c.object-meta.xml
<CustomObject>
    <label>Customer Product Line</label>
    <nameField>
        <displayFormat>PL{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Product_Line__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency Customer</fullName>
            </value>
            <value>
                <fullName>OEM Customer</fullName>
            </value>
            <value>
                <fullName>Customer of Oversea Company</fullName>
            </value>
            <value>
                <fullName>Agency + OEM Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Management_Customer_Branch_Company__c.field-meta.xml
<CustomField>
    <fullName>Management_Customer_Branch_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Management Customer(Branch Company)</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Line__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <label>Product Line Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>Small Domestic Home Appliances</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>Sound Bar</fullName>
            </value>
            <value>
                <fullName>Hitachi Commercial AC</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>B-Monitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>销售姓名</label>
    <nameField>
        <displayFormat>S{0000000000}</displayFormat>
        <label>Salesperson No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/IsKeyUser__c.field-meta.xml
<CustomField>
    <fullName>IsKeyUser__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If there are multiple sales in the same product line, select one sales person as the key user for reports and statistics</inlineHelpText>
    <label>IsKeyUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/Sales_Target_Branch_Company_Use__c.object-meta.xml
<CustomObject>
    <label>Sales Target(Branch Company Use)</label>
    <nameField>
        <label>Sales Target(Branch Company Use) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Target(Branch Company Use)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Target</relationshipLabel>
    <relationshipName>ForecastsC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Customer_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Customer_Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Product Line</label>
    <referenceTo>Customer_Product_Line__c</referenceTo>
    <relationshipLabel>Sales Target</relationshipLabel>
    <relationshipName>Sales_TargetC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>HA</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>WG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Target_Branch_Company_Use__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SalesTargetBranchCompanyUseBatchTest.cls
@isTest
private class SalesTargetBranchCompanyUseBatchTest {
    static testMethod void testMethod1() {
    	ID accId = TestDataUtility.createAccount('BatchTest', '0000504263', '0000504263', 'Hisense USA');

        Profile p = [SELECT Id,Name FROM Profile WHERE Name = 'System Administrator'];

        User user1 = new User(
            Alias = 'admin', Email='systemadmin@hisensetest.com',
            EmailEncodingKey='UTF-8', LastName='sales representative', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='Asia/Kuala_Lumpur',
            UserName='systemadmin@hisensetest.com'
        );
        Database.insert(user1);

        
        Sales__c sales = new Sales__c();
        sales.Customer__c = accId;
        sales.Product_Line__c = 'TV';
        sales.Sales__c = user1.Id;
        sales.IsKeyUser__c = true;
        Database.insert(sales);

        Customer_Product_Line__c cpl = new Customer_Product_Line__c();
        cpl.Management_Customer_Branch_Company__c = accId;
        cpl.Product_Line_Name__c = 'TV';
        cpl.Customer__c = accId;
        cpl.Classification__c = 'Customer of Oversea Company';
        Database.insert(cpl);

        Sales_Target_Branch_Company_Use__c stbc = new Sales_Target_Branch_Company_Use__c();
        stbc.Customer_Name__c = accId;
        stbc.Product_Line__c = Label.SACE;
        stbc.Year__c = '2019';
        Database.insert(stbc);

        SalesTargetBranchCompanyUseShareBatch stbcs = new SalesTargetBranchCompanyUseShareBatch('2019');
        //损益表batch
        Database.executeBatch(stbcs,200);
    }
}