force-app/main/default/objects/Shop_Message_Board__c/Shop_Message_Board__c.object-meta.xml
<CustomObject>
    <label>留言板</label>
    <nameField>
        <label>主题</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>留言板</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop_Message_Board__c/fields/Account_Text__c.field-meta.xml
<CustomField>
    <fullName>Account_Text__c</fullName>
    <label>客户名</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Shop_Message_Board__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>部门</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>第1営業G</fullName>
            </value>
            <value>
                <fullName>マーケティング部</fullName>
            </value>
            <value>
                <fullName>部品管理G</fullName>
            </value>
            <value>
                <fullName>関西サービスセンター</fullName>
            </value>
            <value>
                <fullName>関西出張修理SC</fullName>
            </value>
            <value>
                <fullName>関西整備G</fullName>
            </value>
            <value>
                <fullName>関西在庫管理G</fullName>
            </value>
            <value>
                <fullName>関東サービスセンター</fullName>
            </value>
            <value>
                <fullName>技術サポートG</fullName>
            </value>
            <value>
                <fullName>関東出張修理SC</fullName>
            </value>
            <value>
                <fullName>関東整備G</fullName>
            </value>
            <value>
                <fullName>関東在庫管理G</fullName>
            </value>
            <value>
                <fullName>販売促進部</fullName>
            </value>
            <value>
                <fullName>商品発売部</fullName>
            </value>
            <value>
                <fullName>物流受注部</fullName>
            </value>
            <value>
                <fullName>販売企画部</fullName>
            </value>
            <value>
                <fullName>人事総務部</fullName>
            </value>
            <value>
                <fullName>財務経営管理部</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop_Message_Board__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>(&quot;有效&quot;)</defaultValue>
    <label>是否有效</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>有效</fullName>
            </value>
            <value>
                <fullName>过期</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop_Message_Board__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>留言</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Shop_Message_Board__c/fields/priority__c.field-meta.xml
<CustomField>
    <fullName>priority__c</fullName>
    <label>分类</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>大至急（全部）</fullName>
            </value>
            <value>
                <fullName>大至急</fullName>
            </value>
            <value>
                <fullName>A(☆☆☆)</fullName>
                <label>商品納品情報</label>
            </value>
            <value>
                <fullName>B(☆☆)</fullName>
                <label>カタログ＆POP納品情報</label>
            </value>
            <value>
                <fullName>C(☆)</fullName>
                <label>新商品発売情報</label>
            </value>
            <value>
                <fullName>キャンペンーン情報</fullName>
            </value>
            <value>
                <fullName>定番状況</fullName>
            </value>
            <value>
                <fullName>展示情報</fullName>
            </value>
            <value>
                <fullName>物流情報</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MessageBoardCreateAndEditController.cls
/*
 * @Author: Rain
 * @Date: 2022-04-20 22:12:28
 * @LastEditors: Rain
 * @LastEditTime: 2022-04-21 18:07:36
 * @Description: MessageBoardCreateAndEditLWC controller
 */
public without sharing class MessageBoardCreateAndEditController {
    @AuraEnabled 
    public static ReturnData initData(String recordId) {
        ReturnData returnData = new ReturnData();
        if(String.isNotBlank(recordId)) {
            Shop_Message_Board__c message = getMessageBoard(recordId);
            returnData.isSuccess = true;
            if(message != null) {
                returnData.name = message.Name;
                returnData.message = message.Message__c;
                returnData.priority = message.priority__c;
                returnData.isActive = message.IsActive__c;
                returnData.accountText = message.Account_Text__c;
                returnData.department = message.Department__c;
            }
        }
        return returnData;
    }

    @AuraEnabled
    public static ResultData saveRecord(String recordStr,String recordId){
        ReturnData returnData = (ReturnData)JSON.deserialize(recordStr, ReturnData.class);
        ResultData resultData = new ResultData();
        Shop_Message_Board__c message = new Shop_Message_Board__c();
        message.Name = returnData.name;
        message.Message__c = returnData.message;
        message.priority__c = returnData.priority;
        message.IsActive__c = returnData.isActive;
        message.Account_Text__c = returnData.accountText;
        message.Department__c = returnData.department;

        try {
            Database.SaveResult result = null;
            if(String.isNotBlank(recordId)) {
                message.Id = recordId;
                result = Database.update(message);
            } else {
                result = Database.insert(message);
            }

            if(result.isSuccess()) {
                resultData.isSuccess = true;
                resultData.recordId = result.getId();
            } else {
                String error = '';
                for (Database.Error err : result.getErrors()) {
                    error += err.getMessage();
                }
                resultData.isSuccess = false;
                resultData.errorMsg = error;
            }
            
        } catch (Exception e) {
            resultData.isSuccess = false;
            resultData.errorMsg = e.getMessage();
        }
        return resultData;
    }

    /**
    Name : getMessageBoard
    Purpose : 获取留言板记录内容
    Params : recordId 留言板Id
    Return : 留言板记录
    Author : Rain
    Date : 2022-04-21
    **/ 
    public static Shop_Message_Board__c getMessageBoard(String recordId) {
        return [SELECT 
                    Id,
                    Name,
                    Message__c,
                    IsActive__c,
                    priority__c,
                    Department__c,
                    Account_Text__c
                FROM
                    Shop_Message_Board__c 
                WHERE 
                    Id = :recordId];
    }


    public class ReturnData {
        @AuraEnabled
        public Boolean isSuccess;
        @AuraEnabled
        public String errorMsg;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String message;
        @AuraEnabled
        public String isActive;
        @AuraEnabled
        public String priority;
        @AuraEnabled
        public String department;
        @AuraEnabled
        public String accountText;
    }

    public class ResultData {
        @AuraEnabled
        public Boolean isSuccess;
        @AuraEnabled
        public String errorMsg;
        @AuraEnabled
        public String recordId;
    }
}