force-app/main/default/objects/Promoter_Daily_Report__c/Promoter_Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Report</label>
    <nameField>
        <displayFormat>PWR-{YYYY}{MM}{DD}{00000000}</displayFormat>
        <label>日报编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Only related stores are available.</inlineHelpText>
    <label>门店</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Daily Reports</relationshipLabel>
    <relationshipName>Shop_Promoter_Week_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promoter_Daily_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Daily Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>客户</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shop_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>In Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewPromoterDailyReportTriggerHelperTest.cls
@isTest
public class NewPromoterDailyReportTriggerHelperTest {

    @isTest
    public static void test() {
        
        Test.startTest();
        
        NewTestDataUtility.makePromoterDailyReportData();
        Account customer = NewTestDataUtility.customer;
        Promoter_Daily_Report__c report = NewTestDataUtility.report;
        Shop__c store = new Shop__c();
        store.Account__c = customer.Id;
        insert store;
        report.Shop__c = store.Id;
        update report;
        NewPromoterDailyReportTriggerHelper.afterApproved(new List<Promoter_Daily_Report__c>{report}, new List<Promoter_Daily_Report__c> {new Promoter_Daily_Report__c(
        	Id = report.Id,
            Status__c = 'Approved'
        )});
        Test.stopTest();
    }
}