force-app/main/default/objects/PO__c/PO__c.object-meta.xml
<CustomObject>
    <label>PO</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>PO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PO__c/fields/Category_of_Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Category_of_Delivery_Address__c</fullName>
    <label>Category of Delivery Address</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
                <default>true</default>
                <label>Store</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PO__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PO</relationshipLabel>
    <relationshipName>PO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PO__c/fields/PO__c.field-meta.xml
<CustomField>
    <fullName>PO__c</fullName>
    <formula>HYPERLINK(
&quot;/lightning/cmp/c__lwcWrapper?c__lwcName=uploadStorePicturesLWC&amp;c__versionId=&quot; &amp; CoverImgVersionId__c &amp; &quot;&amp;c__fileType=&quot;&amp; CoverImgFileType__c &amp; &quot;&amp;c__contentBodyId=&quot;&amp; CoverImgContentBodyId__c &amp; &quot;&amp;c__recordId=&quot;&amp; Id &amp; &quot;&amp;c__versionIdField=CoverImgVersionId__c&amp;c__contentBodyIdField=CoverImgContentBodyId__c&amp;c__fileTypeField=CoverImgFileType__c&amp;c__isImgManagement=true&quot;,
IF (
ISBLANK( CoverImgVersionId__c ),
IMAGE(&quot;/logos/Custom/Plus_Primary/logo.png&quot;, &quot;Review&quot;, 20, 20),
IMAGE(&quot;/sfc/servlet.shepherd/version/renditionDownload?rendition=thumb120by90&amp;versionId=&quot; &amp; CoverImgVersionId__c &amp; &quot;&amp;operationContext=CHATTER&amp;contentId=&quot; &amp; CoverImgContentBodyId__c, &quot;Preview is generating, please refresh later&quot;, 90, 120)
),
&quot;_parent&quot;
)</formula>
    <label>PO</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PO__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Model</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>PO</relationshipLabel>
    <relationshipName>PO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PO__c/fields/Sample_Display__c.field-meta.xml
<CustomField>
    <fullName>Sample_Display__c</fullName>
    <label>Sample Display</label>
    <referenceTo>Sample_Display__c</referenceTo>
    <relationshipLabel>PO</relationshipLabel>
    <relationshipName>PO</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Model__c/Product_Model__c.object-meta.xml
<CustomObject>
    <label>Product Model</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Display__c/Sample_Display__c.object-meta.xml
<CustomObject>
    <label>Sample Display</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Sample Display Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Display</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Display__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sample Display</relationshipLabel>
    <relationshipName>Sample_Display</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Model</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>$Source.Sales_Region__c</field>
            <operation>equals</operation>
            <valueField>Product__c.sales_region__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sample Display</relationshipLabel>
    <relationshipName>Sample_Display</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Sample Display</relationshipLabel>
    <relationshipName>Sample_Display</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Display__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/SAP__c/SAP__c.object-meta.xml
<CustomObject>
    <label>SAP</label>
    <nameField>
        <displayFormat>SAP-{0000}</displayFormat>
        <label>SAP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP__c/fields/Sample_Display__c.field-meta.xml
<CustomField>
    <fullName>Sample_Display__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sample Display</label>
    <referenceTo>Sample_Display__c</referenceTo>
    <relationshipLabel>SAP</relationshipLabel>
    <relationshipName>SAP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Detail__c/Store_Detail__c.object-meta.xml
<CustomObject>
    <label>Store Detail</label>
    <nameField>
        <displayFormat>SD-{0000}</displayFormat>
        <label>Store Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Detail__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store_Detail__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Model</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Store Detail</relationshipLabel>
    <relationshipName>Store_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Detail__c/fields/Sample_Display__c.field-meta.xml
<CustomField>
    <fullName>Sample_Display__c</fullName>
    <label>Sample Display</label>
    <referenceTo>Sample_Display__c</referenceTo>
    <relationshipLabel>Store Detail</relationshipLabel>
    <relationshipName>Store_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Detail__c/fields/Split_Number__c.field-meta.xml
<CustomField>
    <fullName>Split_Number__c</fullName>
    <description>拆分了的数量</description>
    <label>Split Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store_Detail__c/fields/Split_Up__c.field-meta.xml
<CustomField>
    <fullName>Split_Up__c</fullName>
    <defaultValue>false</defaultValue>
    <description>拆分结束标记 true：拆分完</description>
    <label>Split Up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Store_Detail__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Store Detail</relationshipLabel>
    <relationshipName>Store_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SampleDisplayPOApprovedController.cls
/*
 * @Author: WFC
 * @Date: 2024-12-18 10:30:16
 * @LastEditors: WFC
 * @LastEditTime: 2024-12-18 13:42:53
 * @Description: sample display审批通过后拆分po，传递sap信息
 * @FilePath: \hisense005\force-app\main\default\classes\SampleDisplayPOApprovedController.cls
 */
public without sharing class SampleDisplayPOApprovedController{
    @InvocableMethod
    public static void splitPO(List<String> sampleDisplayIdList){
        String sdId = sampleDisplayIdList[0];
        // 查询store details表，排序勾选Priority__c,创建时间正序
        List<Store_Detail__c> sdList = [SELECT Id, Name, CreatedDate, Priority__c, Number__c, Sample_Display__c, Product_Model__c, Split_Up__c, Split_Number__c, Sample_Display__r.Customer__c, Store__c
                                        FROM Store_Detail__c
                                        WHERE Sample_Display__c = :sdId
                                        ORDER BY Priority__c DESC, CreatedDate];
        for (Store_Detail__c sd : sdList){
            sd.Split_Up__c = false;
            sd.Split_Number__c = 0;
        }
        // 查询po表
        List<PO__c> poList = [SELECT Id, Name, Number__c, Category_of_Delivery_Address__c
                              FROM PO__c
                              WHERE Sample_Display__c = :sdId
                              ORDER BY CreatedDate];
        // 拆分po，生成sap
        List<SAP__c> addSapList = new List<SAP__c>();
        for (PO__c po : poList){
            // po的数量
            Decimal poNumber = po.Number__c;
            // store类型生成多个sap信息，customer类型生成一个sap信息
            if (po.Category_of_Delivery_Address__c == 'store'){
                for (Store_Detail__c sd : sdList){
                    if (sd.Split_Up__c){
                        continue;
                    }
                    Decimal deTemp = sd.Number__c - sd.Split_Number__c;
                    // 拆分的数量，可能存在部分拆分
                    if (poNumber == deTemp){
                        sd.Split_Up__c = true;
                        // 生成sap
                        SAP__c sap = new SAP__c();
                        sap.Sample_Display__c = sdId;
                        sap.Number__c = deTemp;
                        addSapList.add(sap);
                        break;
                    } else if (poNumber < deTemp){
                        sd.Split_Number__c = sd.Split_Number__c + poNumber;
                        // 生成sap
                        SAP__c sap = new SAP__c();
                        sap.Sample_Display__c = sdId;
                        sap.Number__c = poNumber;
                        addSapList.add(sap);
                        break;
                    } else{
                        sd.Split_Up__c = true;
                        poNumber = poNumber - deTemp;
                        // 生成sap
                        SAP__c sap = new SAP__c();
                        sap.Sample_Display__c = sdId;
                        sap.Number__c = deTemp;
                        addSapList.add(sap);
                    }
                }
            } else{
                for (Store_Detail__c sd : sdList){
                    if (sd.Split_Up__c){
                        continue;
                    }
                    Decimal deTemp = sd.Number__c - sd.Split_Number__c;
                    // 拆分的数量，可能存在部分拆分
                    if (poNumber == deTemp){
                        sd.Split_Up__c = true;
                        break;
                    } else if (poNumber < deTemp){
                        sd.Split_Number__c = sd.Split_Number__c + poNumber;
                        break;
                    } else{
                        sd.Split_Up__c = true;
                        poNumber = poNumber - deTemp;
                    }
                }
                // 生成一个sap信息
                SAP__c sap = new SAP__c();
                sap.Sample_Display__c = sdId;
                sap.Number__c = po.Number__c;
                addSapList.add(sap);
            }
        }
        Database.insert (addSapList);
        // 传送sap数据
        for (SAP__c sap : addSapList){
            SyncSampleDisplayToSAP.syncSampleDisplayToSAP(sap.Id);
        }
    }

}