force-app/main/default/objects/Customer_Model_Product__c/Customer_Model_Product__c.object-meta.xml
<CustomObject>
    <label>产品客户型号</label>
    <nameField>
        <label>Customer Product Model</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook__c/Pricebook__c.object-meta.xml
<CustomObject>
    <label>Pricebook</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook_Entry__c/Pricebook_Entry__c.object-meta.xml
<CustomObject>
    <label>Pricebook Entry</label>
    <nameField>
        <displayFormat>PBE-{00000}</displayFormat>
        <label>PBE No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook_Entry__c/fields/Customer_Model_Product__c.field-meta.xml
<CustomField>
    <fullName>Customer_Model_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Model Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Customer_Model_Product__c.Country_Code__c</field>
            <operation>equals</operation>
            <valueField>$User.Sales_Region__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Sales_Region__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Model_Product__c</referenceTo>
    <relationshipLabel>Pricebook Entry</relationshipLabel>
    <relationshipName>Pricebook_EntryToCustomerModel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook_Entry__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Pricebook__c</referenceTo>
    <relationshipLabel>Pricebook Entry</relationshipLabel>
    <relationshipName>Pricebook_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pricebook_Entry__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>IF( ISBLANK( Customer_Model_Product__c ) , TEXT(Product__r.Product_Line__c) , TEXT(Customer_Model_Product__r.Product_Line__c) )</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricebook</label>
    <referenceTo>Pricebook__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>QuoteToPricebook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Product__c/Quote_Product__c.object-meta.xml
<CustomObject>
    <label>Quote Product</label>
    <nameField>
        <displayFormat>QL{00000000}</displayFormat>
        <label>Quote Product Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Product__c/fields/Customer_Model_Product__c.field-meta.xml
<CustomField>
    <fullName>Customer_Model_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Model Product</label>
    <referenceTo>Customer_Model_Product__c</referenceTo>
    <relationshipLabel>Quote Product</relationshipLabel>
    <relationshipName>Quote_ProductToCustomerModel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Product__c/fields/Number_of_Containers__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Containers__c</fullName>
    <label>Number of Containers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Product__c/fields/Pricebook_Entry__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricebook Entry</label>
    <referenceTo>Pricebook_Entry__c</referenceTo>
    <relationshipLabel>Quote Product</relationshipLabel>
    <relationshipName>Quote_ProductToEntry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Product__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <label>Quote Name</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Product</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Refrigerator</fullName>
    </customValue>
    <customValue>
        <fullName>Freezer</fullName>
    </customValue>
    <customValue>
        <fullName>Laser TV</fullName>
    </customValue>
    <customValue>
        <fullName>LCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Small Domestic Home Appliances</fullName>
    </customValue>
    <customValue>
        <fullName>Cooking</fullName>
    </customValue>
    <customValue>
        <fullName>Dishwasher</fullName>
    </customValue>
    <customValue>
        <fullName>Sound Bar</fullName>
    </customValue>
    <customValue>
        <fullName>Hitachi Commercial AC</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>B-Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <customValue>
        <fullName>BG-Others</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial display</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Medical utltrasound</fullName>
    </customValue>
    <customValue>
        <fullName>Smart City</fullName>
    </customValue>
    <customValue>
        <fullName>WineCabi</fullName>
    </customValue>
    <customValue>
        <fullName>CF</fullName>
    </customValue>
    <customValue>
        <fullName>HeatPump</fullName>
    </customValue>
    <customValue>
        <fullName>CAC</fullName>
        <isActive>false</isActive>
        <label>CAC</label>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
        <isActive>false</isActive>
        <label>CE</label>
    </customValue>
    <customValue>
        <fullName>HA</fullName>
        <isActive>false</isActive>
        <label>HA</label>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuotePDFPageControllerTest.cls
@isTest
private class QuotePDFPageControllerTest {
    static testMethod void testMethod1() {
        Test.startTest();
    	List<Quote__c> quoteList = TestDataUtility.createQuoteList(true);
    	List<Pricebook_Entry__c> pbEntryList = [SELECT Id,Name,Price_Book__c from Pricebook_Entry__c WHERE Price_Book__c=:quoteList[1].Pricebook__c AND Customer_Model_Product__r.Product_Line__c = 'TV' LIMIT 1];
    	QuoteAddProductController.saveSelectedProList(pbEntryList[0].Id,quoteList[1].Id);
    	List<Quote_Product__c> qtItemList = [SELECT Id,Name from Quote_Product__c where Quote_Name__c =:quoteList[1].Id];
    	for(Quote_Product__c qtItem : qtItemList){
            qtItem.Quantity__c = 10;
            qtItem.Number_of_Containers__c = 5;
    	}
    	update qtItemList;
        QuotePDFGenerationController.getQuote(quoteList[1].Id);
    	ApexPages.CurrentPage().getParameters().put('ID',quoteList[1].Id);
    	QuotePDFPageController qtPDF = new QuotePDFPageController();
    	Test.stopTest();
    }
}