force-app/main/default/objects/Customer_Model_Product__c/Customer_Model_Product__c.object-meta.xml
<CustomObject>
    <label>产品客户型号</label>
    <nameField>
        <label>Customer Product Model</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Model_Product__c/fields/Product_Factory_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Factory_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Export Model</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Customer Model Product</relationshipLabel>
    <relationshipName>Customer_Model_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>机会</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product__c/Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OL{00000000}</displayFormat>
        <label>Opportunity Product Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Product__c/fields/Customer_Model_Product__c.field-meta.xml
<CustomField>
    <fullName>Customer_Model_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Model Product</label>
    <referenceTo>Customer_Model_Product__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_ProductToCustomerModel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product__c/fields/Product_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Formula__c</fullName>
    <formula>Product__r.Name</formula>
    <label>Product Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Product__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Product__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <label>Remark</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityEditProductController.cls
/**************************************************************************************************
 * Name:OpportunityEditProductController
 * Purpose:选择业务机会产品
 * Author: Deloitte Johnson
 * Create Date: 2019-03-11
***************************************************************************************************/
global  without sharing class OpportunityEditProductController{
	public Class InitDataWarp{
        public Opportunity__c thisOpp;
        public List<Opportunity_Product__c> productList;
        public List<Utility.PicklistItem> productStatusPicklists;
    }
    //页面初始化数据
    @AuraEnabled 
    public static String initData(String oppId){
        InitDataWarp initData = new InitDataWarp();        
        initData.productList = new List<Opportunity_Product__c>();
        Opportunity__c thisOpp = getOppInfo(oppId);
        initData.thisOpp = thisOpp;
        initData.productList = thisOpp.Opportunity_Products__r;
        initData.productStatusPicklists = Utility.getPicklistValueList('Opportunity_Product__c', 'Product_Status__c');
        System.debug('initData==>>>' +initData);
        return JSON.serialize(initData);
    }
    //保存产品
    @AuraEnabled   
    public static String saveOppProduct(List<Opportunity_Product__c> productList, String oppId){
        String saveMessage = 'SUCCESS';
        system.debug('productList ' +productList);
        List<Opportunity_Product__c> upsertoppItemList = new List<Opportunity_Product__c>();
        Savepoint sp = Database.setSavepoint();
        try{
        	Opportunity__c thisOpp = getOppInfo(oppId);
        	Map<String,Opportunity_Product__c> oppItemIdMap = new Map<String,Opportunity_Product__c>();
        	List<Opportunity_Product__c> deleteOppItemList = new List<Opportunity_Product__c>();
        	for(Opportunity_Product__c oppItem : thisOpp.Opportunity_Products__r){
                oppItemIdMap.put(oppItem.Id,oppItem);
        	}
            for(Opportunity_Product__c oppItem : productList){
                if(String.isNotBlank(oppItem.Id)){
                	//编辑quote product


                    //移除未删除的quote product
                    if(oppItemIdMap.containsKey(oppItem.Id)){
                        oppItemIdMap.remove(oppItem.Id);
                    }             
                }else{
                	//新增quote product
                }
                upsertoppItemList.add(oppItem);
            }
            deleteOppItemList = oppItemIdMap.values();
            update upsertoppItemList;
            if(deleteOppItemList.size() > 0){
                delete deleteOppItemList;
            }

        }catch(Exception e){
            Database.rollback(sp);
            system.debug('error message: '+e.getMessage());
            system.debug('line number: '+e.getLineNumber());
            saveMessage = Utility.getProperErrorMessage(e.getMessage());
        }
        return saveMessage;
    }
    public static Opportunity__c getOppInfo(String oppId){
        Opportunity__c thisOpp = [SELECT Id,Name,RecordType.DeveloperName,(SELECT Id,Name,Product__c,Product__r.Name,Customer_Model_Product__r.Name,Product_Name_Formula__c,
                                  Quantity__c,Product_Status__c,Remark__c FROM Opportunity_Products__r ORDER BY Customer_Model_Product__r.Name ASC) 
                                  FROM Opportunity__c WHERE Id =:oppId];
        return thisOpp;
    }
}