force-app/main/default/objects/Customer_Model_Product__c/Customer_Model_Product__c.object-meta.xml
<CustomObject>
    <label>产品客户型号</label>
    <nameField>
        <label>Customer Product Model</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Model_Product__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Salesforce Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense Malaysia</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>American Sales Department</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa Sales Department</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific Sales Department</fullName>
            </value>
            <value>
                <fullName>Key Account Sales Department</fullName>
            </value>
            <value>
                <fullName>Europe Sales Department</fullName>
            </value>
            <value>
                <fullName>GORENJE, D.D.</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>LOEWE</fullName>
            </value>
            <value>
                <fullName>Hisense Germany</fullName>
            </value>
            <value>
                <fullName>Hisense Dubai</fullName>
            </value>
            <value>
                <fullName>Hisense Russia</fullName>
            </value>
            <value>
                <fullName>Hisense France</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Czech</fullName>
            </value>
            <value>
                <fullName>Hisense Japan</fullName>
            </value>
            <value>
                <fullName>Hisense Thailand</fullName>
            </value>
            <value>
                <fullName>Hisense Spain</fullName>
            </value>
            <value>
                <fullName>Hisense Italy</fullName>
            </value>
            <value>
                <fullName>Hisense India</fullName>
            </value>
            <value>
                <fullName>Hisense Indonesia</fullName>
            </value>
            <value>
                <fullName>Hisense UK</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Model_Product__c/fields/Product_Factory_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Factory_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Export Model</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Customer Model Product</relationshipLabel>
    <relationshipName>Customer_Model_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>SO{0000000000}</displayFormat>
        <label>SF Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/Order_Product__c.object-meta.xml
<CustomObject>
    <label>Order Product</label>
    <nameField>
        <displayFormat>OP{0000000000}</displayFormat>
        <label>Order Line No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Product__c/fields/Customer_Model_Product__c.field-meta.xml
<CustomField>
    <fullName>Customer_Model_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Model Product</label>
    <referenceTo>Customer_Model_Product__c</referenceTo>
    <relationshipLabel>Order Product</relationshipLabel>
    <relationshipName>Order_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Product</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/fields/Product_Export_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Export_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Model</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Product (Product Export Model)</relationshipLabel>
    <relationshipName>Order_Product1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/fields/Product_Factory_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Factory_Model__c</fullName>
    <label>Product Factory Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>SAP_Product_Line__r.Mapping_Code__c</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/fields/SAP_Product_Customer_Model__c.field-meta.xml
<CustomField>
    <fullName>SAP_Product_Customer_Model__c</fullName>
    <label>SAP Product Customer Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/fields/SAP_Product_Export_Model__c.field-meta.xml
<CustomField>
    <fullName>SAP_Product_Export_Model__c</fullName>
    <label>SAP Product Export Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hisense Product</fullName>
                <default>true</default>
                <label>Hisense Product</label>
            </value>
            <value>
                <fullName>Competitive Product</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Refrigerator</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>WM</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Laser TV</fullName>
            </value>
            <value>
                <fullName>LCAC</fullName>
            </value>
            <value>
                <fullName>Small Domestic Home Appliances</fullName>
            </value>
            <value>
                <fullName>Cooking</fullName>
            </value>
            <value>
                <fullName>Dishwasher</fullName>
            </value>
            <value>
                <fullName>Sound Bar</fullName>
            </value>
            <value>
                <fullName>Hitachi Commercial AC</fullName>
            </value>
            <value>
                <fullName>Medical Device</fullName>
            </value>
            <value>
                <fullName>B-Monitor</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/sales_region__c.field-meta.xml
<CustomField>
    <fullName>sales_region__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense USA&apos;) , &apos;Hisense USA&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;USA(OEM)&apos;) , &apos;USA(OEM)&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Mexico&apos;) , &apos;Hisense Mexico&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Australia&apos;) , &apos;Hisense Australia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Malaysia&apos;) , &apos;Hisense Malaysia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense South Africa&apos;) , &apos;Hisense South Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Indonesia&apos;) , &apos;Hisense Indonesia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Chile&apos;) , &apos;Hisense Chile&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;American Sales Department&apos;) , &apos;American Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Middle East and Africa Sales Department&apos;) , &apos;Middle East and Africa Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Asia-Pacific Sales Department&apos;) , &apos;Asia-Pacific Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Key Account Sales Department&apos;) , &apos;Key Account Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Europe Sales Department&apos;) , &apos;Europe Sales Department&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Colombia&apos;) , &apos;Hisense Colombia&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Argentina&apos;) , &apos;Hisense Argentina&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense West Africa&apos;) , &apos;Hisense West Africa&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Saudi&apos;) , &apos;Hisense Saudi&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Vietnam&apos;) , &apos;Hisense Vietnam&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Philippines&apos;) , &apos;Hisense Philippines&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Canada&apos;) , &apos;Hisense Canada&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Hisense Peru&apos;) , &apos;Hisense Peru&apos;,
IF(ISPICKVAL($User.Sales_Region__c, &apos;Communications Sales Department&apos;) , &apos;Communications Sales Department&apos;, &apos;&apos;) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )</defaultValue>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hisense USA</fullName>
            </value>
            <value>
                <fullName>USA(OEM)</fullName>
            </value>
            <value>
                <fullName>Hisense Mexico</fullName>
            </value>
            <value>
                <fullName>Hisense Australia</fullName>
            </value>
            <value>
                <fullName>Hisense Malaysia</fullName>
            </value>
            <value>
                <fullName>Hisense South Africa</fullName>
            </value>
            <value>
                <fullName>American Sales Department</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa Sales Department</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific Sales Department</fullName>
            </value>
            <value>
                <fullName>Key Account Sales Department</fullName>
            </value>
            <value>
                <fullName>Europe Sales Department</fullName>
            </value>
            <value>
                <fullName>Communications Sales Department</fullName>
            </value>
            <value>
                <fullName>Hisense Indonesia</fullName>
            </value>
            <value>
                <fullName>Hisense Chile</fullName>
            </value>
            <value>
                <fullName>Hisense Thailand</fullName>
            </value>
            <value>
                <fullName>Hisense Vietnam</fullName>
            </value>
            <value>
                <fullName>Hisense Colombia</fullName>
            </value>
            <value>
                <fullName>Hisense Argentina</fullName>
            </value>
            <value>
                <fullName>Hisense West Africa</fullName>
            </value>
            <value>
                <fullName>Hisense Saudi</fullName>
            </value>
            <value>
                <fullName>Hisense Canada</fullName>
            </value>
            <value>
                <fullName>Hisense Philippines</fullName>
            </value>
            <value>
                <fullName>Hisense Peru</fullName>
            </value>
            <value>
                <fullName>Hisense Singapore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Region__c/Sales_Region__c.object-meta.xml
<CustomObject>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateSAPOrderProduct.cls
/**********************************************************************
* Name: CreateSAPOrderProduct
* Object: Order 
* Purpose: 
* SAP中传过来的客户型号 产品型号不存在的就新建
* Author: Gerry
* Create Date: 2019-05-28
*************************************************************************/
global class CreateSAPOrderProduct implements Database.Batchable<sObject> {
    public String query;

    global CreateSAPOrderProduct() {
        //a0q0p000000dJYgAAM a0q0p000000dJTGAA2(产品型号和客户型号都不存在) a0q0p000000dJToAAM（产品型号和客户型号都不存在） a0q0p000000dK34AAE
        //a0q0p000000dabbAAA a0q0p000000dabcAAA 
        this.query = 'SELECT SAP_Product_Customer_Model__c,Product_Factory_Model__c,SAP_Product_Export_Model__c,Product_Export_Model__c,Customer_Model_Product__c,'+
                     'Product_Line__c,Order__r.Customer__r.Sales_Region__c FROM Order_Product__c WHERE Product_Export_Model__c=null OR Customer_Model_Product__c=null';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Order_Product__c> orderProductList) {
        Savepoint sp = Database.setSavepoint();
        try{
            //冰冷洗找不到产品型号  对应的出口型号
            Set<String> productModel = new Set<String>();
            //客户型号找不到
            Set<String> customerModel = new Set<String>();
            for (Order_Product__c orderProduct : orderProductList) {
                String productLine = orderProduct.Product_Line__c;
                if (('Refrigerator'.equals(productLine)||'Freezer'.equals(productLine)||'WM'.equals(productLine))
                    &&orderProduct.Product_Export_Model__c==null&&orderProduct.SAP_Product_Export_Model__c!=null) {
                    productModel.add(orderProduct.SAP_Product_Export_Model__c);
                }
                if (orderProduct.Customer_Model_Product__c==null && orderProduct.SAP_Product_Customer_Model__c!=null) {
                    customerModel.add(orderProduct.SAP_Product_Customer_Model__c);
                }    
                if (('AC'.equals(productLine)||'LCAC'.equals(productLine)||'Small Domestic Home Appliances'.equals(productLine)||'Cooking'.equals(productLine)||'Dishwasher'.equals(productLine))
                    && orderProduct.SAP_Product_Export_Model__c!=null && orderProduct.Product_Export_Model__c==null) {
                    productModel.add(orderProduct.SAP_Product_Export_Model__c);
                }
                if (('Laser TV'.equals(productLine)||'TV'.equals(productLine)||'Mobile'.equals(productLine))
                    &&orderProduct.Product_Factory_Model__c!=null&&orderProduct.Product_Export_Model__c==null) {
                    productModel.add(orderProduct.Product_Factory_Model__c);   
                }     
            }

            //已经存在的客户型号
            Map<String,Customer_Model_Product__c> customerMap = new Map<String,Customer_Model_Product__c>();
            for (Customer_Model_Product__c cm : [SELECT ID,Name FROM Customer_Model_Product__c WHERE Name IN :customerModel]) {
                customerMap.put(cm.Name, cm);
            }

            //已经存在的产品
            Map<String,Product__c> factoryMap = new Map<String,Product__c>();
            for (Product__c pro : [SELECT ID,Name FROM Product__c WHERE Name IN :productModel]) {
                factoryMap.put(pro.Name,pro);
            }
            //用来判断客户型号是否已经新建
            Set<String> customerModelFlag = new Set<String>();
            //用来判断工厂型号是否已经新建
            Set<String> factoryModelFlag = new Set<String>();
            //用来判断出口型号是否已经创建
            Set<String> exportModelFlag = new Set<String>();
            List<Customer_Model_Product__c> customerModelProductList = new List<Customer_Model_Product__c>();
            List<Product__c> productList = new List<Product__c>();
            for (Order_Product__c orderProduct : orderProductList) {
                //如果没有关联到Customer Model Product并且sap传过来的客户型号不为空  就直接新建一个Customer Model Product
                if (orderProduct.Customer_Model_Product__c==null && orderProduct.SAP_Product_Customer_Model__c!=null 
                    && !customerModelFlag.contains(orderProduct.SAP_Product_Customer_Model__c)
                    &&customerMap.get(orderProduct.SAP_Product_Customer_Model__c)==null) {
                    Customer_Model_Product__c customerModelProduct = new Customer_Model_Product__c();
                    customerModelProduct.Name = orderProduct.SAP_Product_Customer_Model__c;
                    customerModelProduct.Product_Line__c = orderProduct.Product_Line__c;
                    customerModelProduct.Country_Code__c = orderProduct.Order__r.Customer__r.Sales_Region__c;
                    customerModelProductList.add(customerModelProduct);
                    customerModelFlag.add(orderProduct.SAP_Product_Customer_Model__c);
                }
                String productLine = orderProduct.Product_Line__c;
                //如果为冰冷洗产品线的时候，看出口型号是否有对应的product 如果有就不创建  没有就创建
                if (('Refrigerator'.equals(productLine)||'Freezer'.equals(productLine)||'WM'.equals(productLine))
                    &&orderProduct.Product_Export_Model__c==null&&orderProduct.SAP_Product_Export_Model__c!=null
                    &&factoryMap.get(orderProduct.SAP_Product_Export_Model__c)==null&&!exportModelFlag.contains(orderProduct.SAP_Product_Export_Model__c)) {
                    Product__c product = new Product__c();
                    product.Name = orderProduct.SAP_Product_Export_Model__c;
                    if ('Refrigerator'.equals(productLine)) {
                        product.Product_Line__c = 'Refrigerator';
                        product.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('Refrigerator Product RecordType').getRecordTypeId();
                    }else if ('Freezer'.equals(productLine)) {
                        product.Product_Line__c = 'Freezer';
                        product.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('Freezer Product RecordType').getRecordTypeId();
                    }else{
                        product.Product_Line__c = 'WM';
                        product.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('WM Product RecordType').getRecordTypeId();
                    }
                    productList.add(product);
                    exportModelFlag.add(orderProduct.SAP_Product_Export_Model__c);
                }
                //如果为电视和手机产品线的时候 用直接创建product
                if (('Laser TV'.equals(productLine)||'TV'.equals(productLine)||'Mobile'.equals(productLine))
                    &&orderProduct.Product_Factory_Model__c!=null&&orderProduct.Product_Export_Model__c==null
                    &&!factoryModelFlag.contains(orderProduct.Product_Factory_Model__c)
                    &&factoryMap.get(orderProduct.Product_Factory_Model__c)==null) {
                    Product__c product1 = new Product__c();
                    product1.Name = orderProduct.Product_Factory_Model__c;
                    if ('TV'.equals(productLine)) {
                        product1.Product_Line__c = 'TV';
                        product1.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('TV Product RecordType').getRecordTypeId();
                    }else if ('Laser TV'.equals(productLine)) {
                        product1.Product_Line__c = 'Laser TV';
                        product1.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('TV Product RecordType').getRecordTypeId();
                    }else{
                        product1.Product_Line__c = 'Mobile';
                        product1.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('Mobile Product RecordType').getRecordTypeId();
                    }
                    productList.add(product1);
                    factoryModelFlag.add(orderProduct.Product_Factory_Model__c);
                }
                //如果为AC产品线或者其他产品线的时候
                if (('AC'.equals(productLine)||'LCAC'.equals(productLine)||'Small Domestic Home Appliances'.equals(productLine)||'Cooking'.equals(productLine)||'Dishwasher'.equals(productLine))
                    && orderProduct.SAP_Product_Export_Model__c!=null && orderProduct.Product_Export_Model__c==null && !exportModelFlag.contains(orderProduct.SAP_Product_Export_Model__c)
                    &&factoryMap.get(orderProduct.SAP_Product_Export_Model__c)==null) {
                    Product__c product2 = new Product__c();
                    product2.Name = orderProduct.SAP_Product_Export_Model__c;
                    if ('AC'.equals(productLine)) {
                        product2.Product_Line__c = 'AC';
                        product2.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('AC Product RecordType').getRecordTypeId();
                    }
                    if ('LCAC'.equals(productLine)) {
                        product2.Product_Line__c = 'LCAC';
                        product2.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('AC Product RecordType').getRecordTypeId();
                    }
                    if ('Small Domestic Home Appliances'.equals(productLine)) {
                        product2.Product_Line__c = 'Small Domestic Home Appliances';
                        product2.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('SDHA Product RecordType').getRecordTypeId();
                    }
                    if ('Cooking'.equals(productLine)) {
                        product2.Product_Line__c = 'Cooking';
                        product2.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('Cooking Product RecordType').getRecordTypeId();
                    }
                    if ('Dishwasher'.equals(productLine)) {
                        product2.Product_Line__c = 'Dishwasher';
                        product2.RecordTypeId = Schema.SObjectType.Product__c.getRecordTypeInfosByName().get('Dishwasher Product RecordType').getRecordTypeId();
                    }
                    productList.add(product2);
                    exportModelFlag.add(orderProduct.SAP_Product_Export_Model__c);
                }
            }
            Database.insert(customerModelProductList);
            Database.insert(productList);
        }catch(Exception e){
            System.debug(e.getMessage()+e.getLineNumber());
            Database.rollback(sp);
            String errorMsg = e.getMessage()+e.getLineNumber();
            Utility.insertBatchLog('CreateSAPOrderProduct', errorMsg);
        }    
    }

    global void finish(Database.BatchableContext BC) {

    }
}