force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>SO{0000000000}</displayFormat>
        <label>SF Order No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAP_Order_No__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order_No__c</fullName>
    <label>SAP Order No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Product__c/Order_Product__c.object-meta.xml
<CustomObject>
    <label>Order Product</label>
    <nameField>
        <displayFormat>OP{0000000000}</displayFormat>
        <label>Order Line No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Product__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Product</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpserBulkOrderProductTest.cls
@isTest
private class UpserBulkOrderProductTest {
    static testMethod void testMethod1() {
    	ID accId = TestDataUtility.createAccount('TestAccount 1', '0000504263', '0000504263','Hisense USA');
    	List<Order_Product__c> orderProductList = new List<Order_Product__c>();
    	orderProductList.add(TestDataUtility.createOrderProduct(accId,'0036195576','11'));
        Test.startTest();
        UpserBulkOrderProduct bulkorderProduct = new UpserBulkOrderProduct(orderProductList);
        ID jobID = System.enqueueJob(bulkorderProduct);
        Test.stopTest();
    }

    static testMethod void testMethod2(){
    	List<Order_Product__c> orderProductList = new List<Order_Product__c>();
    	ID accId = TestDataUtility.createAccount('TestAccount 1', '0000504263', '0000504263','Hisense USA');
    	orderProductList.add(TestDataUtility.createOrderProduct(accId,'0036195576','11'));
        Test.startTest();
        UpserBulkOrderProductSecond bulkorderProduct = new UpserBulkOrderProductSecond(orderProductList);
        ID jobID = System.enqueueJob(bulkorderProduct);
        Test.stopTest();
    }

    static testMethod void testMethod3(){
    	ID accId = TestDataUtility.createAccount('TestAccount 1', '0000504263', '0000504263','Hisense USA');
    	List<Order_Product__c> orderProductList = new List<Order_Product__c>();
    	orderProductList.add(TestDataUtility.createOrderProduct(accId,'0036195576','11'));
    	orderProductList.add(TestDataUtility.createOrderProduct(accId,'0036195577','11'));
        Test.startTest();
        UpserBulkOrderProductSecond bulkorderProduct = new UpserBulkOrderProductSecond(orderProductList);
        ID jobID = System.enqueueJob(bulkorderProduct);
        Test.stopTest();
    }

    static testMethod void testMethod4(){
        ID accId = TestDataUtility.createAccount('TestAccount 1', '0000504263', '0000504263','Hisense USA');
        Order__c order = new Order__c(
            Customer__c = accId,
            SAP_Order_No__c = '0036195576'
        );
        Database.insert(order);
        List<Order_Product__c> orderProductList = new List<Order_Product__c>();
        for (Integer i=1;i<10002 ;i++ ) {
            Order_Product__c orderProduct = new Order_Product__c(
                Order__c = order.Id,
                External_Key__c = '0036195576'+i
            ); 
            orderProductList.add(orderProduct);
        }
        Test.startTest();
        UpserBulkOrderProduct bulkorderProduct = new UpserBulkOrderProduct(orderProductList);
        ID jobID = System.enqueueJob(bulkorderProduct);
        Test.stopTest();
    }
}