force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product_Line__c/Store_Product_Line__c.object-meta.xml
<CustomObject>
    <label>Store Product Line</label>
    <nameField>
        <displayFormat>SPLC-{YYYY}{MM}{0000}</displayFormat>
        <label>Store Product Line Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product_Line__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Store Product Lines</relationshipLabel>
    <relationshipName>Store_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StoreProductLineTriggerHandlerTest.cls
@isTest
private class StoreProductLineTriggerHandlerTest {
    static testMethod void testMethod1() {
        
        Shop__c ss = new Shop__c();
        ss.Name = 'test';
        insert ss;
        Store_Product_Line__c s = new Store_Product_Line__c();
        s.Product_Line__c = 'TV';
        s.Store__c = ss.id;
        insert s;

        s.Product_Line__c = 'AC';
        update s;

    }

   
}