force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>城市</description>
    <label>城市</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shop__c/fields/External_Key_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Key_ID__c</fullName>
    <externalId>true</externalId>
    <label>送达方编码</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RefreshShopGriddingBatch.cls
/**
 * @description       : 
 * @author            : chenpeng@deloitte.com.cn
 * @group             : 
 * @last modified on  : 03-05-2022
 * @last modified by  : chenpeng@deloitte.com.cn
**/
global with sharing class RefreshShopGriddingBatch implements Database.Batchable<sObject>,Database.Stateful {
    public String query;
    global RefreshShopGriddingBatch() {
        this.query = 'SELECT Id,City__c,External_Key_ID__c FROM Shop__c';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Shop__c> queryList) {
        if (!queryList.isEmpty()) {
            UPDATE queryList;
        }
    }

    global void finish(Database.BatchableContext BC) {
        
    }
}