force-app/main/default/objects/GlobalSetting__c/GlobalSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>全局设置</label>
</CustomObject>

force-app/main/default/objects/Interface_Url__c/Interface_Url__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Interface_Url</label>
</CustomObject>

force-app/main/default/objects/Interface_Url__c/fields/Basic_Url__c.field-meta.xml
<CustomField>
    <fullName>Basic_Url__c</fullName>
    <label>Basic Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/Responsible_Person__c.object-meta.xml
<CustomObject>
    <label>Responsible person</label>
    <nameField>
        <displayFormat>RP-{YYYY}{MM}{0000}</displayFormat>
        <label>门店负责人编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsible persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Responsible_Person__c/fields/External_Key_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Key_ID__c</fullName>
    <formula>Shop_Name__r.External_Key_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>送达方编码</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>负责人类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>巡店员</fullName>
            </value>
            <value>
                <fullName>促销员</fullName>
            </value>
            <value>
                <fullName>Regional Manager</fullName>
                <label>区域经理</label>
            </value>
            <value>
                <fullName>Backup Floorwalker</fullName>
                <isActive>false</isActive>
                <label>Backup Floorwalker</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/SAPCreate__c.field-meta.xml
<CustomField>
    <fullName>SAPCreate__c</fullName>
    <label>SAP创建者</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/SAPCreateTime__c.field-meta.xml
<CustomField>
    <fullName>SAPCreateTime__c</fullName>
    <label>SAP创建时间</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/SAPExternal__c.field-meta.xml
<CustomField>
    <fullName>SAPExternal__c</fullName>
    <externalId>true</externalId>
    <label>SAP送达方&amp;抛点编码</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/SAPUserName__c.field-meta.xml
<CustomField>
    <fullName>SAPUserName__c</fullName>
    <label>负责人SAP姓名</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Shop_Id__c.field-meta.xml
<CustomField>
    <fullName>Shop_Id__c</fullName>
    <label>门店Id(后台使用)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Responsible_Person__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>门店名称</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>Shop_Responsible_Person</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>门店名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/External_Key_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Key_ID__c</fullName>
    <externalId>true</externalId>
    <label>送达方编码</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Shop__c/fields/Responsible_Person__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>巡店员</label>
    <referenceTo>User</referenceTo>
    <relationshipName>shops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetResponsiblePersonFROMSAP.cls
/**********************************************************************
* Name: GetResponsiblePersonFROMSAP 
* Object: Responsible_Person__c 
* Purpose: 获取门店巡店员
* Author: Gerry
* Create Date: 2020-02-17
*************************************************************************/
public with sharing class GetResponsiblePersonFROMSAP {
	
	public class Result {
		public String FAILREASON;
		public String ISSUCCESS;
		public List<ResponseData> itab;
	}
	public class ResponseData {
		public String KUNWE;
		public String ZPDBM;
		public String ZPDDD;
		public String ERDAT;
		public String ERNAM;
		public String ERZET;
	}	

	public class RequestData {
		public String BUKRS;
		public String ISDATE;
		public String IEDATE;
		public String KUNWE;
	}   

	@Future(callout =true)
	public static void getPersonInfo (String BUKRS, String ISDATE, String IEDATE) {
		String responseBody;
		String requestBody;
		try {
			RequestData requestData = new RequestData();
			requestData.KUNWE = '';
			requestData.BUKRS = BUKRS;
			requestData.ISDATE = ISDATE;
			requestData.IEDATE = IEDATE;	 

			requestBody = JSON.serialize(requestData);
			Blob headerValue = Blob.valueOf(Interface_Url__c.getValues('SAPResponsiblePerson').User_Name__c + ':' + Interface_Url__c.getValues('SAPResponsiblePerson').Password__c);
	        String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
	        HttpRequest request = new HttpRequest();
	        request.setEndpoint(Interface_Url__c.getValues('SAPResponsiblePerson').Basic_Url__c);
	        request.setMethod('POST');
	        request.setTimeout(120000);
	        request.setHeader('Content-Type', 'application/json');
	        request.setHeader('Authorization', authorizationHeader);
	        request.setBody(requestBody);
	        HttpResponse response = new HttpResponse();
	        Http http = new Http(); 
	        response = http.send(request);
	        responseBody = response.getBody();
	        System.debug('responseBody:' + responseBody);
	        if (response.getStatusCode()==200) {
	        	Result result  =(Result)JSON.deserialize(responseBody,Result.class );
	        	if (result.ISSUCCESS == 'True') {
	        		List<Responsible_Person__c> personList = new List<Responsible_Person__c>();
	        		String dateString;
					String timeString;
	        		for (ResponseData re : result.itab) {
	        			Responsible_Person__c person = new Responsible_Person__c();
	        			person.SAPCreate__c = re.ERNAM;
	        			dateString = String.valueOf(re.ERDAT);
						timeString = String.valueOf(re.ERZET);
	        			person.SAPCreateTime__c = dateString.substring(0, 4)+'-'+dateString.substring(4, 6)+'-'+dateString.substring(6)+' '+timeString.substring(0, 2)+':'+timeString.substring(2, 4)+':'+timeString.substring(4);		
	        			person.SAPExternal__c = re.KUNWE + '-' + re.ZPDBM;
						person.SAPUserName__c = re.ZPDDD;
						person.RecordType__c = '巡店员';
						person.Shop_Id__c = re.KUNWE;
						person.Shop_Name__r = new Shop__c(External_Key_ID__c = re.KUNWE);
						personList.add(person);
					}		
					String bodyUserNotExist = '';
	        		if (personList.size()>0) {

						//忽略触发器更新
						GlobalSetting__c ignoreGs = Utility.IgnoreAction(true, true, true, 'GetResponsiblePersonFROMSAP');

						List<Database.upsertResult> resultsOrder = Database.upsert(personList, Responsible_Person__c.Fields.SAPExternal__c, false);
						
						//恢复触发器
						Utility.IgnoreAction(false,false,false,'');

						String errorMessage = '';
						Boolean isSucceed = true;
						for (Database.UpsertResult sr : resultsOrder) {
							if (sr.isSuccess()) {

							}else {
								for(Database.Error err : sr.getErrors()) {
									isSucceed = false;
									errorMessage = errorMessage + err;
									System.debug('error has occurred.' + err.getStatusCode() + ': ' + err.getMessage());                    
									System.debug('fields that affected this error: ' + err.getFields());
								}
							}
						}

						//插入日志
						SFUtility.writeCallLogs(String.valueOf(isSucceed), 'GetResponsiblePersonFROMSAP', requestBody, responseBody, 'Outbound', errorMessage);
	        		}
		            return ;
	        	}else{
					//插入日志
					SFUtility.writeCallLogs('false', 'GetResponsiblePersonFROMSAP', requestBody, responseBody, 'Outbound', '返回ISSUCCESS为false：' + responseBody);
		            return ;
	        	}	
	        }else{
				//插入日志
				SFUtility.writeCallLogs('false', 'GetResponsiblePersonFROMSAP', requestBody, responseBody, 'Outbound', '调用外部接口失败：' + responseBody);
	            return ;
	        }    
		}
		catch (Exception e) {
			String errorMsg = e.getMessage() + 'Line:  ' + e.getLineNumber();

            //插入日志
            SFUtility.writeCallLogs('false', 'GetResponsiblePersonFROMSAP', requestBody, responseBody, 'Outbound', errorMsg);
            return ;     
		}
	}  
}