force-app/main/default/objects/Exhibition_Arrangement__c/Exhibition_Arrangement__c.object-meta.xml
<CustomObject>
    <label>Exhibition Arrangement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Arrangements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Exhibition_Hotel__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Exhibition_Hotel__c.Exhibition_Management__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Exhibition_Management__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Exhibition_Hotel__c</referenceTo>
    <relationshipLabel>Exhibition Arrangements</relationshipLabel>
    <relationshipName>Exhibition_Arrangements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Exhibition_Management__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Management</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Exhibition Arrangements</relationshipLabel>
    <relationshipName>Exhibition_Arrangements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Internal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Internal_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Registration</label>
    <referenceTo>Internal_Registration__c</referenceTo>
    <relationshipName>Exhibition_Vehicle_Arrangements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Roommate__c.field-meta.xml
<CustomField>
    <fullName>Roommate__c</fullName>
    <label>Roommate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exhibition_Hotel__c/Exhibition_Hotel__c.object-meta.xml
<CustomObject>
    <label>Exhibition Point</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Points</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Hotel__c/fields/Exhibition_Management__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Management</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipName>Exhibition_Hotels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Vehical_Booking__c/Exhibition_Vehical_Booking__c.object-meta.xml
<CustomObject>
    <label>Vehical Booking</label>
    <nameField>
        <label>Vehical Booking Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehical Bookings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Vehical_Booking__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <formula>Text(Internal_Registration__r.Approval_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approval Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exhibition_Vehical_Booking__c/fields/Exhibition_Arrangement__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Arrangement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Arrangement</label>
    <referenceTo>Exhibition_Arrangement__c</referenceTo>
    <relationshipLabel>Vehical Bookings</relationshipLabel>
    <relationshipName>Vehical_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Vehical_Booking__c/fields/Exhibition_Management__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Management__c</fullName>
    <formula>ExpoInfo_Id__r.Name +&apos; &apos;+  ExpoInfo_Id__r.TitleEN__c</formula>
    <label>Exhibition Management</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exhibition_Vehical_Booking__c/fields/Internal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Internal_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Registration</label>
    <referenceTo>Internal_Registration__c</referenceTo>
    <relationshipLabel>Vehical Bookings</relationshipLabel>
    <relationshipName>Vehical_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Vehical_Booking__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ShuttleBus</fullName>
                <label>大巴</label>
            </value>
            <value>
                <fullName>PickOff</fullName>
                <label>送机</label>
            </value>
            <value>
                <fullName>PickUp</fullName>
                <label>接机</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/ExpoInfo__c.object-meta.xml
<CustomObject>
    <description>展会信息</description>
    <label>Exhibition Management</label>
    <nameField>
        <label>Exhibition Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Managements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoInfo__c/fields/DisplayInThePortal__c.field-meta.xml
<CustomField>
    <fullName>DisplayInThePortal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display in the Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/LastRegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>LastRegistrationDate__c</fullName>
    <label>Last Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/TitleEN__c.field-meta.xml
<CustomField>
    <fullName>TitleEN__c</fullName>
    <label>Exhibition Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/Internal_Registration__c.object-meta.xml
<CustomObject>
    <label>Internal Registration</label>
    <nameField>
        <label>Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Registration__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>未审批</fullName>
                <default>true</default>
                <label>未审批</label>
            </value>
            <value>
                <fullName>部门审批中</fullName>
            </value>
            <value>
                <fullName>审批通过</fullName>
            </value>
            <value>
                <fullName>审批驳回</fullName>
            </value>
            <value>
                <fullName>部门审批通过</fullName>
            </value>
            <value>
                <fullName>总办审批中</fullName>
            </value>
            <value>
                <fullName>部门审批驳回</fullName>
            </value>
            <value>
                <fullName>高级权限</fullName>
            </value>
            <value>
                <fullName>否决</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总审批中</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总通过</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总驳回</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Deliverable__c.field-meta.xml
<CustomField>
    <fullName>Deliverable__c</fullName>
    <label>Deliverable</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Exhibition_Id__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Exhibition Name</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Internal Registrations</relationshipLabel>
    <relationshipName>Expo_Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Name_CN__c.field-meta.xml
<CustomField>
    <fullName>Name_CN__c</fullName>
    <label>Name CN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Purpose_Of_Exhibition__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Of_Exhibition__c</fullName>
    <label>Purpose Of Exhibition</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>客户接待</fullName>
            </value>
            <value>
                <fullName>筹撤展（限项目组）</fullName>
            </value>
            <value>
                <fullName>Decorate Dismantle（Limited Project Team）</fullName>
            </value>
            <value>
                <fullName>产品讲解</fullName>
            </value>
            <value>
                <fullName>Product Explanation</fullName>
            </value>
            <value>
                <fullName>竞品调研</fullName>
            </value>
            <value>
                <fullName>Competitive Product Research</fullName>
            </value>
            <value>
                <fullName>公关/法务/行政/IT等</fullName>
            </value>
            <value>
                <fullName>Public  Relations/Legal/Administrative /IT, etc</fullName>
            </value>
            <value>
                <fullName>Customer Communication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>岗位</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>岗位编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ExhibitionRemindInternalFillArrTest.cls
@isTest
private class ExhibitionRemindInternalFillArrTest {
     static testMethod void testMethod1() {
        ExpoInfo__c e1 = new ExpoInfo__c(
        	LastRegistrationDate__c = Date.today()+15, 
        	StartDate__c = Date.today()+1, 
        	EndDate__c = Date.today()+10,
        	Name = '展会信息',
        	TitleEN__c = 'Exhibition Informatino',
        	DisplayInThePortal__c = true
        	);
        INSERT e1;

        Internal_Registration__c e2 = new Internal_Registration__c(
        	Exhibition_Id__c = e1.Id,
        	Email__c = 'etpeng@deloitte.com.cn',
        	Position__c = '经理',
        	Phone__c = '18712345678',
        	Name_CN__c = '张三',
        	// //Purpose_Of_Exhibition__c = '参展目的',
        	Deliverable__c = 'werytukjgfsdtrewertyuilkftgjdfrelgeoiagoewutoewutpewprwqoupwertyuiowytrertyuioiytryuoipiuuweoiriueygwritwerhitoewqhojhewfrihgoierjhotkohgjdslgjrojyore',
			Approval_Status__c = '审批通过'
			);
        INSERT e2;

        Exhibition_Hotel__c h1 = new Exhibition_Hotel__c(Name = 'hotel1',
        	Exhibition_Management__c = e1.Id);
        INSERT h1;
        Exhibition_Hotel__c h2 = new Exhibition_Hotel__c(Name = 'hotel2',
        	Exhibition_Management__c = e1.Id);
        INSERT h2;

        Exhibition_Arrangement__c e3 = new Exhibition_Arrangement__c(
        	Internal_Registration__c = e2.Id,
        	Roommate__c = 'shiyong');

        UPSERT e3;

        Exhibition_Vehical_Booking__c b1 = new Exhibition_Vehical_Booking__c(
            Vehicle_Type__c = '大巴',
            Date__c = Date.today(),
            Exhibition_Arrangement__c = e3.Id,
            Internal_Registration__c = e2.Id);
        INSERT b1;
        Exhibition_Vehical_Booking__c b2 = new Exhibition_Vehical_Booking__c(
            Vehicle_Type__c = '大巴',
            Date__c = Date.today(),
            Exhibition_Arrangement__c = e3.Id,
            Internal_Registration__c = e2.Id,
            Is_Arranged__c = TRUE);
        INSERT b2;

        



        ExhibitionRemindInternalFillArrSchedule sch = new ExhibitionRemindInternalFillArrSchedule();
		String fmt = '0 0 0/1 * * ? *';
		System.schedule('ExhibitionInvitationLetterSchedule for Test', fmt, sch);

    }

    static testMethod void testMethod2() {
        String profileName  = '展会 行政商务组';
        Id profileId = [SELECT Id FROM profile WHERE Name = :profileName][0].Id; 
        User user1 = new User(alias = '区域经理', email='TestTom@noemail.com',
        emailencodingkey='UTF-8', lastname='TestTom', languagelocalekey='en_US',
        localesidkey='en_US',profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='testTom@noemail.com');
        INSERT user1;
        
        ExpoInfo__c e1 = new ExpoInfo__c(
        	LastRegistrationDate__c = Date.today()+15, 
        	StartDate__c = Date.today()+1, 
        	EndDate__c = Date.today()+10,
        	Name = '展会信息',
        	TitleEN__c = 'Exhibition Informatino',
        	DisplayInThePortal__c = true
        	);
        INSERT e1;

       	Internal_Registration__c e2 = new Internal_Registration__c(
        	Exhibition_Id__c = e1.Id,
        	Email__c = 'etpeng@deloitte.com.cn',
        	Position__c = '经理',
        	Phone__c = '18712345678',
        	Name_CN__c = '张三',
        	// //Purpose_Of_Exhibition__c = '参展目的',
        	Deliverable__c = 'werytukjgfsdtrewertyuilkftgjdfrelgeoiagoewutoewutpewprwqoupwertyuiowytrertyuioiytryuoipiuuweoiriueygwritwerhitoewqhojhewfrihgoierjhotkohgjdslgjrojyore',
			Approval_Status__c = '审批通过'
			);
        INSERT e2;

        Exhibition_Hotel__c h1 = new Exhibition_Hotel__c(Name = 'hotel1',
        	Exhibition_Management__c = e1.Id);
        INSERT h1;
        Exhibition_Hotel__c h2 = new Exhibition_Hotel__c(Name = 'hotel2',
        	Exhibition_Management__c = e1.Id);
        INSERT h2;

        Exhibition_Arrangement__c e3 = new Exhibition_Arrangement__c(
        	Internal_Registration__c = e2.Id,
        	Roommate__c = 'shiyong');

        UPSERT e3;

        Exhibition_Vehical_Booking__c b1 = new Exhibition_Vehical_Booking__c(
            Vehicle_Type__c = '大巴',
            Date__c = Date.today(),
            Exhibition_Arrangement__c = e3.Id,
            Internal_Registration__c = e2.Id);
        INSERT b1;
        Exhibition_Vehical_Booking__c b2 = new Exhibition_Vehical_Booking__c(
            Vehicle_Type__c = '大巴',
            Date__c = Date.today(),
            Exhibition_Arrangement__c = e3.Id,
            Internal_Registration__c = e2.Id,
            Is_Arranged__c = TRUE);
        INSERT b2;




		ExhibitionRemindInternalFillArrBatch eb = new ExhibitionRemindInternalFillArrBatch();
		Database.executeBatch(eb, 80);

    }
}