force-app/main/default/objects/Exhibition_Arrangement__c/Exhibition_Arrangement__c.object-meta.xml
<CustomObject>
    <label>Exhibition Arrangement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Arrangements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Certificate_Type__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Type__c</fullName>
    <formula>Internal_Registration__r.Certificate_Type_Text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Certificate Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Exhibition_Management__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Management</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Exhibition Arrangements</relationshipLabel>
    <relationshipName>Exhibition_Arrangements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Internal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Internal_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Registration</label>
    <referenceTo>Internal_Registration__c</referenceTo>
    <relationshipName>Exhibition_Vehicle_Arrangements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_OA_Second_Approver__c/Exhibition_OA_Second_Approver__c.object-meta.xml
<CustomObject>
    <label>OA 二级审批人</label>
    <nameField>
        <label>二级审批人</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OA 二级审批人</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_OA_Second_Approver__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>亚太区|Asia-Pacific</fullName>
            </value>
            <value>
                <fullName>欧洲区|Europe</fullName>
            </value>
            <value>
                <fullName>东盟区|ASEAN</fullName>
            </value>
            <value>
                <fullName>中东非-MEA Region</fullName>
            </value>
            <value>
                <fullName>欧洲-EU Region</fullName>
            </value>
            <value>
                <fullName>美洲-Americas Region</fullName>
            </value>
            <value>
                <fullName>总部-HQ</fullName>
            </value>
            <value>
                <fullName>亚太-Asia-Pacific Region</fullName>
            </value>
            <value>
                <fullName>东盟-ASEAN</fullName>
            </value>
            <value>
                <fullName>日本-Japan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exhibition_OA_Second_Approver__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>类型</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>部门</fullName>
            </value>
            <value>
                <fullName>总办</fullName>
            </value>
            <value>
                <fullName>大区</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exhibition_OA_Second_Approver__c/fields/XHNumber__c.field-meta.xml
<CustomField>
    <fullName>XHNumber__c</fullName>
    <label>信鸿号</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expo_Certificate_Assignment__c/Expo_Certificate_Assignment__c.object-meta.xml
<CustomObject>
    <description>用于记录展会不同部门持有的证书类型以及有效期</description>
    <label>Expo Certificate Assignment</label>
    <nameField>
        <displayFormat>SOI-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expo Certificate Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expo_Certificate_Assignment__c/fields/Certificate_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Quantity__c</fullName>
    <description>商证数量</description>
    <label>Certificate Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expo_Certificate_Assignment__c/fields/Exhibition_Management__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Management</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Expo Certificate Assignments</relationshipLabel>
    <relationshipName>Expo_Certificate_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expo_Certificate_Assignment__c/fields/Expend_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Expend_Quantity__c</fullName>
    <description>证书已使用数量</description>
    <label>Expend Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expo_Certificate_Assignment__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIDAA</fullName>
            </value>
            <value>
                <fullName>视像科技公司</fullName>
            </value>
            <value>
                <fullName>家电集团</fullName>
            </value>
            <value>
                <fullName>中国区营销总部</fullName>
            </value>
            <value>
                <fullName>深圳信扬公司</fullName>
            </value>
            <value>
                <fullName>工业设计中心</fullName>
            </value>
            <value>
                <fullName>智慧生活产业集群/研发管理部</fullName>
            </value>
            <value>
                <fullName>总部-HQ</fullName>
            </value>
            <value>
                <fullName>亚太-Asia-Pacific Region</fullName>
            </value>
            <value>
                <fullName>东盟-ASEAN</fullName>
            </value>
            <value>
                <fullName>美洲-Americas Region</fullName>
            </value>
            <value>
                <fullName>集团公司</fullName>
            </value>
            <value>
                <fullName>信息科技公司</fullName>
            </value>
            <value>
                <fullName>欧洲-EU Region</fullName>
            </value>
            <value>
                <fullName>中东非-MEA Region</fullName>
            </value>
            <value>
                <fullName>国际营销领导</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expo_Certificate_Assignment__c/fields/Validity__c.field-meta.xml
<CustomField>
    <fullName>Validity__c</fullName>
    <description>有效天数</description>
    <label>Validity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expo_Certificate_Assignment__c/fields/Validity_Date__c.field-meta.xml
<CustomField>
    <fullName>Validity_Date__c</fullName>
    <defaultValue>0</defaultValue>
    <description>临时证勾选使用天数</description>
    <label>Validity Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expo_Date_Controller__c/Expo_Date_Controller__c.object-meta.xml
<CustomObject>
    <description>对各个场景限定周日进行配置</description>
    <label>Expo Date Controller</label>
    <nameField>
        <label>Expo Date Controller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expo Date Controllers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expo_Date_Controller__c/fields/Exhibition_Management__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Management</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Expo Date Controllers</relationshipLabel>
    <relationshipName>Expo_Date_Controllers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expo_Date_Controller__c/fields/SignUp_End_Date__c.field-meta.xml
<CustomField>
    <fullName>SignUp_End_Date__c</fullName>
    <description>注册结束日期</description>
    <label>SignUp End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/ExpoInfo__c.object-meta.xml
<CustomObject>
    <description>展会信息</description>
    <label>Exhibition Management</label>
    <nameField>
        <label>Exhibition Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Managements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoInfo__c/fields/DisplayInThePortal__c.field-meta.xml
<CustomField>
    <fullName>DisplayInThePortal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display in the Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/LastRegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>LastRegistrationDate__c</fullName>
    <label>Last Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/TitleEN__c.field-meta.xml
<CustomField>
    <fullName>TitleEN__c</fullName>
    <label>Exhibition Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/Internal_Registration__c.object-meta.xml
<CustomObject>
    <label>Internal Registration</label>
    <nameField>
        <label>Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Registration__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>未审批</fullName>
                <default>true</default>
                <label>未审批</label>
            </value>
            <value>
                <fullName>部门审批中</fullName>
            </value>
            <value>
                <fullName>审批通过</fullName>
            </value>
            <value>
                <fullName>审批驳回</fullName>
            </value>
            <value>
                <fullName>部门审批通过</fullName>
            </value>
            <value>
                <fullName>总办审批中</fullName>
            </value>
            <value>
                <fullName>部门审批驳回</fullName>
            </value>
            <value>
                <fullName>高级权限</fullName>
            </value>
            <value>
                <fullName>否决</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总审批中</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总通过</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总驳回</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <label>Approver</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Exhibition_Id__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Exhibition Name</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Internal Registrations</relationshipLabel>
    <relationshipName>Expo_Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Name_CN__c.field-meta.xml
<CustomField>
    <fullName>Name_CN__c</fullName>
    <label>Name CN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Validity_Date__c.field-meta.xml
<CustomField>
    <fullName>Validity_Date__c</fullName>
    <description>供临时证记录使用的日期</description>
    <label>Validity Date</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>04-15</fullName>
            </value>
            <value>
                <fullName>04-16</fullName>
            </value>
            <value>
                <fullName>04-17</fullName>
            </value>
            <value>
                <fullName>04-18</fullName>
            </value>
            <value>
                <fullName>04-19</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/XHNumber__c.field-meta.xml
<CustomField>
    <fullName>XHNumber__c</fullName>
    <inlineHelpText>LDAP账号,邮箱@之前的部分</inlineHelpText>
    <label>XHNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExhibitionSSOVerifyControllerTest.cls
@isTest
private class ExhibitionSSOVerifyControllerTest {
    static testMethod void testMethod1() {
        Exhibition_OA_Second_Approver__c eosa = new Exhibition_OA_Second_Approver__c(Name = '二级审批人',XHNumber__c = 'test3',Type__c='部门');
        INSERT eosa;
        ExhibitionSSOVerifyController.getSecondApprover('部门');
        ExhibitionSSOVerifyController.getOAapprover('部门');
        ExhibitionSSOVerifyController.getExhibition();

    }

    static testMethod void testMethod2() {

        Expo_Certificate_Assignment__c ass = new Expo_Certificate_Assignment__c(
            Approver__c = 'wang@hisense.com',
            Region__c = '总部-HQ',
            Certificate_Quantity__c = 10,
            Expend_Quantity__c = 0,
            Validity__c = 20,
            Validity_Date__c = 0
        );
        INSERT ass;

        Expo_Certificate_Assignment__c ass1 = new Expo_Certificate_Assignment__c(
            Region__c = 'VIDAA',
            Certificate_Quantity__c = 10,
            Expend_Quantity__c = 0,
            Validity__c = 20,
            Validity_Date__c = 0
        );
        INSERT ass1;

        ExpoInfo__c e1 = new ExpoInfo__c(
        	LastRegistrationDate__c = Date.today()+5, 
        	StartDate__c = Date.today()-10, 
        	EndDate__c = Date.today()+10,
        	Name = '展会信息',
        	TitleEN__c = 'Exhibition Informatino',
        	DisplayInThePortal__c = true
        	);
        INSERT e1;

        Expo_Date_Controller__c d = new Expo_Date_Controller__c(
        	Name = 'Exhibition Date',
            Exhibition_Management__c = e1.Id,
        	SignUp_End_Date__c = Date.today()
        );

        INSERT d;

        Internal_Registration__c e2 = new Internal_Registration__c(
        	Exhibition_Id__c = e1.Id,
        	Email__c = 'taojingpeng.ex@hx-partners.com',
        	Position__c = '经理',
        	Phone__c = '18712345678',
        	Name_CN__c = '张三',
            Approval_Status__c = '未审批',
            Certificate_Type__c = '筹展证|Day Voucher for booth construction ;临时证|Day Voucher',
            Approver__c = 'wang@hisense.com',
            Company__c = '总部-HQ',
            Validity_Date__c='03-01',
            XHNumber__c = 'taojingpeng.ex',
        	//Purpose_Of_Exhibition__c = '参展目的',
        	Deliverable__c = 'werytukjgfsdtrewertyuilkftgjdfrelgeoiagoewutoewutpewprwqoupwertyuiowytrertyuioiytryuoipiuuweoiriueygwritwerhitoewqhojhewfrihgoierjhotkohgjdslgjrojyore'
			);
        INSERT e2;

        Internal_Registration__c e5 = new Internal_Registration__c(
        	Exhibition_Id__c = e1.Id,
        	Email__c = 'taojingpeng.ex@hx-partners.com',
        	Position__c = '经理',
        	Phone__c = '18712345678',
        	Name_CN__c = '张三',
            Approval_Status__c = '未审批',
            Certificate_Type__c = '筹展证|Day Voucher for booth construction ;临时证|Day Voucher',
            Approver__c = 'wang@hisense.com',
            Company__c = '总部-HQ',
            Validity_Date__c='03-01',
            XHNumber__c = 'test',
        	//Purpose_Of_Exhibition__c = '参展目的',
        	Deliverable__c = 'werytukjgfsdtrewertyuilkftgjdfrelgeoiagoewutoewutpewprwqoupwertyuiowytrertyuioiytryuoipiuuweoiriueygwritwerhitoewqhojhewfrihgoierjhotkohgjdslgjrojyore'
			);
        INSERT e5;

        Exhibition_Arrangement__c e3 = new Exhibition_Arrangement__c(
        Internal_Registration__c = e2.Id,
		PresenceDate__c =  Datetime.now().addDays(-4).format('MM-dd') +';' + Datetime.now().addDays(-4).format('MM-dd'),
        Roommate__c = 'shiyong');
        INSERT e3;

        Test.startTest();
    	String json1 = '{"resCode": "SUCCESS","resMess": "SUCCESS","tokenId": "8e37cf631b434911be580ade72ed89b9", "effecTime": "2023-08-30 17:50:53"}';
    	Test.setMock(HttpCalloutMock.class, new CalloutMock(json1));
        String json = '{"code": "0","timestamp": "1761794259467","data": {    "telephoneNumber": "",    "mail": "taojingpeng.ex@hx-partners.com",    "ou": "%E5%9B%BD%E9%99%85%E8%90%A5%E9%94%80%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E9%83%A8",    "otherDepartments": [        "1"    ],    "mobile": "18037506005",    "usertype": "external",    "cn": "%E9%99%B6%E9%9D%96%E6%9C%8B.ex",    "title": "",    "idNumber": "411328199711260679",    "employeeNumber": "",    "o": "%E5%A4%96%E9%83%A8%E4%BA%BA%E5%91%98%5C%E5%A4%96%E5%8D%8F%5C%E9%9B%86%E5%9B%A2%E5%85%AC%E5%8F%B8%5C%E6%95%B0%E8%B4%A8%E4%B8%AD%E5%BF%83%5C%E6%95%B0%E7%A7%91%E5%85%AC%E5%8F%B8%5C%E5%9B%BD%E9%99%85%E8%90%A5%E9%94%80%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E9%83%A8",    "uid": "taojingpeng.ex",    "cnen": "taojingpeng.ex",    "sn": "%E9%99%B6"},"msg": "操作成功"}';
        Test.setMock(HttpCalloutMock.class, new CalloutMock(json));


        ExhibitionSSOVerifyController.getDepartment(e1.Id);
        ExhibitionSSOVerifyController.verifyInternalRegistration(e2.Id);
        ExhibitionSSOVerifyController.verifyInternalRegistration(e5.Id);
        ExhibitionSSOVerifyController.getCompany(e1.Id);
        ExhibitionSSOVerifyController.getCompanyAbbr(e1.Id,'总部-HQ');
        ExhibitionSSOVerifyController.IsExistVerify(e1.Id);
        ExhibitionSSOVerifyController.verifyInternalRegistrations(e1.Id);
        Test.stopTest();
    }

}