force-app/main/default/objects/Exhibition_Arrangement__c/Exhibition_Arrangement__c.object-meta.xml
<CustomObject>
    <label>Exhibition Arrangement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Arrangements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Internal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Internal_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Registration</label>
    <referenceTo>Internal_Registration__c</referenceTo>
    <relationshipName>Exhibition_Vehicle_Arrangements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Roommate__c.field-meta.xml
<CustomField>
    <fullName>Roommate__c</fullName>
    <label>Roommate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exhibition_Regular_Bus_Booking__c/Exhibition_Regular_Bus_Booking__c.object-meta.xml
<CustomObject>
    <label>Exhibition Regular Bus Booking</label>
    <nameField>
        <label>Exhibition Regular Bus Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Regular Bus Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Regular_Bus_Booking__c/fields/ExpoInfo_Id__c.field-meta.xml
<CustomField>
    <fullName>ExpoInfo_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ExpoInfo Id</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Exhibition Regular Bus Bookings</relationshipLabel>
    <relationshipName>Exhibition_Regular_Bus_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Regular_Bus_Booking__c/fields/Internal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Internal_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Registration</label>
    <referenceTo>Internal_Registration__c</referenceTo>
    <relationshipLabel>Exhibition Regular Bus Bookings</relationshipLabel>
    <relationshipName>Exhibition_Regular_Bus_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Regular_Bus_Booking__c/fields/Is_Arranged__c.field-meta.xml
<CustomField>
    <fullName>Is_Arranged__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>下发通知</inlineHelpText>
    <label>Is Arranged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/ExpoInfo__c.object-meta.xml
<CustomObject>
    <description>展会信息</description>
    <label>Exhibition Management</label>
    <nameField>
        <label>Exhibition Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Managements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoInfo__c/fields/DisplayInThePortal__c.field-meta.xml
<CustomField>
    <fullName>DisplayInThePortal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display in the Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/LastRegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>LastRegistrationDate__c</fullName>
    <label>Last Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/TitleEN__c.field-meta.xml
<CustomField>
    <fullName>TitleEN__c</fullName>
    <label>Exhibition Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/Internal_Registration__c.object-meta.xml
<CustomObject>
    <label>Internal Registration</label>
    <nameField>
        <label>Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Registration__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>未审批</fullName>
                <default>true</default>
                <label>未审批</label>
            </value>
            <value>
                <fullName>部门审批中</fullName>
            </value>
            <value>
                <fullName>审批通过</fullName>
            </value>
            <value>
                <fullName>审批驳回</fullName>
            </value>
            <value>
                <fullName>部门审批通过</fullName>
            </value>
            <value>
                <fullName>总办审批中</fullName>
            </value>
            <value>
                <fullName>部门审批驳回</fullName>
            </value>
            <value>
                <fullName>高级权限</fullName>
            </value>
            <value>
                <fullName>否决</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总审批中</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总通过</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总驳回</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Deliverable__c.field-meta.xml
<CustomField>
    <fullName>Deliverable__c</fullName>
    <label>Deliverable</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Exhibition_Id__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Exhibition Name</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Internal Registrations</relationshipLabel>
    <relationshipName>Expo_Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Name_CN__c.field-meta.xml
<CustomField>
    <fullName>Name_CN__c</fullName>
    <label>Name CN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Purpose_Of_Exhibition__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Of_Exhibition__c</fullName>
    <label>Purpose Of Exhibition</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>客户接待</fullName>
            </value>
            <value>
                <fullName>筹撤展（限项目组）</fullName>
            </value>
            <value>
                <fullName>Decorate Dismantle（Limited Project Team）</fullName>
            </value>
            <value>
                <fullName>产品讲解</fullName>
            </value>
            <value>
                <fullName>Product Explanation</fullName>
            </value>
            <value>
                <fullName>竞品调研</fullName>
            </value>
            <value>
                <fullName>Competitive Product Research</fullName>
            </value>
            <value>
                <fullName>公关/法务/行政/IT等</fullName>
            </value>
            <value>
                <fullName>Public  Relations/Legal/Administrative /IT, etc</fullName>
            </value>
            <value>
                <fullName>Customer Communication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>岗位</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>岗位编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ExhibitionBusTriggerTest.cls
@isTest
private class ExhibitionBusTriggerTest {
    static testMethod void testMethod1() {
        ExpoInfo__c e1 = new ExpoInfo__c(
        	LastRegistrationDate__c = Date.today()+15, 
        	StartDate__c = Date.today()-1, 
        	EndDate__c = Date.today()+10,
        	Name = '展会信息',
        	TitleEN__c = 'Exhibition Informatino',
        	DisplayInThePortal__c = true
        	);
        INSERT e1;

        Internal_Registration__c e2 = new Internal_Registration__c(
        	Exhibition_Id__c = e1.Id,
        	Email__c = 'etpeng@deloitte.com.cn',
        	Position__c = '经理',
        	Phone__c = '18712345678',
        	Name_CN__c = '张三',
        	//Purpose_Of_Exhibition__c = '参展目的',
        	Deliverable__c = 'werytukjgfsdtrewertyuilkftgjdfrelgeoiagoewutoewutpewprwqoupwertyuiowytrertyuioiytryuoipiuuweoiriueygwritwerhitoewqhojhewfrihgoierjhotkohgjdslgjrojyore',
			Approval_Status__c = '审批通过'
			);
        INSERT e2;

        Exhibition_Arrangement__c e3 = new Exhibition_Arrangement__c(
        	Internal_Registration__c = e2.Id,
        	Roommate__c = 'shiyong');

        INSERT e3;

        e3.Roommate__c = '室友';
        UPDATE e3;

        Exhibition_Regular_Bus_Booking__c b1 = new Exhibition_Regular_Bus_Booking__c(
        	ExpoInfo_Id__c = e1.Id,
            Date__c = Date.today(),
        	Internal_Registration__c = e2.Id
			);
        INSERT b1;

		b1.Is_Arranged__c = TRUE;
        UPDATE b1;
    }
}