force-app/main/default/objects/Exhibition_Arrangement__c/Exhibition_Arrangement__c.object-meta.xml
<CustomObject>
    <label>Exhibition Arrangement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Arrangements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Designated_Hotel__c.field-meta.xml
<CustomField>
    <fullName>Designated_Hotel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Designated Hotel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Exhibition_Management__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Management</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Exhibition Arrangements</relationshipLabel>
    <relationshipName>Exhibition_Arrangements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Hotel_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Hotel_End_Date__c</fullName>
    <label>Hotel Check-out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Name__c</fullName>
    <formula>Exhibition_Hotel__r.Name</formula>
    <label>Hotel Name Invisible</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Hotel_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Start_Date__c</fullName>
    <label>Hotel Check-in Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Inbound_Flight_No__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Flight_No__c</fullName>
    <label>Inbound Flight No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Internal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Internal_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Registration</label>
    <referenceTo>Internal_Registration__c</referenceTo>
    <relationshipName>Exhibition_Vehicle_Arrangements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Is_Not_Flight__c.field-meta.xml
<CustomField>
    <fullName>Is_Not_Flight__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Not Flight</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Is_Not_Need_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Is_Not_Need_Vehicle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Not Need Vehicle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Is_Not_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Is_Not_Vehicle__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Not Vehicle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Return_Flight_No__c.field-meta.xml
<CustomField>
    <fullName>Return_Flight_No__c</fullName>
    <label>Return Flight No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/ExpoInfo__c.object-meta.xml
<CustomObject>
    <description>展会信息</description>
    <label>Exhibition Management</label>
    <nameField>
        <label>Exhibition Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Managements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoInfo__c/fields/LastRegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>LastRegistrationDate__c</fullName>
    <label>Last Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/TitleCN__c.field-meta.xml
<CustomField>
    <fullName>TitleCN__c</fullName>
    <formula>Name</formula>
    <label>Exhibition Name CN Invisible</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/Internal_Registration__c.object-meta.xml
<CustomObject>
    <label>Internal Registration</label>
    <nameField>
        <label>Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Registration__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>未审批</fullName>
                <default>true</default>
                <label>未审批</label>
            </value>
            <value>
                <fullName>部门审批中</fullName>
            </value>
            <value>
                <fullName>审批通过</fullName>
            </value>
            <value>
                <fullName>审批驳回</fullName>
            </value>
            <value>
                <fullName>部门审批通过</fullName>
            </value>
            <value>
                <fullName>总办审批中</fullName>
            </value>
            <value>
                <fullName>部门审批驳回</fullName>
            </value>
            <value>
                <fullName>高级权限</fullName>
            </value>
            <value>
                <fullName>否决</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总审批中</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总通过</fullName>
            </value>
            <value>
                <fullName>分管领导/大区总驳回</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Name_CN__c.field-meta.xml
<CustomField>
    <fullName>Name_CN__c</fullName>
    <label>Name CN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Name_EN__c.field-meta.xml
<CustomField>
    <fullName>Name_EN__c</fullName>
    <formula>Name</formula>
    <label>Name EN Invisible</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExhibitionRemindInternalFillArrBatch.cls
/**************************************************************************************************
 * Name: ExhibitionRemindInternalFillArrBatch
 * Object: Exhibition_Arrangement__c
 * Purpose: 提醒未填写行程信息的用户填写                行程信息-参展员工
 * ************************************************************************************************
 * History
 * --------
 * VERSION     AUTHOR              DATE            DETAIL             Description
 * 1.0          Ethan             2023-11-17         Created      
 
***************************************************************************************************/
global class ExhibitionRemindInternalFillArrBatch implements Database.Batchable<sObject> {
    private final static String Exhibition_Is_Not_Flight = System.label.Exhibition_Is_Not_Flight;
    private final static String Exhibition_Is_Not_Need_Vehicle = System.label.Exhibition_Is_Not_Need_Vehicle;
    private final static String Exhibition_Designated_Hotel = System.label.Exhibition_Designated_Hotel;
    private final static String SITE_URL_FRO = System.Url.getOrgDomainUrl().toExternalForm().split('.com')[0] + '-sites.com/exhibitionArrangementWithout/apex/ExhibitionArrPublicPage?id=';
    public String query;
    public Date queryDate;

    global ExhibitionRemindInternalFillArrBatch() {
        this.query = query;
        this.queryDate = Date.today();

    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        query = 'SELECT Id, Hotel_Name__c,Hotel_Start_Date__c,Hotel_End_Date__c, Designated_Hotel__c, Is_Not_Flight__c, Inbound_Flight_No__c, Return_Flight_No__c, Is_Not_Need_Vehicle__c, Is_Not_Vehicle__c, '  
            +'Internal_Registration__c,Internal_Registration__r.Name_CN__c,Internal_Registration__r.Name_EN__c,Internal_Registration__r.Email__c, '
            +'Exhibition_Management__r.StartDate__c,Exhibition_Management__r.TitleCN__c, Exhibition_Management__r.LastRegistrationDate__c '  
            +'FROM Exhibition_Arrangement__c WHERE Internal_Registration__r.Approval_Status__c = \'审批通过\' AND  Exhibition_Management__r.StartDate__c >=: queryDate '
            + 'AND ( (Is_Not_Flight__c = FALSE AND Inbound_Flight_No__c = NULL) OR (Designated_Hotel__c = FALSE AND Hotel_Start_Date__c = NULL) OR (Is_Not_Need_Vehicle__c = FALSE AND Is_Not_Vehicle__c = TRUE))';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Exhibition_Arrangement__c> scope) {
        try{
            if (!scope.isEmpty()) sendEmail(scope);
        }catch(Exception e) {
            System.debug('ExhibitionRemindInternalFillArrBatch Error--->'+e.getLineNumber()+e.getMessage());
        }
        
    }

    global void finish(Database.BatchableContext BC) {

    }
    global void sendEmail(List<Exhibition_Arrangement__c> exhArrList){
        EmailTemplate emtemp = [SELECT Id, Name, Subject, HtmlValue, Body, BrandTemplateId, DeveloperName 
            FROM EmailTemplate
            WHERE DeveloperName = 'Exhibition_Remind_Internal_Fill_Exhibitino_Arr' LIMIT 1];
        List<Messaging.SingleEmailMessage> sendEmailList = new List<Messaging.SingleEmailMessage>();
        for (Exhibition_Arrangement__c item: exhArrList) {
            String toName  = item.Internal_Registration__r.Name_CN__c == NULL ? '用户' : item.Internal_Registration__r.Name_CN__c;
            String strDate = String.valueOf(item.Exhibition_Management__r.StartDate__c);
            String exhiName = item.Exhibition_Management__r.TitleCN__c;
            String vehicleInfo = '';
                if (!item.Is_Not_Flight__c && item.Inbound_Flight_No__c == NULL) 
                    vehicleInfo+=('<li>'+ Exhibition_Is_Not_Flight + '</li>'); 
                if (!item.Designated_Hotel__c && item.Hotel_Start_Date__c == NULL) 
                    vehicleInfo+=('<li>'+ Exhibition_Designated_Hotel + '</li>'); 
                if (!item.Is_Not_Need_Vehicle__c && item.Is_Not_Vehicle__c) 
                    vehicleInfo+=('<li>'+ Exhibition_Is_Not_Need_Vehicle + '</li>'); 

            String bodyFormat = String.format(emtemp.HtmlValue, new List<String>{toName, strDate, exhiName,vehicleInfo, SITE_URL_FRO+item.Id});
            Messaging.SingleEmailMessage singleEmail = new Messaging.SingleEmailMessage();
                singleEmail.setSaveAsActivity(false);
                singleEmail.setTemplateId(emtemp.Id);
                singleEmail.setSubject(emtemp.Subject + '');
                //设置发送人邮箱
                singleEmail.setOrgWideEmailAddressId(System.Label.Exhibition_Public_Mailbox);
                singleEmail.setHtmlBody(bodyFormat);
                System.debug('bodyFormat-->'+bodyFormat);
                singleEmail.setToAddresses(new List<String>{item.Internal_Registration__r.Email__c});
                // singleEmail.setCcAddresses(item.Email__c);
                sendEmailList.add(singleEmail);
        }

            
            
        

        if (sendEmailList.size() > 0) {
            System.debug('------------>already send ! ');
            Messaging.sendEmail(sendEmailList);
        }

        
    }
}