force-app/main/default/objects/Exhibition_Arrangement__c/Exhibition_Arrangement__c.object-meta.xml
<CustomObject>
    <label>Exhibition Arrangement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Arrangements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Internal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Internal_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Registration</label>
    <referenceTo>Internal_Registration__c</referenceTo>
    <relationshipName>Exhibition_Vehicle_Arrangements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exhibition_Arrangement__c/fields/Roommate__c.field-meta.xml
<CustomField>
    <fullName>Roommate__c</fullName>
    <label>Roommate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/ExpoInfo__c.object-meta.xml
<CustomObject>
    <description>展会信息</description>
    <label>Exhibition Management</label>
    <nameField>
        <label>Exhibition Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Managements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoInfo__c/fields/DisplayInThePortal__c.field-meta.xml
<CustomField>
    <fullName>DisplayInThePortal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display in the Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/LastRegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>LastRegistrationDate__c</fullName>
    <label>Last Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/OutLineCN__c.field-meta.xml
<CustomField>
    <fullName>OutLineCN__c</fullName>
    <label>Exhibition Intro CN</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/TitleEN__c.field-meta.xml
<CustomField>
    <fullName>TitleEN__c</fullName>
    <label>Exhibition Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/Internal_Registration__c.object-meta.xml
<CustomObject>
    <label>Internal Registration</label>
    <nameField>
        <label>Name EN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Internal Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Registration__c/fields/Approval_FDID__c.field-meta.xml
<CustomField>
    <fullName>Approval_FDID__c</fullName>
    <label>Approval FDID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Deliverable__c.field-meta.xml
<CustomField>
    <fullName>Deliverable__c</fullName>
    <label>Deliverable</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Exhibition_Id__c.field-meta.xml
<CustomField>
    <fullName>Exhibition_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Exhibition Name</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Internal Registrations</relationshipLabel>
    <relationshipName>Expo_Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Name_CN__c.field-meta.xml
<CustomField>
    <fullName>Name_CN__c</fullName>
    <label>Name CN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Internal_Registration__c/fields/Purpose_Of_Exhibition__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Of_Exhibition__c</fullName>
    <label>Purpose Of Exhibition</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>客户接待</fullName>
            </value>
            <value>
                <fullName>筹撤展（限项目组）</fullName>
            </value>
            <value>
                <fullName>Decorate Dismantle（Limited Project Team）</fullName>
            </value>
            <value>
                <fullName>产品讲解</fullName>
            </value>
            <value>
                <fullName>Product Explanation</fullName>
            </value>
            <value>
                <fullName>竞品调研</fullName>
            </value>
            <value>
                <fullName>Competitive Product Research</fullName>
            </value>
            <value>
                <fullName>公关/法务/行政/IT等</fullName>
            </value>
            <value>
                <fullName>Public  Relations/Legal/Administrative /IT, etc</fullName>
            </value>
            <value>
                <fullName>Customer Communication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/Mapping_Configuration__c.object-meta.xml
<CustomObject>
    <label>Mapping Configuration</label>
    <nameField>
        <label>FdTemplateId</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping Configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mapping_Configuration__c/fields/Approval_Node1__c.field-meta.xml
<CustomField>
    <fullName>Approval_Node1__c</fullName>
    <label>审批节点1</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/Approval_Node2__c.field-meta.xml
<CustomField>
    <fullName>Approval_Node2__c</fullName>
    <label>审批节点2</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/Map_Name__c.field-meta.xml
<CustomField>
    <fullName>Map_Name__c</fullName>
    <label>配置名称</label>
    <length>225</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OA_Department_Code__c.field-meta.xml
<CustomField>
    <fullName>OA_Department_Code__c</fullName>
    <label>OA部门编码</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OA_Department_Name__c.field-meta.xml
<CustomField>
    <fullName>OA_Department_Name__c</fullName>
    <label>OA部门名称</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OA_Description__c.field-meta.xml
<CustomField>
    <fullName>OA_Description__c</fullName>
    <label>OA简述说明</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OA_Email__c.field-meta.xml
<CustomField>
    <fullName>OA_Email__c</fullName>
    <label>OA邮箱</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OA_Exhibition_Nmae__c.field-meta.xml
<CustomField>
    <fullName>OA_Exhibition_Nmae__c</fullName>
    <label>OA展会名称</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OA_Interactive__c.field-meta.xml
<CustomField>
    <fullName>OA_Interactive__c</fullName>
    <label>OA交互物</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OA_Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>OA_Internal_Name__c</fullName>
    <label>OA员工姓名</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OA_Phone__c.field-meta.xml
<CustomField>
    <fullName>OA_Phone__c</fullName>
    <label>OA电话</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OA_Position__c.field-meta.xml
<CustomField>
    <fullName>OA_Position__c</fullName>
    <label>OA岗位</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OA_Purpose_Exhibition__c.field-meta.xml
<CustomField>
    <fullName>OA_Purpose_Exhibition__c</fullName>
    <label>OA参展目的</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mapping_Configuration__c/fields/OAXH__c.field-meta.xml
<CustomField>
    <fullName>OAXH__c</fullName>
    <label>OAXH</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>岗位</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>岗位编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>岗位</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ReceiveDataFromWithoutExecutiveTest.cls
@isTest
private class ReceiveDataFromWithoutExecutiveTest {
     static testMethod void testMethod1() {
    	ExpoInfo__c e1 = new ExpoInfo__c(
        	LastRegistrationDate__c = Date.today()+15, 
        	StartDate__c = Date.today()-90, 
        	EndDate__c = Date.today()+10,
        	Name = '展会信息',
        	TitleEN__c = 'Exhibition Informatino',
        	DisplayInThePortal__c = true,
        	OutLineCN__c = 'Test_OutLineCN__c'
        	);
        INSERT e1;

        Internal_Registration__c e2 = new Internal_Registration__c(
        	Exhibition_Id__c = e1.Id,
        	Email__c = 'etpeng@deloitte.com.cn',
        	Position__c = '经理',
        	Phone__c = '18712345678',
        	Name_CN__c = '张三',
        	//Purpose_Of_Exhibition__c = '参展目的',
        	Approval_FDID__c = '4096574t3574934643reyw',
        	Deliverable__c = 'werytukjgfsdtrewertyuilkftgjdfrelgeoiagoewutoewutpewprwqoupwertyuiowytrertyuioiytryuoipiuuweoiriueygwritwerhitoewqhojhewfrihgoierjhotkohgjdslgjrojyore'
			);
        INSERT e2;

        Exhibition_Arrangement__c e3 = new Exhibition_Arrangement__c(
        	Internal_Registration__c = e2.Id,
        	Roommate__c = 'shiyong');

        INSERT e3;

        Mapping_Configuration__c m1 = new Mapping_Configuration__c(Map_Name__c = 'OADepartmentApproval',
        	OA_Exhibition_Nmae__c = 'test_OA_Exhibition_Nmae__c',
        	OA_Description__c = 'Test_OA_Description__c',
        	Approval_Node1__c = 'test_Approval_Node1__c',
        	Approval_Node2__c = 'test_Approval_Node2__c',
        	OA_Internal_Name__c = 'test_OA_Internal_Name__c',
        	OA_Position__c = 'test_OA_Position__c',
        	OA_Department_Name__c = 'test_OA_Department_Name__c',
        	OA_Department_Code__c = 'test_OA_Department_Code__c',
        	OA_Purpose_Exhibition__c = 'test_OA_Purpose_Exhibition__c',
        	OA_Interactive__c = 'test_OA_Interactive__c',
        	OA_Email__c = 'test_OA_Email__c',
        	OA_Phone__c = 'test_OA_Phone__c',
        	OAXH__c = 'test_OAXH__c'
        	);
        INSERT m1;


        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        Map<String, String> jsonMap = new Map<String, String>{'fdId'=>e2.Approval_FDID__c, 'docStatus' =>'30','opinion'=>'e07609832048604'};
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        req.requestBody = Blob.valueOf(JSON.serialize(jsonMap));

        ReceiveDataFromWithoutExecutive.doPost() ; 
        Test.stopTest();
    }

    static testMethod void testMethod2() {
    	ExpoInfo__c e1 = new ExpoInfo__c(
        	LastRegistrationDate__c = Date.today()+15, 
        	StartDate__c = Date.today()-90, 
        	EndDate__c = Date.today()+10,
        	Name = '展会信息',
        	TitleEN__c = 'Exhibition Informatino',
        	DisplayInThePortal__c = true,
        	OutLineCN__c = 'Test_OutLineCN__c'
        	);
        INSERT e1;

        Internal_Registration__c e2 = new Internal_Registration__c(
        	Exhibition_Id__c = e1.Id,
        	Email__c = 'etpeng@deloitte.com.cn',
        	Position__c = '经理',
        	Phone__c = '18712345678',
        	Name_CN__c = '张三',
        	//Purpose_Of_Exhibition__c = '参展目的',
        	Approval_FDID__c = '4096574t3574934643reyw',
        	Deliverable__c = 'werytukjgfsdtrewertyuilkftgjdfrelgeoiagoewutoewutpewprwqoupwertyuiowytrertyuioiytryuoipiuuweoiriueygwritwerhitoewqhojhewfrihgoierjhotkohgjdslgjrojyore'
			);
        INSERT e2;

        Exhibition_Arrangement__c e3 = new Exhibition_Arrangement__c(
        	Internal_Registration__c = e2.Id,
        	Roommate__c = 'shiyong');

        INSERT e3;

        Mapping_Configuration__c m1 = new Mapping_Configuration__c(Map_Name__c = 'OADepartmentApproval',
        	OA_Exhibition_Nmae__c = 'test_OA_Exhibition_Nmae__c',
        	OA_Description__c = 'Test_OA_Description__c',
        	Approval_Node1__c = 'test_Approval_Node1__c',
        	Approval_Node2__c = 'test_Approval_Node2__c',
        	OA_Internal_Name__c = 'test_OA_Internal_Name__c',
        	OA_Position__c = 'test_OA_Position__c',
        	OA_Department_Name__c = 'test_OA_Department_Name__c',
        	OA_Department_Code__c = 'test_OA_Department_Code__c',
        	OA_Purpose_Exhibition__c = 'test_OA_Purpose_Exhibition__c',
        	OA_Interactive__c = 'test_OA_Interactive__c',
        	OA_Email__c = 'test_OA_Email__c',
        	OA_Phone__c = 'test_OA_Phone__c',
        	OAXH__c = 'test_OAXH__c'
        	);
        INSERT m1;


        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        Map<String, String> jsonMap = new Map<String, String>{'fdId'=>e2.Approval_FDID__c, 'docStatus' =>'11','opinion'=>'e07609832048604'};
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        req.requestBody = Blob.valueOf(JSON.serialize(jsonMap));

        ReceiveDataFromWithoutExecutive.doPost() ; 
        Test.stopTest();
    }
}