force-app/main/default/objects/SAP_Sales_Actual_Plan__c/SAP_Sales_Actual_Plan__c.object-meta.xml
<CustomObject>
    <label>SAP Sales Actual Plan</label>
    <nameField>
        <displayFormat>No-{0000000}</displayFormat>
        <label>SAP Sales Actual Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Sales Actual Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Sales_Actual_Plan__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SAP Sales Actual Plans</relationshipLabel>
    <relationshipName>SAP_Sales_Actual_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SAP_Sales_Actual_Report__c/SAP_Sales_Actual_Report__c.object-meta.xml
<CustomObject>
    <label>SAP Sales Actual Report</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Sales Actual Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Sales_Actual_Report__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SAP Sales Actual Reports</relationshipLabel>
    <relationshipName>SAP_Sales_Actual_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Sales_Actual_Report__c/fields/SAP_Sales_Actual_Plan__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sales_Actual_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SAP Sales Actual Plan</description>
    <label>SAP Sales Actual Plan</label>
    <referenceTo>SAP_Sales_Actual_Plan__c</referenceTo>
    <relationshipLabel>SAP Sales Actual Reports</relationshipLabel>
    <relationshipName>SAP_Sales_Actual_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SAPSalesActualPlanTriggerHandler.cls
/**************************************************************************************************
 * SAPSalesActualPlanTriggerHandler
 * Purpose:SAP Sales Actual Report添加 SAP Sales Actual Plan
 * Author: wfc
 * Create Date: 2020-10-13
***************************************************************************************************/
public class SAPSalesActualPlanTriggerHandler extends TriggerHandler{

    public override void afterInsert(){
        List<SAP_Sales_Actual_Report__c> reportList = new List<SAP_Sales_Actual_Report__c>();
        for(SAP_Sales_Actual_Plan__c sc : ((list<SAP_Sales_Actual_Plan__c>)Trigger.new)){
            if(String.isNotBlank(sc.Customer__c)){
                // 查询所有的SAP Sales Actual Report表赋值上新建的plan数据
                for(SAP_Sales_Actual_Report__c sar : [SELECT ID, Customer__c from SAP_Sales_Actual_Report__c where Customer__c =: sc.Customer__c]){
                    sar.SAP_Sales_Actual_Plan__c = sc.id;
                    reportList.add(sar);
                }
            }
        }
        update reportList;  
    }
    
}