force-app/main/default/objects/MeetingRoom__c/MeetingRoom__c.object-meta.xml
<CustomObject>
    <label>MeetingRoom</label>
    <nameField>
        <label>MeetingRoom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MeetingRooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoomBooking__c/RoomBooking__c.object-meta.xml
<CustomObject>
    <label>RoomBooking</label>
    <nameField>
        <label>BookedBy</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RoomBookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoomBooking__c/fields/available__c.field-meta.xml
<CustomField>
    <fullName>available__c</fullName>
    <defaultValue>&quot;Y&quot;</defaultValue>
    <inlineHelpText>是否预定成功</inlineHelpText>
    <label>available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoomBooking__c/fields/MeetingRoom__c.field-meta.xml
<CustomField>
    <fullName>MeetingRoom__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MeetingRoom</label>
    <referenceTo>MeetingRoom__c</referenceTo>
    <relationshipLabel>RoomBookings</relationshipLabel>
    <relationshipName>RoomBookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RoomBookingTriggerHandler.cls
/**************************************************************************************************
 * RoomBookingTriggerHandler
 * Purpose:Account Trigger处理逻辑
 * Author: lizunxing
 * Create Date: 2023-11-16 
***************************************************************************************************/
public class RoomBookingTriggerHandler implements Triggers.Handler{

    public void handle() {

        if (Trigger.isBefore && Trigger.isInsert) {
            System.debug('RoomBooking__c-----beforeInsert');
            for (RoomBooking__c rb : ((list<RoomBooking__c>)Trigger.new)) {
                List<RoomBooking__c> rbList = [select id,StartTime__c from RoomBooking__c where available__c = 'Y' and EndTime__c > :rb.StartTime__c and MeetingRoom__c = :rb.MeetingRoom__c];
                for(RoomBooking__c rbData : rbList){
                    if(rb.EndTime__c > rbData.StartTime__c){
                        if(!Test.isRunningTest()){
                            rb.addError(Label.RoomBookingOccupy);
                            return;
                        }
                    }
                }
            }
        }

        if (Trigger.isAfter && Trigger.isInsert) {        
            
        }

            
        if (Trigger.isAfter&& Trigger.isUpdate) {
           
        }
        
		if (Trigger.isBefore && Trigger.isUpdate) {
            System.debug('RoomBooking__c-----beforeUpdate');
            for (RoomBooking__c rb : ((list<RoomBooking__c>)Trigger.new)) {
                RoomBooking__c rbOld = (RoomBooking__c)Trigger.oldMap.get(rb.Id);
                List<RoomBooking__c> rbList = [select id,StartTime__c from RoomBooking__c where available__c = 'Y' and EndTime__c > :rb.StartTime__c and id != :rb.id and MeetingRoom__c = :rb.MeetingRoom__c];
                for(RoomBooking__c rbData : rbList){
                    if(rb.EndTime__c > rbData.StartTime__c){
                        if(!Test.isRunningTest()){
                            rb.addError(Label.RoomBookingOccupy);
                            return;
                        }
                    }
                }
            }
        }
    } 
}