force-app/main/default/objects/Exhibition_Region_Owner__c/Exhibition_Region_Owner__c.object-meta.xml
<CustomObject>
    <label>展会区组负责人</label>
    <nameField>
        <label>姓名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>展会区组负责人</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Region_Owner__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>邮箱</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Exhibition_Region_Owner__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>关联用户</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exhibition_Region_Owners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExhibitionRegionHandlerHelper.cls
public without sharing class ExhibitionRegionHandlerHelper {
    public static void initUserInfo(List<Exhibition_Region_Owner__c> newList){
    	List<String> emailList = new LisqContainer(newList).SelectSField('Email__c');
        Map<String, String> emailRegMap = new Map<String, String>();
        if (emailList.size() > 0) {
            // Exhibition_Region_Owner__c
            for (User item : [SELECT Id, Email FROM User WHERE Email IN: emailList])
                emailRegMap.put(item.Email, item.Id);
            for (Exhibition_Region_Owner__c itemChange: newList) 
                itemChange.User__c = emailRegMap.get(itemChange.Email__c) == NULL ? NULL : emailRegMap.get(itemChange.Email__c);
        }
    }
}