force-app/main/default/objects/Exhibition_Region_Owner__c/Exhibition_Region_Owner__c.object-meta.xml
<CustomObject>
    <label>展会区组负责人</label>
    <nameField>
        <label>姓名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>展会区组负责人</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Region_Owner__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>邮箱</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/ExhibitionRegionTriggerTest.cls
@isTest
private class ExhibitionRegionTriggerTest {
    static testMethod void testMethod1() {
    	String profileName  = '展会 展务组';
        Id profileId = [SELECT Id FROM profile WHERE Name = :profileName][0].Id; 
        User user1 = new User(alias = '区域经理', email='TestTom@noemail.com',
        emailencodingkey='UTF-8', lastname='TestTom', languagelocalekey='en_US',
        localesidkey='en_US',profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='testTom@noemail.com');
        INSERT user1;

        Exhibition_Region_Owner__c e = new Exhibition_Region_Owner__c(Name = '测试用户', Email__c = 'TestTom@noemail.com');
        INSERT e;
        e.Name = 'Test Name';
        UPDATE e;

    }
}