force-app/main/default/objects/Exhibition_Region_Owner__c/Exhibition_Region_Owner__c.object-meta.xml
<CustomObject>
    <label>展会区组负责人</label>
    <nameField>
        <label>姓名</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>展会区组负责人</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exhibition_Region_Owner__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>品牌</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Exhibition_Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exhibition_Region_Owner__c/fields/Counry__c.field-meta.xml
<CustomField>
    <fullName>Counry__c</fullName>
    <label>国家</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Primary_Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exhibition_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exhibition_Region_Owner__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>邮箱</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Exhibition_Region_Owner__c/fields/Primary_Department__c.field-meta.xml
<CustomField>
    <fullName>Primary_Department__c</fullName>
    <label>所属区域</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America Region</fullName>
                <label>美洲地区 America Region</label>
            </value>
            <value>
                <fullName>Europe Region</fullName>
                <label>欧洲地区 Europe Region</label>
            </value>
            <value>
                <fullName>Mid-East &amp; Africa Region</fullName>
                <label>中东和非洲地区 Mid-East &amp; Africa Region</label>
            </value>
            <value>
                <fullName>Asia-Pacific Region</fullName>
                <label>亚太地区 Asia-Pacific Region</label>
            </value>
            <value>
                <fullName>Japan Region</fullName>
                <label>日本地区 Japan Region</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exhibition_Region_Owner__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>产品线</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Exhibition_Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exhibition_Region_Owner__c/fields/Secondary_Department__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Department__c</fullName>
    <label>二级部门</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/ExpoApplyInfo__c.object-meta.xml
<CustomObject>
    <label>Exhibition Customer</label>
    <nameField>
        <label>VisitorCode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoApplyInfo__c/fields/BrandPreferenceCN__c.field-meta.xml
<CustomField>
    <fullName>BrandPreferenceCN__c</fullName>
    <label>Brand Preference CN</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hisense</fullName>
            </value>
            <value>
                <fullName>Gorenje</fullName>
            </value>
            <value>
                <fullName>ASKO</fullName>
            </value>
            <value>
                <fullName>Toshiba</fullName>
            </value>
            <value>
                <fullName>MORA</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Other Brands</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/CountryRegionCN__c.field-meta.xml
<CustomField>
    <fullName>CountryRegionCN__c</fullName>
    <label>Country CN</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/CountryRegionEN__c.field-meta.xml
<CustomField>
    <fullName>CountryRegionEN__c</fullName>
    <label>Country EN</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/ExpoId__c.field-meta.xml
<CustomField>
    <fullName>ExpoId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exhibition Information</label>
    <referenceTo>ExpoInfo__c</referenceTo>
    <relationshipLabel>Exhibition Customers</relationshipLabel>
    <relationshipName>ExpoApplyInfos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/FirstNameCN__c.field-meta.xml
<CustomField>
    <fullName>FirstNameCN__c</fullName>
    <label>First Name CN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/FirstNameEN__c.field-meta.xml
<CustomField>
    <fullName>FirstNameEN__c</fullName>
    <label>First Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/Is_Present__c.field-meta.xml
<CustomField>
    <fullName>Is_Present__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attand on-site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/LastNameEN__c.field-meta.xml
<CustomField>
    <fullName>LastNameEN__c</fullName>
    <label>Last Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/ProductInterestCN__c.field-meta.xml
<CustomField>
    <fullName>ProductInterestCN__c</fullName>
    <label>Product Interest CN</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>电视</fullName>
            </value>
            <value>
                <fullName>激光电视</fullName>
            </value>
            <value>
                <fullName>商用显示</fullName>
            </value>
            <value>
                <fullName>冰箱</fullName>
            </value>
            <value>
                <fullName>洗衣机</fullName>
            </value>
            <value>
                <fullName>冷柜</fullName>
            </value>
            <value>
                <fullName>厨电</fullName>
            </value>
            <value>
                <fullName>小家电</fullName>
            </value>
            <value>
                <fullName>家用空调</fullName>
            </value>
            <value>
                <fullName>轻型商用空调</fullName>
            </value>
            <value>
                <fullName>商用空调</fullName>
            </value>
            <value>
                <fullName>手机</fullName>
            </value>
            <value>
                <fullName>其他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
            <value>
                <fullName>总部-HQ</fullName>
            </value>
            <value>
                <fullName>北美区-North America Region</fullName>
            </value>
            <value>
                <fullName>中东非-Middle East and Africa Region</fullName>
            </value>
            <value>
                <fullName>亚太区-Asia-Pacific Region</fullName>
            </value>
            <value>
                <fullName>东盟区-ASEAN Region</fullName>
            </value>
            <value>
                <fullName>欧洲区-Eurepean Region</fullName>
            </value>
            <value>
                <fullName>印度区-Inida Region</fullName>
            </value>
            <value>
                <fullName>中南美区-Central and South America Region</fullName>
            </value>
            <value>
                <fullName>Japan Region</fullName>
                <isActive>false</isActive>
                <label>日本地区 Japan Region</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <label>Telephone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ExpoApplyInfo__c/fields/WorkTel__c.field-meta.xml
<CustomField>
    <fullName>WorkTel__c</fullName>
    <label>Work Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ExpoCountrysBazaar__c/ExpoCountrysBazaar__c.object-meta.xml
<CustomObject>
    <label>ExpoCountrysBazaar</label>
    <nameField>
        <label>Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpoCountrysBazaars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoCountrysBazaar__c/fields/NameEN__c.field-meta.xml
<CustomField>
    <fullName>NameEN__c</fullName>
    <label>Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoCountrysBazaar__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Asia-Pacific</fullName>
            </value>
            <value>
                <fullName>America</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>总部-HQ</fullName>
            </value>
            <value>
                <fullName>北美区-North America Region</fullName>
            </value>
            <value>
                <fullName>中东非-Middle East and Africa Region</fullName>
            </value>
            <value>
                <fullName>亚太区-Asia-Pacific Region</fullName>
            </value>
            <value>
                <fullName>东盟区-ASEAN Region</fullName>
            </value>
            <value>
                <fullName>欧洲区-Eurepean Region</fullName>
            </value>
            <value>
                <fullName>印度区-Inida Region</fullName>
            </value>
            <value>
                <fullName>中南美区-Central and South America Region</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
                <isActive>false</isActive>
                <label>Japan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/ExpoInfo__c.object-meta.xml
<CustomObject>
    <description>展会信息</description>
    <label>Exhibition Management</label>
    <nameField>
        <label>Exhibition Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibition Managements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoInfo__c/fields/DisplayInThePortal__c.field-meta.xml
<CustomField>
    <fullName>DisplayInThePortal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display in the Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/LastRegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>LastRegistrationDate__c</fullName>
    <label>Last Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ExpoInfo__c/fields/TitleEN__c.field-meta.xml
<CustomField>
    <fullName>TitleEN__c</fullName>
    <label>Exhibition Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExpoProductPreference__c/ExpoProductPreference__c.object-meta.xml
<CustomObject>
    <label>Expo Product Preference</label>
    <nameField>
        <label>Product Name CN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expo Product Preferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpoProductPreference__c/fields/ProductEN__c.field-meta.xml
<CustomField>
    <fullName>ProductEN__c</fullName>
    <label>Product Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Exhibition_Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hisense</fullName>
    </customValue>
    <customValue>
        <fullName>Gorenje</fullName>
    </customValue>
    <customValue>
        <fullName>ASKO</fullName>
    </customValue>
    <customValue>
        <fullName>Toshiba</fullName>
    </customValue>
    <customValue>
        <fullName>MORA</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Other Brands</fullName>
    </customValue>
    <customValue>
        <fullName>Godrej</fullName>
        <isActive>false</isActive>
        <label>Godrej</label>
    </customValue>
    <customValue>
        <fullName>东芝</fullName>
        <isActive>false</isActive>
        <label>东芝</label>
    </customValue>
    <customValue>
        <fullName>Beko</fullName>
        <isActive>false</isActive>
        <label>Beko</label>
    </customValue>
    <customValue>
        <fullName>Fujitsu</fullName>
        <isActive>false</isActive>
        <label>Fujitsu</label>
    </customValue>
    <customValue>
        <fullName>York</fullName>
        <isActive>false</isActive>
        <label>York</label>
    </customValue>
    <customValue>
        <fullName>Hitachi</fullName>
        <isActive>false</isActive>
        <label>Hitachi</label>
    </customValue>
    <customValue>
        <fullName>Whirlpool</fullName>
        <isActive>false</isActive>
        <label>Whirlpool</label>
    </customValue>
    <customValue>
        <fullName>LG</fullName>
        <isActive>false</isActive>
        <label>LG</label>
    </customValue>
    <masterLabel>展会品牌</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Exhibition_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>不丹</fullName>
    </customValue>
    <customValue>
        <fullName>东帝汶岛</fullName>
    </customValue>
    <customValue>
        <fullName>中国</fullName>
    </customValue>
    <customValue>
        <fullName>中国台湾</fullName>
    </customValue>
    <customValue>
        <fullName>中国澳门</fullName>
    </customValue>
    <customValue>
        <fullName>中国香港</fullName>
    </customValue>
    <customValue>
        <fullName>中非共和国</fullName>
    </customValue>
    <customValue>
        <fullName>丹麦</fullName>
    </customValue>
    <customValue>
        <fullName>乌克兰</fullName>
    </customValue>
    <customValue>
        <fullName>乌兹别克斯坦</fullName>
    </customValue>
    <customValue>
        <fullName>乌干达</fullName>
    </customValue>
    <customValue>
        <fullName>乌拉圭</fullName>
    </customValue>
    <customValue>
        <fullName>乍得</fullName>
    </customValue>
    <customValue>
        <fullName>也门</fullName>
    </customValue>
    <customValue>
        <fullName>亚美尼亚</fullName>
    </customValue>
    <customValue>
        <fullName>以色列</fullName>
    </customValue>
    <customValue>
        <fullName>伊拉克</fullName>
    </customValue>
    <customValue>
        <fullName>伊朗</fullName>
    </customValue>
    <customValue>
        <fullName>伯利兹</fullName>
    </customValue>
    <customValue>
        <fullName>佛得角群岛</fullName>
    </customValue>
    <customValue>
        <fullName>俄罗斯联邦</fullName>
    </customValue>
    <customValue>
        <fullName>保加利亚</fullName>
    </customValue>
    <customValue>
        <fullName>克罗地亚</fullName>
    </customValue>
    <customValue>
        <fullName>关岛</fullName>
    </customValue>
    <customValue>
        <fullName>其他</fullName>
    </customValue>
    <customValue>
        <fullName>冈比亚</fullName>
    </customValue>
    <customValue>
        <fullName>冰岛</fullName>
    </customValue>
    <customValue>
        <fullName>几内亚</fullName>
    </customValue>
    <customValue>
        <fullName>几内亚比绍</fullName>
    </customValue>
    <customValue>
        <fullName>列支敦士登</fullName>
    </customValue>
    <masterLabel>展会国家</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Exhibition_Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>电视</fullName>
    </customValue>
    <customValue>
        <fullName>激光电视</fullName>
    </customValue>
    <customValue>
        <fullName>冰冷产品</fullName>
    </customValue>
    <customValue>
        <fullName>洗衣机</fullName>
    </customValue>
    <customValue>
        <fullName>厨电产品</fullName>
    </customValue>
    <customValue>
        <fullName>小家电</fullName>
    </customValue>
    <customValue>
        <fullName>暖通空调</fullName>
    </customValue>
    <customValue>
        <fullName>其他</fullName>
    </customValue>
    <customValue>
        <fullName>音箱</fullName>
    </customValue>
    <customValue>
        <fullName>冰冷</fullName>
    </customValue>
    <customValue>
        <fullName>厨电</fullName>
    </customValue>
    <customValue>
        <fullName>音响</fullName>
    </customValue>
    <customValue>
        <fullName>空调产品线</fullName>
        <isActive>false</isActive>
        <label>空调产品线</label>
    </customValue>
    <customValue>
        <fullName>电视产品线</fullName>
        <isActive>false</isActive>
        <label>电视产品线</label>
    </customValue>
    <customValue>
        <fullName>冰箱产品线</fullName>
        <isActive>false</isActive>
        <label>冰箱产品线</label>
    </customValue>
    <customValue>
        <fullName>冰冷洗厨</fullName>
        <isActive>false</isActive>
        <label>冰冷洗厨</label>
    </customValue>
    <customValue>
        <fullName>空调</fullName>
        <isActive>false</isActive>
        <label>空调</label>
    </customValue>
    <customValue>
        <fullName>手机</fullName>
        <isActive>false</isActive>
        <label>手机</label>
    </customValue>
    <customValue>
        <fullName>商用空调</fullName>
        <isActive>false</isActive>
        <label>商用空调</label>
    </customValue>
    <customValue>
        <fullName>轻型商用空调</fullName>
        <isActive>false</isActive>
        <label>轻型商用空调</label>
    </customValue>
    <customValue>
        <fullName>冷柜</fullName>
        <isActive>false</isActive>
        <label>冷柜</label>
    </customValue>
    <customValue>
        <fullName>所有白电及厨小产品</fullName>
        <isActive>false</isActive>
        <label>所有白电及厨小产品</label>
    </customValue>
    <customValue>
        <fullName>商用显示</fullName>
        <isActive>false</isActive>
        <label>商用显示</label>
    </customValue>
    <customValue>
        <fullName>小家电及厨小产品</fullName>
        <isActive>false</isActive>
        <label>小家电及厨小产品</label>
    </customValue>
    <masterLabel>展会产品线</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TextLnControllerTest.cls
@isTest
private class TextLnControllerTest {
    static testMethod void testMethod1() {
    	Test.startTest();
        String profileName  = '展会 展务组';
        Id profileId = [SELECT Id FROM profile WHERE Name = :profileName][0].Id; 
        User user1 = new User(alias = '区域经理', email='TestTom@noemail.com',
        emailencodingkey='UTF-8', lastname='TestTom', languagelocalekey='en_US',
        localesidkey='en_US',profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='testTom@noemail.com');
        INSERT user1;

        User user2 = new User(alias = '区域经理', email='QTestTom@noemail.com',
        emailencodingkey='UTF-8', lastname='TestTom', languagelocalekey='en_US',
        localesidkey='en_US',profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='qtestTom@noemail.com');
        INSERT user2;

        User user3 = new User(alias = '区域经理', email='WTestTom@noemail.com',
        emailencodingkey='UTF-8', lastname='TestTom', languagelocalekey='en_US',
        localesidkey='en_US',profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='wtestTom@noemail.com');
        INSERT user3;

        User user4 = new User(alias = '区域经理', email='ETestTom@noemail.com',
        emailencodingkey='UTF-8', lastname='TestTom', languagelocalekey='en_US',
        localesidkey='en_US',profileid = profileId, country='United States',IsActive =true,
        timezonesidkey='America/Los_Angeles', username='etestTom@noemail.com');
        INSERT user4;

        Exhibition_Region_Owner__c e = new Exhibition_Region_Owner__c(Name = '测试用户', 
            Email__c = 'TestTom@noemail.com', 
            Primary_Department__c = 'Asia-Pacific Region', 
            Secondary_Department__c = 'ChinaBrand',
            Counry__c = '中国', Brand__c = 'Hisense', Product_Line__c = '小家电');
        INSERT e;
        Exhibition_Region_Owner__c ee = new Exhibition_Region_Owner__c(Name = '测试用户', 
            Email__c = 'QTestTom@noemail.com', 
            Primary_Department__c = 'Asia-Pacific Region', 
            Secondary_Department__c = 'ChinaBrand',
            Counry__c = '中国', Brand__c = 'Hisense;OEM', Product_Line__c = '');
        INSERT ee;
        Exhibition_Region_Owner__c ee1 = new Exhibition_Region_Owner__c(Name = '测试用户', 
            Email__c = 'WTestTom@noemail.com', 
            Primary_Department__c = 'Asia-Pacific Region', 
            Secondary_Department__c = 'ChinaBrand',
            Counry__c = '中国', Brand__c = '', Product_Line__c = '');
        INSERT ee1;
        Exhibition_Region_Owner__c ee12 = new Exhibition_Region_Owner__c(Name = '测试用户', 
            Email__c = 'ETestTom@noemail.com', 
            Primary_Department__c = 'Asia-Pacific Region', 
            Secondary_Department__c = 'ChinaBrand',
            Counry__c = '', Brand__c = '', Product_Line__c = '');
        INSERT ee12;

        ExpoProductPreference__c pro = new ExpoProductPreference__c(Name = '小家电',ProductEN__c = ' Small Domestic Appliance（SDA）');
        INSERT pro;

        ExpoCountrysBazaar__c ctry = new ExpoCountrysBazaar__c(Name = '中国', NameEN__c = 'China');
        INSERT ctry;
        ExpoInfo__c e1 = new ExpoInfo__c(
        	LastRegistrationDate__c = Date.today()+15, 
        	StartDate__c = Date.today()-1, 
        	EndDate__c = Date.today()+10,
        	Name = '展会信息',
        	TitleEN__c = 'Exhibition Informatino',
        	DisplayInThePortal__c = true
        	);
        INSERT e1;

        // TextLnController textln = 

        TextLnController.createRecord(e1.Id, 'lastNameCN', 'lastNameEN', 'firstNameCN', 'firstNameEN', 
        	'28712345678', 'email@etret.com', '18712345432', '437694703', '40968457','duty', '部门','dshtoiewoa','rewot.com', 'jtoewer', 'oegwhgoiew', true, '');


       

        ExpoApplyInfo__c e2 = new ExpoApplyInfo__c(
            ExpoId__c = e1.Id,
            FirstNameEN__c = 'San',
            FirstNameCN__c = '三',
            LastNameCN__c = '张',
            LastNameEN__c = 'Zhang',
            Email__c = 'zs@zs.com',
            Telephone__c = '18712345678',
            WorkTel__c = '18712345678',
            Region__c = 'Asia-Pacific Region', CountryRegionCN__c='中国', ProductInterestCN__c = '小家电', BrandPreferenceCN__c = 'Hisense',
            Is_Present__c = true            
            );
        INSERT e2;

        ExpoApplyInfo__c e3 = new ExpoApplyInfo__c(
            ExpoId__c = e1.Id,
            FirstNameEN__c = 'SanSan',
            FirstNameCN__c = '三珊',
            LastNameCN__c = '张',
            LastNameEN__c = 'Zhang',
            Email__c = 'zstry@zs.com',
            Telephone__c = '187ewte12345678',
            WorkTel__c = '187treyrte12345678',
            Region__c = 'Asia-Pacific Region', CountryRegionEN__c='China', ProductInterestEN__c = '小家电', BrandPreferenceEN__c = 'Hisense',
            Is_Present__c = true            
            );
        INSERT e3;


        TextLnController.queryOwnerInfo(e2.Id);

        TextLnController.queryOwnerInfo(e3.Id);


        ExpoApplyInfo__c customer = new ExpoApplyInfo__c();
        customer.Country__c = '中国';
        customer.ProductInterestCN__c = '电视';
        TextLnController.createRecord(e1.Id, 'lastNameCN', 'lastNameEN', 'firstNameCN', 'firstNameEN', 
        	'28712345678', 'email@etret.com', '18712345432', '437694703', '40968457','duty', '部门','dshtoiewoa','rewot.com', 'jtoewer', 'oegwhgoiew', true, Json.serialize(customer));

        TextLnController.getExhibitionOptions();


        Test.stopTest();
    }
}